package jay_test

import (
	"github.com/speedyhoon/jay"
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestReadBool1(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 128 {
		assert.Equal(t, byte(i), jay.Bool1(jay.ReadBool1(byte(i))))
	}
}
func TestReadBool2(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 64 {
		assert.Equal(t, byte(i), jay.Bool2(jay.ReadBool2(byte(i))))
	}
}
func TestReadBool3(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 32 {
		assert.Equal(t, byte(i), jay.Bool3(jay.ReadBool3(byte(i))))
	}
}
func TestReadBool4(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 16 {
		assert.Equal(t, byte(i), jay.Bool4(jay.ReadBool4(byte(i))))
	}
}
func TestReadBool5(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 8 {
		assert.Equal(t, byte(i), jay.Bool5(jay.ReadBool5(byte(i))))
	}
}
func TestReadBool6(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 4 {
		assert.Equal(t, byte(i), jay.Bool6(jay.ReadBool6(byte(i))))
	}
}
func TestReadBool7(t *testing.T) {
	for i := 0; i <= MaxUint8; i += 2 {
		assert.Equal(t, byte(i), jay.Bool7(jay.ReadBool7(byte(i))))
	}
}
func TestReadBool8(t *testing.T) {
	for i := 0; i <= MaxUint8; i++ {
		assert.Equal(t, byte(i), jay.Bool8(jay.ReadBool8(byte(i))))
	}
}

func TestBool1(t *testing.T) {
	assert.Equal(t, byte(128), jay.Bool1(true))
	assert.Equal(t, byte(0), jay.Bool1(false))
}

func TestBool2(t *testing.T) {
	assert.Equal(t, byte(192), jay.Bool2(true, true))
	assert.Equal(t, byte(128), jay.Bool2(true, false))
	assert.Equal(t, byte(64), jay.Bool2(false, true))
	assert.Equal(t, byte(0), jay.Bool2(false, false))
}

func TestBool3(t *testing.T) {
	assert.Equal(t, byte(224), jay.Bool3(true, true, true))
	assert.Equal(t, byte(192), jay.Bool3(true, true, false))
	assert.Equal(t, byte(160), jay.Bool3(true, false, true))
	assert.Equal(t, byte(128), jay.Bool3(true, false, false))
	assert.Equal(t, byte(96), jay.Bool3(false, true, true))
	assert.Equal(t, byte(64), jay.Bool3(false, true, false))
	assert.Equal(t, byte(32), jay.Bool3(false, false, true))
	assert.Equal(t, byte(0), jay.Bool3(false, false, false))
}

func TestBool4(t *testing.T) {
	assert.Equal(t, byte(240), jay.Bool4(true, true, true, true))
	assert.Equal(t, byte(224), jay.Bool4(true, true, true, false))
	assert.Equal(t, byte(208), jay.Bool4(true, true, false, true))
	assert.Equal(t, byte(192), jay.Bool4(true, true, false, false))
	assert.Equal(t, byte(176), jay.Bool4(true, false, true, true))
	assert.Equal(t, byte(160), jay.Bool4(true, false, true, false))
	assert.Equal(t, byte(144), jay.Bool4(true, false, false, true))
	assert.Equal(t, byte(128), jay.Bool4(true, false, false, false))
	assert.Equal(t, byte(112), jay.Bool4(false, true, true, true))
	assert.Equal(t, byte(96), jay.Bool4(false, true, true, false))
	assert.Equal(t, byte(80), jay.Bool4(false, true, false, true))
	assert.Equal(t, byte(64), jay.Bool4(false, true, false, false))
	assert.Equal(t, byte(48), jay.Bool4(false, false, true, true))
	assert.Equal(t, byte(32), jay.Bool4(false, false, true, false))
	assert.Equal(t, byte(16), jay.Bool4(false, false, false, true))
	assert.Equal(t, byte(0), jay.Bool4(false, false, false, false))
}

func TestBool5(t *testing.T) {
	assert.Equal(t, byte(248), jay.Bool5(true, true, true, true, true))
	assert.Equal(t, byte(240), jay.Bool5(true, true, true, true, false))
	assert.Equal(t, byte(232), jay.Bool5(true, true, true, false, true))
	assert.Equal(t, byte(224), jay.Bool5(true, true, true, false, false))
	assert.Equal(t, byte(216), jay.Bool5(true, true, false, true, true))
	assert.Equal(t, byte(208), jay.Bool5(true, true, false, true, false))
	assert.Equal(t, byte(200), jay.Bool5(true, true, false, false, true))
	assert.Equal(t, byte(192), jay.Bool5(true, true, false, false, false))
	assert.Equal(t, byte(184), jay.Bool5(true, false, true, true, true))
	assert.Equal(t, byte(176), jay.Bool5(true, false, true, true, false))
	assert.Equal(t, byte(168), jay.Bool5(true, false, true, false, true))
	assert.Equal(t, byte(160), jay.Bool5(true, false, true, false, false))
	assert.Equal(t, byte(152), jay.Bool5(true, false, false, true, true))
	assert.Equal(t, byte(144), jay.Bool5(true, false, false, true, false))
	assert.Equal(t, byte(136), jay.Bool5(true, false, false, false, true))
	assert.Equal(t, byte(128), jay.Bool5(true, false, false, false, false))
	assert.Equal(t, byte(120), jay.Bool5(false, true, true, true, true))
	assert.Equal(t, byte(112), jay.Bool5(false, true, true, true, false))
	assert.Equal(t, byte(104), jay.Bool5(false, true, true, false, true))
	assert.Equal(t, byte(96), jay.Bool5(false, true, true, false, false))
	assert.Equal(t, byte(88), jay.Bool5(false, true, false, true, true))
	assert.Equal(t, byte(80), jay.Bool5(false, true, false, true, false))
	assert.Equal(t, byte(72), jay.Bool5(false, true, false, false, true))
	assert.Equal(t, byte(64), jay.Bool5(false, true, false, false, false))
	assert.Equal(t, byte(56), jay.Bool5(false, false, true, true, true))
	assert.Equal(t, byte(48), jay.Bool5(false, false, true, true, false))
	assert.Equal(t, byte(40), jay.Bool5(false, false, true, false, true))
	assert.Equal(t, byte(32), jay.Bool5(false, false, true, false, false))
	assert.Equal(t, byte(24), jay.Bool5(false, false, false, true, true))
	assert.Equal(t, byte(16), jay.Bool5(false, false, false, true, false))
	assert.Equal(t, byte(8), jay.Bool5(false, false, false, false, true))
	assert.Equal(t, byte(0), jay.Bool5(false, false, false, false, false))
}

func TestBool6(t *testing.T) {
	assert.Equal(t, byte(252), jay.Bool6(true, true, true, true, true, true))
	assert.Equal(t, byte(248), jay.Bool6(true, true, true, true, true, false))
	assert.Equal(t, byte(244), jay.Bool6(true, true, true, true, false, true))
	assert.Equal(t, byte(240), jay.Bool6(true, true, true, true, false, false))
	assert.Equal(t, byte(236), jay.Bool6(true, true, true, false, true, true))
	assert.Equal(t, byte(232), jay.Bool6(true, true, true, false, true, false))
	assert.Equal(t, byte(228), jay.Bool6(true, true, true, false, false, true))
	assert.Equal(t, byte(224), jay.Bool6(true, true, true, false, false, false))
	assert.Equal(t, byte(220), jay.Bool6(true, true, false, true, true, true))
	assert.Equal(t, byte(216), jay.Bool6(true, true, false, true, true, false))
	assert.Equal(t, byte(212), jay.Bool6(true, true, false, true, false, true))
	assert.Equal(t, byte(208), jay.Bool6(true, true, false, true, false, false))
	assert.Equal(t, byte(204), jay.Bool6(true, true, false, false, true, true))
	assert.Equal(t, byte(200), jay.Bool6(true, true, false, false, true, false))
	assert.Equal(t, byte(196), jay.Bool6(true, true, false, false, false, true))
	assert.Equal(t, byte(192), jay.Bool6(true, true, false, false, false, false))
	assert.Equal(t, byte(188), jay.Bool6(true, false, true, true, true, true))
	assert.Equal(t, byte(184), jay.Bool6(true, false, true, true, true, false))
	assert.Equal(t, byte(180), jay.Bool6(true, false, true, true, false, true))
	assert.Equal(t, byte(176), jay.Bool6(true, false, true, true, false, false))
	assert.Equal(t, byte(172), jay.Bool6(true, false, true, false, true, true))
	assert.Equal(t, byte(168), jay.Bool6(true, false, true, false, true, false))
	assert.Equal(t, byte(164), jay.Bool6(true, false, true, false, false, true))
	assert.Equal(t, byte(160), jay.Bool6(true, false, true, false, false, false))
	assert.Equal(t, byte(156), jay.Bool6(true, false, false, true, true, true))
	assert.Equal(t, byte(152), jay.Bool6(true, false, false, true, true, false))
	assert.Equal(t, byte(148), jay.Bool6(true, false, false, true, false, true))
	assert.Equal(t, byte(144), jay.Bool6(true, false, false, true, false, false))
	assert.Equal(t, byte(140), jay.Bool6(true, false, false, false, true, true))
	assert.Equal(t, byte(136), jay.Bool6(true, false, false, false, true, false))
	assert.Equal(t, byte(132), jay.Bool6(true, false, false, false, false, true))
	assert.Equal(t, byte(128), jay.Bool6(true, false, false, false, false, false))
	assert.Equal(t, byte(124), jay.Bool6(false, true, true, true, true, true))
	assert.Equal(t, byte(120), jay.Bool6(false, true, true, true, true, false))
	assert.Equal(t, byte(116), jay.Bool6(false, true, true, true, false, true))
	assert.Equal(t, byte(112), jay.Bool6(false, true, true, true, false, false))
	assert.Equal(t, byte(108), jay.Bool6(false, true, true, false, true, true))
	assert.Equal(t, byte(104), jay.Bool6(false, true, true, false, true, false))
	assert.Equal(t, byte(100), jay.Bool6(false, true, true, false, false, true))
	assert.Equal(t, byte(96), jay.Bool6(false, true, true, false, false, false))
	assert.Equal(t, byte(92), jay.Bool6(false, true, false, true, true, true))
	assert.Equal(t, byte(88), jay.Bool6(false, true, false, true, true, false))
	assert.Equal(t, byte(84), jay.Bool6(false, true, false, true, false, true))
	assert.Equal(t, byte(80), jay.Bool6(false, true, false, true, false, false))
	assert.Equal(t, byte(76), jay.Bool6(false, true, false, false, true, true))
	assert.Equal(t, byte(72), jay.Bool6(false, true, false, false, true, false))
	assert.Equal(t, byte(68), jay.Bool6(false, true, false, false, false, true))
	assert.Equal(t, byte(64), jay.Bool6(false, true, false, false, false, false))
	assert.Equal(t, byte(60), jay.Bool6(false, false, true, true, true, true))
	assert.Equal(t, byte(56), jay.Bool6(false, false, true, true, true, false))
	assert.Equal(t, byte(52), jay.Bool6(false, false, true, true, false, true))
	assert.Equal(t, byte(48), jay.Bool6(false, false, true, true, false, false))
	assert.Equal(t, byte(44), jay.Bool6(false, false, true, false, true, true))
	assert.Equal(t, byte(40), jay.Bool6(false, false, true, false, true, false))
	assert.Equal(t, byte(36), jay.Bool6(false, false, true, false, false, true))
	assert.Equal(t, byte(32), jay.Bool6(false, false, true, false, false, false))
	assert.Equal(t, byte(28), jay.Bool6(false, false, false, true, true, true))
	assert.Equal(t, byte(24), jay.Bool6(false, false, false, true, true, false))
	assert.Equal(t, byte(20), jay.Bool6(false, false, false, true, false, true))
	assert.Equal(t, byte(16), jay.Bool6(false, false, false, true, false, false))
	assert.Equal(t, byte(12), jay.Bool6(false, false, false, false, true, true))
	assert.Equal(t, byte(8), jay.Bool6(false, false, false, false, true, false))
	assert.Equal(t, byte(4), jay.Bool6(false, false, false, false, false, true))
	assert.Equal(t, byte(0), jay.Bool6(false, false, false, false, false, false))
}

func TestBool7(t *testing.T) {
	assert.Equal(t, byte(254), jay.Bool7(true, true, true, true, true, true, true))
	assert.Equal(t, byte(252), jay.Bool7(true, true, true, true, true, true, false))
	assert.Equal(t, byte(250), jay.Bool7(true, true, true, true, true, false, true))
	assert.Equal(t, byte(248), jay.Bool7(true, true, true, true, true, false, false))
	assert.Equal(t, byte(246), jay.Bool7(true, true, true, true, false, true, true))
	assert.Equal(t, byte(244), jay.Bool7(true, true, true, true, false, true, false))
	assert.Equal(t, byte(242), jay.Bool7(true, true, true, true, false, false, true))
	assert.Equal(t, byte(240), jay.Bool7(true, true, true, true, false, false, false))
	assert.Equal(t, byte(238), jay.Bool7(true, true, true, false, true, true, true))
	assert.Equal(t, byte(236), jay.Bool7(true, true, true, false, true, true, false))
	assert.Equal(t, byte(234), jay.Bool7(true, true, true, false, true, false, true))
	assert.Equal(t, byte(232), jay.Bool7(true, true, true, false, true, false, false))
	assert.Equal(t, byte(230), jay.Bool7(true, true, true, false, false, true, true))
	assert.Equal(t, byte(228), jay.Bool7(true, true, true, false, false, true, false))
	assert.Equal(t, byte(226), jay.Bool7(true, true, true, false, false, false, true))
	assert.Equal(t, byte(224), jay.Bool7(true, true, true, false, false, false, false))
	assert.Equal(t, byte(222), jay.Bool7(true, true, false, true, true, true, true))
	assert.Equal(t, byte(220), jay.Bool7(true, true, false, true, true, true, false))
	assert.Equal(t, byte(218), jay.Bool7(true, true, false, true, true, false, true))
	assert.Equal(t, byte(216), jay.Bool7(true, true, false, true, true, false, false))
	assert.Equal(t, byte(214), jay.Bool7(true, true, false, true, false, true, true))
	assert.Equal(t, byte(212), jay.Bool7(true, true, false, true, false, true, false))
	assert.Equal(t, byte(210), jay.Bool7(true, true, false, true, false, false, true))
	assert.Equal(t, byte(208), jay.Bool7(true, true, false, true, false, false, false))
	assert.Equal(t, byte(206), jay.Bool7(true, true, false, false, true, true, true))
	assert.Equal(t, byte(204), jay.Bool7(true, true, false, false, true, true, false))
	assert.Equal(t, byte(202), jay.Bool7(true, true, false, false, true, false, true))
	assert.Equal(t, byte(200), jay.Bool7(true, true, false, false, true, false, false))
	assert.Equal(t, byte(198), jay.Bool7(true, true, false, false, false, true, true))
	assert.Equal(t, byte(196), jay.Bool7(true, true, false, false, false, true, false))
	assert.Equal(t, byte(194), jay.Bool7(true, true, false, false, false, false, true))
	assert.Equal(t, byte(192), jay.Bool7(true, true, false, false, false, false, false))
	assert.Equal(t, byte(190), jay.Bool7(true, false, true, true, true, true, true))
	assert.Equal(t, byte(188), jay.Bool7(true, false, true, true, true, true, false))
	assert.Equal(t, byte(186), jay.Bool7(true, false, true, true, true, false, true))
	assert.Equal(t, byte(184), jay.Bool7(true, false, true, true, true, false, false))
	assert.Equal(t, byte(182), jay.Bool7(true, false, true, true, false, true, true))
	assert.Equal(t, byte(180), jay.Bool7(true, false, true, true, false, true, false))
	assert.Equal(t, byte(178), jay.Bool7(true, false, true, true, false, false, true))
	assert.Equal(t, byte(176), jay.Bool7(true, false, true, true, false, false, false))
	assert.Equal(t, byte(174), jay.Bool7(true, false, true, false, true, true, true))
	assert.Equal(t, byte(172), jay.Bool7(true, false, true, false, true, true, false))
	assert.Equal(t, byte(170), jay.Bool7(true, false, true, false, true, false, true))
	assert.Equal(t, byte(168), jay.Bool7(true, false, true, false, true, false, false))
	assert.Equal(t, byte(166), jay.Bool7(true, false, true, false, false, true, true))
	assert.Equal(t, byte(164), jay.Bool7(true, false, true, false, false, true, false))
	assert.Equal(t, byte(162), jay.Bool7(true, false, true, false, false, false, true))
	assert.Equal(t, byte(160), jay.Bool7(true, false, true, false, false, false, false))
	assert.Equal(t, byte(158), jay.Bool7(true, false, false, true, true, true, true))
	assert.Equal(t, byte(156), jay.Bool7(true, false, false, true, true, true, false))
	assert.Equal(t, byte(154), jay.Bool7(true, false, false, true, true, false, true))
	assert.Equal(t, byte(152), jay.Bool7(true, false, false, true, true, false, false))
	assert.Equal(t, byte(150), jay.Bool7(true, false, false, true, false, true, true))
	assert.Equal(t, byte(148), jay.Bool7(true, false, false, true, false, true, false))
	assert.Equal(t, byte(146), jay.Bool7(true, false, false, true, false, false, true))
	assert.Equal(t, byte(144), jay.Bool7(true, false, false, true, false, false, false))
	assert.Equal(t, byte(142), jay.Bool7(true, false, false, false, true, true, true))
	assert.Equal(t, byte(140), jay.Bool7(true, false, false, false, true, true, false))
	assert.Equal(t, byte(138), jay.Bool7(true, false, false, false, true, false, true))
	assert.Equal(t, byte(136), jay.Bool7(true, false, false, false, true, false, false))
	assert.Equal(t, byte(134), jay.Bool7(true, false, false, false, false, true, true))
	assert.Equal(t, byte(132), jay.Bool7(true, false, false, false, false, true, false))
	assert.Equal(t, byte(130), jay.Bool7(true, false, false, false, false, false, true))
	assert.Equal(t, byte(128), jay.Bool7(true, false, false, false, false, false, false))
	assert.Equal(t, byte(126), jay.Bool7(false, true, true, true, true, true, true))
	assert.Equal(t, byte(124), jay.Bool7(false, true, true, true, true, true, false))
	assert.Equal(t, byte(122), jay.Bool7(false, true, true, true, true, false, true))
	assert.Equal(t, byte(120), jay.Bool7(false, true, true, true, true, false, false))
	assert.Equal(t, byte(118), jay.Bool7(false, true, true, true, false, true, true))
	assert.Equal(t, byte(116), jay.Bool7(false, true, true, true, false, true, false))
	assert.Equal(t, byte(114), jay.Bool7(false, true, true, true, false, false, true))
	assert.Equal(t, byte(112), jay.Bool7(false, true, true, true, false, false, false))
	assert.Equal(t, byte(110), jay.Bool7(false, true, true, false, true, true, true))
	assert.Equal(t, byte(108), jay.Bool7(false, true, true, false, true, true, false))
	assert.Equal(t, byte(106), jay.Bool7(false, true, true, false, true, false, true))
	assert.Equal(t, byte(104), jay.Bool7(false, true, true, false, true, false, false))
	assert.Equal(t, byte(102), jay.Bool7(false, true, true, false, false, true, true))
	assert.Equal(t, byte(100), jay.Bool7(false, true, true, false, false, true, false))
	assert.Equal(t, byte(98), jay.Bool7(false, true, true, false, false, false, true))
	assert.Equal(t, byte(96), jay.Bool7(false, true, true, false, false, false, false))
	assert.Equal(t, byte(94), jay.Bool7(false, true, false, true, true, true, true))
	assert.Equal(t, byte(92), jay.Bool7(false, true, false, true, true, true, false))
	assert.Equal(t, byte(90), jay.Bool7(false, true, false, true, true, false, true))
	assert.Equal(t, byte(88), jay.Bool7(false, true, false, true, true, false, false))
	assert.Equal(t, byte(86), jay.Bool7(false, true, false, true, false, true, true))
	assert.Equal(t, byte(84), jay.Bool7(false, true, false, true, false, true, false))
	assert.Equal(t, byte(82), jay.Bool7(false, true, false, true, false, false, true))
	assert.Equal(t, byte(80), jay.Bool7(false, true, false, true, false, false, false))
	assert.Equal(t, byte(78), jay.Bool7(false, true, false, false, true, true, true))
	assert.Equal(t, byte(76), jay.Bool7(false, true, false, false, true, true, false))
	assert.Equal(t, byte(74), jay.Bool7(false, true, false, false, true, false, true))
	assert.Equal(t, byte(72), jay.Bool7(false, true, false, false, true, false, false))
	assert.Equal(t, byte(70), jay.Bool7(false, true, false, false, false, true, true))
	assert.Equal(t, byte(68), jay.Bool7(false, true, false, false, false, true, false))
	assert.Equal(t, byte(66), jay.Bool7(false, true, false, false, false, false, true))
	assert.Equal(t, byte(64), jay.Bool7(false, true, false, false, false, false, false))
	assert.Equal(t, byte(62), jay.Bool7(false, false, true, true, true, true, true))
	assert.Equal(t, byte(60), jay.Bool7(false, false, true, true, true, true, false))
	assert.Equal(t, byte(58), jay.Bool7(false, false, true, true, true, false, true))
	assert.Equal(t, byte(56), jay.Bool7(false, false, true, true, true, false, false))
	assert.Equal(t, byte(54), jay.Bool7(false, false, true, true, false, true, true))
	assert.Equal(t, byte(52), jay.Bool7(false, false, true, true, false, true, false))
	assert.Equal(t, byte(50), jay.Bool7(false, false, true, true, false, false, true))
	assert.Equal(t, byte(48), jay.Bool7(false, false, true, true, false, false, false))
	assert.Equal(t, byte(46), jay.Bool7(false, false, true, false, true, true, true))
	assert.Equal(t, byte(44), jay.Bool7(false, false, true, false, true, true, false))
	assert.Equal(t, byte(42), jay.Bool7(false, false, true, false, true, false, true))
	assert.Equal(t, byte(40), jay.Bool7(false, false, true, false, true, false, false))
	assert.Equal(t, byte(38), jay.Bool7(false, false, true, false, false, true, true))
	assert.Equal(t, byte(36), jay.Bool7(false, false, true, false, false, true, false))
	assert.Equal(t, byte(34), jay.Bool7(false, false, true, false, false, false, true))
	assert.Equal(t, byte(32), jay.Bool7(false, false, true, false, false, false, false))
	assert.Equal(t, byte(30), jay.Bool7(false, false, false, true, true, true, true))
	assert.Equal(t, byte(28), jay.Bool7(false, false, false, true, true, true, false))
	assert.Equal(t, byte(26), jay.Bool7(false, false, false, true, true, false, true))
	assert.Equal(t, byte(24), jay.Bool7(false, false, false, true, true, false, false))
	assert.Equal(t, byte(22), jay.Bool7(false, false, false, true, false, true, true))
	assert.Equal(t, byte(20), jay.Bool7(false, false, false, true, false, true, false))
	assert.Equal(t, byte(18), jay.Bool7(false, false, false, true, false, false, true))
	assert.Equal(t, byte(16), jay.Bool7(false, false, false, true, false, false, false))
	assert.Equal(t, byte(14), jay.Bool7(false, false, false, false, true, true, true))
	assert.Equal(t, byte(12), jay.Bool7(false, false, false, false, true, true, false))
	assert.Equal(t, byte(10), jay.Bool7(false, false, false, false, true, false, true))
	assert.Equal(t, byte(8), jay.Bool7(false, false, false, false, true, false, false))
	assert.Equal(t, byte(6), jay.Bool7(false, false, false, false, false, true, true))
	assert.Equal(t, byte(4), jay.Bool7(false, false, false, false, false, true, false))
	assert.Equal(t, byte(2), jay.Bool7(false, false, false, false, false, false, true))
	assert.Equal(t, byte(0), jay.Bool7(false, false, false, false, false, false, false))
}
func TestBool8(t *testing.T) {
	assert.Equal(t, byte(255), jay.Bool8(true, true, true, true, true, true, true, true))
	assert.Equal(t, byte(254), jay.Bool8(true, true, true, true, true, true, true, false))
	assert.Equal(t, byte(253), jay.Bool8(true, true, true, true, true, true, false, true))
	assert.Equal(t, byte(252), jay.Bool8(true, true, true, true, true, true, false, false))
	assert.Equal(t, byte(251), jay.Bool8(true, true, true, true, true, false, true, true))
	assert.Equal(t, byte(250), jay.Bool8(true, true, true, true, true, false, true, false))
	assert.Equal(t, byte(249), jay.Bool8(true, true, true, true, true, false, false, true))
	assert.Equal(t, byte(248), jay.Bool8(true, true, true, true, true, false, false, false))
	assert.Equal(t, byte(247), jay.Bool8(true, true, true, true, false, true, true, true))
	assert.Equal(t, byte(246), jay.Bool8(true, true, true, true, false, true, true, false))
	assert.Equal(t, byte(245), jay.Bool8(true, true, true, true, false, true, false, true))
	assert.Equal(t, byte(244), jay.Bool8(true, true, true, true, false, true, false, false))
	assert.Equal(t, byte(243), jay.Bool8(true, true, true, true, false, false, true, true))
	assert.Equal(t, byte(242), jay.Bool8(true, true, true, true, false, false, true, false))
	assert.Equal(t, byte(241), jay.Bool8(true, true, true, true, false, false, false, true))
	assert.Equal(t, byte(240), jay.Bool8(true, true, true, true, false, false, false, false))
	assert.Equal(t, byte(239), jay.Bool8(true, true, true, false, true, true, true, true))
	assert.Equal(t, byte(238), jay.Bool8(true, true, true, false, true, true, true, false))
	assert.Equal(t, byte(237), jay.Bool8(true, true, true, false, true, true, false, true))
	assert.Equal(t, byte(236), jay.Bool8(true, true, true, false, true, true, false, false))
	assert.Equal(t, byte(235), jay.Bool8(true, true, true, false, true, false, true, true))
	assert.Equal(t, byte(234), jay.Bool8(true, true, true, false, true, false, true, false))
	assert.Equal(t, byte(233), jay.Bool8(true, true, true, false, true, false, false, true))
	assert.Equal(t, byte(232), jay.Bool8(true, true, true, false, true, false, false, false))
	assert.Equal(t, byte(231), jay.Bool8(true, true, true, false, false, true, true, true))
	assert.Equal(t, byte(230), jay.Bool8(true, true, true, false, false, true, true, false))
	assert.Equal(t, byte(229), jay.Bool8(true, true, true, false, false, true, false, true))
	assert.Equal(t, byte(228), jay.Bool8(true, true, true, false, false, true, false, false))
	assert.Equal(t, byte(227), jay.Bool8(true, true, true, false, false, false, true, true))
	assert.Equal(t, byte(226), jay.Bool8(true, true, true, false, false, false, true, false))
	assert.Equal(t, byte(225), jay.Bool8(true, true, true, false, false, false, false, true))
	assert.Equal(t, byte(224), jay.Bool8(true, true, true, false, false, false, false, false))
	assert.Equal(t, byte(223), jay.Bool8(true, true, false, true, true, true, true, true))
	assert.Equal(t, byte(222), jay.Bool8(true, true, false, true, true, true, true, false))
	assert.Equal(t, byte(221), jay.Bool8(true, true, false, true, true, true, false, true))
	assert.Equal(t, byte(220), jay.Bool8(true, true, false, true, true, true, false, false))
	assert.Equal(t, byte(219), jay.Bool8(true, true, false, true, true, false, true, true))
	assert.Equal(t, byte(218), jay.Bool8(true, true, false, true, true, false, true, false))
	assert.Equal(t, byte(217), jay.Bool8(true, true, false, true, true, false, false, true))
	assert.Equal(t, byte(216), jay.Bool8(true, true, false, true, true, false, false, false))
	assert.Equal(t, byte(215), jay.Bool8(true, true, false, true, false, true, true, true))
	assert.Equal(t, byte(214), jay.Bool8(true, true, false, true, false, true, true, false))
	assert.Equal(t, byte(213), jay.Bool8(true, true, false, true, false, true, false, true))
	assert.Equal(t, byte(212), jay.Bool8(true, true, false, true, false, true, false, false))
	assert.Equal(t, byte(211), jay.Bool8(true, true, false, true, false, false, true, true))
	assert.Equal(t, byte(210), jay.Bool8(true, true, false, true, false, false, true, false))
	assert.Equal(t, byte(209), jay.Bool8(true, true, false, true, false, false, false, true))
	assert.Equal(t, byte(208), jay.Bool8(true, true, false, true, false, false, false, false))
	assert.Equal(t, byte(207), jay.Bool8(true, true, false, false, true, true, true, true))
	assert.Equal(t, byte(206), jay.Bool8(true, true, false, false, true, true, true, false))
	assert.Equal(t, byte(205), jay.Bool8(true, true, false, false, true, true, false, true))
	assert.Equal(t, byte(204), jay.Bool8(true, true, false, false, true, true, false, false))
	assert.Equal(t, byte(203), jay.Bool8(true, true, false, false, true, false, true, true))
	assert.Equal(t, byte(202), jay.Bool8(true, true, false, false, true, false, true, false))
	assert.Equal(t, byte(201), jay.Bool8(true, true, false, false, true, false, false, true))
	assert.Equal(t, byte(200), jay.Bool8(true, true, false, false, true, false, false, false))
	assert.Equal(t, byte(199), jay.Bool8(true, true, false, false, false, true, true, true))
	assert.Equal(t, byte(198), jay.Bool8(true, true, false, false, false, true, true, false))
	assert.Equal(t, byte(197), jay.Bool8(true, true, false, false, false, true, false, true))
	assert.Equal(t, byte(196), jay.Bool8(true, true, false, false, false, true, false, false))
	assert.Equal(t, byte(195), jay.Bool8(true, true, false, false, false, false, true, true))
	assert.Equal(t, byte(194), jay.Bool8(true, true, false, false, false, false, true, false))
	assert.Equal(t, byte(193), jay.Bool8(true, true, false, false, false, false, false, true))
	assert.Equal(t, byte(192), jay.Bool8(true, true, false, false, false, false, false, false))
	assert.Equal(t, byte(191), jay.Bool8(true, false, true, true, true, true, true, true))
	assert.Equal(t, byte(190), jay.Bool8(true, false, true, true, true, true, true, false))
	assert.Equal(t, byte(189), jay.Bool8(true, false, true, true, true, true, false, true))
	assert.Equal(t, byte(188), jay.Bool8(true, false, true, true, true, true, false, false))
	assert.Equal(t, byte(187), jay.Bool8(true, false, true, true, true, false, true, true))
	assert.Equal(t, byte(186), jay.Bool8(true, false, true, true, true, false, true, false))
	assert.Equal(t, byte(185), jay.Bool8(true, false, true, true, true, false, false, true))
	assert.Equal(t, byte(184), jay.Bool8(true, false, true, true, true, false, false, false))
	assert.Equal(t, byte(183), jay.Bool8(true, false, true, true, false, true, true, true))
	assert.Equal(t, byte(182), jay.Bool8(true, false, true, true, false, true, true, false))
	assert.Equal(t, byte(181), jay.Bool8(true, false, true, true, false, true, false, true))
	assert.Equal(t, byte(180), jay.Bool8(true, false, true, true, false, true, false, false))
	assert.Equal(t, byte(179), jay.Bool8(true, false, true, true, false, false, true, true))
	assert.Equal(t, byte(178), jay.Bool8(true, false, true, true, false, false, true, false))
	assert.Equal(t, byte(177), jay.Bool8(true, false, true, true, false, false, false, true))
	assert.Equal(t, byte(176), jay.Bool8(true, false, true, true, false, false, false, false))
	assert.Equal(t, byte(175), jay.Bool8(true, false, true, false, true, true, true, true))
	assert.Equal(t, byte(174), jay.Bool8(true, false, true, false, true, true, true, false))
	assert.Equal(t, byte(173), jay.Bool8(true, false, true, false, true, true, false, true))
	assert.Equal(t, byte(172), jay.Bool8(true, false, true, false, true, true, false, false))
	assert.Equal(t, byte(171), jay.Bool8(true, false, true, false, true, false, true, true))
	assert.Equal(t, byte(170), jay.Bool8(true, false, true, false, true, false, true, false))
	assert.Equal(t, byte(169), jay.Bool8(true, false, true, false, true, false, false, true))
	assert.Equal(t, byte(168), jay.Bool8(true, false, true, false, true, false, false, false))
	assert.Equal(t, byte(167), jay.Bool8(true, false, true, false, false, true, true, true))
	assert.Equal(t, byte(166), jay.Bool8(true, false, true, false, false, true, true, false))
	assert.Equal(t, byte(165), jay.Bool8(true, false, true, false, false, true, false, true))
	assert.Equal(t, byte(164), jay.Bool8(true, false, true, false, false, true, false, false))
	assert.Equal(t, byte(163), jay.Bool8(true, false, true, false, false, false, true, true))
	assert.Equal(t, byte(162), jay.Bool8(true, false, true, false, false, false, true, false))
	assert.Equal(t, byte(161), jay.Bool8(true, false, true, false, false, false, false, true))
	assert.Equal(t, byte(160), jay.Bool8(true, false, true, false, false, false, false, false))
	assert.Equal(t, byte(159), jay.Bool8(true, false, false, true, true, true, true, true))
	assert.Equal(t, byte(158), jay.Bool8(true, false, false, true, true, true, true, false))
	assert.Equal(t, byte(157), jay.Bool8(true, false, false, true, true, true, false, true))
	assert.Equal(t, byte(156), jay.Bool8(true, false, false, true, true, true, false, false))
	assert.Equal(t, byte(155), jay.Bool8(true, false, false, true, true, false, true, true))
	assert.Equal(t, byte(154), jay.Bool8(true, false, false, true, true, false, true, false))
	assert.Equal(t, byte(153), jay.Bool8(true, false, false, true, true, false, false, true))
	assert.Equal(t, byte(152), jay.Bool8(true, false, false, true, true, false, false, false))
	assert.Equal(t, byte(151), jay.Bool8(true, false, false, true, false, true, true, true))
	assert.Equal(t, byte(150), jay.Bool8(true, false, false, true, false, true, true, false))
	assert.Equal(t, byte(149), jay.Bool8(true, false, false, true, false, true, false, true))
	assert.Equal(t, byte(148), jay.Bool8(true, false, false, true, false, true, false, false))
	assert.Equal(t, byte(147), jay.Bool8(true, false, false, true, false, false, true, true))
	assert.Equal(t, byte(146), jay.Bool8(true, false, false, true, false, false, true, false))
	assert.Equal(t, byte(145), jay.Bool8(true, false, false, true, false, false, false, true))
	assert.Equal(t, byte(144), jay.Bool8(true, false, false, true, false, false, false, false))
	assert.Equal(t, byte(143), jay.Bool8(true, false, false, false, true, true, true, true))
	assert.Equal(t, byte(142), jay.Bool8(true, false, false, false, true, true, true, false))
	assert.Equal(t, byte(141), jay.Bool8(true, false, false, false, true, true, false, true))
	assert.Equal(t, byte(140), jay.Bool8(true, false, false, false, true, true, false, false))
	assert.Equal(t, byte(139), jay.Bool8(true, false, false, false, true, false, true, true))
	assert.Equal(t, byte(138), jay.Bool8(true, false, false, false, true, false, true, false))
	assert.Equal(t, byte(137), jay.Bool8(true, false, false, false, true, false, false, true))
	assert.Equal(t, byte(136), jay.Bool8(true, false, false, false, true, false, false, false))
	assert.Equal(t, byte(135), jay.Bool8(true, false, false, false, false, true, true, true))
	assert.Equal(t, byte(134), jay.Bool8(true, false, false, false, false, true, true, false))
	assert.Equal(t, byte(133), jay.Bool8(true, false, false, false, false, true, false, true))
	assert.Equal(t, byte(132), jay.Bool8(true, false, false, false, false, true, false, false))
	assert.Equal(t, byte(131), jay.Bool8(true, false, false, false, false, false, true, true))
	assert.Equal(t, byte(130), jay.Bool8(true, false, false, false, false, false, true, false))
	assert.Equal(t, byte(129), jay.Bool8(true, false, false, false, false, false, false, true))
	assert.Equal(t, byte(128), jay.Bool8(true, false, false, false, false, false, false, false))
	assert.Equal(t, byte(127), jay.Bool8(false, true, true, true, true, true, true, true))
	assert.Equal(t, byte(126), jay.Bool8(false, true, true, true, true, true, true, false))
	assert.Equal(t, byte(125), jay.Bool8(false, true, true, true, true, true, false, true))
	assert.Equal(t, byte(124), jay.Bool8(false, true, true, true, true, true, false, false))
	assert.Equal(t, byte(123), jay.Bool8(false, true, true, true, true, false, true, true))
	assert.Equal(t, byte(122), jay.Bool8(false, true, true, true, true, false, true, false))
	assert.Equal(t, byte(121), jay.Bool8(false, true, true, true, true, false, false, true))
	assert.Equal(t, byte(120), jay.Bool8(false, true, true, true, true, false, false, false))
	assert.Equal(t, byte(119), jay.Bool8(false, true, true, true, false, true, true, true))
	assert.Equal(t, byte(118), jay.Bool8(false, true, true, true, false, true, true, false))
	assert.Equal(t, byte(117), jay.Bool8(false, true, true, true, false, true, false, true))
	assert.Equal(t, byte(116), jay.Bool8(false, true, true, true, false, true, false, false))
	assert.Equal(t, byte(115), jay.Bool8(false, true, true, true, false, false, true, true))
	assert.Equal(t, byte(114), jay.Bool8(false, true, true, true, false, false, true, false))
	assert.Equal(t, byte(113), jay.Bool8(false, true, true, true, false, false, false, true))
	assert.Equal(t, byte(112), jay.Bool8(false, true, true, true, false, false, false, false))
	assert.Equal(t, byte(111), jay.Bool8(false, true, true, false, true, true, true, true))
	assert.Equal(t, byte(110), jay.Bool8(false, true, true, false, true, true, true, false))
	assert.Equal(t, byte(109), jay.Bool8(false, true, true, false, true, true, false, true))
	assert.Equal(t, byte(108), jay.Bool8(false, true, true, false, true, true, false, false))
	assert.Equal(t, byte(107), jay.Bool8(false, true, true, false, true, false, true, true))
	assert.Equal(t, byte(106), jay.Bool8(false, true, true, false, true, false, true, false))
	assert.Equal(t, byte(105), jay.Bool8(false, true, true, false, true, false, false, true))
	assert.Equal(t, byte(104), jay.Bool8(false, true, true, false, true, false, false, false))
	assert.Equal(t, byte(103), jay.Bool8(false, true, true, false, false, true, true, true))
	assert.Equal(t, byte(102), jay.Bool8(false, true, true, false, false, true, true, false))
	assert.Equal(t, byte(101), jay.Bool8(false, true, true, false, false, true, false, true))
	assert.Equal(t, byte(100), jay.Bool8(false, true, true, false, false, true, false, false))
	assert.Equal(t, byte(99), jay.Bool8(false, true, true, false, false, false, true, true))
	assert.Equal(t, byte(98), jay.Bool8(false, true, true, false, false, false, true, false))
	assert.Equal(t, byte(97), jay.Bool8(false, true, true, false, false, false, false, true))
	assert.Equal(t, byte(96), jay.Bool8(false, true, true, false, false, false, false, false))
	assert.Equal(t, byte(95), jay.Bool8(false, true, false, true, true, true, true, true))
	assert.Equal(t, byte(94), jay.Bool8(false, true, false, true, true, true, true, false))
	assert.Equal(t, byte(93), jay.Bool8(false, true, false, true, true, true, false, true))
	assert.Equal(t, byte(92), jay.Bool8(false, true, false, true, true, true, false, false))
	assert.Equal(t, byte(91), jay.Bool8(false, true, false, true, true, false, true, true))
	assert.Equal(t, byte(90), jay.Bool8(false, true, false, true, true, false, true, false))
	assert.Equal(t, byte(89), jay.Bool8(false, true, false, true, true, false, false, true))
	assert.Equal(t, byte(88), jay.Bool8(false, true, false, true, true, false, false, false))
	assert.Equal(t, byte(87), jay.Bool8(false, true, false, true, false, true, true, true))
	assert.Equal(t, byte(86), jay.Bool8(false, true, false, true, false, true, true, false))
	assert.Equal(t, byte(85), jay.Bool8(false, true, false, true, false, true, false, true))
	assert.Equal(t, byte(84), jay.Bool8(false, true, false, true, false, true, false, false))
	assert.Equal(t, byte(83), jay.Bool8(false, true, false, true, false, false, true, true))
	assert.Equal(t, byte(82), jay.Bool8(false, true, false, true, false, false, true, false))
	assert.Equal(t, byte(81), jay.Bool8(false, true, false, true, false, false, false, true))
	assert.Equal(t, byte(80), jay.Bool8(false, true, false, true, false, false, false, false))
	assert.Equal(t, byte(79), jay.Bool8(false, true, false, false, true, true, true, true))
	assert.Equal(t, byte(78), jay.Bool8(false, true, false, false, true, true, true, false))
	assert.Equal(t, byte(77), jay.Bool8(false, true, false, false, true, true, false, true))
	assert.Equal(t, byte(76), jay.Bool8(false, true, false, false, true, true, false, false))
	assert.Equal(t, byte(75), jay.Bool8(false, true, false, false, true, false, true, true))
	assert.Equal(t, byte(74), jay.Bool8(false, true, false, false, true, false, true, false))
	assert.Equal(t, byte(73), jay.Bool8(false, true, false, false, true, false, false, true))
	assert.Equal(t, byte(72), jay.Bool8(false, true, false, false, true, false, false, false))
	assert.Equal(t, byte(71), jay.Bool8(false, true, false, false, false, true, true, true))
	assert.Equal(t, byte(70), jay.Bool8(false, true, false, false, false, true, true, false))
	assert.Equal(t, byte(69), jay.Bool8(false, true, false, false, false, true, false, true))
	assert.Equal(t, byte(68), jay.Bool8(false, true, false, false, false, true, false, false))
	assert.Equal(t, byte(67), jay.Bool8(false, true, false, false, false, false, true, true))
	assert.Equal(t, byte(66), jay.Bool8(false, true, false, false, false, false, true, false))
	assert.Equal(t, byte(65), jay.Bool8(false, true, false, false, false, false, false, true))
	assert.Equal(t, byte(64), jay.Bool8(false, true, false, false, false, false, false, false))
	assert.Equal(t, byte(63), jay.Bool8(false, false, true, true, true, true, true, true))
	assert.Equal(t, byte(62), jay.Bool8(false, false, true, true, true, true, true, false))
	assert.Equal(t, byte(61), jay.Bool8(false, false, true, true, true, true, false, true))
	assert.Equal(t, byte(60), jay.Bool8(false, false, true, true, true, true, false, false))
	assert.Equal(t, byte(59), jay.Bool8(false, false, true, true, true, false, true, true))
	assert.Equal(t, byte(58), jay.Bool8(false, false, true, true, true, false, true, false))
	assert.Equal(t, byte(57), jay.Bool8(false, false, true, true, true, false, false, true))
	assert.Equal(t, byte(56), jay.Bool8(false, false, true, true, true, false, false, false))
	assert.Equal(t, byte(55), jay.Bool8(false, false, true, true, false, true, true, true))
	assert.Equal(t, byte(54), jay.Bool8(false, false, true, true, false, true, true, false))
	assert.Equal(t, byte(53), jay.Bool8(false, false, true, true, false, true, false, true))
	assert.Equal(t, byte(52), jay.Bool8(false, false, true, true, false, true, false, false))
	assert.Equal(t, byte(51), jay.Bool8(false, false, true, true, false, false, true, true))
	assert.Equal(t, byte(50), jay.Bool8(false, false, true, true, false, false, true, false))
	assert.Equal(t, byte(49), jay.Bool8(false, false, true, true, false, false, false, true))
	assert.Equal(t, byte(48), jay.Bool8(false, false, true, true, false, false, false, false))
	assert.Equal(t, byte(47), jay.Bool8(false, false, true, false, true, true, true, true))
	assert.Equal(t, byte(46), jay.Bool8(false, false, true, false, true, true, true, false))
	assert.Equal(t, byte(45), jay.Bool8(false, false, true, false, true, true, false, true))
	assert.Equal(t, byte(44), jay.Bool8(false, false, true, false, true, true, false, false))
	assert.Equal(t, byte(43), jay.Bool8(false, false, true, false, true, false, true, true))
	assert.Equal(t, byte(42), jay.Bool8(false, false, true, false, true, false, true, false))
	assert.Equal(t, byte(41), jay.Bool8(false, false, true, false, true, false, false, true))
	assert.Equal(t, byte(40), jay.Bool8(false, false, true, false, true, false, false, false))
	assert.Equal(t, byte(39), jay.Bool8(false, false, true, false, false, true, true, true))
	assert.Equal(t, byte(38), jay.Bool8(false, false, true, false, false, true, true, false))
	assert.Equal(t, byte(37), jay.Bool8(false, false, true, false, false, true, false, true))
	assert.Equal(t, byte(36), jay.Bool8(false, false, true, false, false, true, false, false))
	assert.Equal(t, byte(35), jay.Bool8(false, false, true, false, false, false, true, true))
	assert.Equal(t, byte(34), jay.Bool8(false, false, true, false, false, false, true, false))
	assert.Equal(t, byte(33), jay.Bool8(false, false, true, false, false, false, false, true))
	assert.Equal(t, byte(32), jay.Bool8(false, false, true, false, false, false, false, false))
	assert.Equal(t, byte(31), jay.Bool8(false, false, false, true, true, true, true, true))
	assert.Equal(t, byte(30), jay.Bool8(false, false, false, true, true, true, true, false))
	assert.Equal(t, byte(29), jay.Bool8(false, false, false, true, true, true, false, true))
	assert.Equal(t, byte(28), jay.Bool8(false, false, false, true, true, true, false, false))
	assert.Equal(t, byte(27), jay.Bool8(false, false, false, true, true, false, true, true))
	assert.Equal(t, byte(26), jay.Bool8(false, false, false, true, true, false, true, false))
	assert.Equal(t, byte(25), jay.Bool8(false, false, false, true, true, false, false, true))
	assert.Equal(t, byte(24), jay.Bool8(false, false, false, true, true, false, false, false))
	assert.Equal(t, byte(23), jay.Bool8(false, false, false, true, false, true, true, true))
	assert.Equal(t, byte(22), jay.Bool8(false, false, false, true, false, true, true, false))
	assert.Equal(t, byte(21), jay.Bool8(false, false, false, true, false, true, false, true))
	assert.Equal(t, byte(20), jay.Bool8(false, false, false, true, false, true, false, false))
	assert.Equal(t, byte(19), jay.Bool8(false, false, false, true, false, false, true, true))
	assert.Equal(t, byte(18), jay.Bool8(false, false, false, true, false, false, true, false))
	assert.Equal(t, byte(17), jay.Bool8(false, false, false, true, false, false, false, true))
	assert.Equal(t, byte(16), jay.Bool8(false, false, false, true, false, false, false, false))
	assert.Equal(t, byte(15), jay.Bool8(false, false, false, false, true, true, true, true))
	assert.Equal(t, byte(14), jay.Bool8(false, false, false, false, true, true, true, false))
	assert.Equal(t, byte(13), jay.Bool8(false, false, false, false, true, true, false, true))
	assert.Equal(t, byte(12), jay.Bool8(false, false, false, false, true, true, false, false))
	assert.Equal(t, byte(11), jay.Bool8(false, false, false, false, true, false, true, true))
	assert.Equal(t, byte(10), jay.Bool8(false, false, false, false, true, false, true, false))
	assert.Equal(t, byte(9), jay.Bool8(false, false, false, false, true, false, false, true))
	assert.Equal(t, byte(8), jay.Bool8(false, false, false, false, true, false, false, false))
	assert.Equal(t, byte(7), jay.Bool8(false, false, false, false, false, true, true, true))
	assert.Equal(t, byte(6), jay.Bool8(false, false, false, false, false, true, true, false))
	assert.Equal(t, byte(5), jay.Bool8(false, false, false, false, false, true, false, true))
	assert.Equal(t, byte(4), jay.Bool8(false, false, false, false, false, true, false, false))
	assert.Equal(t, byte(3), jay.Bool8(false, false, false, false, false, false, true, true))
	assert.Equal(t, byte(2), jay.Bool8(false, false, false, false, false, false, true, false))
	assert.Equal(t, byte(1), jay.Bool8(false, false, false, false, false, false, false, true))
	assert.Equal(t, byte(0), jay.Bool8(false, false, false, false, false, false, false, false))
}
