package jay

import (
	"github.com/stretchr/testify/assert"
	"math"
	"testing"
)

func TestReadBool1(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 128 {
		assert.Equal(t, byte(i), Bool1(ReadBool1(byte(i))))
	}
}
func TestReadBool2(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 64 {
		assert.Equal(t, byte(i), Bool2(ReadBool2(byte(i))))
	}
}
func TestReadBool3(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 32 {
		assert.Equal(t, byte(i), Bool3(ReadBool3(byte(i))))
	}
}
func TestReadBool4(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 16 {
		assert.Equal(t, byte(i), Bool4(ReadBool4(byte(i))))
	}
}
func TestReadBool5(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 8 {
		assert.Equal(t, byte(i), Bool5(ReadBool5(byte(i))))
	}
}
func TestReadBool6(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 4 {
		assert.Equal(t, byte(i), Bool6(ReadBool6(byte(i))))
	}
}
func TestReadBool7(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i += 2 {
		assert.Equal(t, byte(i), Bool7(ReadBool7(byte(i))))
	}
}
func TestReadBool8(t *testing.T) {
	for i := 0; i <= math.MaxUint8; i++ {
		assert.Equal(t, byte(i), Bool8(ReadBool8(byte(i))))
	}
}

func TestBool1(t *testing.T) {
	assert.Equal(t, byte(128), Bool1(true))
	assert.Equal(t, byte(0), Bool1(false))
}

func TestBool2(t *testing.T) {
	assert.Equal(t, byte(192), Bool2(true, true))
	assert.Equal(t, byte(128), Bool2(true, false))
	assert.Equal(t, byte(64), Bool2(false, true))
	assert.Equal(t, byte(0), Bool2(false, false))
}

func TestBool3(t *testing.T) {
	assert.Equal(t, byte(224), Bool3(true, true, true))
	assert.Equal(t, byte(192), Bool3(true, true, false))
	assert.Equal(t, byte(160), Bool3(true, false, true))
	assert.Equal(t, byte(128), Bool3(true, false, false))
	assert.Equal(t, byte(96), Bool3(false, true, true))
	assert.Equal(t, byte(64), Bool3(false, true, false))
	assert.Equal(t, byte(32), Bool3(false, false, true))
	assert.Equal(t, byte(0), Bool3(false, false, false))
}

func TestBool4(t *testing.T) {
	assert.Equal(t, byte(240), Bool4(true, true, true, true))
	assert.Equal(t, byte(224), Bool4(true, true, true, false))
	assert.Equal(t, byte(208), Bool4(true, true, false, true))
	assert.Equal(t, byte(192), Bool4(true, true, false, false))
	assert.Equal(t, byte(176), Bool4(true, false, true, true))
	assert.Equal(t, byte(160), Bool4(true, false, true, false))
	assert.Equal(t, byte(144), Bool4(true, false, false, true))
	assert.Equal(t, byte(128), Bool4(true, false, false, false))
	assert.Equal(t, byte(112), Bool4(false, true, true, true))
	assert.Equal(t, byte(96), Bool4(false, true, true, false))
	assert.Equal(t, byte(80), Bool4(false, true, false, true))
	assert.Equal(t, byte(64), Bool4(false, true, false, false))
	assert.Equal(t, byte(48), Bool4(false, false, true, true))
	assert.Equal(t, byte(32), Bool4(false, false, true, false))
	assert.Equal(t, byte(16), Bool4(false, false, false, true))
	assert.Equal(t, byte(0), Bool4(false, false, false, false))
}

func TestBool5(t *testing.T) {
	assert.Equal(t, byte(248), Bool5(true, true, true, true, true))
	assert.Equal(t, byte(240), Bool5(true, true, true, true, false))
	assert.Equal(t, byte(232), Bool5(true, true, true, false, true))
	assert.Equal(t, byte(224), Bool5(true, true, true, false, false))
	assert.Equal(t, byte(216), Bool5(true, true, false, true, true))
	assert.Equal(t, byte(208), Bool5(true, true, false, true, false))
	assert.Equal(t, byte(200), Bool5(true, true, false, false, true))
	assert.Equal(t, byte(192), Bool5(true, true, false, false, false))
	assert.Equal(t, byte(184), Bool5(true, false, true, true, true))
	assert.Equal(t, byte(176), Bool5(true, false, true, true, false))
	assert.Equal(t, byte(168), Bool5(true, false, true, false, true))
	assert.Equal(t, byte(160), Bool5(true, false, true, false, false))
	assert.Equal(t, byte(152), Bool5(true, false, false, true, true))
	assert.Equal(t, byte(144), Bool5(true, false, false, true, false))
	assert.Equal(t, byte(136), Bool5(true, false, false, false, true))
	assert.Equal(t, byte(128), Bool5(true, false, false, false, false))
	assert.Equal(t, byte(120), Bool5(false, true, true, true, true))
	assert.Equal(t, byte(112), Bool5(false, true, true, true, false))
	assert.Equal(t, byte(104), Bool5(false, true, true, false, true))
	assert.Equal(t, byte(96), Bool5(false, true, true, false, false))
	assert.Equal(t, byte(88), Bool5(false, true, false, true, true))
	assert.Equal(t, byte(80), Bool5(false, true, false, true, false))
	assert.Equal(t, byte(72), Bool5(false, true, false, false, true))
	assert.Equal(t, byte(64), Bool5(false, true, false, false, false))
	assert.Equal(t, byte(56), Bool5(false, false, true, true, true))
	assert.Equal(t, byte(48), Bool5(false, false, true, true, false))
	assert.Equal(t, byte(40), Bool5(false, false, true, false, true))
	assert.Equal(t, byte(32), Bool5(false, false, true, false, false))
	assert.Equal(t, byte(24), Bool5(false, false, false, true, true))
	assert.Equal(t, byte(16), Bool5(false, false, false, true, false))
	assert.Equal(t, byte(8), Bool5(false, false, false, false, true))
	assert.Equal(t, byte(0), Bool5(false, false, false, false, false))
}

func TestBool6(t *testing.T) {
	assert.Equal(t, byte(252), Bool6(true, true, true, true, true, true))
	assert.Equal(t, byte(248), Bool6(true, true, true, true, true, false))
	assert.Equal(t, byte(244), Bool6(true, true, true, true, false, true))
	assert.Equal(t, byte(240), Bool6(true, true, true, true, false, false))
	assert.Equal(t, byte(236), Bool6(true, true, true, false, true, true))
	assert.Equal(t, byte(232), Bool6(true, true, true, false, true, false))
	assert.Equal(t, byte(228), Bool6(true, true, true, false, false, true))
	assert.Equal(t, byte(224), Bool6(true, true, true, false, false, false))
	assert.Equal(t, byte(220), Bool6(true, true, false, true, true, true))
	assert.Equal(t, byte(216), Bool6(true, true, false, true, true, false))
	assert.Equal(t, byte(212), Bool6(true, true, false, true, false, true))
	assert.Equal(t, byte(208), Bool6(true, true, false, true, false, false))
	assert.Equal(t, byte(204), Bool6(true, true, false, false, true, true))
	assert.Equal(t, byte(200), Bool6(true, true, false, false, true, false))
	assert.Equal(t, byte(196), Bool6(true, true, false, false, false, true))
	assert.Equal(t, byte(192), Bool6(true, true, false, false, false, false))
	assert.Equal(t, byte(188), Bool6(true, false, true, true, true, true))
	assert.Equal(t, byte(184), Bool6(true, false, true, true, true, false))
	assert.Equal(t, byte(180), Bool6(true, false, true, true, false, true))
	assert.Equal(t, byte(176), Bool6(true, false, true, true, false, false))
	assert.Equal(t, byte(172), Bool6(true, false, true, false, true, true))
	assert.Equal(t, byte(168), Bool6(true, false, true, false, true, false))
	assert.Equal(t, byte(164), Bool6(true, false, true, false, false, true))
	assert.Equal(t, byte(160), Bool6(true, false, true, false, false, false))
	assert.Equal(t, byte(156), Bool6(true, false, false, true, true, true))
	assert.Equal(t, byte(152), Bool6(true, false, false, true, true, false))
	assert.Equal(t, byte(148), Bool6(true, false, false, true, false, true))
	assert.Equal(t, byte(144), Bool6(true, false, false, true, false, false))
	assert.Equal(t, byte(140), Bool6(true, false, false, false, true, true))
	assert.Equal(t, byte(136), Bool6(true, false, false, false, true, false))
	assert.Equal(t, byte(132), Bool6(true, false, false, false, false, true))
	assert.Equal(t, byte(128), Bool6(true, false, false, false, false, false))
	assert.Equal(t, byte(124), Bool6(false, true, true, true, true, true))
	assert.Equal(t, byte(120), Bool6(false, true, true, true, true, false))
	assert.Equal(t, byte(116), Bool6(false, true, true, true, false, true))
	assert.Equal(t, byte(112), Bool6(false, true, true, true, false, false))
	assert.Equal(t, byte(108), Bool6(false, true, true, false, true, true))
	assert.Equal(t, byte(104), Bool6(false, true, true, false, true, false))
	assert.Equal(t, byte(100), Bool6(false, true, true, false, false, true))
	assert.Equal(t, byte(96), Bool6(false, true, true, false, false, false))
	assert.Equal(t, byte(92), Bool6(false, true, false, true, true, true))
	assert.Equal(t, byte(88), Bool6(false, true, false, true, true, false))
	assert.Equal(t, byte(84), Bool6(false, true, false, true, false, true))
	assert.Equal(t, byte(80), Bool6(false, true, false, true, false, false))
	assert.Equal(t, byte(76), Bool6(false, true, false, false, true, true))
	assert.Equal(t, byte(72), Bool6(false, true, false, false, true, false))
	assert.Equal(t, byte(68), Bool6(false, true, false, false, false, true))
	assert.Equal(t, byte(64), Bool6(false, true, false, false, false, false))
	assert.Equal(t, byte(60), Bool6(false, false, true, true, true, true))
	assert.Equal(t, byte(56), Bool6(false, false, true, true, true, false))
	assert.Equal(t, byte(52), Bool6(false, false, true, true, false, true))
	assert.Equal(t, byte(48), Bool6(false, false, true, true, false, false))
	assert.Equal(t, byte(44), Bool6(false, false, true, false, true, true))
	assert.Equal(t, byte(40), Bool6(false, false, true, false, true, false))
	assert.Equal(t, byte(36), Bool6(false, false, true, false, false, true))
	assert.Equal(t, byte(32), Bool6(false, false, true, false, false, false))
	assert.Equal(t, byte(28), Bool6(false, false, false, true, true, true))
	assert.Equal(t, byte(24), Bool6(false, false, false, true, true, false))
	assert.Equal(t, byte(20), Bool6(false, false, false, true, false, true))
	assert.Equal(t, byte(16), Bool6(false, false, false, true, false, false))
	assert.Equal(t, byte(12), Bool6(false, false, false, false, true, true))
	assert.Equal(t, byte(8), Bool6(false, false, false, false, true, false))
	assert.Equal(t, byte(4), Bool6(false, false, false, false, false, true))
	assert.Equal(t, byte(0), Bool6(false, false, false, false, false, false))
}

func TestBool7(t *testing.T) {
	assert.Equal(t, byte(254), Bool7(true, true, true, true, true, true, true))
	assert.Equal(t, byte(252), Bool7(true, true, true, true, true, true, false))
	assert.Equal(t, byte(250), Bool7(true, true, true, true, true, false, true))
	assert.Equal(t, byte(248), Bool7(true, true, true, true, true, false, false))
	assert.Equal(t, byte(246), Bool7(true, true, true, true, false, true, true))
	assert.Equal(t, byte(244), Bool7(true, true, true, true, false, true, false))
	assert.Equal(t, byte(242), Bool7(true, true, true, true, false, false, true))
	assert.Equal(t, byte(240), Bool7(true, true, true, true, false, false, false))
	assert.Equal(t, byte(238), Bool7(true, true, true, false, true, true, true))
	assert.Equal(t, byte(236), Bool7(true, true, true, false, true, true, false))
	assert.Equal(t, byte(234), Bool7(true, true, true, false, true, false, true))
	assert.Equal(t, byte(232), Bool7(true, true, true, false, true, false, false))
	assert.Equal(t, byte(230), Bool7(true, true, true, false, false, true, true))
	assert.Equal(t, byte(228), Bool7(true, true, true, false, false, true, false))
	assert.Equal(t, byte(226), Bool7(true, true, true, false, false, false, true))
	assert.Equal(t, byte(224), Bool7(true, true, true, false, false, false, false))
	assert.Equal(t, byte(222), Bool7(true, true, false, true, true, true, true))
	assert.Equal(t, byte(220), Bool7(true, true, false, true, true, true, false))
	assert.Equal(t, byte(218), Bool7(true, true, false, true, true, false, true))
	assert.Equal(t, byte(216), Bool7(true, true, false, true, true, false, false))
	assert.Equal(t, byte(214), Bool7(true, true, false, true, false, true, true))
	assert.Equal(t, byte(212), Bool7(true, true, false, true, false, true, false))
	assert.Equal(t, byte(210), Bool7(true, true, false, true, false, false, true))
	assert.Equal(t, byte(208), Bool7(true, true, false, true, false, false, false))
	assert.Equal(t, byte(206), Bool7(true, true, false, false, true, true, true))
	assert.Equal(t, byte(204), Bool7(true, true, false, false, true, true, false))
	assert.Equal(t, byte(202), Bool7(true, true, false, false, true, false, true))
	assert.Equal(t, byte(200), Bool7(true, true, false, false, true, false, false))
	assert.Equal(t, byte(198), Bool7(true, true, false, false, false, true, true))
	assert.Equal(t, byte(196), Bool7(true, true, false, false, false, true, false))
	assert.Equal(t, byte(194), Bool7(true, true, false, false, false, false, true))
	assert.Equal(t, byte(192), Bool7(true, true, false, false, false, false, false))
	assert.Equal(t, byte(190), Bool7(true, false, true, true, true, true, true))
	assert.Equal(t, byte(188), Bool7(true, false, true, true, true, true, false))
	assert.Equal(t, byte(186), Bool7(true, false, true, true, true, false, true))
	assert.Equal(t, byte(184), Bool7(true, false, true, true, true, false, false))
	assert.Equal(t, byte(182), Bool7(true, false, true, true, false, true, true))
	assert.Equal(t, byte(180), Bool7(true, false, true, true, false, true, false))
	assert.Equal(t, byte(178), Bool7(true, false, true, true, false, false, true))
	assert.Equal(t, byte(176), Bool7(true, false, true, true, false, false, false))
	assert.Equal(t, byte(174), Bool7(true, false, true, false, true, true, true))
	assert.Equal(t, byte(172), Bool7(true, false, true, false, true, true, false))
	assert.Equal(t, byte(170), Bool7(true, false, true, false, true, false, true))
	assert.Equal(t, byte(168), Bool7(true, false, true, false, true, false, false))
	assert.Equal(t, byte(166), Bool7(true, false, true, false, false, true, true))
	assert.Equal(t, byte(164), Bool7(true, false, true, false, false, true, false))
	assert.Equal(t, byte(162), Bool7(true, false, true, false, false, false, true))
	assert.Equal(t, byte(160), Bool7(true, false, true, false, false, false, false))
	assert.Equal(t, byte(158), Bool7(true, false, false, true, true, true, true))
	assert.Equal(t, byte(156), Bool7(true, false, false, true, true, true, false))
	assert.Equal(t, byte(154), Bool7(true, false, false, true, true, false, true))
	assert.Equal(t, byte(152), Bool7(true, false, false, true, true, false, false))
	assert.Equal(t, byte(150), Bool7(true, false, false, true, false, true, true))
	assert.Equal(t, byte(148), Bool7(true, false, false, true, false, true, false))
	assert.Equal(t, byte(146), Bool7(true, false, false, true, false, false, true))
	assert.Equal(t, byte(144), Bool7(true, false, false, true, false, false, false))
	assert.Equal(t, byte(142), Bool7(true, false, false, false, true, true, true))
	assert.Equal(t, byte(140), Bool7(true, false, false, false, true, true, false))
	assert.Equal(t, byte(138), Bool7(true, false, false, false, true, false, true))
	assert.Equal(t, byte(136), Bool7(true, false, false, false, true, false, false))
	assert.Equal(t, byte(134), Bool7(true, false, false, false, false, true, true))
	assert.Equal(t, byte(132), Bool7(true, false, false, false, false, true, false))
	assert.Equal(t, byte(130), Bool7(true, false, false, false, false, false, true))
	assert.Equal(t, byte(128), Bool7(true, false, false, false, false, false, false))
	assert.Equal(t, byte(126), Bool7(false, true, true, true, true, true, true))
	assert.Equal(t, byte(124), Bool7(false, true, true, true, true, true, false))
	assert.Equal(t, byte(122), Bool7(false, true, true, true, true, false, true))
	assert.Equal(t, byte(120), Bool7(false, true, true, true, true, false, false))
	assert.Equal(t, byte(118), Bool7(false, true, true, true, false, true, true))
	assert.Equal(t, byte(116), Bool7(false, true, true, true, false, true, false))
	assert.Equal(t, byte(114), Bool7(false, true, true, true, false, false, true))
	assert.Equal(t, byte(112), Bool7(false, true, true, true, false, false, false))
	assert.Equal(t, byte(110), Bool7(false, true, true, false, true, true, true))
	assert.Equal(t, byte(108), Bool7(false, true, true, false, true, true, false))
	assert.Equal(t, byte(106), Bool7(false, true, true, false, true, false, true))
	assert.Equal(t, byte(104), Bool7(false, true, true, false, true, false, false))
	assert.Equal(t, byte(102), Bool7(false, true, true, false, false, true, true))
	assert.Equal(t, byte(100), Bool7(false, true, true, false, false, true, false))
	assert.Equal(t, byte(98), Bool7(false, true, true, false, false, false, true))
	assert.Equal(t, byte(96), Bool7(false, true, true, false, false, false, false))
	assert.Equal(t, byte(94), Bool7(false, true, false, true, true, true, true))
	assert.Equal(t, byte(92), Bool7(false, true, false, true, true, true, false))
	assert.Equal(t, byte(90), Bool7(false, true, false, true, true, false, true))
	assert.Equal(t, byte(88), Bool7(false, true, false, true, true, false, false))
	assert.Equal(t, byte(86), Bool7(false, true, false, true, false, true, true))
	assert.Equal(t, byte(84), Bool7(false, true, false, true, false, true, false))
	assert.Equal(t, byte(82), Bool7(false, true, false, true, false, false, true))
	assert.Equal(t, byte(80), Bool7(false, true, false, true, false, false, false))
	assert.Equal(t, byte(78), Bool7(false, true, false, false, true, true, true))
	assert.Equal(t, byte(76), Bool7(false, true, false, false, true, true, false))
	assert.Equal(t, byte(74), Bool7(false, true, false, false, true, false, true))
	assert.Equal(t, byte(72), Bool7(false, true, false, false, true, false, false))
	assert.Equal(t, byte(70), Bool7(false, true, false, false, false, true, true))
	assert.Equal(t, byte(68), Bool7(false, true, false, false, false, true, false))
	assert.Equal(t, byte(66), Bool7(false, true, false, false, false, false, true))
	assert.Equal(t, byte(64), Bool7(false, true, false, false, false, false, false))
	assert.Equal(t, byte(62), Bool7(false, false, true, true, true, true, true))
	assert.Equal(t, byte(60), Bool7(false, false, true, true, true, true, false))
	assert.Equal(t, byte(58), Bool7(false, false, true, true, true, false, true))
	assert.Equal(t, byte(56), Bool7(false, false, true, true, true, false, false))
	assert.Equal(t, byte(54), Bool7(false, false, true, true, false, true, true))
	assert.Equal(t, byte(52), Bool7(false, false, true, true, false, true, false))
	assert.Equal(t, byte(50), Bool7(false, false, true, true, false, false, true))
	assert.Equal(t, byte(48), Bool7(false, false, true, true, false, false, false))
	assert.Equal(t, byte(46), Bool7(false, false, true, false, true, true, true))
	assert.Equal(t, byte(44), Bool7(false, false, true, false, true, true, false))
	assert.Equal(t, byte(42), Bool7(false, false, true, false, true, false, true))
	assert.Equal(t, byte(40), Bool7(false, false, true, false, true, false, false))
	assert.Equal(t, byte(38), Bool7(false, false, true, false, false, true, true))
	assert.Equal(t, byte(36), Bool7(false, false, true, false, false, true, false))
	assert.Equal(t, byte(34), Bool7(false, false, true, false, false, false, true))
	assert.Equal(t, byte(32), Bool7(false, false, true, false, false, false, false))
	assert.Equal(t, byte(30), Bool7(false, false, false, true, true, true, true))
	assert.Equal(t, byte(28), Bool7(false, false, false, true, true, true, false))
	assert.Equal(t, byte(26), Bool7(false, false, false, true, true, false, true))
	assert.Equal(t, byte(24), Bool7(false, false, false, true, true, false, false))
	assert.Equal(t, byte(22), Bool7(false, false, false, true, false, true, true))
	assert.Equal(t, byte(20), Bool7(false, false, false, true, false, true, false))
	assert.Equal(t, byte(18), Bool7(false, false, false, true, false, false, true))
	assert.Equal(t, byte(16), Bool7(false, false, false, true, false, false, false))
	assert.Equal(t, byte(14), Bool7(false, false, false, false, true, true, true))
	assert.Equal(t, byte(12), Bool7(false, false, false, false, true, true, false))
	assert.Equal(t, byte(10), Bool7(false, false, false, false, true, false, true))
	assert.Equal(t, byte(8), Bool7(false, false, false, false, true, false, false))
	assert.Equal(t, byte(6), Bool7(false, false, false, false, false, true, true))
	assert.Equal(t, byte(4), Bool7(false, false, false, false, false, true, false))
	assert.Equal(t, byte(2), Bool7(false, false, false, false, false, false, true))
	assert.Equal(t, byte(0), Bool7(false, false, false, false, false, false, false))
}
func TestBool8(t *testing.T) {
	assert.Equal(t, byte(255), Bool8(true, true, true, true, true, true, true, true))
	assert.Equal(t, byte(254), Bool8(true, true, true, true, true, true, true, false))
	assert.Equal(t, byte(253), Bool8(true, true, true, true, true, true, false, true))
	assert.Equal(t, byte(252), Bool8(true, true, true, true, true, true, false, false))
	assert.Equal(t, byte(251), Bool8(true, true, true, true, true, false, true, true))
	assert.Equal(t, byte(250), Bool8(true, true, true, true, true, false, true, false))
	assert.Equal(t, byte(249), Bool8(true, true, true, true, true, false, false, true))
	assert.Equal(t, byte(248), Bool8(true, true, true, true, true, false, false, false))
	assert.Equal(t, byte(247), Bool8(true, true, true, true, false, true, true, true))
	assert.Equal(t, byte(246), Bool8(true, true, true, true, false, true, true, false))
	assert.Equal(t, byte(245), Bool8(true, true, true, true, false, true, false, true))
	assert.Equal(t, byte(244), Bool8(true, true, true, true, false, true, false, false))
	assert.Equal(t, byte(243), Bool8(true, true, true, true, false, false, true, true))
	assert.Equal(t, byte(242), Bool8(true, true, true, true, false, false, true, false))
	assert.Equal(t, byte(241), Bool8(true, true, true, true, false, false, false, true))
	assert.Equal(t, byte(240), Bool8(true, true, true, true, false, false, false, false))
	assert.Equal(t, byte(239), Bool8(true, true, true, false, true, true, true, true))
	assert.Equal(t, byte(238), Bool8(true, true, true, false, true, true, true, false))
	assert.Equal(t, byte(237), Bool8(true, true, true, false, true, true, false, true))
	assert.Equal(t, byte(236), Bool8(true, true, true, false, true, true, false, false))
	assert.Equal(t, byte(235), Bool8(true, true, true, false, true, false, true, true))
	assert.Equal(t, byte(234), Bool8(true, true, true, false, true, false, true, false))
	assert.Equal(t, byte(233), Bool8(true, true, true, false, true, false, false, true))
	assert.Equal(t, byte(232), Bool8(true, true, true, false, true, false, false, false))
	assert.Equal(t, byte(231), Bool8(true, true, true, false, false, true, true, true))
	assert.Equal(t, byte(230), Bool8(true, true, true, false, false, true, true, false))
	assert.Equal(t, byte(229), Bool8(true, true, true, false, false, true, false, true))
	assert.Equal(t, byte(228), Bool8(true, true, true, false, false, true, false, false))
	assert.Equal(t, byte(227), Bool8(true, true, true, false, false, false, true, true))
	assert.Equal(t, byte(226), Bool8(true, true, true, false, false, false, true, false))
	assert.Equal(t, byte(225), Bool8(true, true, true, false, false, false, false, true))
	assert.Equal(t, byte(224), Bool8(true, true, true, false, false, false, false, false))
	assert.Equal(t, byte(223), Bool8(true, true, false, true, true, true, true, true))
	assert.Equal(t, byte(222), Bool8(true, true, false, true, true, true, true, false))
	assert.Equal(t, byte(221), Bool8(true, true, false, true, true, true, false, true))
	assert.Equal(t, byte(220), Bool8(true, true, false, true, true, true, false, false))
	assert.Equal(t, byte(219), Bool8(true, true, false, true, true, false, true, true))
	assert.Equal(t, byte(218), Bool8(true, true, false, true, true, false, true, false))
	assert.Equal(t, byte(217), Bool8(true, true, false, true, true, false, false, true))
	assert.Equal(t, byte(216), Bool8(true, true, false, true, true, false, false, false))
	assert.Equal(t, byte(215), Bool8(true, true, false, true, false, true, true, true))
	assert.Equal(t, byte(214), Bool8(true, true, false, true, false, true, true, false))
	assert.Equal(t, byte(213), Bool8(true, true, false, true, false, true, false, true))
	assert.Equal(t, byte(212), Bool8(true, true, false, true, false, true, false, false))
	assert.Equal(t, byte(211), Bool8(true, true, false, true, false, false, true, true))
	assert.Equal(t, byte(210), Bool8(true, true, false, true, false, false, true, false))
	assert.Equal(t, byte(209), Bool8(true, true, false, true, false, false, false, true))
	assert.Equal(t, byte(208), Bool8(true, true, false, true, false, false, false, false))
	assert.Equal(t, byte(207), Bool8(true, true, false, false, true, true, true, true))
	assert.Equal(t, byte(206), Bool8(true, true, false, false, true, true, true, false))
	assert.Equal(t, byte(205), Bool8(true, true, false, false, true, true, false, true))
	assert.Equal(t, byte(204), Bool8(true, true, false, false, true, true, false, false))
	assert.Equal(t, byte(203), Bool8(true, true, false, false, true, false, true, true))
	assert.Equal(t, byte(202), Bool8(true, true, false, false, true, false, true, false))
	assert.Equal(t, byte(201), Bool8(true, true, false, false, true, false, false, true))
	assert.Equal(t, byte(200), Bool8(true, true, false, false, true, false, false, false))
	assert.Equal(t, byte(199), Bool8(true, true, false, false, false, true, true, true))
	assert.Equal(t, byte(198), Bool8(true, true, false, false, false, true, true, false))
	assert.Equal(t, byte(197), Bool8(true, true, false, false, false, true, false, true))
	assert.Equal(t, byte(196), Bool8(true, true, false, false, false, true, false, false))
	assert.Equal(t, byte(195), Bool8(true, true, false, false, false, false, true, true))
	assert.Equal(t, byte(194), Bool8(true, true, false, false, false, false, true, false))
	assert.Equal(t, byte(193), Bool8(true, true, false, false, false, false, false, true))
	assert.Equal(t, byte(192), Bool8(true, true, false, false, false, false, false, false))
	assert.Equal(t, byte(191), Bool8(true, false, true, true, true, true, true, true))
	assert.Equal(t, byte(190), Bool8(true, false, true, true, true, true, true, false))
	assert.Equal(t, byte(189), Bool8(true, false, true, true, true, true, false, true))
	assert.Equal(t, byte(188), Bool8(true, false, true, true, true, true, false, false))
	assert.Equal(t, byte(187), Bool8(true, false, true, true, true, false, true, true))
	assert.Equal(t, byte(186), Bool8(true, false, true, true, true, false, true, false))
	assert.Equal(t, byte(185), Bool8(true, false, true, true, true, false, false, true))
	assert.Equal(t, byte(184), Bool8(true, false, true, true, true, false, false, false))
	assert.Equal(t, byte(183), Bool8(true, false, true, true, false, true, true, true))
	assert.Equal(t, byte(182), Bool8(true, false, true, true, false, true, true, false))
	assert.Equal(t, byte(181), Bool8(true, false, true, true, false, true, false, true))
	assert.Equal(t, byte(180), Bool8(true, false, true, true, false, true, false, false))
	assert.Equal(t, byte(179), Bool8(true, false, true, true, false, false, true, true))
	assert.Equal(t, byte(178), Bool8(true, false, true, true, false, false, true, false))
	assert.Equal(t, byte(177), Bool8(true, false, true, true, false, false, false, true))
	assert.Equal(t, byte(176), Bool8(true, false, true, true, false, false, false, false))
	assert.Equal(t, byte(175), Bool8(true, false, true, false, true, true, true, true))
	assert.Equal(t, byte(174), Bool8(true, false, true, false, true, true, true, false))
	assert.Equal(t, byte(173), Bool8(true, false, true, false, true, true, false, true))
	assert.Equal(t, byte(172), Bool8(true, false, true, false, true, true, false, false))
	assert.Equal(t, byte(171), Bool8(true, false, true, false, true, false, true, true))
	assert.Equal(t, byte(170), Bool8(true, false, true, false, true, false, true, false))
	assert.Equal(t, byte(169), Bool8(true, false, true, false, true, false, false, true))
	assert.Equal(t, byte(168), Bool8(true, false, true, false, true, false, false, false))
	assert.Equal(t, byte(167), Bool8(true, false, true, false, false, true, true, true))
	assert.Equal(t, byte(166), Bool8(true, false, true, false, false, true, true, false))
	assert.Equal(t, byte(165), Bool8(true, false, true, false, false, true, false, true))
	assert.Equal(t, byte(164), Bool8(true, false, true, false, false, true, false, false))
	assert.Equal(t, byte(163), Bool8(true, false, true, false, false, false, true, true))
	assert.Equal(t, byte(162), Bool8(true, false, true, false, false, false, true, false))
	assert.Equal(t, byte(161), Bool8(true, false, true, false, false, false, false, true))
	assert.Equal(t, byte(160), Bool8(true, false, true, false, false, false, false, false))
	assert.Equal(t, byte(159), Bool8(true, false, false, true, true, true, true, true))
	assert.Equal(t, byte(158), Bool8(true, false, false, true, true, true, true, false))
	assert.Equal(t, byte(157), Bool8(true, false, false, true, true, true, false, true))
	assert.Equal(t, byte(156), Bool8(true, false, false, true, true, true, false, false))
	assert.Equal(t, byte(155), Bool8(true, false, false, true, true, false, true, true))
	assert.Equal(t, byte(154), Bool8(true, false, false, true, true, false, true, false))
	assert.Equal(t, byte(153), Bool8(true, false, false, true, true, false, false, true))
	assert.Equal(t, byte(152), Bool8(true, false, false, true, true, false, false, false))
	assert.Equal(t, byte(151), Bool8(true, false, false, true, false, true, true, true))
	assert.Equal(t, byte(150), Bool8(true, false, false, true, false, true, true, false))
	assert.Equal(t, byte(149), Bool8(true, false, false, true, false, true, false, true))
	assert.Equal(t, byte(148), Bool8(true, false, false, true, false, true, false, false))
	assert.Equal(t, byte(147), Bool8(true, false, false, true, false, false, true, true))
	assert.Equal(t, byte(146), Bool8(true, false, false, true, false, false, true, false))
	assert.Equal(t, byte(145), Bool8(true, false, false, true, false, false, false, true))
	assert.Equal(t, byte(144), Bool8(true, false, false, true, false, false, false, false))
	assert.Equal(t, byte(143), Bool8(true, false, false, false, true, true, true, true))
	assert.Equal(t, byte(142), Bool8(true, false, false, false, true, true, true, false))
	assert.Equal(t, byte(141), Bool8(true, false, false, false, true, true, false, true))
	assert.Equal(t, byte(140), Bool8(true, false, false, false, true, true, false, false))
	assert.Equal(t, byte(139), Bool8(true, false, false, false, true, false, true, true))
	assert.Equal(t, byte(138), Bool8(true, false, false, false, true, false, true, false))
	assert.Equal(t, byte(137), Bool8(true, false, false, false, true, false, false, true))
	assert.Equal(t, byte(136), Bool8(true, false, false, false, true, false, false, false))
	assert.Equal(t, byte(135), Bool8(true, false, false, false, false, true, true, true))
	assert.Equal(t, byte(134), Bool8(true, false, false, false, false, true, true, false))
	assert.Equal(t, byte(133), Bool8(true, false, false, false, false, true, false, true))
	assert.Equal(t, byte(132), Bool8(true, false, false, false, false, true, false, false))
	assert.Equal(t, byte(131), Bool8(true, false, false, false, false, false, true, true))
	assert.Equal(t, byte(130), Bool8(true, false, false, false, false, false, true, false))
	assert.Equal(t, byte(129), Bool8(true, false, false, false, false, false, false, true))
	assert.Equal(t, byte(128), Bool8(true, false, false, false, false, false, false, false))
	assert.Equal(t, byte(127), Bool8(false, true, true, true, true, true, true, true))
	assert.Equal(t, byte(126), Bool8(false, true, true, true, true, true, true, false))
	assert.Equal(t, byte(125), Bool8(false, true, true, true, true, true, false, true))
	assert.Equal(t, byte(124), Bool8(false, true, true, true, true, true, false, false))
	assert.Equal(t, byte(123), Bool8(false, true, true, true, true, false, true, true))
	assert.Equal(t, byte(122), Bool8(false, true, true, true, true, false, true, false))
	assert.Equal(t, byte(121), Bool8(false, true, true, true, true, false, false, true))
	assert.Equal(t, byte(120), Bool8(false, true, true, true, true, false, false, false))
	assert.Equal(t, byte(119), Bool8(false, true, true, true, false, true, true, true))
	assert.Equal(t, byte(118), Bool8(false, true, true, true, false, true, true, false))
	assert.Equal(t, byte(117), Bool8(false, true, true, true, false, true, false, true))
	assert.Equal(t, byte(116), Bool8(false, true, true, true, false, true, false, false))
	assert.Equal(t, byte(115), Bool8(false, true, true, true, false, false, true, true))
	assert.Equal(t, byte(114), Bool8(false, true, true, true, false, false, true, false))
	assert.Equal(t, byte(113), Bool8(false, true, true, true, false, false, false, true))
	assert.Equal(t, byte(112), Bool8(false, true, true, true, false, false, false, false))
	assert.Equal(t, byte(111), Bool8(false, true, true, false, true, true, true, true))
	assert.Equal(t, byte(110), Bool8(false, true, true, false, true, true, true, false))
	assert.Equal(t, byte(109), Bool8(false, true, true, false, true, true, false, true))
	assert.Equal(t, byte(108), Bool8(false, true, true, false, true, true, false, false))
	assert.Equal(t, byte(107), Bool8(false, true, true, false, true, false, true, true))
	assert.Equal(t, byte(106), Bool8(false, true, true, false, true, false, true, false))
	assert.Equal(t, byte(105), Bool8(false, true, true, false, true, false, false, true))
	assert.Equal(t, byte(104), Bool8(false, true, true, false, true, false, false, false))
	assert.Equal(t, byte(103), Bool8(false, true, true, false, false, true, true, true))
	assert.Equal(t, byte(102), Bool8(false, true, true, false, false, true, true, false))
	assert.Equal(t, byte(101), Bool8(false, true, true, false, false, true, false, true))
	assert.Equal(t, byte(100), Bool8(false, true, true, false, false, true, false, false))
	assert.Equal(t, byte(99), Bool8(false, true, true, false, false, false, true, true))
	assert.Equal(t, byte(98), Bool8(false, true, true, false, false, false, true, false))
	assert.Equal(t, byte(97), Bool8(false, true, true, false, false, false, false, true))
	assert.Equal(t, byte(96), Bool8(false, true, true, false, false, false, false, false))
	assert.Equal(t, byte(95), Bool8(false, true, false, true, true, true, true, true))
	assert.Equal(t, byte(94), Bool8(false, true, false, true, true, true, true, false))
	assert.Equal(t, byte(93), Bool8(false, true, false, true, true, true, false, true))
	assert.Equal(t, byte(92), Bool8(false, true, false, true, true, true, false, false))
	assert.Equal(t, byte(91), Bool8(false, true, false, true, true, false, true, true))
	assert.Equal(t, byte(90), Bool8(false, true, false, true, true, false, true, false))
	assert.Equal(t, byte(89), Bool8(false, true, false, true, true, false, false, true))
	assert.Equal(t, byte(88), Bool8(false, true, false, true, true, false, false, false))
	assert.Equal(t, byte(87), Bool8(false, true, false, true, false, true, true, true))
	assert.Equal(t, byte(86), Bool8(false, true, false, true, false, true, true, false))
	assert.Equal(t, byte(85), Bool8(false, true, false, true, false, true, false, true))
	assert.Equal(t, byte(84), Bool8(false, true, false, true, false, true, false, false))
	assert.Equal(t, byte(83), Bool8(false, true, false, true, false, false, true, true))
	assert.Equal(t, byte(82), Bool8(false, true, false, true, false, false, true, false))
	assert.Equal(t, byte(81), Bool8(false, true, false, true, false, false, false, true))
	assert.Equal(t, byte(80), Bool8(false, true, false, true, false, false, false, false))
	assert.Equal(t, byte(79), Bool8(false, true, false, false, true, true, true, true))
	assert.Equal(t, byte(78), Bool8(false, true, false, false, true, true, true, false))
	assert.Equal(t, byte(77), Bool8(false, true, false, false, true, true, false, true))
	assert.Equal(t, byte(76), Bool8(false, true, false, false, true, true, false, false))
	assert.Equal(t, byte(75), Bool8(false, true, false, false, true, false, true, true))
	assert.Equal(t, byte(74), Bool8(false, true, false, false, true, false, true, false))
	assert.Equal(t, byte(73), Bool8(false, true, false, false, true, false, false, true))
	assert.Equal(t, byte(72), Bool8(false, true, false, false, true, false, false, false))
	assert.Equal(t, byte(71), Bool8(false, true, false, false, false, true, true, true))
	assert.Equal(t, byte(70), Bool8(false, true, false, false, false, true, true, false))
	assert.Equal(t, byte(69), Bool8(false, true, false, false, false, true, false, true))
	assert.Equal(t, byte(68), Bool8(false, true, false, false, false, true, false, false))
	assert.Equal(t, byte(67), Bool8(false, true, false, false, false, false, true, true))
	assert.Equal(t, byte(66), Bool8(false, true, false, false, false, false, true, false))
	assert.Equal(t, byte(65), Bool8(false, true, false, false, false, false, false, true))
	assert.Equal(t, byte(64), Bool8(false, true, false, false, false, false, false, false))
	assert.Equal(t, byte(63), Bool8(false, false, true, true, true, true, true, true))
	assert.Equal(t, byte(62), Bool8(false, false, true, true, true, true, true, false))
	assert.Equal(t, byte(61), Bool8(false, false, true, true, true, true, false, true))
	assert.Equal(t, byte(60), Bool8(false, false, true, true, true, true, false, false))
	assert.Equal(t, byte(59), Bool8(false, false, true, true, true, false, true, true))
	assert.Equal(t, byte(58), Bool8(false, false, true, true, true, false, true, false))
	assert.Equal(t, byte(57), Bool8(false, false, true, true, true, false, false, true))
	assert.Equal(t, byte(56), Bool8(false, false, true, true, true, false, false, false))
	assert.Equal(t, byte(55), Bool8(false, false, true, true, false, true, true, true))
	assert.Equal(t, byte(54), Bool8(false, false, true, true, false, true, true, false))
	assert.Equal(t, byte(53), Bool8(false, false, true, true, false, true, false, true))
	assert.Equal(t, byte(52), Bool8(false, false, true, true, false, true, false, false))
	assert.Equal(t, byte(51), Bool8(false, false, true, true, false, false, true, true))
	assert.Equal(t, byte(50), Bool8(false, false, true, true, false, false, true, false))
	assert.Equal(t, byte(49), Bool8(false, false, true, true, false, false, false, true))
	assert.Equal(t, byte(48), Bool8(false, false, true, true, false, false, false, false))
	assert.Equal(t, byte(47), Bool8(false, false, true, false, true, true, true, true))
	assert.Equal(t, byte(46), Bool8(false, false, true, false, true, true, true, false))
	assert.Equal(t, byte(45), Bool8(false, false, true, false, true, true, false, true))
	assert.Equal(t, byte(44), Bool8(false, false, true, false, true, true, false, false))
	assert.Equal(t, byte(43), Bool8(false, false, true, false, true, false, true, true))
	assert.Equal(t, byte(42), Bool8(false, false, true, false, true, false, true, false))
	assert.Equal(t, byte(41), Bool8(false, false, true, false, true, false, false, true))
	assert.Equal(t, byte(40), Bool8(false, false, true, false, true, false, false, false))
	assert.Equal(t, byte(39), Bool8(false, false, true, false, false, true, true, true))
	assert.Equal(t, byte(38), Bool8(false, false, true, false, false, true, true, false))
	assert.Equal(t, byte(37), Bool8(false, false, true, false, false, true, false, true))
	assert.Equal(t, byte(36), Bool8(false, false, true, false, false, true, false, false))
	assert.Equal(t, byte(35), Bool8(false, false, true, false, false, false, true, true))
	assert.Equal(t, byte(34), Bool8(false, false, true, false, false, false, true, false))
	assert.Equal(t, byte(33), Bool8(false, false, true, false, false, false, false, true))
	assert.Equal(t, byte(32), Bool8(false, false, true, false, false, false, false, false))
	assert.Equal(t, byte(31), Bool8(false, false, false, true, true, true, true, true))
	assert.Equal(t, byte(30), Bool8(false, false, false, true, true, true, true, false))
	assert.Equal(t, byte(29), Bool8(false, false, false, true, true, true, false, true))
	assert.Equal(t, byte(28), Bool8(false, false, false, true, true, true, false, false))
	assert.Equal(t, byte(27), Bool8(false, false, false, true, true, false, true, true))
	assert.Equal(t, byte(26), Bool8(false, false, false, true, true, false, true, false))
	assert.Equal(t, byte(25), Bool8(false, false, false, true, true, false, false, true))
	assert.Equal(t, byte(24), Bool8(false, false, false, true, true, false, false, false))
	assert.Equal(t, byte(23), Bool8(false, false, false, true, false, true, true, true))
	assert.Equal(t, byte(22), Bool8(false, false, false, true, false, true, true, false))
	assert.Equal(t, byte(21), Bool8(false, false, false, true, false, true, false, true))
	assert.Equal(t, byte(20), Bool8(false, false, false, true, false, true, false, false))
	assert.Equal(t, byte(19), Bool8(false, false, false, true, false, false, true, true))
	assert.Equal(t, byte(18), Bool8(false, false, false, true, false, false, true, false))
	assert.Equal(t, byte(17), Bool8(false, false, false, true, false, false, false, true))
	assert.Equal(t, byte(16), Bool8(false, false, false, true, false, false, false, false))
	assert.Equal(t, byte(15), Bool8(false, false, false, false, true, true, true, true))
	assert.Equal(t, byte(14), Bool8(false, false, false, false, true, true, true, false))
	assert.Equal(t, byte(13), Bool8(false, false, false, false, true, true, false, true))
	assert.Equal(t, byte(12), Bool8(false, false, false, false, true, true, false, false))
	assert.Equal(t, byte(11), Bool8(false, false, false, false, true, false, true, true))
	assert.Equal(t, byte(10), Bool8(false, false, false, false, true, false, true, false))
	assert.Equal(t, byte(9), Bool8(false, false, false, false, true, false, false, true))
	assert.Equal(t, byte(8), Bool8(false, false, false, false, true, false, false, false))
	assert.Equal(t, byte(7), Bool8(false, false, false, false, false, true, true, true))
	assert.Equal(t, byte(6), Bool8(false, false, false, false, false, true, true, false))
	assert.Equal(t, byte(5), Bool8(false, false, false, false, false, true, false, true))
	assert.Equal(t, byte(4), Bool8(false, false, false, false, false, true, false, false))
	assert.Equal(t, byte(3), Bool8(false, false, false, false, false, false, true, true))
	assert.Equal(t, byte(2), Bool8(false, false, false, false, false, false, true, false))
	assert.Equal(t, byte(1), Bool8(false, false, false, false, false, false, false, true))
	assert.Equal(t, byte(0), Bool8(false, false, false, false, false, false, false, false))
}
