// Code generated by Jay; DO NOT EDIT. Tool documentation available at: https://github.com/speedyhoon/jay

package main

import "github.com/speedyhoon/jay"

func (o *One) MarshalJ() []byte {
	return []byte{jay.Bool1(o.One)}
}

func (o *One) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	o.One = jay.ReadBool1(b[0])
	return nil
}

func (t *Two) MarshalJ() []byte {
	return []byte{jay.Bool2(t.One, t.Two)}
}

func (t *Two) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two = jay.ReadBool2(b[0])
	return nil
}

func (t *Three) MarshalJ() []byte {
	return []byte{jay.Bool3(t.One, t.Two, t.Three)}
}

func (t *Three) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three = jay.ReadBool3(b[0])
	return nil
}

func (f *Four) MarshalJ() []byte {
	return []byte{jay.Bool4(f.One, f.Two, f.Three, f.Four)}
}

func (f *Four) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	f.One, f.Two, f.Three, f.Four = jay.ReadBool4(b[0])
	return nil
}

func (f *Five) MarshalJ() []byte {
	return []byte{jay.Bool5(f.One, f.Two, f.Three, f.Four, f.Five)}
}

func (f *Five) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	f.One, f.Two, f.Three, f.Four, f.Five = jay.ReadBool5(b[0])
	return nil
}

func (s *Six) MarshalJ() []byte {
	return []byte{jay.Bool6(s.One, s.Two, s.Three, s.Four, s.Five, s.Six)}
}

func (s *Six) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	s.One, s.Two, s.Three, s.Four, s.Five, s.Six = jay.ReadBool6(b[0])
	return nil
}

func (s *Seven) MarshalJ() []byte {
	return []byte{jay.Bool7(s.One, s.Two, s.Three, s.Four, s.Five, s.Six, s.Seven)}
}

func (s *Seven) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	s.One, s.Two, s.Three, s.Four, s.Five, s.Six, s.Seven = jay.ReadBool7(b[0])
	return nil
}

func (e *Eight) MarshalJ() []byte {
	return []byte{jay.Bool8(e.One, e.Two, e.Three, e.Four, e.Five, e.Six, e.Seven, e.Eight)}
}

func (e *Eight) UnmarshalJ(b []byte) error {
	if len(b) < 1 {
		return jay.ErrUnexpectedEOB
	}
	e.One, e.Two, e.Three, e.Four, e.Five, e.Six, e.Seven, e.Eight = jay.ReadBool8(b[0])
	return nil
}

func (n *Nine) MarshalJ() []byte {
	return []byte{jay.Bool8(n.One, n.Two, n.Three, n.Four, n.Five, n.Six, n.Seven, n.Eight), jay.Bool1(n.Nine)}
}

func (n *Nine) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	n.One, n.Two, n.Three, n.Four, n.Five, n.Six, n.Seven, n.Eight = jay.ReadBool8(b[0])
	n.Nine = jay.ReadBool1(b[1])
	return nil
}

func (t *Ten) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool2(t.Nine, t.Ten)}
}

func (t *Ten) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten = jay.ReadBool2(b[1])
	return nil
}

func (e *Eleven) MarshalJ() []byte {
	return []byte{jay.Bool8(e.One, e.Two, e.Three, e.Four, e.Five, e.Six, e.Seven, e.Eight), jay.Bool3(e.Nine, e.Ten, e.Eleven)}
}

func (e *Eleven) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	e.One, e.Two, e.Three, e.Four, e.Five, e.Six, e.Seven, e.Eight = jay.ReadBool8(b[0])
	e.Nine, e.Ten, e.Eleven = jay.ReadBool3(b[1])
	return nil
}

func (t *Twelve) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool4(t.Nine, t.Ten, t.Eleven, t.Twelve)}
}

func (t *Twelve) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten, t.Eleven, t.Twelve = jay.ReadBool4(b[1])
	return nil
}

func (t *Thirteen) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool5(t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen)}
}

func (t *Thirteen) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen = jay.ReadBool5(b[1])
	return nil
}

func (f *Fourteen) MarshalJ() []byte {
	return []byte{jay.Bool8(f.One, f.Two, f.Three, f.Four, f.Five, f.Six, f.Seven, f.Eight), jay.Bool6(f.Nine, f.Ten, f.Eleven, f.Twelve, f.Thirteen, f.Fourteen)}
}

func (f *Fourteen) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	f.One, f.Two, f.Three, f.Four, f.Five, f.Six, f.Seven, f.Eight = jay.ReadBool8(b[0])
	f.Nine, f.Ten, f.Eleven, f.Twelve, f.Thirteen, f.Fourteen = jay.ReadBool6(b[1])
	return nil
}

func (f *Fifteen) MarshalJ() []byte {
	return []byte{jay.Bool8(f.One, f.Two, f.Three, f.Four, f.Five, f.Six, f.Seven, f.Eight), jay.Bool7(f.Nine, f.Ten, f.Eleven, f.Twelve, f.Thirteen, f.Fourteen, f.Fifteen)}
}

func (f *Fifteen) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	f.One, f.Two, f.Three, f.Four, f.Five, f.Six, f.Seven, f.Eight = jay.ReadBool8(b[0])
	f.Nine, f.Ten, f.Eleven, f.Twelve, f.Thirteen, f.Fourteen, f.Fifteen = jay.ReadBool7(b[1])
	return nil
}

func (s *Sixteen) MarshalJ() []byte {
	return []byte{jay.Bool8(s.One, s.Two, s.Three, s.Four, s.Five, s.Six, s.Seven, s.Eight), jay.Bool8(s.Nine, s.Ten, s.Eleven, s.Twelve, s.Thirteen, s.Fourteen, s.Fifteen, s.Sixteen)}
}

func (s *Sixteen) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	s.One, s.Two, s.Three, s.Four, s.Five, s.Six, s.Seven, s.Eight = jay.ReadBool8(b[0])
	s.Nine, s.Ten, s.Eleven, s.Twelve, s.Thirteen, s.Fourteen, s.Fifteen, s.Sixteen = jay.ReadBool8(b[1])
	return nil
}

func (s *Seventeen) MarshalJ() []byte {
	return []byte{jay.Bool8(s.One, s.Two, s.Three, s.Four, s.Five, s.Six, s.Seven, s.Eight), jay.Bool8(s.Nine, s.Ten, s.Eleven, s.Twelve, s.Thirteen, s.Fourteen, s.Fifteen, s.Sixteen), jay.Bool1(s.Seventeen)}
}

func (s *Seventeen) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	s.One, s.Two, s.Three, s.Four, s.Five, s.Six, s.Seven, s.Eight = jay.ReadBool8(b[0])
	s.Nine, s.Ten, s.Eleven, s.Twelve, s.Thirteen, s.Fourteen, s.Fifteen, s.Sixteen = jay.ReadBool8(b[1])
	s.Seventeen = jay.ReadBool1(b[2])
	return nil
}

func (e *Eighteen) MarshalJ() []byte {
	return []byte{jay.Bool8(e.One, e.Two, e.Three, e.Four, e.Five, e.Six, e.Seven, e.Eight), jay.Bool8(e.Nine, e.Ten, e.Eleven, e.Twelve, e.Thirteen, e.Fourteen, e.Fifteen, e.Sixteen), jay.Bool2(e.Seventeen, e.Eighteen)}
}

func (e *Eighteen) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	e.One, e.Two, e.Three, e.Four, e.Five, e.Six, e.Seven, e.Eight = jay.ReadBool8(b[0])
	e.Nine, e.Ten, e.Eleven, e.Twelve, e.Thirteen, e.Fourteen, e.Fifteen, e.Sixteen = jay.ReadBool8(b[1])
	e.Seventeen, e.Eighteen = jay.ReadBool2(b[2])
	return nil
}

func (n *Nineteen) MarshalJ() []byte {
	return []byte{jay.Bool8(n.One, n.Two, n.Three, n.Four, n.Five, n.Six, n.Seven, n.Eight), jay.Bool8(n.Nine, n.Ten, n.Eleven, n.Twelve, n.Thirteen, n.Fourteen, n.Fifteen, n.Sixteen), jay.Bool3(n.Seventeen, n.Eighteen, n.Nineteen)}
}

func (n *Nineteen) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	n.One, n.Two, n.Three, n.Four, n.Five, n.Six, n.Seven, n.Eight = jay.ReadBool8(b[0])
	n.Nine, n.Ten, n.Eleven, n.Twelve, n.Thirteen, n.Fourteen, n.Fifteen, n.Sixteen = jay.ReadBool8(b[1])
	n.Seventeen, n.Eighteen, n.Nineteen = jay.ReadBool3(b[2])
	return nil
}

func (t *Twenty) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool8(t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen), jay.Bool4(t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty)}
}

func (t *Twenty) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen = jay.ReadBool8(b[1])
	t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty = jay.ReadBool4(b[2])
	return nil
}

func (t *TwentyOne) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool8(t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen), jay.Bool5(t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty, t.TwentyOne)}
}

func (t *TwentyOne) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen = jay.ReadBool8(b[1])
	t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty, t.TwentyOne = jay.ReadBool5(b[2])
	return nil
}

func (t *TwentyTwo) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool8(t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen), jay.Bool6(t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty, t.TwentyOne, t.TwentyTwo)}
}

func (t *TwentyTwo) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen = jay.ReadBool8(b[1])
	t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty, t.TwentyOne, t.TwentyTwo = jay.ReadBool6(b[2])
	return nil
}

func (t *TwentyThree) MarshalJ() []byte {
	return []byte{jay.Bool8(t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight), jay.Bool8(t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen), jay.Bool7(t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty, t.TwentyOne, t.TwentyTwo, t.TwentyThree)}
}

func (t *TwentyThree) UnmarshalJ(b []byte) error {
	if len(b) < 3 {
		return jay.ErrUnexpectedEOB
	}
	t.One, t.Two, t.Three, t.Four, t.Five, t.Six, t.Seven, t.Eight = jay.ReadBool8(b[0])
	t.Nine, t.Ten, t.Eleven, t.Twelve, t.Thirteen, t.Fourteen, t.Fifteen, t.Sixteen = jay.ReadBool8(b[1])
	t.Seventeen, t.Eighteen, t.Nineteen, t.Twenty, t.TwentyOne, t.TwentyTwo, t.TwentyThree = jay.ReadBool7(b[2])
	return nil
}
