// Code generated by Jay; DO NOT EDIT.
package main

import "github.com/speedyhoon/jay"

func (c *Car) MarshalJ() (b []byte) {
	b = make([]byte, c.SizeJ())
	c.MarshalJTo(b)
	return b
}

func (c *Car) MarshalJTo(b []byte) {
	b[0] = jay.BoolToByte(c.Auto)
	jay.WriteUint64Bytes(b[1:], c.ID)
	jay.WriteUint64Bytes(b[9:], c.Row-1)
	at := c.Gearbox.MarshalJTo(b[17:])
	at = jay.WriteString(b, at+17, &c.Name)
	at = jay.WriteString(b, at, &c.CC)
	jay.WriteString(b, at, &c.Timing)
}

func (c *Car) SizeJ() int {
	return 20 + len(c.Name) + len(c.CC) + len(c.Timing) + c.Gearbox.SizeJ()
}

func (c *Car) UnmarshalJ(b []byte) (err error) {
	return nil
}

func (g *Gearbox) MarshalJ() (b []byte) {
	b = make([]byte, g.SizeJ())
	g.MarshalJTo(b)
	return b
}

func (g *Gearbox) MarshalJTo(b []byte) (at int) {
	jay.WriteIntBytes(b, g.Gears)
	b[8] = g.Reverse
	b[9] = jay.BoolToByte(g.Sequential)
	b[10] = jay.BoolToByte(g.Automatic)
	at = jay.WriteString(b, 11, &g.Model)
	return jay.WriteString(b, at, &g.Manufacturer)
}

func (g *Gearbox) SizeJ() int {
	return 13 + len(g.Model) + len(g.Manufacturer)
}

func (g *Gearbox) UnmarshalJ(b []byte) (err error) {
	return nil
}
