// Code generated by Jay; DO NOT EDIT. Tool documentation available at: https://github.com/speedyhoon/jay

package main

import "github.com/speedyhoon/jay"

func (o *One) MarshalJ() (b []byte) {
	b = make([]byte, 2)
	jay.WriteInt16(b, int16(o.One))
	return
}

func (o *One) UnmarshalJ(b []byte) error {
	if len(b) < 2 {
		return jay.ErrUnexpectedEOB
	}
	o.One = short(jay.ReadInt16(b[:2]))
	return nil
}

func (t *Two) MarshalJ() (b []byte) {
	b = make([]byte, 4)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:], int16(t.Two))
	return
}

func (t *Two) UnmarshalJ(b []byte) error {
	if len(b) < 4 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	return nil
}

func (t *Three) MarshalJ() (b []byte) {
	b = make([]byte, 6)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:], int16(t.Three))
	return
}

func (t *Three) UnmarshalJ(b []byte) error {
	if len(b) < 6 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	return nil
}

func (f *Four) MarshalJ() (b []byte) {
	b = make([]byte, 8)
	jay.WriteInt16(b[:2], int16(f.One))
	jay.WriteInt16(b[2:4], int16(f.Two))
	jay.WriteInt16(b[4:6], int16(f.Three))
	jay.WriteInt16(b[6:], int16(f.Four))
	return
}

func (f *Four) UnmarshalJ(b []byte) error {
	if len(b) < 8 {
		return jay.ErrUnexpectedEOB
	}
	f.One = short(jay.ReadInt16(b[:2]))
	f.Two = short(jay.ReadInt16(b[2:4]))
	f.Three = short(jay.ReadInt16(b[4:6]))
	f.Four = short(jay.ReadInt16(b[6:8]))
	return nil
}

func (f *Five) MarshalJ() (b []byte) {
	b = make([]byte, 10)
	jay.WriteInt16(b[:2], int16(f.One))
	jay.WriteInt16(b[2:4], int16(f.Two))
	jay.WriteInt16(b[4:6], int16(f.Three))
	jay.WriteInt16(b[6:8], int16(f.Four))
	jay.WriteInt16(b[8:], int16(f.Five))
	return
}

func (f *Five) UnmarshalJ(b []byte) error {
	if len(b) < 10 {
		return jay.ErrUnexpectedEOB
	}
	f.One = short(jay.ReadInt16(b[:2]))
	f.Two = short(jay.ReadInt16(b[2:4]))
	f.Three = short(jay.ReadInt16(b[4:6]))
	f.Four = short(jay.ReadInt16(b[6:8]))
	f.Five = short(jay.ReadInt16(b[8:10]))
	return nil
}

func (s *Six) MarshalJ() (b []byte) {
	b = make([]byte, 12)
	jay.WriteInt16(b[:2], int16(s.One))
	jay.WriteInt16(b[2:4], int16(s.Two))
	jay.WriteInt16(b[4:6], int16(s.Three))
	jay.WriteInt16(b[6:8], int16(s.Four))
	jay.WriteInt16(b[8:10], int16(s.Five))
	jay.WriteInt16(b[10:], int16(s.Six))
	return
}

func (s *Six) UnmarshalJ(b []byte) error {
	if len(b) < 12 {
		return jay.ErrUnexpectedEOB
	}
	s.One = short(jay.ReadInt16(b[:2]))
	s.Two = short(jay.ReadInt16(b[2:4]))
	s.Three = short(jay.ReadInt16(b[4:6]))
	s.Four = short(jay.ReadInt16(b[6:8]))
	s.Five = short(jay.ReadInt16(b[8:10]))
	s.Six = short(jay.ReadInt16(b[10:12]))
	return nil
}

func (s *Seven) MarshalJ() (b []byte) {
	b = make([]byte, 14)
	jay.WriteInt16(b[:2], int16(s.One))
	jay.WriteInt16(b[2:4], int16(s.Two))
	jay.WriteInt16(b[4:6], int16(s.Three))
	jay.WriteInt16(b[6:8], int16(s.Four))
	jay.WriteInt16(b[8:10], int16(s.Five))
	jay.WriteInt16(b[10:12], int16(s.Six))
	jay.WriteInt16(b[12:], int16(s.Seven))
	return
}

func (s *Seven) UnmarshalJ(b []byte) error {
	if len(b) < 14 {
		return jay.ErrUnexpectedEOB
	}
	s.One = short(jay.ReadInt16(b[:2]))
	s.Two = short(jay.ReadInt16(b[2:4]))
	s.Three = short(jay.ReadInt16(b[4:6]))
	s.Four = short(jay.ReadInt16(b[6:8]))
	s.Five = short(jay.ReadInt16(b[8:10]))
	s.Six = short(jay.ReadInt16(b[10:12]))
	s.Seven = short(jay.ReadInt16(b[12:14]))
	return nil
}

func (e *Eight) MarshalJ() (b []byte) {
	b = make([]byte, 16)
	jay.WriteInt16(b[:2], int16(e.One))
	jay.WriteInt16(b[2:4], int16(e.Two))
	jay.WriteInt16(b[4:6], int16(e.Three))
	jay.WriteInt16(b[6:8], int16(e.Four))
	jay.WriteInt16(b[8:10], int16(e.Five))
	jay.WriteInt16(b[10:12], int16(e.Six))
	jay.WriteInt16(b[12:14], int16(e.Seven))
	jay.WriteInt16(b[14:], int16(e.Eight))
	return
}

func (e *Eight) UnmarshalJ(b []byte) error {
	if len(b) < 16 {
		return jay.ErrUnexpectedEOB
	}
	e.One = short(jay.ReadInt16(b[:2]))
	e.Two = short(jay.ReadInt16(b[2:4]))
	e.Three = short(jay.ReadInt16(b[4:6]))
	e.Four = short(jay.ReadInt16(b[6:8]))
	e.Five = short(jay.ReadInt16(b[8:10]))
	e.Six = short(jay.ReadInt16(b[10:12]))
	e.Seven = short(jay.ReadInt16(b[12:14]))
	e.Eight = short(jay.ReadInt16(b[14:16]))
	return nil
}

func (n *Nine) MarshalJ() (b []byte) {
	b = make([]byte, 18)
	jay.WriteInt16(b[:2], int16(n.One))
	jay.WriteInt16(b[2:4], int16(n.Two))
	jay.WriteInt16(b[4:6], int16(n.Three))
	jay.WriteInt16(b[6:8], int16(n.Four))
	jay.WriteInt16(b[8:10], int16(n.Five))
	jay.WriteInt16(b[10:12], int16(n.Six))
	jay.WriteInt16(b[12:14], int16(n.Seven))
	jay.WriteInt16(b[14:16], int16(n.Eight))
	jay.WriteInt16(b[16:], int16(n.Nine))
	return
}

func (n *Nine) UnmarshalJ(b []byte) error {
	if len(b) < 18 {
		return jay.ErrUnexpectedEOB
	}
	n.One = short(jay.ReadInt16(b[:2]))
	n.Two = short(jay.ReadInt16(b[2:4]))
	n.Three = short(jay.ReadInt16(b[4:6]))
	n.Four = short(jay.ReadInt16(b[6:8]))
	n.Five = short(jay.ReadInt16(b[8:10]))
	n.Six = short(jay.ReadInt16(b[10:12]))
	n.Seven = short(jay.ReadInt16(b[12:14]))
	n.Eight = short(jay.ReadInt16(b[14:16]))
	n.Nine = short(jay.ReadInt16(b[16:18]))
	return nil
}

func (t *Ten) MarshalJ() (b []byte) {
	b = make([]byte, 20)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:], int16(t.Ten))
	return
}

func (t *Ten) UnmarshalJ(b []byte) error {
	if len(b) < 20 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	return nil
}

func (e *Eleven) MarshalJ() (b []byte) {
	b = make([]byte, 22)
	jay.WriteInt16(b[:2], int16(e.One))
	jay.WriteInt16(b[2:4], int16(e.Two))
	jay.WriteInt16(b[4:6], int16(e.Three))
	jay.WriteInt16(b[6:8], int16(e.Four))
	jay.WriteInt16(b[8:10], int16(e.Five))
	jay.WriteInt16(b[10:12], int16(e.Six))
	jay.WriteInt16(b[12:14], int16(e.Seven))
	jay.WriteInt16(b[14:16], int16(e.Eight))
	jay.WriteInt16(b[16:18], int16(e.Nine))
	jay.WriteInt16(b[18:20], int16(e.Ten))
	jay.WriteInt16(b[20:], int16(e.Eleven))
	return
}

func (e *Eleven) UnmarshalJ(b []byte) error {
	if len(b) < 22 {
		return jay.ErrUnexpectedEOB
	}
	e.One = short(jay.ReadInt16(b[:2]))
	e.Two = short(jay.ReadInt16(b[2:4]))
	e.Three = short(jay.ReadInt16(b[4:6]))
	e.Four = short(jay.ReadInt16(b[6:8]))
	e.Five = short(jay.ReadInt16(b[8:10]))
	e.Six = short(jay.ReadInt16(b[10:12]))
	e.Seven = short(jay.ReadInt16(b[12:14]))
	e.Eight = short(jay.ReadInt16(b[14:16]))
	e.Nine = short(jay.ReadInt16(b[16:18]))
	e.Ten = short(jay.ReadInt16(b[18:20]))
	e.Eleven = short(jay.ReadInt16(b[20:22]))
	return nil
}

func (t *Twelve) MarshalJ() (b []byte) {
	b = make([]byte, 24)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:20], int16(t.Ten))
	jay.WriteInt16(b[20:22], int16(t.Eleven))
	jay.WriteInt16(b[22:], int16(t.Twelve))
	return
}

func (t *Twelve) UnmarshalJ(b []byte) error {
	if len(b) < 24 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	t.Eleven = short(jay.ReadInt16(b[20:22]))
	t.Twelve = short(jay.ReadInt16(b[22:24]))
	return nil
}

func (t *Thirteen) MarshalJ() (b []byte) {
	b = make([]byte, 26)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:20], int16(t.Ten))
	jay.WriteInt16(b[20:22], int16(t.Eleven))
	jay.WriteInt16(b[22:24], int16(t.Twelve))
	jay.WriteInt16(b[24:], int16(t.Thirteen))
	return
}

func (t *Thirteen) UnmarshalJ(b []byte) error {
	if len(b) < 26 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	t.Eleven = short(jay.ReadInt16(b[20:22]))
	t.Twelve = short(jay.ReadInt16(b[22:24]))
	t.Thirteen = short(jay.ReadInt16(b[24:26]))
	return nil
}

func (f *Fourteen) MarshalJ() (b []byte) {
	b = make([]byte, 28)
	jay.WriteInt16(b[:2], int16(f.One))
	jay.WriteInt16(b[2:4], int16(f.Two))
	jay.WriteInt16(b[4:6], int16(f.Three))
	jay.WriteInt16(b[6:8], int16(f.Four))
	jay.WriteInt16(b[8:10], int16(f.Five))
	jay.WriteInt16(b[10:12], int16(f.Six))
	jay.WriteInt16(b[12:14], int16(f.Seven))
	jay.WriteInt16(b[14:16], int16(f.Eight))
	jay.WriteInt16(b[16:18], int16(f.Nine))
	jay.WriteInt16(b[18:20], int16(f.Ten))
	jay.WriteInt16(b[20:22], int16(f.Eleven))
	jay.WriteInt16(b[22:24], int16(f.Twelve))
	jay.WriteInt16(b[24:26], int16(f.Thirteen))
	jay.WriteInt16(b[26:], int16(f.Fourteen))
	return
}

func (f *Fourteen) UnmarshalJ(b []byte) error {
	if len(b) < 28 {
		return jay.ErrUnexpectedEOB
	}
	f.One = short(jay.ReadInt16(b[:2]))
	f.Two = short(jay.ReadInt16(b[2:4]))
	f.Three = short(jay.ReadInt16(b[4:6]))
	f.Four = short(jay.ReadInt16(b[6:8]))
	f.Five = short(jay.ReadInt16(b[8:10]))
	f.Six = short(jay.ReadInt16(b[10:12]))
	f.Seven = short(jay.ReadInt16(b[12:14]))
	f.Eight = short(jay.ReadInt16(b[14:16]))
	f.Nine = short(jay.ReadInt16(b[16:18]))
	f.Ten = short(jay.ReadInt16(b[18:20]))
	f.Eleven = short(jay.ReadInt16(b[20:22]))
	f.Twelve = short(jay.ReadInt16(b[22:24]))
	f.Thirteen = short(jay.ReadInt16(b[24:26]))
	f.Fourteen = short(jay.ReadInt16(b[26:28]))
	return nil
}

func (f *Fifteen) MarshalJ() (b []byte) {
	b = make([]byte, 30)
	jay.WriteInt16(b[:2], int16(f.One))
	jay.WriteInt16(b[2:4], int16(f.Two))
	jay.WriteInt16(b[4:6], int16(f.Three))
	jay.WriteInt16(b[6:8], int16(f.Four))
	jay.WriteInt16(b[8:10], int16(f.Five))
	jay.WriteInt16(b[10:12], int16(f.Six))
	jay.WriteInt16(b[12:14], int16(f.Seven))
	jay.WriteInt16(b[14:16], int16(f.Eight))
	jay.WriteInt16(b[16:18], int16(f.Nine))
	jay.WriteInt16(b[18:20], int16(f.Ten))
	jay.WriteInt16(b[20:22], int16(f.Eleven))
	jay.WriteInt16(b[22:24], int16(f.Twelve))
	jay.WriteInt16(b[24:26], int16(f.Thirteen))
	jay.WriteInt16(b[26:28], int16(f.Fourteen))
	jay.WriteInt16(b[28:], int16(f.Fifteen))
	return
}

func (f *Fifteen) UnmarshalJ(b []byte) error {
	if len(b) < 30 {
		return jay.ErrUnexpectedEOB
	}
	f.One = short(jay.ReadInt16(b[:2]))
	f.Two = short(jay.ReadInt16(b[2:4]))
	f.Three = short(jay.ReadInt16(b[4:6]))
	f.Four = short(jay.ReadInt16(b[6:8]))
	f.Five = short(jay.ReadInt16(b[8:10]))
	f.Six = short(jay.ReadInt16(b[10:12]))
	f.Seven = short(jay.ReadInt16(b[12:14]))
	f.Eight = short(jay.ReadInt16(b[14:16]))
	f.Nine = short(jay.ReadInt16(b[16:18]))
	f.Ten = short(jay.ReadInt16(b[18:20]))
	f.Eleven = short(jay.ReadInt16(b[20:22]))
	f.Twelve = short(jay.ReadInt16(b[22:24]))
	f.Thirteen = short(jay.ReadInt16(b[24:26]))
	f.Fourteen = short(jay.ReadInt16(b[26:28]))
	f.Fifteen = short(jay.ReadInt16(b[28:30]))
	return nil
}

func (s *Sixteen) MarshalJ() (b []byte) {
	b = make([]byte, 32)
	jay.WriteInt16(b[:2], int16(s.One))
	jay.WriteInt16(b[2:4], int16(s.Two))
	jay.WriteInt16(b[4:6], int16(s.Three))
	jay.WriteInt16(b[6:8], int16(s.Four))
	jay.WriteInt16(b[8:10], int16(s.Five))
	jay.WriteInt16(b[10:12], int16(s.Six))
	jay.WriteInt16(b[12:14], int16(s.Seven))
	jay.WriteInt16(b[14:16], int16(s.Eight))
	jay.WriteInt16(b[16:18], int16(s.Nine))
	jay.WriteInt16(b[18:20], int16(s.Ten))
	jay.WriteInt16(b[20:22], int16(s.Eleven))
	jay.WriteInt16(b[22:24], int16(s.Twelve))
	jay.WriteInt16(b[24:26], int16(s.Thirteen))
	jay.WriteInt16(b[26:28], int16(s.Fourteen))
	jay.WriteInt16(b[28:30], int16(s.Fifteen))
	jay.WriteInt16(b[30:], int16(s.Sixteen))
	return
}

func (s *Sixteen) UnmarshalJ(b []byte) error {
	if len(b) < 32 {
		return jay.ErrUnexpectedEOB
	}
	s.One = short(jay.ReadInt16(b[:2]))
	s.Two = short(jay.ReadInt16(b[2:4]))
	s.Three = short(jay.ReadInt16(b[4:6]))
	s.Four = short(jay.ReadInt16(b[6:8]))
	s.Five = short(jay.ReadInt16(b[8:10]))
	s.Six = short(jay.ReadInt16(b[10:12]))
	s.Seven = short(jay.ReadInt16(b[12:14]))
	s.Eight = short(jay.ReadInt16(b[14:16]))
	s.Nine = short(jay.ReadInt16(b[16:18]))
	s.Ten = short(jay.ReadInt16(b[18:20]))
	s.Eleven = short(jay.ReadInt16(b[20:22]))
	s.Twelve = short(jay.ReadInt16(b[22:24]))
	s.Thirteen = short(jay.ReadInt16(b[24:26]))
	s.Fourteen = short(jay.ReadInt16(b[26:28]))
	s.Fifteen = short(jay.ReadInt16(b[28:30]))
	s.Sixteen = short(jay.ReadInt16(b[30:32]))
	return nil
}

func (s *Seventeen) MarshalJ() (b []byte) {
	b = make([]byte, 34)
	jay.WriteInt16(b[:2], int16(s.One))
	jay.WriteInt16(b[2:4], int16(s.Two))
	jay.WriteInt16(b[4:6], int16(s.Three))
	jay.WriteInt16(b[6:8], int16(s.Four))
	jay.WriteInt16(b[8:10], int16(s.Five))
	jay.WriteInt16(b[10:12], int16(s.Six))
	jay.WriteInt16(b[12:14], int16(s.Seven))
	jay.WriteInt16(b[14:16], int16(s.Eight))
	jay.WriteInt16(b[16:18], int16(s.Nine))
	jay.WriteInt16(b[18:20], int16(s.Ten))
	jay.WriteInt16(b[20:22], int16(s.Eleven))
	jay.WriteInt16(b[22:24], int16(s.Twelve))
	jay.WriteInt16(b[24:26], int16(s.Thirteen))
	jay.WriteInt16(b[26:28], int16(s.Fourteen))
	jay.WriteInt16(b[28:30], int16(s.Fifteen))
	jay.WriteInt16(b[30:32], int16(s.Sixteen))
	jay.WriteInt16(b[32:], int16(s.Seventeen))
	return
}

func (s *Seventeen) UnmarshalJ(b []byte) error {
	if len(b) < 34 {
		return jay.ErrUnexpectedEOB
	}
	s.One = short(jay.ReadInt16(b[:2]))
	s.Two = short(jay.ReadInt16(b[2:4]))
	s.Three = short(jay.ReadInt16(b[4:6]))
	s.Four = short(jay.ReadInt16(b[6:8]))
	s.Five = short(jay.ReadInt16(b[8:10]))
	s.Six = short(jay.ReadInt16(b[10:12]))
	s.Seven = short(jay.ReadInt16(b[12:14]))
	s.Eight = short(jay.ReadInt16(b[14:16]))
	s.Nine = short(jay.ReadInt16(b[16:18]))
	s.Ten = short(jay.ReadInt16(b[18:20]))
	s.Eleven = short(jay.ReadInt16(b[20:22]))
	s.Twelve = short(jay.ReadInt16(b[22:24]))
	s.Thirteen = short(jay.ReadInt16(b[24:26]))
	s.Fourteen = short(jay.ReadInt16(b[26:28]))
	s.Fifteen = short(jay.ReadInt16(b[28:30]))
	s.Sixteen = short(jay.ReadInt16(b[30:32]))
	s.Seventeen = short(jay.ReadInt16(b[32:34]))
	return nil
}

func (e *Eighteen) MarshalJ() (b []byte) {
	b = make([]byte, 36)
	jay.WriteInt16(b[:2], int16(e.One))
	jay.WriteInt16(b[2:4], int16(e.Two))
	jay.WriteInt16(b[4:6], int16(e.Three))
	jay.WriteInt16(b[6:8], int16(e.Four))
	jay.WriteInt16(b[8:10], int16(e.Five))
	jay.WriteInt16(b[10:12], int16(e.Six))
	jay.WriteInt16(b[12:14], int16(e.Seven))
	jay.WriteInt16(b[14:16], int16(e.Eight))
	jay.WriteInt16(b[16:18], int16(e.Nine))
	jay.WriteInt16(b[18:20], int16(e.Ten))
	jay.WriteInt16(b[20:22], int16(e.Eleven))
	jay.WriteInt16(b[22:24], int16(e.Twelve))
	jay.WriteInt16(b[24:26], int16(e.Thirteen))
	jay.WriteInt16(b[26:28], int16(e.Fourteen))
	jay.WriteInt16(b[28:30], int16(e.Fifteen))
	jay.WriteInt16(b[30:32], int16(e.Sixteen))
	jay.WriteInt16(b[32:34], int16(e.Seventeen))
	jay.WriteInt16(b[34:], int16(e.Eighteen))
	return
}

func (e *Eighteen) UnmarshalJ(b []byte) error {
	if len(b) < 36 {
		return jay.ErrUnexpectedEOB
	}
	e.One = short(jay.ReadInt16(b[:2]))
	e.Two = short(jay.ReadInt16(b[2:4]))
	e.Three = short(jay.ReadInt16(b[4:6]))
	e.Four = short(jay.ReadInt16(b[6:8]))
	e.Five = short(jay.ReadInt16(b[8:10]))
	e.Six = short(jay.ReadInt16(b[10:12]))
	e.Seven = short(jay.ReadInt16(b[12:14]))
	e.Eight = short(jay.ReadInt16(b[14:16]))
	e.Nine = short(jay.ReadInt16(b[16:18]))
	e.Ten = short(jay.ReadInt16(b[18:20]))
	e.Eleven = short(jay.ReadInt16(b[20:22]))
	e.Twelve = short(jay.ReadInt16(b[22:24]))
	e.Thirteen = short(jay.ReadInt16(b[24:26]))
	e.Fourteen = short(jay.ReadInt16(b[26:28]))
	e.Fifteen = short(jay.ReadInt16(b[28:30]))
	e.Sixteen = short(jay.ReadInt16(b[30:32]))
	e.Seventeen = short(jay.ReadInt16(b[32:34]))
	e.Eighteen = short(jay.ReadInt16(b[34:36]))
	return nil
}

func (n *Nineteen) MarshalJ() (b []byte) {
	b = make([]byte, 38)
	jay.WriteInt16(b[:2], int16(n.One))
	jay.WriteInt16(b[2:4], int16(n.Two))
	jay.WriteInt16(b[4:6], int16(n.Three))
	jay.WriteInt16(b[6:8], int16(n.Four))
	jay.WriteInt16(b[8:10], int16(n.Five))
	jay.WriteInt16(b[10:12], int16(n.Six))
	jay.WriteInt16(b[12:14], int16(n.Seven))
	jay.WriteInt16(b[14:16], int16(n.Eight))
	jay.WriteInt16(b[16:18], int16(n.Nine))
	jay.WriteInt16(b[18:20], int16(n.Ten))
	jay.WriteInt16(b[20:22], int16(n.Eleven))
	jay.WriteInt16(b[22:24], int16(n.Twelve))
	jay.WriteInt16(b[24:26], int16(n.Thirteen))
	jay.WriteInt16(b[26:28], int16(n.Fourteen))
	jay.WriteInt16(b[28:30], int16(n.Fifteen))
	jay.WriteInt16(b[30:32], int16(n.Sixteen))
	jay.WriteInt16(b[32:34], int16(n.Seventeen))
	jay.WriteInt16(b[34:36], int16(n.Eighteen))
	jay.WriteInt16(b[36:], int16(n.Nineteen))
	return
}

func (n *Nineteen) UnmarshalJ(b []byte) error {
	if len(b) < 38 {
		return jay.ErrUnexpectedEOB
	}
	n.One = short(jay.ReadInt16(b[:2]))
	n.Two = short(jay.ReadInt16(b[2:4]))
	n.Three = short(jay.ReadInt16(b[4:6]))
	n.Four = short(jay.ReadInt16(b[6:8]))
	n.Five = short(jay.ReadInt16(b[8:10]))
	n.Six = short(jay.ReadInt16(b[10:12]))
	n.Seven = short(jay.ReadInt16(b[12:14]))
	n.Eight = short(jay.ReadInt16(b[14:16]))
	n.Nine = short(jay.ReadInt16(b[16:18]))
	n.Ten = short(jay.ReadInt16(b[18:20]))
	n.Eleven = short(jay.ReadInt16(b[20:22]))
	n.Twelve = short(jay.ReadInt16(b[22:24]))
	n.Thirteen = short(jay.ReadInt16(b[24:26]))
	n.Fourteen = short(jay.ReadInt16(b[26:28]))
	n.Fifteen = short(jay.ReadInt16(b[28:30]))
	n.Sixteen = short(jay.ReadInt16(b[30:32]))
	n.Seventeen = short(jay.ReadInt16(b[32:34]))
	n.Eighteen = short(jay.ReadInt16(b[34:36]))
	n.Nineteen = short(jay.ReadInt16(b[36:38]))
	return nil
}

func (t *Twenty) MarshalJ() (b []byte) {
	b = make([]byte, 40)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:20], int16(t.Ten))
	jay.WriteInt16(b[20:22], int16(t.Eleven))
	jay.WriteInt16(b[22:24], int16(t.Twelve))
	jay.WriteInt16(b[24:26], int16(t.Thirteen))
	jay.WriteInt16(b[26:28], int16(t.Fourteen))
	jay.WriteInt16(b[28:30], int16(t.Fifteen))
	jay.WriteInt16(b[30:32], int16(t.Sixteen))
	jay.WriteInt16(b[32:34], int16(t.Seventeen))
	jay.WriteInt16(b[34:36], int16(t.Eighteen))
	jay.WriteInt16(b[36:38], int16(t.Nineteen))
	jay.WriteInt16(b[38:], int16(t.Twenty))
	return
}

func (t *Twenty) UnmarshalJ(b []byte) error {
	if len(b) < 40 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	t.Eleven = short(jay.ReadInt16(b[20:22]))
	t.Twelve = short(jay.ReadInt16(b[22:24]))
	t.Thirteen = short(jay.ReadInt16(b[24:26]))
	t.Fourteen = short(jay.ReadInt16(b[26:28]))
	t.Fifteen = short(jay.ReadInt16(b[28:30]))
	t.Sixteen = short(jay.ReadInt16(b[30:32]))
	t.Seventeen = short(jay.ReadInt16(b[32:34]))
	t.Eighteen = short(jay.ReadInt16(b[34:36]))
	t.Nineteen = short(jay.ReadInt16(b[36:38]))
	t.Twenty = short(jay.ReadInt16(b[38:40]))
	return nil
}

func (t *TwentyOne) MarshalJ() (b []byte) {
	b = make([]byte, 42)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:20], int16(t.Ten))
	jay.WriteInt16(b[20:22], int16(t.Eleven))
	jay.WriteInt16(b[22:24], int16(t.Twelve))
	jay.WriteInt16(b[24:26], int16(t.Thirteen))
	jay.WriteInt16(b[26:28], int16(t.Fourteen))
	jay.WriteInt16(b[28:30], int16(t.Fifteen))
	jay.WriteInt16(b[30:32], int16(t.Sixteen))
	jay.WriteInt16(b[32:34], int16(t.Seventeen))
	jay.WriteInt16(b[34:36], int16(t.Eighteen))
	jay.WriteInt16(b[36:38], int16(t.Nineteen))
	jay.WriteInt16(b[38:40], int16(t.Twenty))
	jay.WriteInt16(b[40:], int16(t.TwentyOne))
	return
}

func (t *TwentyOne) UnmarshalJ(b []byte) error {
	if len(b) < 42 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	t.Eleven = short(jay.ReadInt16(b[20:22]))
	t.Twelve = short(jay.ReadInt16(b[22:24]))
	t.Thirteen = short(jay.ReadInt16(b[24:26]))
	t.Fourteen = short(jay.ReadInt16(b[26:28]))
	t.Fifteen = short(jay.ReadInt16(b[28:30]))
	t.Sixteen = short(jay.ReadInt16(b[30:32]))
	t.Seventeen = short(jay.ReadInt16(b[32:34]))
	t.Eighteen = short(jay.ReadInt16(b[34:36]))
	t.Nineteen = short(jay.ReadInt16(b[36:38]))
	t.Twenty = short(jay.ReadInt16(b[38:40]))
	t.TwentyOne = short(jay.ReadInt16(b[40:42]))
	return nil
}

func (t *TwentyTwo) MarshalJ() (b []byte) {
	b = make([]byte, 44)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:20], int16(t.Ten))
	jay.WriteInt16(b[20:22], int16(t.Eleven))
	jay.WriteInt16(b[22:24], int16(t.Twelve))
	jay.WriteInt16(b[24:26], int16(t.Thirteen))
	jay.WriteInt16(b[26:28], int16(t.Fourteen))
	jay.WriteInt16(b[28:30], int16(t.Fifteen))
	jay.WriteInt16(b[30:32], int16(t.Sixteen))
	jay.WriteInt16(b[32:34], int16(t.Seventeen))
	jay.WriteInt16(b[34:36], int16(t.Eighteen))
	jay.WriteInt16(b[36:38], int16(t.Nineteen))
	jay.WriteInt16(b[38:40], int16(t.Twenty))
	jay.WriteInt16(b[40:42], int16(t.TwentyOne))
	jay.WriteInt16(b[42:], int16(t.TwentyTwo))
	return
}

func (t *TwentyTwo) UnmarshalJ(b []byte) error {
	if len(b) < 44 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	t.Eleven = short(jay.ReadInt16(b[20:22]))
	t.Twelve = short(jay.ReadInt16(b[22:24]))
	t.Thirteen = short(jay.ReadInt16(b[24:26]))
	t.Fourteen = short(jay.ReadInt16(b[26:28]))
	t.Fifteen = short(jay.ReadInt16(b[28:30]))
	t.Sixteen = short(jay.ReadInt16(b[30:32]))
	t.Seventeen = short(jay.ReadInt16(b[32:34]))
	t.Eighteen = short(jay.ReadInt16(b[34:36]))
	t.Nineteen = short(jay.ReadInt16(b[36:38]))
	t.Twenty = short(jay.ReadInt16(b[38:40]))
	t.TwentyOne = short(jay.ReadInt16(b[40:42]))
	t.TwentyTwo = short(jay.ReadInt16(b[42:44]))
	return nil
}

func (t *TwentyThree) MarshalJ() (b []byte) {
	b = make([]byte, 46)
	jay.WriteInt16(b[:2], int16(t.One))
	jay.WriteInt16(b[2:4], int16(t.Two))
	jay.WriteInt16(b[4:6], int16(t.Three))
	jay.WriteInt16(b[6:8], int16(t.Four))
	jay.WriteInt16(b[8:10], int16(t.Five))
	jay.WriteInt16(b[10:12], int16(t.Six))
	jay.WriteInt16(b[12:14], int16(t.Seven))
	jay.WriteInt16(b[14:16], int16(t.Eight))
	jay.WriteInt16(b[16:18], int16(t.Nine))
	jay.WriteInt16(b[18:20], int16(t.Ten))
	jay.WriteInt16(b[20:22], int16(t.Eleven))
	jay.WriteInt16(b[22:24], int16(t.Twelve))
	jay.WriteInt16(b[24:26], int16(t.Thirteen))
	jay.WriteInt16(b[26:28], int16(t.Fourteen))
	jay.WriteInt16(b[28:30], int16(t.Fifteen))
	jay.WriteInt16(b[30:32], int16(t.Sixteen))
	jay.WriteInt16(b[32:34], int16(t.Seventeen))
	jay.WriteInt16(b[34:36], int16(t.Eighteen))
	jay.WriteInt16(b[36:38], int16(t.Nineteen))
	jay.WriteInt16(b[38:40], int16(t.Twenty))
	jay.WriteInt16(b[40:42], int16(t.TwentyOne))
	jay.WriteInt16(b[42:44], int16(t.TwentyTwo))
	jay.WriteInt16(b[44:], int16(t.TwentyThree))
	return
}

func (t *TwentyThree) UnmarshalJ(b []byte) error {
	if len(b) < 46 {
		return jay.ErrUnexpectedEOB
	}
	t.One = short(jay.ReadInt16(b[:2]))
	t.Two = short(jay.ReadInt16(b[2:4]))
	t.Three = short(jay.ReadInt16(b[4:6]))
	t.Four = short(jay.ReadInt16(b[6:8]))
	t.Five = short(jay.ReadInt16(b[8:10]))
	t.Six = short(jay.ReadInt16(b[10:12]))
	t.Seven = short(jay.ReadInt16(b[12:14]))
	t.Eight = short(jay.ReadInt16(b[14:16]))
	t.Nine = short(jay.ReadInt16(b[16:18]))
	t.Ten = short(jay.ReadInt16(b[18:20]))
	t.Eleven = short(jay.ReadInt16(b[20:22]))
	t.Twelve = short(jay.ReadInt16(b[22:24]))
	t.Thirteen = short(jay.ReadInt16(b[24:26]))
	t.Fourteen = short(jay.ReadInt16(b[26:28]))
	t.Fifteen = short(jay.ReadInt16(b[28:30]))
	t.Sixteen = short(jay.ReadInt16(b[30:32]))
	t.Seventeen = short(jay.ReadInt16(b[32:34]))
	t.Eighteen = short(jay.ReadInt16(b[34:36]))
	t.Nineteen = short(jay.ReadInt16(b[36:38]))
	t.Twenty = short(jay.ReadInt16(b[38:40]))
	t.TwentyOne = short(jay.ReadInt16(b[40:42]))
	t.TwentyTwo = short(jay.ReadInt16(b[42:44]))
	t.TwentyThree = short(jay.ReadInt16(b[44:46]))
	return nil
}
