// Code generated by testdata/fuzz_test; DO NOT EDIT.

package main

type One struct {
	One complex64
}

type Two struct {
	One complex64
	Two complex64
}

type Three struct {
	One   complex64
	Two   complex64
	Three complex64
}

type Four struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
}

type Five struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
	Five  complex64
}

type Six struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
	Five  complex64
	Six   complex64
}

type Seven struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
	Five  complex64
	Six   complex64
	Seven complex64
}

type Eight struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
	Five  complex64
	Six   complex64
	Seven complex64
	Eight complex64
}

type Nine struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
	Five  complex64
	Six   complex64
	Seven complex64
	Eight complex64
	Nine  complex64
}

type Ten struct {
	One   complex64
	Two   complex64
	Three complex64
	Four  complex64
	Five  complex64
	Six   complex64
	Seven complex64
	Eight complex64
	Nine  complex64
	Ten   complex64
}

type Eleven struct {
	One    complex64
	Two    complex64
	Three  complex64
	Four   complex64
	Five   complex64
	Six    complex64
	Seven  complex64
	Eight  complex64
	Nine   complex64
	Ten    complex64
	Eleven complex64
}

type Twelve struct {
	One    complex64
	Two    complex64
	Three  complex64
	Four   complex64
	Five   complex64
	Six    complex64
	Seven  complex64
	Eight  complex64
	Nine   complex64
	Ten    complex64
	Eleven complex64
	Twelve complex64
}

type Thirteen struct {
	One      complex64
	Two      complex64
	Three    complex64
	Four     complex64
	Five     complex64
	Six      complex64
	Seven    complex64
	Eight    complex64
	Nine     complex64
	Ten      complex64
	Eleven   complex64
	Twelve   complex64
	Thirteen complex64
}

type Fourteen struct {
	One      complex64
	Two      complex64
	Three    complex64
	Four     complex64
	Five     complex64
	Six      complex64
	Seven    complex64
	Eight    complex64
	Nine     complex64
	Ten      complex64
	Eleven   complex64
	Twelve   complex64
	Thirteen complex64
	Fourteen complex64
}

type Fifteen struct {
	One      complex64
	Two      complex64
	Three    complex64
	Four     complex64
	Five     complex64
	Six      complex64
	Seven    complex64
	Eight    complex64
	Nine     complex64
	Ten      complex64
	Eleven   complex64
	Twelve   complex64
	Thirteen complex64
	Fourteen complex64
	Fifteen  complex64
}

type Sixteen struct {
	One      complex64
	Two      complex64
	Three    complex64
	Four     complex64
	Five     complex64
	Six      complex64
	Seven    complex64
	Eight    complex64
	Nine     complex64
	Ten      complex64
	Eleven   complex64
	Twelve   complex64
	Thirteen complex64
	Fourteen complex64
	Fifteen  complex64
	Sixteen  complex64
}

type Seventeen struct {
	One       complex64
	Two       complex64
	Three     complex64
	Four      complex64
	Five      complex64
	Six       complex64
	Seven     complex64
	Eight     complex64
	Nine      complex64
	Ten       complex64
	Eleven    complex64
	Twelve    complex64
	Thirteen  complex64
	Fourteen  complex64
	Fifteen   complex64
	Sixteen   complex64
	Seventeen complex64
}

type Eighteen struct {
	One       complex64
	Two       complex64
	Three     complex64
	Four      complex64
	Five      complex64
	Six       complex64
	Seven     complex64
	Eight     complex64
	Nine      complex64
	Ten       complex64
	Eleven    complex64
	Twelve    complex64
	Thirteen  complex64
	Fourteen  complex64
	Fifteen   complex64
	Sixteen   complex64
	Seventeen complex64
	Eighteen  complex64
}

type Nineteen struct {
	One       complex64
	Two       complex64
	Three     complex64
	Four      complex64
	Five      complex64
	Six       complex64
	Seven     complex64
	Eight     complex64
	Nine      complex64
	Ten       complex64
	Eleven    complex64
	Twelve    complex64
	Thirteen  complex64
	Fourteen  complex64
	Fifteen   complex64
	Sixteen   complex64
	Seventeen complex64
	Eighteen  complex64
	Nineteen  complex64
}

type Twenty struct {
	One       complex64
	Two       complex64
	Three     complex64
	Four      complex64
	Five      complex64
	Six       complex64
	Seven     complex64
	Eight     complex64
	Nine      complex64
	Ten       complex64
	Eleven    complex64
	Twelve    complex64
	Thirteen  complex64
	Fourteen  complex64
	Fifteen   complex64
	Sixteen   complex64
	Seventeen complex64
	Eighteen  complex64
	Nineteen  complex64
	Twenty    complex64
}

type TwentyOne struct {
	One       complex64
	Two       complex64
	Three     complex64
	Four      complex64
	Five      complex64
	Six       complex64
	Seven     complex64
	Eight     complex64
	Nine      complex64
	Ten       complex64
	Eleven    complex64
	Twelve    complex64
	Thirteen  complex64
	Fourteen  complex64
	Fifteen   complex64
	Sixteen   complex64
	Seventeen complex64
	Eighteen  complex64
	Nineteen  complex64
	Twenty    complex64
	TwentyOne complex64
}

type TwentyTwo struct {
	One       complex64
	Two       complex64
	Three     complex64
	Four      complex64
	Five      complex64
	Six       complex64
	Seven     complex64
	Eight     complex64
	Nine      complex64
	Ten       complex64
	Eleven    complex64
	Twelve    complex64
	Thirteen  complex64
	Fourteen  complex64
	Fifteen   complex64
	Sixteen   complex64
	Seventeen complex64
	Eighteen  complex64
	Nineteen  complex64
	Twenty    complex64
	TwentyOne complex64
	TwentyTwo complex64
}

type TwentyThree struct {
	One         complex64
	Two         complex64
	Three       complex64
	Four        complex64
	Five        complex64
	Six         complex64
	Seven       complex64
	Eight       complex64
	Nine        complex64
	Ten         complex64
	Eleven      complex64
	Twelve      complex64
	Thirteen    complex64
	Fourteen    complex64
	Fifteen     complex64
	Sixteen     complex64
	Seventeen   complex64
	Eighteen    complex64
	Nineteen    complex64
	Twenty      complex64
	TwentyOne   complex64
	TwentyTwo   complex64
	TwentyThree complex64
}
