// Code generated by Jay; DO NOT EDIT. Tool documentation available at: https://github.com/speedyhoon/jay

package main

import "github.com/speedyhoon/jay"

func (o *One) MarshalJ() (b []byte) {
	l0 := len(o.One)
	b = make([]byte, 1+l0*2)
	b[0] = byte(l0)
	jay.WriteUint16s(b[1:], o.One, l0)
	return
}

func (o *One) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 1 {
		return jay.ErrUnexpectedEOB
	}
	l0 := int(b[0])
	if l < 1+l0 {
		return jay.ErrUnexpectedEOB
	}
	o.One = jay.ReadUint16s(b[1:], l0)
	return nil
}

func (t *Two) MarshalJ() (b []byte) {
	l0, l1 := len(t.One), len(t.Two)
	b = make([]byte, 2+l0*2+l1*2)
	b[0], b[1] = byte(l0), byte(l1)
	at, end := 2, 2+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	jay.WriteUint16s(b[end:], t.Two, l1)
	return
}

func (t *Two) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 2 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1 := int(b[0]), int(b[1])
	if l < 2+l0+l1 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 2, 2+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	t.Two = jay.ReadUint16s(b[end:], l1)
	return nil
}

func (t *Three) MarshalJ() (b []byte) {
	l0, l1, l2 := len(t.One), len(t.Two), len(t.Three)
	b = make([]byte, 3+l0*2+l1*2+l2*2)
	b[0], b[1], b[2] = byte(l0), byte(l1), byte(l2)
	at, end := 3, 3+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	jay.WriteUint16s(b[end:], t.Three, l2)
	return
}

func (t *Three) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 3 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2 := int(b[0]), int(b[1]), int(b[2])
	if l < 3+l0+l1+l2 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 3, 3+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	t.Three = jay.ReadUint16s(b[end:], l2)
	return nil
}

func (f *Four) MarshalJ() (b []byte) {
	l0, l1, l2, l3 := len(f.One), len(f.Two), len(f.Three), len(f.Four)
	b = make([]byte, 4+l0*2+l1*2+l2*2+l3*2)
	b[0], b[1], b[2], b[3] = byte(l0), byte(l1), byte(l2), byte(l3)
	at, end := 4, 4+l0*2
	jay.WriteUint16s(b[at:end], f.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], f.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], f.Three, l2)
	jay.WriteUint16s(b[end:], f.Four, l3)
	return
}

func (f *Four) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 4 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3 := int(b[0]), int(b[1]), int(b[2]), int(b[3])
	if l < 4+l0+l1+l2+l3 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 4, 4+l0*2
	f.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	f.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	f.Three = jay.ReadUint16s(b[at:end], l2)
	f.Four = jay.ReadUint16s(b[end:], l3)
	return nil
}

func (f *Five) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4 := len(f.One), len(f.Two), len(f.Three), len(f.Four), len(f.Five)
	b = make([]byte, 5+l0*2+l1*2+l2*2+l3*2+l4*2)
	b[0], b[1], b[2], b[3], b[4] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4)
	at, end := 5, 5+l0*2
	jay.WriteUint16s(b[at:end], f.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], f.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], f.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], f.Four, l3)
	jay.WriteUint16s(b[end:], f.Five, l4)
	return
}

func (f *Five) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 5 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4])
	if l < 5+l0+l1+l2+l3+l4 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 5, 5+l0*2
	f.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	f.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	f.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	f.Four = jay.ReadUint16s(b[at:end], l3)
	f.Five = jay.ReadUint16s(b[end:], l4)
	return nil
}

func (s *Six) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5 := len(s.One), len(s.Two), len(s.Three), len(s.Four), len(s.Five), len(s.Six)
	b = make([]byte, 6+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2)
	b[0], b[1], b[2], b[3], b[4], b[5] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5)
	at, end := 6, 6+l0*2
	jay.WriteUint16s(b[at:end], s.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], s.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], s.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], s.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], s.Five, l4)
	jay.WriteUint16s(b[end:], s.Six, l5)
	return
}

func (s *Six) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 6 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5])
	if l < 6+l0+l1+l2+l3+l4+l5 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 6, 6+l0*2
	s.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	s.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	s.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	s.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	s.Five = jay.ReadUint16s(b[at:end], l4)
	s.Six = jay.ReadUint16s(b[end:], l5)
	return nil
}

func (s *Seven) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6 := len(s.One), len(s.Two), len(s.Three), len(s.Four), len(s.Five), len(s.Six), len(s.Seven)
	b = make([]byte, 7+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6)
	at, end := 7, 7+l0*2
	jay.WriteUint16s(b[at:end], s.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], s.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], s.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], s.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], s.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], s.Six, l5)
	jay.WriteUint16s(b[end:], s.Seven, l6)
	return
}

func (s *Seven) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 7 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6])
	if l < 7+l0+l1+l2+l3+l4+l5+l6 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 7, 7+l0*2
	s.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	s.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	s.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	s.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	s.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	s.Six = jay.ReadUint16s(b[at:end], l5)
	s.Seven = jay.ReadUint16s(b[end:], l6)
	return nil
}

func (e *Eight) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7 := len(e.One), len(e.Two), len(e.Three), len(e.Four), len(e.Five), len(e.Six), len(e.Seven), len(e.Eight)
	b = make([]byte, 8+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7)
	at, end := 8, 8+l0*2
	jay.WriteUint16s(b[at:end], e.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], e.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], e.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], e.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], e.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], e.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], e.Seven, l6)
	jay.WriteUint16s(b[end:], e.Eight, l7)
	return
}

func (e *Eight) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 8 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7])
	if l < 8+l0+l1+l2+l3+l4+l5+l6+l7 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 8, 8+l0*2
	e.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	e.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	e.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	e.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	e.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	e.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	e.Seven = jay.ReadUint16s(b[at:end], l6)
	e.Eight = jay.ReadUint16s(b[end:], l7)
	return nil
}

func (n *Nine) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8 := len(n.One), len(n.Two), len(n.Three), len(n.Four), len(n.Five), len(n.Six), len(n.Seven), len(n.Eight), len(n.Nine)
	b = make([]byte, 9+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8)
	at, end := 9, 9+l0*2
	jay.WriteUint16s(b[at:end], n.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], n.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], n.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], n.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], n.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], n.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], n.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], n.Eight, l7)
	jay.WriteUint16s(b[end:], n.Nine, l8)
	return
}

func (n *Nine) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 9 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8])
	if l < 9+l0+l1+l2+l3+l4+l5+l6+l7+l8 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 9, 9+l0*2
	n.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	n.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	n.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	n.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	n.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	n.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	n.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	n.Eight = jay.ReadUint16s(b[at:end], l7)
	n.Nine = jay.ReadUint16s(b[end:], l8)
	return nil
}

func (t *Ten) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten)
	b = make([]byte, 10+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9)
	at, end := 10, 10+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	jay.WriteUint16s(b[end:], t.Ten, l9)
	return
}

func (t *Ten) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 10 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9])
	if l < 10+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 10, 10+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	t.Ten = jay.ReadUint16s(b[end:], l9)
	return nil
}

func (e *Eleven) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10 := len(e.One), len(e.Two), len(e.Three), len(e.Four), len(e.Five), len(e.Six), len(e.Seven), len(e.Eight), len(e.Nine), len(e.Ten), len(e.Eleven)
	b = make([]byte, 11+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10)
	at, end := 11, 11+l0*2
	jay.WriteUint16s(b[at:end], e.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], e.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], e.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], e.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], e.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], e.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], e.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], e.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], e.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], e.Ten, l9)
	jay.WriteUint16s(b[end:], e.Eleven, l10)
	return
}

func (e *Eleven) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 11 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10])
	if l < 11+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 11, 11+l0*2
	e.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	e.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	e.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	e.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	e.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	e.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	e.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	e.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	e.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	e.Ten = jay.ReadUint16s(b[at:end], l9)
	e.Eleven = jay.ReadUint16s(b[end:], l10)
	return nil
}

func (t *Twelve) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten), len(t.Eleven), len(t.Twelve)
	b = make([]byte, 12+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11)
	at, end := 12, 12+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], t.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], t.Eleven, l10)
	jay.WriteUint16s(b[end:], t.Twelve, l11)
	return
}

func (t *Twelve) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 12 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11])
	if l < 12+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 12, 12+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	t.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	t.Eleven = jay.ReadUint16s(b[at:end], l10)
	t.Twelve = jay.ReadUint16s(b[end:], l11)
	return nil
}

func (t *Thirteen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten), len(t.Eleven), len(t.Twelve), len(t.Thirteen)
	b = make([]byte, 13+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12)
	at, end := 13, 13+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], t.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], t.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], t.Twelve, l11)
	jay.WriteUint16s(b[end:], t.Thirteen, l12)
	return
}

func (t *Thirteen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 13 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12])
	if l < 13+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 13, 13+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	t.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	t.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	t.Twelve = jay.ReadUint16s(b[at:end], l11)
	t.Thirteen = jay.ReadUint16s(b[end:], l12)
	return nil
}

func (f *Fourteen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13 := len(f.One), len(f.Two), len(f.Three), len(f.Four), len(f.Five), len(f.Six), len(f.Seven), len(f.Eight), len(f.Nine), len(f.Ten), len(f.Eleven), len(f.Twelve), len(f.Thirteen), len(f.Fourteen)
	b = make([]byte, 14+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13)
	at, end := 14, 14+l0*2
	jay.WriteUint16s(b[at:end], f.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], f.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], f.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], f.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], f.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], f.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], f.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], f.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], f.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], f.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], f.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], f.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], f.Thirteen, l12)
	jay.WriteUint16s(b[end:], f.Fourteen, l13)
	return
}

func (f *Fourteen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 14 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13])
	if l < 14+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 14, 14+l0*2
	f.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	f.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	f.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	f.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	f.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	f.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	f.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	f.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	f.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	f.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	f.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	f.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	f.Thirteen = jay.ReadUint16s(b[at:end], l12)
	f.Fourteen = jay.ReadUint16s(b[end:], l13)
	return nil
}

func (f *Fifteen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14 := len(f.One), len(f.Two), len(f.Three), len(f.Four), len(f.Five), len(f.Six), len(f.Seven), len(f.Eight), len(f.Nine), len(f.Ten), len(f.Eleven), len(f.Twelve), len(f.Thirteen), len(f.Fourteen), len(f.Fifteen)
	b = make([]byte, 15+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14)
	at, end := 15, 15+l0*2
	jay.WriteUint16s(b[at:end], f.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], f.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], f.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], f.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], f.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], f.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], f.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], f.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], f.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], f.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], f.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], f.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], f.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], f.Fourteen, l13)
	jay.WriteUint16s(b[end:], f.Fifteen, l14)
	return
}

func (f *Fifteen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 15 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14])
	if l < 15+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 15, 15+l0*2
	f.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	f.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	f.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	f.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	f.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	f.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	f.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	f.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	f.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	f.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	f.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	f.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	f.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	f.Fourteen = jay.ReadUint16s(b[at:end], l13)
	f.Fifteen = jay.ReadUint16s(b[end:], l14)
	return nil
}

func (s *Sixteen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15 := len(s.One), len(s.Two), len(s.Three), len(s.Four), len(s.Five), len(s.Six), len(s.Seven), len(s.Eight), len(s.Nine), len(s.Ten), len(s.Eleven), len(s.Twelve), len(s.Thirteen), len(s.Fourteen), len(s.Fifteen), len(s.Sixteen)
	b = make([]byte, 16+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15)
	at, end := 16, 16+l0*2
	jay.WriteUint16s(b[at:end], s.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], s.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], s.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], s.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], s.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], s.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], s.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], s.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], s.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], s.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], s.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], s.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], s.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], s.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], s.Fifteen, l14)
	jay.WriteUint16s(b[end:], s.Sixteen, l15)
	return
}

func (s *Sixteen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 16 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15])
	if l < 16+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 16, 16+l0*2
	s.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	s.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	s.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	s.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	s.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	s.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	s.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	s.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	s.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	s.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	s.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	s.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	s.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	s.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	s.Fifteen = jay.ReadUint16s(b[at:end], l14)
	s.Sixteen = jay.ReadUint16s(b[end:], l15)
	return nil
}

func (s *Seventeen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16 := len(s.One), len(s.Two), len(s.Three), len(s.Four), len(s.Five), len(s.Six), len(s.Seven), len(s.Eight), len(s.Nine), len(s.Ten), len(s.Eleven), len(s.Twelve), len(s.Thirteen), len(s.Fourteen), len(s.Fifteen), len(s.Sixteen), len(s.Seventeen)
	b = make([]byte, 17+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16)
	at, end := 17, 17+l0*2
	jay.WriteUint16s(b[at:end], s.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], s.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], s.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], s.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], s.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], s.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], s.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], s.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], s.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], s.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], s.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], s.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], s.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], s.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], s.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], s.Sixteen, l15)
	jay.WriteUint16s(b[end:], s.Seventeen, l16)
	return
}

func (s *Seventeen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 17 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16])
	if l < 17+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 17, 17+l0*2
	s.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	s.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	s.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	s.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	s.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	s.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	s.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	s.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	s.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	s.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	s.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	s.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	s.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	s.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	s.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	s.Sixteen = jay.ReadUint16s(b[at:end], l15)
	s.Seventeen = jay.ReadUint16s(b[end:], l16)
	return nil
}

func (e *Eighteen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17 := len(e.One), len(e.Two), len(e.Three), len(e.Four), len(e.Five), len(e.Six), len(e.Seven), len(e.Eight), len(e.Nine), len(e.Ten), len(e.Eleven), len(e.Twelve), len(e.Thirteen), len(e.Fourteen), len(e.Fifteen), len(e.Sixteen), len(e.Seventeen), len(e.Eighteen)
	b = make([]byte, 18+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2+l17*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16), byte(l17)
	at, end := 18, 18+l0*2
	jay.WriteUint16s(b[at:end], e.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], e.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], e.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], e.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], e.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], e.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], e.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], e.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], e.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], e.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], e.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], e.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], e.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], e.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], e.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], e.Sixteen, l15)
	at, end = end, end+l16*2
	jay.WriteUint16s(b[at:end], e.Seventeen, l16)
	jay.WriteUint16s(b[end:], e.Eighteen, l17)
	return
}

func (e *Eighteen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 18 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16]), int(b[17])
	if l < 18+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16+l17 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 18, 18+l0*2
	e.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	e.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	e.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	e.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	e.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	e.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	e.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	e.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	e.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	e.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	e.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	e.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	e.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	e.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	e.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	e.Sixteen = jay.ReadUint16s(b[at:end], l15)
	at, end = end, end+l16*2
	e.Seventeen = jay.ReadUint16s(b[at:end], l16)
	e.Eighteen = jay.ReadUint16s(b[end:], l17)
	return nil
}

func (n *Nineteen) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18 := len(n.One), len(n.Two), len(n.Three), len(n.Four), len(n.Five), len(n.Six), len(n.Seven), len(n.Eight), len(n.Nine), len(n.Ten), len(n.Eleven), len(n.Twelve), len(n.Thirteen), len(n.Fourteen), len(n.Fifteen), len(n.Sixteen), len(n.Seventeen), len(n.Eighteen), len(n.Nineteen)
	b = make([]byte, 19+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2+l17*2+l18*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17], b[18] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16), byte(l17), byte(l18)
	at, end := 19, 19+l0*2
	jay.WriteUint16s(b[at:end], n.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], n.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], n.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], n.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], n.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], n.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], n.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], n.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], n.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], n.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], n.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], n.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], n.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], n.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], n.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], n.Sixteen, l15)
	at, end = end, end+l16*2
	jay.WriteUint16s(b[at:end], n.Seventeen, l16)
	at, end = end, end+l17*2
	jay.WriteUint16s(b[at:end], n.Eighteen, l17)
	jay.WriteUint16s(b[end:], n.Nineteen, l18)
	return
}

func (n *Nineteen) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 19 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16]), int(b[17]), int(b[18])
	if l < 19+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16+l17+l18 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 19, 19+l0*2
	n.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	n.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	n.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	n.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	n.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	n.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	n.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	n.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	n.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	n.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	n.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	n.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	n.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	n.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	n.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	n.Sixteen = jay.ReadUint16s(b[at:end], l15)
	at, end = end, end+l16*2
	n.Seventeen = jay.ReadUint16s(b[at:end], l16)
	at, end = end, end+l17*2
	n.Eighteen = jay.ReadUint16s(b[at:end], l17)
	n.Nineteen = jay.ReadUint16s(b[end:], l18)
	return nil
}

func (t *Twenty) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten), len(t.Eleven), len(t.Twelve), len(t.Thirteen), len(t.Fourteen), len(t.Fifteen), len(t.Sixteen), len(t.Seventeen), len(t.Eighteen), len(t.Nineteen), len(t.Twenty)
	b = make([]byte, 20+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2+l17*2+l18*2+l19*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17], b[18], b[19] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16), byte(l17), byte(l18), byte(l19)
	at, end := 20, 20+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], t.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], t.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], t.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], t.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], t.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], t.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], t.Sixteen, l15)
	at, end = end, end+l16*2
	jay.WriteUint16s(b[at:end], t.Seventeen, l16)
	at, end = end, end+l17*2
	jay.WriteUint16s(b[at:end], t.Eighteen, l17)
	at, end = end, end+l18*2
	jay.WriteUint16s(b[at:end], t.Nineteen, l18)
	jay.WriteUint16s(b[end:], t.Twenty, l19)
	return
}

func (t *Twenty) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 20 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16]), int(b[17]), int(b[18]), int(b[19])
	if l < 20+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16+l17+l18+l19 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 20, 20+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	t.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	t.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	t.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	t.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	t.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	t.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	t.Sixteen = jay.ReadUint16s(b[at:end], l15)
	at, end = end, end+l16*2
	t.Seventeen = jay.ReadUint16s(b[at:end], l16)
	at, end = end, end+l17*2
	t.Eighteen = jay.ReadUint16s(b[at:end], l17)
	at, end = end, end+l18*2
	t.Nineteen = jay.ReadUint16s(b[at:end], l18)
	t.Twenty = jay.ReadUint16s(b[end:], l19)
	return nil
}

func (t *TwentyOne) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten), len(t.Eleven), len(t.Twelve), len(t.Thirteen), len(t.Fourteen), len(t.Fifteen), len(t.Sixteen), len(t.Seventeen), len(t.Eighteen), len(t.Nineteen), len(t.Twenty), len(t.TwentyOne)
	b = make([]byte, 21+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2+l17*2+l18*2+l19*2+l20*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17], b[18], b[19], b[20] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16), byte(l17), byte(l18), byte(l19), byte(l20)
	at, end := 21, 21+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], t.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], t.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], t.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], t.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], t.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], t.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], t.Sixteen, l15)
	at, end = end, end+l16*2
	jay.WriteUint16s(b[at:end], t.Seventeen, l16)
	at, end = end, end+l17*2
	jay.WriteUint16s(b[at:end], t.Eighteen, l17)
	at, end = end, end+l18*2
	jay.WriteUint16s(b[at:end], t.Nineteen, l18)
	at, end = end, end+l19*2
	jay.WriteUint16s(b[at:end], t.Twenty, l19)
	jay.WriteUint16s(b[end:], t.TwentyOne, l20)
	return
}

func (t *TwentyOne) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 21 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16]), int(b[17]), int(b[18]), int(b[19]), int(b[20])
	if l < 21+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16+l17+l18+l19+l20 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 21, 21+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	t.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	t.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	t.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	t.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	t.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	t.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	t.Sixteen = jay.ReadUint16s(b[at:end], l15)
	at, end = end, end+l16*2
	t.Seventeen = jay.ReadUint16s(b[at:end], l16)
	at, end = end, end+l17*2
	t.Eighteen = jay.ReadUint16s(b[at:end], l17)
	at, end = end, end+l18*2
	t.Nineteen = jay.ReadUint16s(b[at:end], l18)
	at, end = end, end+l19*2
	t.Twenty = jay.ReadUint16s(b[at:end], l19)
	t.TwentyOne = jay.ReadUint16s(b[end:], l20)
	return nil
}

func (t *TwentyTwo) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten), len(t.Eleven), len(t.Twelve), len(t.Thirteen), len(t.Fourteen), len(t.Fifteen), len(t.Sixteen), len(t.Seventeen), len(t.Eighteen), len(t.Nineteen), len(t.Twenty), len(t.TwentyOne), len(t.TwentyTwo)
	b = make([]byte, 22+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2+l17*2+l18*2+l19*2+l20*2+l21*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17], b[18], b[19], b[20], b[21] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16), byte(l17), byte(l18), byte(l19), byte(l20), byte(l21)
	at, end := 22, 22+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], t.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], t.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], t.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], t.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], t.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], t.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], t.Sixteen, l15)
	at, end = end, end+l16*2
	jay.WriteUint16s(b[at:end], t.Seventeen, l16)
	at, end = end, end+l17*2
	jay.WriteUint16s(b[at:end], t.Eighteen, l17)
	at, end = end, end+l18*2
	jay.WriteUint16s(b[at:end], t.Nineteen, l18)
	at, end = end, end+l19*2
	jay.WriteUint16s(b[at:end], t.Twenty, l19)
	at, end = end, end+l20*2
	jay.WriteUint16s(b[at:end], t.TwentyOne, l20)
	jay.WriteUint16s(b[end:], t.TwentyTwo, l21)
	return
}

func (t *TwentyTwo) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 22 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16]), int(b[17]), int(b[18]), int(b[19]), int(b[20]), int(b[21])
	if l < 22+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16+l17+l18+l19+l20+l21 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 22, 22+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	t.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	t.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	t.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	t.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	t.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	t.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	t.Sixteen = jay.ReadUint16s(b[at:end], l15)
	at, end = end, end+l16*2
	t.Seventeen = jay.ReadUint16s(b[at:end], l16)
	at, end = end, end+l17*2
	t.Eighteen = jay.ReadUint16s(b[at:end], l17)
	at, end = end, end+l18*2
	t.Nineteen = jay.ReadUint16s(b[at:end], l18)
	at, end = end, end+l19*2
	t.Twenty = jay.ReadUint16s(b[at:end], l19)
	at, end = end, end+l20*2
	t.TwentyOne = jay.ReadUint16s(b[at:end], l20)
	t.TwentyTwo = jay.ReadUint16s(b[end:], l21)
	return nil
}

func (t *TwentyThree) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21, l22 := len(t.One), len(t.Two), len(t.Three), len(t.Four), len(t.Five), len(t.Six), len(t.Seven), len(t.Eight), len(t.Nine), len(t.Ten), len(t.Eleven), len(t.Twelve), len(t.Thirteen), len(t.Fourteen), len(t.Fifteen), len(t.Sixteen), len(t.Seventeen), len(t.Eighteen), len(t.Nineteen), len(t.Twenty), len(t.TwentyOne), len(t.TwentyTwo), len(t.TwentyThree)
	b = make([]byte, 23+l0*2+l1*2+l2*2+l3*2+l4*2+l5*2+l6*2+l7*2+l8*2+l9*2+l10*2+l11*2+l12*2+l13*2+l14*2+l15*2+l16*2+l17*2+l18*2+l19*2+l20*2+l21*2+l22*2)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15], b[16], b[17], b[18], b[19], b[20], b[21], b[22] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14), byte(l15), byte(l16), byte(l17), byte(l18), byte(l19), byte(l20), byte(l21), byte(l22)
	at, end := 23, 23+l0*2
	jay.WriteUint16s(b[at:end], t.One, l0)
	at, end = end, end+l1*2
	jay.WriteUint16s(b[at:end], t.Two, l1)
	at, end = end, end+l2*2
	jay.WriteUint16s(b[at:end], t.Three, l2)
	at, end = end, end+l3*2
	jay.WriteUint16s(b[at:end], t.Four, l3)
	at, end = end, end+l4*2
	jay.WriteUint16s(b[at:end], t.Five, l4)
	at, end = end, end+l5*2
	jay.WriteUint16s(b[at:end], t.Six, l5)
	at, end = end, end+l6*2
	jay.WriteUint16s(b[at:end], t.Seven, l6)
	at, end = end, end+l7*2
	jay.WriteUint16s(b[at:end], t.Eight, l7)
	at, end = end, end+l8*2
	jay.WriteUint16s(b[at:end], t.Nine, l8)
	at, end = end, end+l9*2
	jay.WriteUint16s(b[at:end], t.Ten, l9)
	at, end = end, end+l10*2
	jay.WriteUint16s(b[at:end], t.Eleven, l10)
	at, end = end, end+l11*2
	jay.WriteUint16s(b[at:end], t.Twelve, l11)
	at, end = end, end+l12*2
	jay.WriteUint16s(b[at:end], t.Thirteen, l12)
	at, end = end, end+l13*2
	jay.WriteUint16s(b[at:end], t.Fourteen, l13)
	at, end = end, end+l14*2
	jay.WriteUint16s(b[at:end], t.Fifteen, l14)
	at, end = end, end+l15*2
	jay.WriteUint16s(b[at:end], t.Sixteen, l15)
	at, end = end, end+l16*2
	jay.WriteUint16s(b[at:end], t.Seventeen, l16)
	at, end = end, end+l17*2
	jay.WriteUint16s(b[at:end], t.Eighteen, l17)
	at, end = end, end+l18*2
	jay.WriteUint16s(b[at:end], t.Nineteen, l18)
	at, end = end, end+l19*2
	jay.WriteUint16s(b[at:end], t.Twenty, l19)
	at, end = end, end+l20*2
	jay.WriteUint16s(b[at:end], t.TwentyOne, l20)
	at, end = end, end+l21*2
	jay.WriteUint16s(b[at:end], t.TwentyTwo, l21)
	jay.WriteUint16s(b[end:], t.TwentyThree, l22)
	return
}

func (t *TwentyThree) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 23 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21, l22 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14]), int(b[15]), int(b[16]), int(b[17]), int(b[18]), int(b[19]), int(b[20]), int(b[21]), int(b[22])
	if l < 23+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14+l15+l16+l17+l18+l19+l20+l21+l22 {
		return jay.ErrUnexpectedEOB
	}
	at, end := 23, 23+l0*2
	t.One = jay.ReadUint16s(b[at:end], l0)
	at, end = end, end+l1*2
	t.Two = jay.ReadUint16s(b[at:end], l1)
	at, end = end, end+l2*2
	t.Three = jay.ReadUint16s(b[at:end], l2)
	at, end = end, end+l3*2
	t.Four = jay.ReadUint16s(b[at:end], l3)
	at, end = end, end+l4*2
	t.Five = jay.ReadUint16s(b[at:end], l4)
	at, end = end, end+l5*2
	t.Six = jay.ReadUint16s(b[at:end], l5)
	at, end = end, end+l6*2
	t.Seven = jay.ReadUint16s(b[at:end], l6)
	at, end = end, end+l7*2
	t.Eight = jay.ReadUint16s(b[at:end], l7)
	at, end = end, end+l8*2
	t.Nine = jay.ReadUint16s(b[at:end], l8)
	at, end = end, end+l9*2
	t.Ten = jay.ReadUint16s(b[at:end], l9)
	at, end = end, end+l10*2
	t.Eleven = jay.ReadUint16s(b[at:end], l10)
	at, end = end, end+l11*2
	t.Twelve = jay.ReadUint16s(b[at:end], l11)
	at, end = end, end+l12*2
	t.Thirteen = jay.ReadUint16s(b[at:end], l12)
	at, end = end, end+l13*2
	t.Fourteen = jay.ReadUint16s(b[at:end], l13)
	at, end = end, end+l14*2
	t.Fifteen = jay.ReadUint16s(b[at:end], l14)
	at, end = end, end+l15*2
	t.Sixteen = jay.ReadUint16s(b[at:end], l15)
	at, end = end, end+l16*2
	t.Seventeen = jay.ReadUint16s(b[at:end], l16)
	at, end = end, end+l17*2
	t.Eighteen = jay.ReadUint16s(b[at:end], l17)
	at, end = end, end+l18*2
	t.Nineteen = jay.ReadUint16s(b[at:end], l18)
	at, end = end, end+l19*2
	t.Twenty = jay.ReadUint16s(b[at:end], l19)
	at, end = end, end+l20*2
	t.TwentyOne = jay.ReadUint16s(b[at:end], l20)
	at, end = end, end+l21*2
	t.TwentyTwo = jay.ReadUint16s(b[at:end], l21)
	t.TwentyThree = jay.ReadUint16s(b[end:], l22)
	return nil
}
