// Code generated by Jay; DO NOT EDIT. Tool documentation available at: https://github.com/speedyhoon/jay

package fuzz03

import "github.com/speedyhoon/jay"

func (u U6Ba28tAovfMN2Gps74G0I5ErVW18M0rpFA7o7v78k1155Oa50taNaINQ14Mfv0S8CQHHo4272N03el3uMYVC370201VR3mKRYud) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13 := len(u.YmswLkr8Dgw2), len(u.Ob3e7p2C8pH8ejwBUy61nFbHFjRueurwmi72j2tfr35cVjS5O3y), len(u.FbH70qR073dEIWDCXxpJ4a0qJhC4W72g2pS7D6gEQoYU2y7AW), len(u.KjOXx4VqJuY01327itq0cMJ), len(u.K43U6foxWwro6M4J1P), len(u.BUw556Nqj3ytxnel3bm05caCa5uTgDK0sDv730qrt62srrfS1LoOM821), len(u.B5iXRo45537P8Np1PLu1pqeRD6S5dCR8skLecU65k5h7UgC1iO82vSc0iWlnC352I7sK20FH4YJ), len(u.UajCPLMc1j135Y74dk3yS6Gj6DC618UDf6262A4pUB0GH8JY7aJjp7kAQVjO3Q40xAQCe7t), len(u.I1x65d4VlQOPjiW5an0NXbls4cos3d3g2Nk3T7715wM236UGDaSsr77OYOtDm4YC), len(u.H0xmq10YD74U08b5uGh2l0eOpvbw2qL55c23hF13vi15Tp62p8OPBfjwaHMEqKx05ilHlN3Cd47eAKIKHLP1x06V8MA7v4), len(u.S2ftw6CjCpV0l0ie1d2X50wT6Kmqphq1EaC4FBATe60T0j3AAFbCo3yJsYQ5754vANBej4mGog832baX78oTf7ek), len(u.WGfpP5D83jy240J0o033ExaQR1G6i1tOD5R8koKQBifcY17P), len(u.C68vT35W147w0t4j0wo0yM0bVJMTE64Wnj4pGJX35Q11H2ocrb01Av3UM0), len(u.W40BE7b61Jvc0c5syJ3I62sesO410oR2Bg1W8mRn04kEjwCY12xt5AbUTmcskSNBk7dG5QxM3tlVy8g)
	b = make([]byte, 506+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13)
	b[14] = jay.Bool4(u.BKr2, u.M8fr2E7t6Im5aRsb7Q4gmwh4s3ssjki276VSh2bt1Djj6L, u.R5jb2V36AAs32Um6o4d7DP86rATW4REH82C355ohp0BmytuSXDPAq5D3384vlA2U1MMk87Uf783CyWd6PG2, u.D54GF0atqJiJouFiV0uk)
	b[15] = byte(u.FB5)
	b[16] = u.DfOtR3hc4BO6M8hCedOUE6O3Js87au8IP07UuhlTVsP807V85434OelJ08bO
	b[17] = u.OQ7THTAIhV2VpaiKSD4xuTRiuw1LTtM7qyxTw3
	b[18] = byte(u.Mt184oX0Ro4x4T82V5rsTOY)
	b[19] = u.Lgwds7s7GpomEUqtienXd00nLIpbmwmU60TuqYx
	b[20] = u.MyGN5ejNrXI6q7Q4M3R640NU67WKY3Q3M6
	b[21] = byte(u.K81iHA2S2U58WP3mGn5NRwokr08dE)
	b[22] = byte(u.KWNupuB872iLb7o77bpv5X46o7XiA52rVllRy3735I)
	b[23] = byte(u.VlvgXa2AhcAFR203Ak2IhvbG6yBH76EkUTFC5uvlV4hYUdBna2cvb6Sh0j2jTXDHhf6Rjb0jF7uBR3KLo3)
	b[24] = u.P0c2w4LcfBBO5oQx2L8541hY5Gq4WGMoQsa2wE72BE6h43oUG17pUmc80XYMt87b6
	b[25] = u.JApJX5w85QrBN8Gx6Vd7HnQpb7UXJhrx7Eh6vcfIPW
	b[26] = u.Y2R0HOwwlx1K8PA657S0UOxfXgPX
	b[27] = u.NYPBko0r11Ie6F4BtT1qN6Wv0ovL0pXyS72G02XV6IYLgBgfal6RJ3wU4lHVKDya3m1L0gjRefGd7e8G2O8475bnOx3
	b[28] = byte(u.NkPL31kYNMlQ)
	b[29] = byte(u.V1rbMQNgMpNbBI1nC1cOxo55BaG002gqbSAN1aJTjpMTq6iRfrY5aWv6jt27nTV43G26827jY1L8mBApEyvXI4gsklSWSH)
	b[30] = u.YCUi7gefL3bN8m8AVaXv2i2Or43Jruqf6b7I5MaG
	b[31] = u.Nch8snS4JBFtq0tlc66bbj0XgO2156CXao6P30q45qyXdP5oBkXYo
	b[32] = u.T8s83xw2VGQXbx75f4YXtjxaD4yJ2nW3v2xr5GH4m572a63vD3AQqviL1p7Vjw2rXVbC2NOhrFPj6OmGd7wu5S8L8ykNFtb
	b[33] = u.X7Al578fv1pVN2BJxJ60p24AuBWiDAGL83Fu30Tv1w7vWUp8Hf23NAJ5Cgll1U3j0Ql2FlCP2WkNfQuMVj0NoU38E323kduhPGk
	b[34] = u.XYtyA45acpr
	b[35] = u.D6J37KOh31dq15wuWeM7k3ik0ys55Q2V5nJmRSH5h0Y1CB
	b[36] = u.TH1gcwG3ra86ejMrVX1bq6Bx4FRxhatW1G36QGrA
	b[37] = u.UlFA1IDU83uru855o84HYBK64W4teyL18l7282HIMrqWpvGiKH86Kb2AedAsrjm
	b[38] = u.E53776TgHEH2xvl0HlI8u85Xj451GFK1E3v3X6CPv5A3PFCbVl4hGm
	b[39] = u.Y4eg67RO1b2CLCL7H7SsPX2bsw65eEb01Cu5C8vC2Ner40ytEep0mLuBV2vMe0S88NE0E8KUh72E8
	b[40] = u.U3gt4UOFBfn7T22Msi4HXH3mO2YULF
	b[41] = u.O6CVCbxx22qifwL
	jay.WriteUintArch64(b[42:50], u.Y4IxMY5J5q5ou8358GsF6vQ784orH8Cj4gg8Lk0uwsTHwb0T)
	jay.WriteUint32(b[50:54], u.Xj6WsmID64IN1ycdcOkpf0O23c68WL5UkJ7hLI3y)
	jay.WriteInt16(b[54:56], u.ToTj35ccb85A6ekp46r6ROc5SgEX4sVl1Md63rWII8O8ELv10EE354s8M0a8Gy)
	jay.WriteInt32(b[56:60], u.DL0nDLKeo325W5P0008RBNUuCE3s262lSrXQ6p30A27XmwrUcIkKWT15A52Omk1G)
	jay.WriteInt32(b[60:64], u.AaIfn2E85rmH1x251p8)
	jay.WriteUint32(b[64:68], u.C1vXkuYrKkd32lVEgQv1LJGD)
	jay.WriteUint64(b[68:76], u.B2kN848uQn1CXPpXP3d5vh6rAkQ33X7He846T3074L245E3uKEQ7FnkVI1v4)
	jay.WriteInt32(b[76:80], u.Qe23F71nf138W0)
	jay.WriteUint64(b[80:88], u.EoD5sv8XET4eJE1M7DVE5WvdViH3Gj7C1wRg8g2ODOBxMosDoCv0ASPY36qh28AL76O2cup172g561HLS3XS7m38L4hJYx)
	jay.WriteFloat64(b[88:96], u.LsgWd470C4GU8461MayF3L24q5bt2Stb5)
	jay.WriteTime(b[96:104], u.WYDNq14085mbH6h6lRpff08ik8U4IV5PAB5Nxri661YS1i7Jh5NW2822xTpQxrX3cWheQ5Hc1PxI33y)
	jay.WriteUint16(b[104:106], u.C7U8wtKq67Hj0x2rSoQ5cyEV)
	jay.WriteUint64(b[106:114], u.WPxPg7t8eEKe8BX005wbFcu381f2PPh2vfauWdUEJ3ticDPY0cur7366aXq)
	jay.WriteInt32(b[114:118], u.U17xJNRrn56JXiwOY2I2tE)
	jay.WriteFloat32(b[118:122], u.FyQw246H0g8WSB5Gg27H12U02qaxGAp3UNCg2504U7d78G3M5DwJBu2cEw0NxVlhi15w2)
	jay.WriteUint64(b[122:130], u.D57w4L0XKdNOKXHU8Nldg3g4rvcjd44rUj)
	jay.WriteUint32(b[130:134], u.Gi6uWWcsAyW62180u1QvTxgm1JAa5Ur6sW85StLuDm0EbUJg1qh)
	jay.WriteUint32(b[134:138], u.X0S04XSMSFsD4yimwcVptaVTC107bX0iaGhvPFRuKP)
	jay.WriteInt64(b[138:146], u.RFuyK3bxptLK6l0a4w6204lIPmufL3LDcc1kTWutolY7JNWdCYxbF3bTp)
	jay.WriteInt32(b[146:150], u.EnmLK1177yoa4Clg7n4rr873goMnL7klUAcJ13J6w2CnTHhgOj)
	jay.WriteUint32(b[150:154], u.OMgOr088rM8RK0C7nCJ3IAbI6rl512g64nrx1RtW18RcA6V2fo7738R1VB0GO6p51s6klyWYM3KSqAtr)
	jay.WriteUint64(b[154:162], u.W7R21Qu80xlJSD04IyU5G)
	jay.WriteUint32(b[162:166], u.Ww)
	jay.WriteIntArch64(b[166:174], u.JC15jt63PL0QrJ6Y6k406A8gcE5acWPLOU14ey155t5q278VSuWl8qtkigws)
	jay.WriteIntArch64(b[174:182], u.KQG3at6K83cs0Uu57lpa2c8cXd6Sf1c4LQyE612chsV67XhV2HdyK3ymhd)
	jay.WriteFloat32(b[182:186], u.Xu7tb4fiyv3443)
	jay.WriteUintArch64(b[186:194], u.H6pK0obynl2xCovLTQ)
	jay.WriteInt32(b[194:198], u.FJnOx87UYQuf8tBDQx2p13u8d51womM0lIiGDJ7336L562l5m5c4qg6t2tal0p67hcV)
	jay.WriteInt32(b[198:202], u.UiM7DeG6vVFWf6x28h246YGLVyUGY15g7ppvkGmGE14y11aEbq1Q72TytReLMF003p3S7dvMkhdlhpR5r7OP5P1GYY4vL)
	jay.WriteInt32(b[202:206], u.V6mx4W0SrM7h38j35nDoD1yCJg5u)
	jay.WriteIntArch64(b[206:214], u.JauN4lWtqUoPjPjtu5i1tsvlxHtnn228KVHgb)
	jay.WriteUint32(b[214:218], u.I30p6eGXN0E26oGIL6y2P5PILei4113fPpTG3dlE3Si2)
	jay.WriteFloat64(b[218:226], u.W2Jwe5l34SF14305wWd2w33fWCo6XjqEuvi7D0m3wWNda837iQ16tJ71o0ry44PuWSdi1h470i8sgt57l5rCMs7)
	jay.WriteUint64(b[226:234], u.L25053SD1a3A43KvK30ac066Y1SL6SvV0ttWOxTufhjpavt37PW4f1o5m7)
	jay.WriteInt64(b[234:242], u.X526723l8y8NK2nCX6gFyLx)
	jay.WriteFloat64(b[242:250], u.I41i0)
	jay.WriteFloat64(b[250:258], u.QeRYJnnTLBpVcVYd5BoP8gu0x2vBpaMQ6SGg68vcISubbTE676AXrc7Uw61)
	jay.WriteTime(b[258:266], u.K5qIxy7r4i61Dn2I)
	jay.WriteFloat32(b[266:270], u.N73Y8sR1qnP37C2umdayTB0f7p7kDRehElRpdLOte8AW4jm1YrlCP2kbEjM0qb1EkyFBsNkMHdC)
	jay.WriteTime(b[270:278], u.O1)
	jay.WriteInt64(b[278:286], u.PqN5YPsr14qM5724j1A1psJiGvViBiUQ7IuB33Aowoxy7plRoF2AQkmH8581MqpQE1hFxW6T0N)
	jay.WriteFloat32(b[286:290], u.Liq4r3)
	jay.WriteUintArch64(b[290:298], u.M0cTVE3ugBkQ1LoCYpg4M2be01GYHh3u0kkXCoRf5aCAc81G8Q8Yru5yxGp03)
	jay.WriteFloat64(b[298:306], u.I255rW7f35Wux633KX46sE76134s0q44MYJfS5r6M6r2F53Mjo4IHo3S6Qjk4an3231co2hALMsVLEw)
	jay.WriteFloat32(b[306:310], u.Qj6Nu36K3a2TLm4Dn3136s8jhtoBbJ7I585400sJ62fpfiQKg5QD2g2eEJclsr0r24HK7803PME8eBIf6cJG)
	jay.WriteUint16(b[310:312], u.YR3m3m55o8lk153g56syAoG)
	jay.WriteInt64(b[312:320], u.UBoO3Ydf2)
	jay.WriteFloat32(b[320:324], u.Q2)
	jay.WriteUint16(b[324:326], u.P2AV5ydE43o7R3gICkA1pfvl5C11B48uYo8h6OxirTq735d65G0OB502)
	jay.WriteInt32(b[326:330], u.O8GNbDOR0VDLa7gepyLT3WaaU51SJbLyI844j0X0IG5wYo2vBy1S6KqUi6h8XD5UA4U)
	jay.WriteInt64(b[330:338], u.VCXjCc5wi3RC7p8553xG1pqEDV4bwh)
	jay.WriteInt64(b[338:346], u.G7O2WdU858fiFlj2Eh00Qi0o0UJ1Eo5yGA26J08LEx6S1ld6A8D864pXDKC1371xkU8L3L0fuLw77ge0v5gBNr74NxFrA)
	jay.WriteUintArch64(b[346:354], u.M058HpLSba)
	jay.WriteUint16(b[354:356], u.Gc5Dmq4XRoHK5b5M4B3R2y0X8MCK6qvVACW5Eo1y6In7342Vuq2JKO2yJLdi0qBAvKEIV2ETDm8SHTg8J)
	jay.WriteUint64(b[356:364], u.Habi)
	jay.WriteIntArch64(b[364:372], u.Fn0jLrHddFY4BjR7lY5CtfK6HL7G123meNYM)
	jay.WriteFloat32(b[372:376], u.Hwx1kPR7nk0055PlmkkI6SDQSj)
	jay.WriteIntArch64(b[376:384], u.Y2ej7y)
	jay.WriteUint64(b[384:392], u.TqK1kI25Ra35fU21Nd5HUQV6P6U6CBD0i2b5KKq0pyl4DO0nfXv533H582k402btyETaMjFTXly487oY51Pa8S)
	jay.WriteUintArch64(b[392:400], u.U6K0Gile4TqLh77VLmO0wXJntY8A2K4FU2Mj86155fqkNx)
	jay.WriteInt64(b[400:408], u.SPGKsb4U17NLrw6f3D53Dcvt0BC4422J1br44biN641WS0d5V8yv6rEAIohp4S0k7aoU0CO0Y)
	jay.WriteUint64(b[408:416], u.CCJq6l32gjXkm6PLqGggTX4Ds1H821bbA3r3HP6KiW5Tys83TJ6SB2damIHGKTs874Bm8J4eIP7)
	jay.WriteInt16(b[416:418], u.VUl8nexnfQen)
	jay.WriteInt16(b[418:420], u.TLN)
	jay.WriteUint16(b[420:422], u.MWPHR37T2r875tMc6vmUJg2Rx3SGmIb6JB5j52FfqY0VXu33MJxN)
	jay.WriteIntArch64(b[422:430], u.El0lD5gXvu601EENN338dX7c8O7qD6a2u64X06QI13g77G4qse7Vg7yn727ui716JRfSsb1)
	jay.WriteUint16(b[430:432], u.TqI6Ry2JgQ6rS845B8mhe31S38VPt35cq44VxSsE77Wnpfmlsp4IvVAQ4733lNkd84VS00t578J)
	jay.WriteFloat64(b[432:440], u.DS7SNB237Ya76NsxIK1d5W1peC5r5i1U8FDt)
	jay.WriteInt32(b[440:444], u.G4ocC2hiJpL28D)
	jay.WriteUintArch64(b[444:452], u.PNiwx3K52q41YCuLqu3lgpxoA4P653v5H5jFX11u3vbS3VtaOmB06y0yf6NyAspOe0UR1O4qE0n8)
	jay.WriteUint32(b[452:456], u.KqJfR4UE2Y2X3iiD7RJICs65lrAPyia2rNFFr35263R8vdgg2w6sGRS1HNAD5kxm)
	jay.WriteFloat64(b[456:464], u.P2u0U4a6NR3G65S5I7y67j5uU2MW3pMypJmd)
	jay.WriteInt16(b[464:466], u.O2wC1CIKAFCKR68MykRpvTWy6Q5g)
	jay.WriteInt64(b[466:474], u.L2j7b531X1ihaJn6pu2ek2v3WdmbN867Gvw50iH6ot2Sit0Nb6UN33Xxn651I8dfv408Q81oUm2EurWd5kJvEwB)
	jay.WriteInt16(b[474:476], u.LkP8r3g55A33cG8o1X0dQ6vDmsxkM8xr7MijI3764ro6HbORKr7m063XSRd3GPTMhE5Fa0v24hIe2qsO602mhX)
	jay.WriteUint64(b[476:484], u.FHquL5rYEk543pm324LHg08tS7D02133dcFmJx8Ilw3vi4TJ5a6q3PHrgDqsmUMwyeWu48nQn0FbwN2uiEh2x)
	jay.WriteIntArch64(b[484:492], u.Wv2qRIkOgt1D4b45pN0t40X04nV3f)
	jay.WriteInt32(b[492:496], u.J0C074ChJ74p2f42eX5v33jGHkqY45y0m8Oe7Eli0vwoD12yfebDKHRgp67n3gdqYinCC)
	jay.WriteInt64(b[496:504], u.EsmkoN4Ra8kH88)
	jay.WriteInt16(b[504:506], u.Kfxx2L3Rh6a5Tf50p4c5)
	at, end := 506, 506+l0
	copy(b[at:end], u.YmswLkr8Dgw2)
	at, end = end, end+l1
	if l1 != 0 {
		copy(b[at:end], u.Ob3e7p2C8pH8ejwBUy61nFbHFjRueurwmi72j2tfr35cVjS5O3y)
	}
	at, end = end, end+l2
	if l2 != 0 {
		copy(b[at:end], u.FbH70qR073dEIWDCXxpJ4a0qJhC4W72g2pS7D6gEQoYU2y7AW)
	}
	at, end = end, end+l3
	copy(b[at:end], u.KjOXx4VqJuY01327itq0cMJ)
	at, end = end, end+l4
	if l4 != 0 {
		copy(b[at:end], u.K43U6foxWwro6M4J1P)
	}
	at, end = end, end+l5
	if l5 != 0 {
		copy(b[at:end], u.BUw556Nqj3ytxnel3bm05caCa5uTgDK0sDv730qrt62srrfS1LoOM821)
	}
	at, end = end, end+l6
	copy(b[at:end], u.B5iXRo45537P8Np1PLu1pqeRD6S5dCR8skLecU65k5h7UgC1iO82vSc0iWlnC352I7sK20FH4YJ)
	at, end = end, end+l7
	if l7 != 0 {
		copy(b[at:end], u.UajCPLMc1j135Y74dk3yS6Gj6DC618UDf6262A4pUB0GH8JY7aJjp7kAQVjO3Q40xAQCe7t)
	}
	at, end = end, end+l8
	copy(b[at:end], u.I1x65d4VlQOPjiW5an0NXbls4cos3d3g2Nk3T7715wM236UGDaSsr77OYOtDm4YC)
	at, end = end, end+l9
	copy(b[at:end], u.H0xmq10YD74U08b5uGh2l0eOpvbw2qL55c23hF13vi15Tp62p8OPBfjwaHMEqKx05ilHlN3Cd47eAKIKHLP1x06V8MA7v4)
	at, end = end, end+l10
	if l10 != 0 {
		copy(b[at:end], u.S2ftw6CjCpV0l0ie1d2X50wT6Kmqphq1EaC4FBATe60T0j3AAFbCo3yJsYQ5754vANBej4mGog832baX78oTf7ek)
	}
	at, end = end, end+l11
	if l11 != 0 {
		copy(b[at:end], u.WGfpP5D83jy240J0o033ExaQR1G6i1tOD5R8koKQBifcY17P)
	}
	at, end = end, end+l12
	copy(b[at:end], u.C68vT35W147w0t4j0wo0yM0bVJMTE64Wnj4pGJX35Q11H2ocrb01Av3UM0)
	copy(b[end:], u.W40BE7b61Jvc0c5syJ3I62sesO410oR2Bg1W8mRn04kEjwCY12xt5AbUTmcskSNBk7dG5QxM3tlVy8g)
	return
}

func (u *U6Ba28tAovfMN2Gps74G0I5ErVW18M0rpFA7o7v78k1155Oa50taNaINQ14Mfv0S8CQHHo4272N03el3uMYVC370201VR3mKRYud) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 506 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13])
	if l < 506+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13 {
		return jay.ErrUnexpectedEOB
	}
	u.BKr2, u.M8fr2E7t6Im5aRsb7Q4gmwh4s3ssjki276VSh2bt1Djj6L, u.R5jb2V36AAs32Um6o4d7DP86rATW4REH82C355ohp0BmytuSXDPAq5D3384vlA2U1MMk87Uf783CyWd6PG2, u.D54GF0atqJiJouFiV0uk = jay.ReadBool4(b[14])
	u.FB5 = int8(b[15])
	u.DfOtR3hc4BO6M8hCedOUE6O3Js87au8IP07UuhlTVsP807V85434OelJ08bO = b[16]
	u.OQ7THTAIhV2VpaiKSD4xuTRiuw1LTtM7qyxTw3 = b[17]
	u.Mt184oX0Ro4x4T82V5rsTOY = int8(b[18])
	u.Lgwds7s7GpomEUqtienXd00nLIpbmwmU60TuqYx = b[19]
	u.MyGN5ejNrXI6q7Q4M3R640NU67WKY3Q3M6 = b[20]
	u.K81iHA2S2U58WP3mGn5NRwokr08dE = int8(b[21])
	u.KWNupuB872iLb7o77bpv5X46o7XiA52rVllRy3735I = int8(b[22])
	u.VlvgXa2AhcAFR203Ak2IhvbG6yBH76EkUTFC5uvlV4hYUdBna2cvb6Sh0j2jTXDHhf6Rjb0jF7uBR3KLo3 = int8(b[23])
	u.P0c2w4LcfBBO5oQx2L8541hY5Gq4WGMoQsa2wE72BE6h43oUG17pUmc80XYMt87b6 = b[24]
	u.JApJX5w85QrBN8Gx6Vd7HnQpb7UXJhrx7Eh6vcfIPW = b[25]
	u.Y2R0HOwwlx1K8PA657S0UOxfXgPX = b[26]
	u.NYPBko0r11Ie6F4BtT1qN6Wv0ovL0pXyS72G02XV6IYLgBgfal6RJ3wU4lHVKDya3m1L0gjRefGd7e8G2O8475bnOx3 = b[27]
	u.NkPL31kYNMlQ = int8(b[28])
	u.V1rbMQNgMpNbBI1nC1cOxo55BaG002gqbSAN1aJTjpMTq6iRfrY5aWv6jt27nTV43G26827jY1L8mBApEyvXI4gsklSWSH = int8(b[29])
	u.YCUi7gefL3bN8m8AVaXv2i2Or43Jruqf6b7I5MaG = b[30]
	u.Nch8snS4JBFtq0tlc66bbj0XgO2156CXao6P30q45qyXdP5oBkXYo = b[31]
	u.T8s83xw2VGQXbx75f4YXtjxaD4yJ2nW3v2xr5GH4m572a63vD3AQqviL1p7Vjw2rXVbC2NOhrFPj6OmGd7wu5S8L8ykNFtb = b[32]
	u.X7Al578fv1pVN2BJxJ60p24AuBWiDAGL83Fu30Tv1w7vWUp8Hf23NAJ5Cgll1U3j0Ql2FlCP2WkNfQuMVj0NoU38E323kduhPGk = b[33]
	u.XYtyA45acpr = b[34]
	u.D6J37KOh31dq15wuWeM7k3ik0ys55Q2V5nJmRSH5h0Y1CB = b[35]
	u.TH1gcwG3ra86ejMrVX1bq6Bx4FRxhatW1G36QGrA = b[36]
	u.UlFA1IDU83uru855o84HYBK64W4teyL18l7282HIMrqWpvGiKH86Kb2AedAsrjm = b[37]
	u.E53776TgHEH2xvl0HlI8u85Xj451GFK1E3v3X6CPv5A3PFCbVl4hGm = b[38]
	u.Y4eg67RO1b2CLCL7H7SsPX2bsw65eEb01Cu5C8vC2Ner40ytEep0mLuBV2vMe0S88NE0E8KUh72E8 = b[39]
	u.U3gt4UOFBfn7T22Msi4HXH3mO2YULF = b[40]
	u.O6CVCbxx22qifwL = b[41]
	u.Y4IxMY5J5q5ou8358GsF6vQ784orH8Cj4gg8Lk0uwsTHwb0T = jay.ReadUintArch64(b[42:50])
	u.Xj6WsmID64IN1ycdcOkpf0O23c68WL5UkJ7hLI3y = jay.ReadUint32(b[50:54])
	u.ToTj35ccb85A6ekp46r6ROc5SgEX4sVl1Md63rWII8O8ELv10EE354s8M0a8Gy = jay.ReadInt16(b[54:56])
	u.DL0nDLKeo325W5P0008RBNUuCE3s262lSrXQ6p30A27XmwrUcIkKWT15A52Omk1G = jay.ReadInt32(b[56:60])
	u.AaIfn2E85rmH1x251p8 = jay.ReadInt32(b[60:64])
	u.C1vXkuYrKkd32lVEgQv1LJGD = jay.ReadUint32(b[64:68])
	u.B2kN848uQn1CXPpXP3d5vh6rAkQ33X7He846T3074L245E3uKEQ7FnkVI1v4 = jay.ReadUint64(b[68:76])
	u.Qe23F71nf138W0 = jay.ReadInt32(b[76:80])
	u.EoD5sv8XET4eJE1M7DVE5WvdViH3Gj7C1wRg8g2ODOBxMosDoCv0ASPY36qh28AL76O2cup172g561HLS3XS7m38L4hJYx = jay.ReadUint64(b[80:88])
	u.LsgWd470C4GU8461MayF3L24q5bt2Stb5 = jay.ReadFloat64(b[88:96])
	u.WYDNq14085mbH6h6lRpff08ik8U4IV5PAB5Nxri661YS1i7Jh5NW2822xTpQxrX3cWheQ5Hc1PxI33y = jay.ReadTime(b[96:104])
	u.C7U8wtKq67Hj0x2rSoQ5cyEV = jay.ReadUint16(b[104:106])
	u.WPxPg7t8eEKe8BX005wbFcu381f2PPh2vfauWdUEJ3ticDPY0cur7366aXq = jay.ReadUint64(b[106:114])
	u.U17xJNRrn56JXiwOY2I2tE = jay.ReadInt32(b[114:118])
	u.FyQw246H0g8WSB5Gg27H12U02qaxGAp3UNCg2504U7d78G3M5DwJBu2cEw0NxVlhi15w2 = jay.ReadFloat32(b[118:122])
	u.D57w4L0XKdNOKXHU8Nldg3g4rvcjd44rUj = jay.ReadUint64(b[122:130])
	u.Gi6uWWcsAyW62180u1QvTxgm1JAa5Ur6sW85StLuDm0EbUJg1qh = jay.ReadUint32(b[130:134])
	u.X0S04XSMSFsD4yimwcVptaVTC107bX0iaGhvPFRuKP = jay.ReadUint32(b[134:138])
	u.RFuyK3bxptLK6l0a4w6204lIPmufL3LDcc1kTWutolY7JNWdCYxbF3bTp = jay.ReadInt64(b[138:146])
	u.EnmLK1177yoa4Clg7n4rr873goMnL7klUAcJ13J6w2CnTHhgOj = jay.ReadInt32(b[146:150])
	u.OMgOr088rM8RK0C7nCJ3IAbI6rl512g64nrx1RtW18RcA6V2fo7738R1VB0GO6p51s6klyWYM3KSqAtr = jay.ReadUint32(b[150:154])
	u.W7R21Qu80xlJSD04IyU5G = jay.ReadUint64(b[154:162])
	u.Ww = jay.ReadUint32(b[162:166])
	u.JC15jt63PL0QrJ6Y6k406A8gcE5acWPLOU14ey155t5q278VSuWl8qtkigws = jay.ReadIntArch64(b[166:174])
	u.KQG3at6K83cs0Uu57lpa2c8cXd6Sf1c4LQyE612chsV67XhV2HdyK3ymhd = jay.ReadIntArch64(b[174:182])
	u.Xu7tb4fiyv3443 = jay.ReadFloat32(b[182:186])
	u.H6pK0obynl2xCovLTQ = jay.ReadUintArch64(b[186:194])
	u.FJnOx87UYQuf8tBDQx2p13u8d51womM0lIiGDJ7336L562l5m5c4qg6t2tal0p67hcV = jay.ReadInt32(b[194:198])
	u.UiM7DeG6vVFWf6x28h246YGLVyUGY15g7ppvkGmGE14y11aEbq1Q72TytReLMF003p3S7dvMkhdlhpR5r7OP5P1GYY4vL = jay.ReadInt32(b[198:202])
	u.V6mx4W0SrM7h38j35nDoD1yCJg5u = jay.ReadInt32(b[202:206])
	u.JauN4lWtqUoPjPjtu5i1tsvlxHtnn228KVHgb = jay.ReadIntArch64(b[206:214])
	u.I30p6eGXN0E26oGIL6y2P5PILei4113fPpTG3dlE3Si2 = jay.ReadUint32(b[214:218])
	u.W2Jwe5l34SF14305wWd2w33fWCo6XjqEuvi7D0m3wWNda837iQ16tJ71o0ry44PuWSdi1h470i8sgt57l5rCMs7 = jay.ReadFloat64(b[218:226])
	u.L25053SD1a3A43KvK30ac066Y1SL6SvV0ttWOxTufhjpavt37PW4f1o5m7 = jay.ReadUint64(b[226:234])
	u.X526723l8y8NK2nCX6gFyLx = jay.ReadInt64(b[234:242])
	u.I41i0 = jay.ReadFloat64(b[242:250])
	u.QeRYJnnTLBpVcVYd5BoP8gu0x2vBpaMQ6SGg68vcISubbTE676AXrc7Uw61 = jay.ReadFloat64(b[250:258])
	u.K5qIxy7r4i61Dn2I = jay.ReadTime(b[258:266])
	u.N73Y8sR1qnP37C2umdayTB0f7p7kDRehElRpdLOte8AW4jm1YrlCP2kbEjM0qb1EkyFBsNkMHdC = jay.ReadFloat32(b[266:270])
	u.O1 = jay.ReadTime(b[270:278])
	u.PqN5YPsr14qM5724j1A1psJiGvViBiUQ7IuB33Aowoxy7plRoF2AQkmH8581MqpQE1hFxW6T0N = jay.ReadInt64(b[278:286])
	u.Liq4r3 = jay.ReadFloat32(b[286:290])
	u.M0cTVE3ugBkQ1LoCYpg4M2be01GYHh3u0kkXCoRf5aCAc81G8Q8Yru5yxGp03 = jay.ReadUintArch64(b[290:298])
	u.I255rW7f35Wux633KX46sE76134s0q44MYJfS5r6M6r2F53Mjo4IHo3S6Qjk4an3231co2hALMsVLEw = jay.ReadFloat64(b[298:306])
	u.Qj6Nu36K3a2TLm4Dn3136s8jhtoBbJ7I585400sJ62fpfiQKg5QD2g2eEJclsr0r24HK7803PME8eBIf6cJG = jay.ReadFloat32(b[306:310])
	u.YR3m3m55o8lk153g56syAoG = jay.ReadUint16(b[310:312])
	u.UBoO3Ydf2 = jay.ReadInt64(b[312:320])
	u.Q2 = jay.ReadFloat32(b[320:324])
	u.P2AV5ydE43o7R3gICkA1pfvl5C11B48uYo8h6OxirTq735d65G0OB502 = jay.ReadUint16(b[324:326])
	u.O8GNbDOR0VDLa7gepyLT3WaaU51SJbLyI844j0X0IG5wYo2vBy1S6KqUi6h8XD5UA4U = jay.ReadInt32(b[326:330])
	u.VCXjCc5wi3RC7p8553xG1pqEDV4bwh = jay.ReadInt64(b[330:338])
	u.G7O2WdU858fiFlj2Eh00Qi0o0UJ1Eo5yGA26J08LEx6S1ld6A8D864pXDKC1371xkU8L3L0fuLw77ge0v5gBNr74NxFrA = jay.ReadInt64(b[338:346])
	u.M058HpLSba = jay.ReadUintArch64(b[346:354])
	u.Gc5Dmq4XRoHK5b5M4B3R2y0X8MCK6qvVACW5Eo1y6In7342Vuq2JKO2yJLdi0qBAvKEIV2ETDm8SHTg8J = jay.ReadUint16(b[354:356])
	u.Habi = jay.ReadUint64(b[356:364])
	u.Fn0jLrHddFY4BjR7lY5CtfK6HL7G123meNYM = jay.ReadIntArch64(b[364:372])
	u.Hwx1kPR7nk0055PlmkkI6SDQSj = jay.ReadFloat32(b[372:376])
	u.Y2ej7y = jay.ReadIntArch64(b[376:384])
	u.TqK1kI25Ra35fU21Nd5HUQV6P6U6CBD0i2b5KKq0pyl4DO0nfXv533H582k402btyETaMjFTXly487oY51Pa8S = jay.ReadUint64(b[384:392])
	u.U6K0Gile4TqLh77VLmO0wXJntY8A2K4FU2Mj86155fqkNx = jay.ReadUintArch64(b[392:400])
	u.SPGKsb4U17NLrw6f3D53Dcvt0BC4422J1br44biN641WS0d5V8yv6rEAIohp4S0k7aoU0CO0Y = jay.ReadInt64(b[400:408])
	u.CCJq6l32gjXkm6PLqGggTX4Ds1H821bbA3r3HP6KiW5Tys83TJ6SB2damIHGKTs874Bm8J4eIP7 = jay.ReadUint64(b[408:416])
	u.VUl8nexnfQen = jay.ReadInt16(b[416:418])
	u.TLN = jay.ReadInt16(b[418:420])
	u.MWPHR37T2r875tMc6vmUJg2Rx3SGmIb6JB5j52FfqY0VXu33MJxN = jay.ReadUint16(b[420:422])
	u.El0lD5gXvu601EENN338dX7c8O7qD6a2u64X06QI13g77G4qse7Vg7yn727ui716JRfSsb1 = jay.ReadIntArch64(b[422:430])
	u.TqI6Ry2JgQ6rS845B8mhe31S38VPt35cq44VxSsE77Wnpfmlsp4IvVAQ4733lNkd84VS00t578J = jay.ReadUint16(b[430:432])
	u.DS7SNB237Ya76NsxIK1d5W1peC5r5i1U8FDt = jay.ReadFloat64(b[432:440])
	u.G4ocC2hiJpL28D = jay.ReadInt32(b[440:444])
	u.PNiwx3K52q41YCuLqu3lgpxoA4P653v5H5jFX11u3vbS3VtaOmB06y0yf6NyAspOe0UR1O4qE0n8 = jay.ReadUintArch64(b[444:452])
	u.KqJfR4UE2Y2X3iiD7RJICs65lrAPyia2rNFFr35263R8vdgg2w6sGRS1HNAD5kxm = jay.ReadUint32(b[452:456])
	u.P2u0U4a6NR3G65S5I7y67j5uU2MW3pMypJmd = jay.ReadFloat64(b[456:464])
	u.O2wC1CIKAFCKR68MykRpvTWy6Q5g = jay.ReadInt16(b[464:466])
	u.L2j7b531X1ihaJn6pu2ek2v3WdmbN867Gvw50iH6ot2Sit0Nb6UN33Xxn651I8dfv408Q81oUm2EurWd5kJvEwB = jay.ReadInt64(b[466:474])
	u.LkP8r3g55A33cG8o1X0dQ6vDmsxkM8xr7MijI3764ro6HbORKr7m063XSRd3GPTMhE5Fa0v24hIe2qsO602mhX = jay.ReadInt16(b[474:476])
	u.FHquL5rYEk543pm324LHg08tS7D02133dcFmJx8Ilw3vi4TJ5a6q3PHrgDqsmUMwyeWu48nQn0FbwN2uiEh2x = jay.ReadUint64(b[476:484])
	u.Wv2qRIkOgt1D4b45pN0t40X04nV3f = jay.ReadIntArch64(b[484:492])
	u.J0C074ChJ74p2f42eX5v33jGHkqY45y0m8Oe7Eli0vwoD12yfebDKHRgp67n3gdqYinCC = jay.ReadInt32(b[492:496])
	u.EsmkoN4Ra8kH88 = jay.ReadInt64(b[496:504])
	u.Kfxx2L3Rh6a5Tf50p4c5 = jay.ReadInt16(b[504:506])
	at, end := 506, 506+l0
	u.YmswLkr8Dgw2 = string(b[at:end])
	at, end = end, end+l1
	if l1 != 0 {
		u.Ob3e7p2C8pH8ejwBUy61nFbHFjRueurwmi72j2tfr35cVjS5O3y = b[at:end]
	}
	at, end = end, end+l2
	if l2 != 0 {
		u.FbH70qR073dEIWDCXxpJ4a0qJhC4W72g2pS7D6gEQoYU2y7AW = b[at:end]
	}
	at, end = end, end+l3
	u.KjOXx4VqJuY01327itq0cMJ = string(b[at:end])
	at, end = end, end+l4
	if l4 != 0 {
		u.K43U6foxWwro6M4J1P = b[at:end]
	}
	at, end = end, end+l5
	if l5 != 0 {
		u.BUw556Nqj3ytxnel3bm05caCa5uTgDK0sDv730qrt62srrfS1LoOM821 = b[at:end]
	}
	at, end = end, end+l6
	u.B5iXRo45537P8Np1PLu1pqeRD6S5dCR8skLecU65k5h7UgC1iO82vSc0iWlnC352I7sK20FH4YJ = string(b[at:end])
	at, end = end, end+l7
	if l7 != 0 {
		u.UajCPLMc1j135Y74dk3yS6Gj6DC618UDf6262A4pUB0GH8JY7aJjp7kAQVjO3Q40xAQCe7t = b[at:end]
	}
	at, end = end, end+l8
	u.I1x65d4VlQOPjiW5an0NXbls4cos3d3g2Nk3T7715wM236UGDaSsr77OYOtDm4YC = string(b[at:end])
	at, end = end, end+l9
	u.H0xmq10YD74U08b5uGh2l0eOpvbw2qL55c23hF13vi15Tp62p8OPBfjwaHMEqKx05ilHlN3Cd47eAKIKHLP1x06V8MA7v4 = string(b[at:end])
	at, end = end, end+l10
	if l10 != 0 {
		u.S2ftw6CjCpV0l0ie1d2X50wT6Kmqphq1EaC4FBATe60T0j3AAFbCo3yJsYQ5754vANBej4mGog832baX78oTf7ek = b[at:end]
	}
	at, end = end, end+l11
	if l11 != 0 {
		u.WGfpP5D83jy240J0o033ExaQR1G6i1tOD5R8koKQBifcY17P = b[at:end]
	}
	at, end = end, end+l12
	u.C68vT35W147w0t4j0wo0yM0bVJMTE64Wnj4pGJX35Q11H2ocrb01Av3UM0 = string(b[at:end])
	u.W40BE7b61Jvc0c5syJ3I62sesO410oR2Bg1W8mRn04kEjwCY12xt5AbUTmcskSNBk7dG5QxM3tlVy8g = string(b[end:])
	return nil
}

func (m MYh4g5vnmfR0Cl0fDWMn13r7KlRB8J6c3la4bN4nD3m8wcT0eOFSUk3t) MarshalJ() (b []byte) {
	l0 := len(m.Kd2CfE274tOMYecW72j28D51oIg183e5a8dmSYKlP0OE7uyKr48B)
	b = make([]byte, 75+l0)
	b[0] = byte(l0)
	b[1] = jay.Bool1(m.U4fmGkQtfA5AaBl0bh7)
	b[2] = byte(m.HJn5oC6o67h07Jq7n5KFn5v3k1dkj560gQOF)
	jay.WriteUint16(b[3:5], m.N71Sb0VaK57Or5s5)
	jay.WriteUint16(b[5:7], m.XHvtfmW60wYlW52gQ0D2L2Pn0uH8f0lHA3PCNmgrm6pRNDXij68O2)
	jay.WriteUint64(b[7:15], m.WNjSRx06bG2rRkmKJ2r0Hu5j3y0Q88110uSsPOha61Uxlwc5sO24uLR2rDxwMduP56O6EXPqAMf7SYwmuOwInYEahG7)
	jay.WriteFloat64(b[15:23], m.TffGEPr0FL)
	jay.WriteUintArch64(b[23:31], m.RUc5e5dH7ia2L2awyRKKWyr486YPgNy2r1YTvP7X8f24xR3WJ6iuw3tllrk688F77peKkEqswNy34ad4Dvb7lB414M)
	jay.WriteUint16(b[31:33], m.QIAfLs1MJ6AmV1Otl47)
	jay.WriteInt16(b[33:35], m.E3270gSfDLppevk0pdh62T6l0fk42u65v70rPR0sfo72H7GBLNsc1LnHi52OOvo5y0)
	jay.WriteUint16(b[35:37], m.E2e3VnjcT11t3mnb04gpWEeFb4KvYN3)
	jay.WriteIntArch64(b[37:45], m.TLt5o8BUd6X12iDsfG40587PNoU7G0uds7wIg5RVcw72Nyedhi8X0Mj11WFmoBSDgN4QmdwHWdamS)
	jay.WriteUint32(b[45:49], m.JU675641NIwp1A51UHL86gxU0cmp2FYkwCSsi2oGF3LUQ06ku42H)
	jay.WriteUint64(b[49:57], m.N0i6Okd130ck5cBYxtEW121JNOS15SgLr2HRcLPLWjO1A8x31x2il56BfK7AvnQCtGQeo7p4pLj)
	jay.WriteUint32(b[57:61], m.RHhV0W185xrV162y0sOfCdood46WJ6GlR7rUa4kQwt017P5q168l43aSF5UP)
	jay.WriteInt16(b[61:63], m.I5N7120u6b5t6ICoqLBYSW3mv3dWY36x3T8CDjSo7frY4uvPylgt632YTx3sg80O25eJ32XV2)
	jay.WriteFloat32(b[63:67], m.SEp0kW8oostEGaqO5nBG73RuM06aB3wnI7lJu5M2Ir2NaEP4aqrwS)
	jay.WriteInt32(b[67:71], m.Ma1e5W6I6NS2820Yqh0uyIE7S28lpbKCyU17JjRnN3ess67X4VuT3KvOsntaTrHj8YImG8OgXmj0I6T)
	jay.WriteInt32(b[71:75], m.Dt7wD5Tl8KnmwL574PKg3O41cufsDLa6feTYh6k6GdDg6VAQkAmA82p2Vy836xQkuGKs3S7aF7mSlipI0G1q76iQosEpPee84BdJ)
	if l0 != 0 {
		copy(b[75:], m.Kd2CfE274tOMYecW72j28D51oIg183e5a8dmSYKlP0OE7uyKr48B)
	}
	return
}

func (m *MYh4g5vnmfR0Cl0fDWMn13r7KlRB8J6c3la4bN4nD3m8wcT0eOFSUk3t) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 75 {
		return jay.ErrUnexpectedEOB
	}
	l0 := int(b[0])
	if l < 75+l0 {
		return jay.ErrUnexpectedEOB
	}
	m.U4fmGkQtfA5AaBl0bh7 = jay.ReadBool1(b[1])
	m.HJn5oC6o67h07Jq7n5KFn5v3k1dkj560gQOF = int8(b[2])
	m.N71Sb0VaK57Or5s5 = jay.ReadUint16(b[3:5])
	m.XHvtfmW60wYlW52gQ0D2L2Pn0uH8f0lHA3PCNmgrm6pRNDXij68O2 = jay.ReadUint16(b[5:7])
	m.WNjSRx06bG2rRkmKJ2r0Hu5j3y0Q88110uSsPOha61Uxlwc5sO24uLR2rDxwMduP56O6EXPqAMf7SYwmuOwInYEahG7 = jay.ReadUint64(b[7:15])
	m.TffGEPr0FL = jay.ReadFloat64(b[15:23])
	m.RUc5e5dH7ia2L2awyRKKWyr486YPgNy2r1YTvP7X8f24xR3WJ6iuw3tllrk688F77peKkEqswNy34ad4Dvb7lB414M = jay.ReadUintArch64(b[23:31])
	m.QIAfLs1MJ6AmV1Otl47 = jay.ReadUint16(b[31:33])
	m.E3270gSfDLppevk0pdh62T6l0fk42u65v70rPR0sfo72H7GBLNsc1LnHi52OOvo5y0 = jay.ReadInt16(b[33:35])
	m.E2e3VnjcT11t3mnb04gpWEeFb4KvYN3 = jay.ReadUint16(b[35:37])
	m.TLt5o8BUd6X12iDsfG40587PNoU7G0uds7wIg5RVcw72Nyedhi8X0Mj11WFmoBSDgN4QmdwHWdamS = jay.ReadIntArch64(b[37:45])
	m.JU675641NIwp1A51UHL86gxU0cmp2FYkwCSsi2oGF3LUQ06ku42H = jay.ReadUint32(b[45:49])
	m.N0i6Okd130ck5cBYxtEW121JNOS15SgLr2HRcLPLWjO1A8x31x2il56BfK7AvnQCtGQeo7p4pLj = jay.ReadUint64(b[49:57])
	m.RHhV0W185xrV162y0sOfCdood46WJ6GlR7rUa4kQwt017P5q168l43aSF5UP = jay.ReadUint32(b[57:61])
	m.I5N7120u6b5t6ICoqLBYSW3mv3dWY36x3T8CDjSo7frY4uvPylgt632YTx3sg80O25eJ32XV2 = jay.ReadInt16(b[61:63])
	m.SEp0kW8oostEGaqO5nBG73RuM06aB3wnI7lJu5M2Ir2NaEP4aqrwS = jay.ReadFloat32(b[63:67])
	m.Ma1e5W6I6NS2820Yqh0uyIE7S28lpbKCyU17JjRnN3ess67X4VuT3KvOsntaTrHj8YImG8OgXmj0I6T = jay.ReadInt32(b[67:71])
	m.Dt7wD5Tl8KnmwL574PKg3O41cufsDLa6feTYh6k6GdDg6VAQkAmA82p2Vy836xQkuGKs3S7aF7mSlipI0G1q76iQosEpPee84BdJ = jay.ReadInt32(b[71:75])
	if l0 != 0 {
		m.Kd2CfE274tOMYecW72j28D51oIg183e5a8dmSYKlP0OE7uyKr48B = b[75:]
	}
	return nil
}

func (h HUEnJpdeWBcCf7465T267y4A4Inn0l2CMNAkbC) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14 := len(h.J6F7V6), len(h.Oy0MPln83S3lVB53TLKqXr4l4PsYN7Ej15qGQqd537ipGrJT3p34545mWS), len(h.K1qm1iY7mqd30O721bmawsKWI7FPA0J17cYa0f1X627Ly585han2P), len(h.FeJ42rl3jI2DU8NXOTv4qe7e7aT2Y8o22oPoi3cbfyO8qK8TD73), len(h.U07ppaq2x0c74vB66b1), len(h.Wa5K2552bSnB6123K46C8jpp22wIl73EOT03wMO2m0eP7513XFoVuNDjxLrcf471A2Id50Y07I1H43Di6eo8oC03), len(h.C4EvAraDW88Ae541f5KqR5l762C4dA7OVHWCy7h6w2KXWfqllip), len(h.Ju7Ag14p01uTrByUMK6Dj2tp6if13r0qLJEsIKKXR11Ih1Le61TSlMNW8JAT1FEKM0A1wTpojsWDY4vO24T), len(h.P2OC82hiO70N3I7BEW0ek5VyB142Pq7Psu4eI70xF434tf), len(h.BMT7QYrph2yT2ipQ0vl73y3rq4c7C2dUkr), len(h.Fq2t0), len(h.UB6BQ08jJ2aECLM4cqdB35Sw27aQ3H7u6n0G741L03qb3HFT55Nm1Q6JyN70CJ4W), len(h.FmE0GYdUFc45YI3pOVQ4o2F4C1Oh6S8jYWfxJ7b1qG4vs0KOuiU5), len(h.BSnQ177Y46It5hRI0Ls77VPtPftQ3R12tmH2), len(h.G3dMX37XYLwhrGy6kVs8r54uKl52766R8waSS83C3sEyF6n4UqCR7Dx0p)
	b = make([]byte, 356+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9), byte(l10), byte(l11), byte(l12), byte(l13), byte(l14)
	b[15] = jay.Bool2(h.TvEVgWmkKd77vK4jci, h.EepjkP87kiwkf208w0oyVm58eBxV03PGP7cR8Qkql4s8fx5MAsAnc2EX576R1IR0eEoY40UX0kktMr0yoOhWJt2uMEP)
	b[16] = h.W5Poi
	b[17] = h.X8thJMy
	b[18] = byte(h.I0gftd3vV60cUpA15qMk7BbBqr5ovc58aRobvUg54r4VxS31x5sGgDxOTW8r7BS17nWXpeaR6tr21pgh)
	b[19] = byte(h.HPX7jtH0P451o85jcRxVhcOsg6Pr)
	b[20] = h.LaYm65Hej78FT7wUWrb42WOq2gH4Klc01e1WQqRv1Bc1LkHugeKwn8erXnEV7tvOOIOb72vfvDD25EA1dRovpu02K57R7VQ6
	b[21] = byte(h.OXr0vL3T0w0Ddt47J4hbkpwb81cI60L23nwyaTHy74iM41F68MYnk8EIpQxhJ07VpwAoyV00nrra0kUDVo)
	b[22] = h.E66R73Hee5cJ3b4in2fO
	b[23] = byte(h.RTnDjpF5rOHX34DVH0Kx3L4gqwi3x00ia6LGl41M2rsD7YiwLwOH2R2FUspMs6CuB82sdg)
	b[24] = h.K6HxP04pvg3j8vDH8aDWT76rPisiAftWkJ54U11XNmVE5fXxUni4bHXBNg4NLlr57PdEV51J5H08b1n6ij37it
	b[25] = h.SRjyu46667ria45qeQm62ClW85vMgpD2UP43C544y675hD386Mocgow4l8jsHu2M771Y4R3V
	b[26] = h.ET840iKNawa1iy6SWxNT701aHrKtqsVG7mLnlEf76I6Q70q
	b[27] = h.PV23jGwBinbxHPkO6W5TW65AEpF83nl1lcJ66713YBBhpWifyxG6PWyJa7qH1dQP7PGYFu82k860D7EVu
	b[28] = byte(h.E6gJB12oBTVM1aTmFScW3eW01gH3sJ2QOeoWSL6Yp)
	b[29] = h.U3F5Dx26kc7c6UyLf
	jay.WriteFloat32(b[30:34], h.G126mt0ekf63prSv4WK7x4lpS3wcTD22xt2AsV0E0c6h5Ehs2t63G3wgnLANj2W)
	jay.WriteUint64(b[34:42], h.GWSY14a557y23WjBRO6W2av6nsB11Tf50F0BjJADFDn1GjyCqAoL)
	jay.WriteFloat64(b[42:50], h.SY)
	jay.WriteUint16(b[50:52], h.PdM25DDXmn)
	jay.WriteUint32(b[52:56], h.PG2M7Op8KbwXxKi82L6AQ4u3e57DR4HVNG47jVH85bOrD80ry5)
	jay.WriteInt16(b[56:58], h.VBQIhLG4TrDXNJH0ES0V)
	jay.WriteInt32(b[58:62], h.K5rb6RG6P547XV8e31O7Ka1P276d5xWScWr4DG3gAs08s)
	jay.WriteUint16(b[62:64], h.RdaIa6ATpho1YK46M80i0UYVIX76U252AG3HP35x6843Y8dHdWkb3q7mEY2u)
	jay.WriteInt16(b[64:66], h.NK84h07ce5wc367Lc2h8d6Xd1w4nCfwD5om85itKj5ce5AV2IW3YQxWfA0jmklnH7x811L25wvpuq61J)
	jay.WriteUint16(b[66:68], h.YUDpsW3A5154c3nh04Oh215bGgbI02xPyGJWBtb7448M50pau8Sr7T1erv5m8wqxD)
	jay.WriteInt64(b[68:76], h.Gob54P7Is0iaFplWW6g0YW1Fpo1cBfXS08kreXK1v)
	jay.WriteInt16(b[76:78], h.DhtO30miJ1CigNaB50PbhY1H0IkW3LyBTw7C2PgIK4mJhJ83L0)
	jay.WriteUint16(b[78:80], h.ITRHJ1J6rBi41ib22HX6R475wU61Ywo77MeVseKE6P6Y2a5co8of8efqdyEGp36HsW177nup6So5y4)
	jay.WriteIntArch64(b[80:88], h.PCYS4t3t7Lnw2NUjQ1DN2j064q56AL3kpiy1A1d2s021mba64jQ24n0cB65al3)
	jay.WriteFloat64(b[88:96], h.ISTc2Af1eov7i7w7234iD2riYPgR8M7uU5Dwm67jMY87Ws503pm11LCCHOjB5xHNCg1xQuOb2)
	jay.WriteFloat64(b[96:104], h.Aa6rIWR10cRqYL82ptVrKiSg465M6xGd05Mgq5xO5f1lqq00W722PM48gJNBa8F16xwFr22rb4YsqTF7sne)
	jay.WriteInt64(b[104:112], h.AY6uYkOfhQa152y4g3tSLcPPPcJNUtToJ620h75n6g3CKd04213Poja0Sq4MG3d58y2K4WU0E15rd8AT)
	jay.WriteInt64(b[112:120], h.WYw73A2hJ5lBr866STr3537548NmFSji7)
	jay.WriteInt16(b[120:122], h.BdXBSF0B83P81hM2178EvJvd08dC7R55RDvf27UdJWO)
	jay.WriteFloat32(b[122:126], h.XDQjt8Ybgr20ph0cox57C23vtc2nBDcMe0E5fEx25kxpCS15ulFw4xIYkOe4qDi4V3Ct3QGBLrwlFknnC)
	jay.WriteUint16(b[126:128], h.NVXiKhqQts3Ligocr4nDW)
	jay.WriteTime(b[128:136], h.F3PQ8gIcSB58T84ky682inWR58fBxs54L1whWuE5AS65Ao4s1t5Hl657XwTq1BoN)
	jay.WriteIntArch64(b[136:144], h.YQb2PAA5uDdutQu7yrLj3ASTL3M7pEQcscmMGS2Doy6l2jOafs1t1X4e82MSU)
	jay.WriteFloat32(b[144:148], h.T53226NG4617UO0C615rbop44j83MIENQEs62FiD4p4xEi5U1K4m8c642W47u2U701X2QV2XruOOUSI)
	jay.WriteUintArch64(b[148:156], h.KgxUaTK66N6kwj7Y4q51p807gUuIU8dlmRxeb3pbm1811xtUVf)
	jay.WriteFloat32(b[156:160], h.V60B261UedL0686e1XmYG8h)
	jay.WriteTime(b[160:168], h.UaLA18b8hT6NN7Q67Iwj38KjhdRCSHERfL8l7sVgN3dcmhRtu68K6M66Y4Gs77rt)
	jay.WriteInt32(b[168:172], h.Vp1kxF3g1s4e6W2)
	jay.WriteUint16(b[172:174], h.Ke7vfch7)
	jay.WriteUint16(b[174:176], h.NeG7sAlaNC3w0DCUUwl0)
	jay.WriteUint32(b[176:180], h.Yd2sqKoo)
	jay.WriteInt32(b[180:184], h.N7RUXC3hq01nnXwYxB41W0FjsfNyF1LviN)
	jay.WriteUintArch64(b[184:192], h.SwF5F37vHVb1BXiQOEdP3a1e)
	jay.WriteInt16(b[192:194], h.CWG06hS)
	jay.WriteInt32(b[194:198], h.U4DUa3V8W4KwARaj6F1RXwBP5KWexdgK37LK)
	jay.WriteUint64(b[198:206], h.Imo4oy0qRIx1nl4adgS)
	jay.WriteFloat32(b[206:210], h.P7Yh80tP7q3OWpVDSB60d6sP57V5O2DR7pcilaxp)
	jay.WriteUint16(b[210:212], h.V2Ch07hrD8XBsRvlRBWyye7E114871Ia010sNK507mCfXer1a0rf5KdEM4272XLVY4KvurWbOa3v4WCS8na4w)
	jay.WriteUintArch64(b[212:220], h.GXw212r1EhWvUl82IrJu15ruYn8gnJ276Vv43w577e006aWObCs5na1C7Xd5DN0uj2WnIA5FtxY256Pf2C0uAe82WTW8)
	jay.WriteIntArch64(b[220:228], h.PM7QNFhfXO54UFH)
	jay.WriteUint16(b[228:230], h.FJwFu36jVAXsS4EhQquqv4CfdPk6S753Fx0ooV6jy4Ir2HKHKKT4Kwj5pns37O786T0)
	jay.WriteInt32(b[230:234], h.O6aX4Qjed3)
	jay.WriteIntArch64(b[234:242], h.A2CCQila4eHdQt38g)
	jay.WriteTime(b[242:250], h.IXV6p7JEwYYxR16GP55X27NQjEa486Fe3r48t6U08U6bmx61jgHCY2IJQU518pvlB4x6BYMkVcWDkOYmya5W587dP0TE3tw)
	jay.WriteInt32(b[250:254], h.W2EO3802d72Q0EIiiaCnOeq6Ij16I3R58KTwh)
	jay.WriteInt32(b[254:258], h.FO2b6o8V6ub10hN1q1DtbQwiYwJrHqThTDniM5ym6AR1Xat877l6RyJ)
	jay.WriteUint16(b[258:260], h.Yhkke0s356R5U61Hn2o0Hq2g80qQllO44bQsD156Ob5oBgY4LmEXchD0On1va5ItVq41UMX5El5M63lR4kJR30x0p)
	jay.WriteUint64(b[260:268], h.S5660)
	jay.WriteUint32(b[268:272], h.EcnM3nwbhA8G61kCLW)
	jay.WriteInt64(b[272:280], h.H8CTn1lYwc8YH5qj5Tj8L1s)
	jay.WriteUint64(b[280:288], h.DF2FjhNx)
	jay.WriteInt64(b[288:296], h.WKKf584CH0LxFWtePGT2bGo20Whru7pTSK36p60272nME5j5v5)
	jay.WriteUint32(b[296:300], h.RMFGbE5VfCIGU3D)
	jay.WriteFloat32(b[300:304], h.Di43v27R16Q5ls4NGaGt4v2xV3pY0q3WAeTJ)
	jay.WriteUint32(b[304:308], h.TnHXimlqg8m1LwB24UwbbMCNC5D2Yv520Wbr35CRSr7)
	jay.WriteIntArch64(b[308:316], h.YJIWtKj4OB6SEPd44)
	jay.WriteUint32(b[316:320], h.Fc8R313AU32dncvO3X2UHYYdfWS452yUPImo4b6dn5ka2mI0qGh252JG7D57VwruefLYuwl41GeRwI8Oxt71jgXckL2og0nny5)
	jay.WriteUintArch64(b[320:328], h.HA4pILnTlUG0E0o568agIVNLLoJqpAe0)
	jay.WriteUint16(b[328:330], h.FU5NvAjBf27ry3bmE1Qd84doE4sI652Ix8g5kgAj7evQ1FJkl8uQNSKYQmN3Pbtl67EU8u82Vs7URBR8Yy8)
	jay.WriteFloat32(b[330:334], h.SGS2G23djBG8t4m2b0h10dhuFp8257Q6ptfNsifohyjN2vc6h4B)
	jay.WriteUint16(b[334:336], h.D5ga03e2P8sk70j2X0qyq3SiH417GQ2Cx5p)
	jay.WriteFloat64(b[336:344], h.NP1CJbHo01E5vw6xn51phlNNVn1MHW33aDlkAgaH6q738v)
	jay.WriteUint32(b[344:348], h.MoJ5VH76Gqq7X05A4w7pjGE2LeJ80x0guGKNdWi4hv)
	jay.WriteTime(b[348:356], h.BR3)
	at, end := 356, 356+l0
	copy(b[at:end], h.J6F7V6)
	at, end = end, end+l1
	if l1 != 0 {
		copy(b[at:end], h.Oy0MPln83S3lVB53TLKqXr4l4PsYN7Ej15qGQqd537ipGrJT3p34545mWS)
	}
	at, end = end, end+l2
	copy(b[at:end], h.K1qm1iY7mqd30O721bmawsKWI7FPA0J17cYa0f1X627Ly585han2P)
	at, end = end, end+l3
	if l3 != 0 {
		copy(b[at:end], h.FeJ42rl3jI2DU8NXOTv4qe7e7aT2Y8o22oPoi3cbfyO8qK8TD73)
	}
	at, end = end, end+l4
	copy(b[at:end], h.U07ppaq2x0c74vB66b1)
	at, end = end, end+l5
	if l5 != 0 {
		copy(b[at:end], h.Wa5K2552bSnB6123K46C8jpp22wIl73EOT03wMO2m0eP7513XFoVuNDjxLrcf471A2Id50Y07I1H43Di6eo8oC03)
	}
	at, end = end, end+l6
	if l6 != 0 {
		copy(b[at:end], h.C4EvAraDW88Ae541f5KqR5l762C4dA7OVHWCy7h6w2KXWfqllip)
	}
	at, end = end, end+l7
	copy(b[at:end], h.Ju7Ag14p01uTrByUMK6Dj2tp6if13r0qLJEsIKKXR11Ih1Le61TSlMNW8JAT1FEKM0A1wTpojsWDY4vO24T)
	at, end = end, end+l8
	copy(b[at:end], h.P2OC82hiO70N3I7BEW0ek5VyB142Pq7Psu4eI70xF434tf)
	at, end = end, end+l9
	if l9 != 0 {
		copy(b[at:end], h.BMT7QYrph2yT2ipQ0vl73y3rq4c7C2dUkr)
	}
	at, end = end, end+l10
	if l10 != 0 {
		copy(b[at:end], h.Fq2t0)
	}
	at, end = end, end+l11
	copy(b[at:end], h.UB6BQ08jJ2aECLM4cqdB35Sw27aQ3H7u6n0G741L03qb3HFT55Nm1Q6JyN70CJ4W)
	at, end = end, end+l12
	if l12 != 0 {
		copy(b[at:end], h.FmE0GYdUFc45YI3pOVQ4o2F4C1Oh6S8jYWfxJ7b1qG4vs0KOuiU5)
	}
	at, end = end, end+l13
	copy(b[at:end], h.BSnQ177Y46It5hRI0Ls77VPtPftQ3R12tmH2)
	copy(b[end:], h.G3dMX37XYLwhrGy6kVs8r54uKl52766R8waSS83C3sEyF6n4UqCR7Dx0p)
	return
}

func (h *HUEnJpdeWBcCf7465T267y4A4Inn0l2CMNAkbC) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 356 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9]), int(b[10]), int(b[11]), int(b[12]), int(b[13]), int(b[14])
	if l < 356+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9+l10+l11+l12+l13+l14 {
		return jay.ErrUnexpectedEOB
	}
	h.TvEVgWmkKd77vK4jci, h.EepjkP87kiwkf208w0oyVm58eBxV03PGP7cR8Qkql4s8fx5MAsAnc2EX576R1IR0eEoY40UX0kktMr0yoOhWJt2uMEP = jay.ReadBool2(b[15])
	h.W5Poi = b[16]
	h.X8thJMy = b[17]
	h.I0gftd3vV60cUpA15qMk7BbBqr5ovc58aRobvUg54r4VxS31x5sGgDxOTW8r7BS17nWXpeaR6tr21pgh = int8(b[18])
	h.HPX7jtH0P451o85jcRxVhcOsg6Pr = int8(b[19])
	h.LaYm65Hej78FT7wUWrb42WOq2gH4Klc01e1WQqRv1Bc1LkHugeKwn8erXnEV7tvOOIOb72vfvDD25EA1dRovpu02K57R7VQ6 = b[20]
	h.OXr0vL3T0w0Ddt47J4hbkpwb81cI60L23nwyaTHy74iM41F68MYnk8EIpQxhJ07VpwAoyV00nrra0kUDVo = int8(b[21])
	h.E66R73Hee5cJ3b4in2fO = b[22]
	h.RTnDjpF5rOHX34DVH0Kx3L4gqwi3x00ia6LGl41M2rsD7YiwLwOH2R2FUspMs6CuB82sdg = int8(b[23])
	h.K6HxP04pvg3j8vDH8aDWT76rPisiAftWkJ54U11XNmVE5fXxUni4bHXBNg4NLlr57PdEV51J5H08b1n6ij37it = b[24]
	h.SRjyu46667ria45qeQm62ClW85vMgpD2UP43C544y675hD386Mocgow4l8jsHu2M771Y4R3V = b[25]
	h.ET840iKNawa1iy6SWxNT701aHrKtqsVG7mLnlEf76I6Q70q = b[26]
	h.PV23jGwBinbxHPkO6W5TW65AEpF83nl1lcJ66713YBBhpWifyxG6PWyJa7qH1dQP7PGYFu82k860D7EVu = b[27]
	h.E6gJB12oBTVM1aTmFScW3eW01gH3sJ2QOeoWSL6Yp = int8(b[28])
	h.U3F5Dx26kc7c6UyLf = b[29]
	h.G126mt0ekf63prSv4WK7x4lpS3wcTD22xt2AsV0E0c6h5Ehs2t63G3wgnLANj2W = jay.ReadFloat32(b[30:34])
	h.GWSY14a557y23WjBRO6W2av6nsB11Tf50F0BjJADFDn1GjyCqAoL = jay.ReadUint64(b[34:42])
	h.SY = jay.ReadFloat64(b[42:50])
	h.PdM25DDXmn = jay.ReadUint16(b[50:52])
	h.PG2M7Op8KbwXxKi82L6AQ4u3e57DR4HVNG47jVH85bOrD80ry5 = jay.ReadUint32(b[52:56])
	h.VBQIhLG4TrDXNJH0ES0V = jay.ReadInt16(b[56:58])
	h.K5rb6RG6P547XV8e31O7Ka1P276d5xWScWr4DG3gAs08s = jay.ReadInt32(b[58:62])
	h.RdaIa6ATpho1YK46M80i0UYVIX76U252AG3HP35x6843Y8dHdWkb3q7mEY2u = jay.ReadUint16(b[62:64])
	h.NK84h07ce5wc367Lc2h8d6Xd1w4nCfwD5om85itKj5ce5AV2IW3YQxWfA0jmklnH7x811L25wvpuq61J = jay.ReadInt16(b[64:66])
	h.YUDpsW3A5154c3nh04Oh215bGgbI02xPyGJWBtb7448M50pau8Sr7T1erv5m8wqxD = jay.ReadUint16(b[66:68])
	h.Gob54P7Is0iaFplWW6g0YW1Fpo1cBfXS08kreXK1v = jay.ReadInt64(b[68:76])
	h.DhtO30miJ1CigNaB50PbhY1H0IkW3LyBTw7C2PgIK4mJhJ83L0 = jay.ReadInt16(b[76:78])
	h.ITRHJ1J6rBi41ib22HX6R475wU61Ywo77MeVseKE6P6Y2a5co8of8efqdyEGp36HsW177nup6So5y4 = jay.ReadUint16(b[78:80])
	h.PCYS4t3t7Lnw2NUjQ1DN2j064q56AL3kpiy1A1d2s021mba64jQ24n0cB65al3 = jay.ReadIntArch64(b[80:88])
	h.ISTc2Af1eov7i7w7234iD2riYPgR8M7uU5Dwm67jMY87Ws503pm11LCCHOjB5xHNCg1xQuOb2 = jay.ReadFloat64(b[88:96])
	h.Aa6rIWR10cRqYL82ptVrKiSg465M6xGd05Mgq5xO5f1lqq00W722PM48gJNBa8F16xwFr22rb4YsqTF7sne = jay.ReadFloat64(b[96:104])
	h.AY6uYkOfhQa152y4g3tSLcPPPcJNUtToJ620h75n6g3CKd04213Poja0Sq4MG3d58y2K4WU0E15rd8AT = jay.ReadInt64(b[104:112])
	h.WYw73A2hJ5lBr866STr3537548NmFSji7 = jay.ReadInt64(b[112:120])
	h.BdXBSF0B83P81hM2178EvJvd08dC7R55RDvf27UdJWO = jay.ReadInt16(b[120:122])
	h.XDQjt8Ybgr20ph0cox57C23vtc2nBDcMe0E5fEx25kxpCS15ulFw4xIYkOe4qDi4V3Ct3QGBLrwlFknnC = jay.ReadFloat32(b[122:126])
	h.NVXiKhqQts3Ligocr4nDW = jay.ReadUint16(b[126:128])
	h.F3PQ8gIcSB58T84ky682inWR58fBxs54L1whWuE5AS65Ao4s1t5Hl657XwTq1BoN = jay.ReadTime(b[128:136])
	h.YQb2PAA5uDdutQu7yrLj3ASTL3M7pEQcscmMGS2Doy6l2jOafs1t1X4e82MSU = jay.ReadIntArch64(b[136:144])
	h.T53226NG4617UO0C615rbop44j83MIENQEs62FiD4p4xEi5U1K4m8c642W47u2U701X2QV2XruOOUSI = jay.ReadFloat32(b[144:148])
	h.KgxUaTK66N6kwj7Y4q51p807gUuIU8dlmRxeb3pbm1811xtUVf = jay.ReadUintArch64(b[148:156])
	h.V60B261UedL0686e1XmYG8h = jay.ReadFloat32(b[156:160])
	h.UaLA18b8hT6NN7Q67Iwj38KjhdRCSHERfL8l7sVgN3dcmhRtu68K6M66Y4Gs77rt = jay.ReadTime(b[160:168])
	h.Vp1kxF3g1s4e6W2 = jay.ReadInt32(b[168:172])
	h.Ke7vfch7 = jay.ReadUint16(b[172:174])
	h.NeG7sAlaNC3w0DCUUwl0 = jay.ReadUint16(b[174:176])
	h.Yd2sqKoo = jay.ReadUint32(b[176:180])
	h.N7RUXC3hq01nnXwYxB41W0FjsfNyF1LviN = jay.ReadInt32(b[180:184])
	h.SwF5F37vHVb1BXiQOEdP3a1e = jay.ReadUintArch64(b[184:192])
	h.CWG06hS = jay.ReadInt16(b[192:194])
	h.U4DUa3V8W4KwARaj6F1RXwBP5KWexdgK37LK = jay.ReadInt32(b[194:198])
	h.Imo4oy0qRIx1nl4adgS = jay.ReadUint64(b[198:206])
	h.P7Yh80tP7q3OWpVDSB60d6sP57V5O2DR7pcilaxp = jay.ReadFloat32(b[206:210])
	h.V2Ch07hrD8XBsRvlRBWyye7E114871Ia010sNK507mCfXer1a0rf5KdEM4272XLVY4KvurWbOa3v4WCS8na4w = jay.ReadUint16(b[210:212])
	h.GXw212r1EhWvUl82IrJu15ruYn8gnJ276Vv43w577e006aWObCs5na1C7Xd5DN0uj2WnIA5FtxY256Pf2C0uAe82WTW8 = jay.ReadUintArch64(b[212:220])
	h.PM7QNFhfXO54UFH = jay.ReadIntArch64(b[220:228])
	h.FJwFu36jVAXsS4EhQquqv4CfdPk6S753Fx0ooV6jy4Ir2HKHKKT4Kwj5pns37O786T0 = jay.ReadUint16(b[228:230])
	h.O6aX4Qjed3 = jay.ReadInt32(b[230:234])
	h.A2CCQila4eHdQt38g = jay.ReadIntArch64(b[234:242])
	h.IXV6p7JEwYYxR16GP55X27NQjEa486Fe3r48t6U08U6bmx61jgHCY2IJQU518pvlB4x6BYMkVcWDkOYmya5W587dP0TE3tw = jay.ReadTime(b[242:250])
	h.W2EO3802d72Q0EIiiaCnOeq6Ij16I3R58KTwh = jay.ReadInt32(b[250:254])
	h.FO2b6o8V6ub10hN1q1DtbQwiYwJrHqThTDniM5ym6AR1Xat877l6RyJ = jay.ReadInt32(b[254:258])
	h.Yhkke0s356R5U61Hn2o0Hq2g80qQllO44bQsD156Ob5oBgY4LmEXchD0On1va5ItVq41UMX5El5M63lR4kJR30x0p = jay.ReadUint16(b[258:260])
	h.S5660 = jay.ReadUint64(b[260:268])
	h.EcnM3nwbhA8G61kCLW = jay.ReadUint32(b[268:272])
	h.H8CTn1lYwc8YH5qj5Tj8L1s = jay.ReadInt64(b[272:280])
	h.DF2FjhNx = jay.ReadUint64(b[280:288])
	h.WKKf584CH0LxFWtePGT2bGo20Whru7pTSK36p60272nME5j5v5 = jay.ReadInt64(b[288:296])
	h.RMFGbE5VfCIGU3D = jay.ReadUint32(b[296:300])
	h.Di43v27R16Q5ls4NGaGt4v2xV3pY0q3WAeTJ = jay.ReadFloat32(b[300:304])
	h.TnHXimlqg8m1LwB24UwbbMCNC5D2Yv520Wbr35CRSr7 = jay.ReadUint32(b[304:308])
	h.YJIWtKj4OB6SEPd44 = jay.ReadIntArch64(b[308:316])
	h.Fc8R313AU32dncvO3X2UHYYdfWS452yUPImo4b6dn5ka2mI0qGh252JG7D57VwruefLYuwl41GeRwI8Oxt71jgXckL2og0nny5 = jay.ReadUint32(b[316:320])
	h.HA4pILnTlUG0E0o568agIVNLLoJqpAe0 = jay.ReadUintArch64(b[320:328])
	h.FU5NvAjBf27ry3bmE1Qd84doE4sI652Ix8g5kgAj7evQ1FJkl8uQNSKYQmN3Pbtl67EU8u82Vs7URBR8Yy8 = jay.ReadUint16(b[328:330])
	h.SGS2G23djBG8t4m2b0h10dhuFp8257Q6ptfNsifohyjN2vc6h4B = jay.ReadFloat32(b[330:334])
	h.D5ga03e2P8sk70j2X0qyq3SiH417GQ2Cx5p = jay.ReadUint16(b[334:336])
	h.NP1CJbHo01E5vw6xn51phlNNVn1MHW33aDlkAgaH6q738v = jay.ReadFloat64(b[336:344])
	h.MoJ5VH76Gqq7X05A4w7pjGE2LeJ80x0guGKNdWi4hv = jay.ReadUint32(b[344:348])
	h.BR3 = jay.ReadTime(b[348:356])
	at, end := 356, 356+l0
	h.J6F7V6 = string(b[at:end])
	at, end = end, end+l1
	if l1 != 0 {
		h.Oy0MPln83S3lVB53TLKqXr4l4PsYN7Ej15qGQqd537ipGrJT3p34545mWS = b[at:end]
	}
	at, end = end, end+l2
	h.K1qm1iY7mqd30O721bmawsKWI7FPA0J17cYa0f1X627Ly585han2P = string(b[at:end])
	at, end = end, end+l3
	if l3 != 0 {
		h.FeJ42rl3jI2DU8NXOTv4qe7e7aT2Y8o22oPoi3cbfyO8qK8TD73 = b[at:end]
	}
	at, end = end, end+l4
	h.U07ppaq2x0c74vB66b1 = string(b[at:end])
	at, end = end, end+l5
	if l5 != 0 {
		h.Wa5K2552bSnB6123K46C8jpp22wIl73EOT03wMO2m0eP7513XFoVuNDjxLrcf471A2Id50Y07I1H43Di6eo8oC03 = b[at:end]
	}
	at, end = end, end+l6
	if l6 != 0 {
		h.C4EvAraDW88Ae541f5KqR5l762C4dA7OVHWCy7h6w2KXWfqllip = b[at:end]
	}
	at, end = end, end+l7
	h.Ju7Ag14p01uTrByUMK6Dj2tp6if13r0qLJEsIKKXR11Ih1Le61TSlMNW8JAT1FEKM0A1wTpojsWDY4vO24T = string(b[at:end])
	at, end = end, end+l8
	h.P2OC82hiO70N3I7BEW0ek5VyB142Pq7Psu4eI70xF434tf = string(b[at:end])
	at, end = end, end+l9
	if l9 != 0 {
		h.BMT7QYrph2yT2ipQ0vl73y3rq4c7C2dUkr = b[at:end]
	}
	at, end = end, end+l10
	if l10 != 0 {
		h.Fq2t0 = b[at:end]
	}
	at, end = end, end+l11
	h.UB6BQ08jJ2aECLM4cqdB35Sw27aQ3H7u6n0G741L03qb3HFT55Nm1Q6JyN70CJ4W = string(b[at:end])
	at, end = end, end+l12
	if l12 != 0 {
		h.FmE0GYdUFc45YI3pOVQ4o2F4C1Oh6S8jYWfxJ7b1qG4vs0KOuiU5 = b[at:end]
	}
	at, end = end, end+l13
	h.BSnQ177Y46It5hRI0Ls77VPtPftQ3R12tmH2 = string(b[at:end])
	h.G3dMX37XYLwhrGy6kVs8r54uKl52766R8waSS83C3sEyF6n4UqCR7Dx0p = string(b[end:])
	return nil
}

func (a AMly01oki2JC2n77UJT22AVlo2VAiUh06W43tGk43P7th6t6MSj3ejR5PrL103BBIN1ji) MarshalJ() (b []byte) {
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9 := len(a.Kc3xL2bowR7TwOLpKkDMP44WlLgB5Rh5Ro82kAob3knH34), len(a.IW0B1ASu1777OmeqCcPQ45lC5YX2iqq), len(a.U82Uao8X38P7YLkt4d8qmyl8dNBtG5HxD0DWt161SeQWT6mE), len(a.B46TTl2OIN0mgMdUcD8p21rsFa04Cm4sv), len(a.C81nWkpqm630B8F0hS107UXT5T8), len(a.E161pw2FDkee46cYa85y2Y4X8), len(a.UvSK), len(a.F6w1voK3gWJ7wphds0Li8dJQ52W503DLR2lfRup0XxJ0Jf5VBkLN4F56Q), len(a.C56q26r), len(a.NEFmR3GYcsX67Uai11Ybyo4KyPhTa25E17EUEX36agNChN2j2k5064G830g08ta5Oje4rskK0xToMvYXWQYjCP21wFQF82xEbRw)
	b = make([]byte, 518+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9)
	b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9] = byte(l0), byte(l1), byte(l2), byte(l3), byte(l4), byte(l5), byte(l6), byte(l7), byte(l8), byte(l9)
	b[10] = jay.Bool8(a.K3EJ1UrKYkbWAauAtqwSN8AuP1rPdIEf2WJ886V006o, a.V5JvbOv0107N8qM2m5EPuM3rTIEPGSWFpkGLt4tvRWAk66181NKn7u3C1jak6A4YRc0S6hGQ8l7, a.UNW8I, a.Lv6uxvmRy6k50UkufS0i3LAC622511QkNF3pDmUCGpH6P6teD3oMJS0HkL5OLBVmjelU4O56f45ypWqy6UTLXD3x7GY8Q8MPRx, a.XDUv6BF2hW1u588d76C6qS0F64Q5c, a.F2iof7ha2MhsYvU3MQhB6ivy6X, a.P2J035F8Nk1, a.PX06Ty52WFLl3HwggY387niD34HBEp4QTvD37SXFBog7vh02RUMc4OI1OKJ641Ib3r67P)
	b[11] = jay.Bool4(a.A6SPqF3gTP3b7kAHKcaQCjV1tT7pCTJOlP7Jtd5YWGP78Diw7N5F26kNPS, a.U2ii03A226243h1p18Wg7oUPc4sI, a.H82PSTYkUKHQ, a.X56gJ8sLWa2wbeWqSI7qK17563i6yh3O6fLjiQMh)
	b[12] = a.RqwPs577d5lTDAQO171A0NwWB1L4cev
	b[13] = a.YCiS0s6Jgw2bWcHF685JKDC6Pi8N45aliRgAgcdtePj23p4w3OeAXvO78W6fb
	b[14] = a.U1CY87y2437vhKnBn6I3w527L05
	b[15] = a.Ue0J8g2JhAeC0I
	b[16] = a.YBEW261AWb7VYuPT31nJ30LbCPg7y8YdXtj1sUN5q8rfxsNn1s024e6E17cfN21vng81mh1Y5jrD1QgHgRs7uTSw5h
	b[17] = a.T05AXG1G6h42vGYicYHni7hSo
	b[18] = a.NbF3sI6ScBuembX1mg3Tm0iGh2mC26R1M1FabP3rOc31M3Nmgpf7
	b[19] = a.A5lQ
	b[20] = a.I5oWnf6tyS2mk4v3al1inMxpN7Wj08x7M15usu3xt63bM0epMffOCixf2Ogi3R351gO0
	b[21] = a.Uq23yRI4W6
	b[22] = byte(a.E5wqcATKLnLHQ60rdrWDJ1yQ4oI16rxrN68FVMrN5RV1bjaLL6p7kNi6C4xLuyTPxb0cr7d7I287)
	b[23] = a.W2xc78gY3V3xUESRUk44pxX16Ti002wW308Gk24HfgCckt70P3wmjmVwheea4w5b42Ju2m7S2AvO8thp507341yC7UHaIT0NB
	b[24] = a.EYW6cXT3PdjjbV5k52YMo7e7yY5FMDPuoY4GuUF11
	b[25] = a.X6H47D6k02LwQQ08
	b[26] = a.Gn01Up7J08XvEv6G5ure51GV0u8c7DGj0n7phy5U0clGd4dC2Cd3P5FNq1
	b[27] = a.EFUQx0FBGN345SBPrwf42L82MGov7DkUBQk
	b[28] = a.F2Gfck8ev41X08qQE3wVKJ0weRiYTjgB5eYD0Ho4sx7jbMfs1Ftb42c52lYqtN22e4k6h617Ai
	b[29] = byte(a.FE0118sftca22Uv)
	b[30] = byte(a.We4o7Xt5TTm7Q0Xxb8XqTc1xj5LQ1daGEaqlQvJ6dF7d6TT42xIpDh)
	b[31] = byte(a.CHaMB7Cw311V418f2W24J0kVYkVe548wfhv08Bk0275QnXbI)
	b[32] = byte(a.PuNeJcTcveW3p5)
	b[33] = a.JT0Mq1CSXk2rO4t1PMDW0YOiB14ih1pm6FgdvCbG3332i2Kl5c
	b[34] = a.O58y041UjLx2ew73u70WJcqFKrC654XTLsmb4EcM0aitN05VUyjp1kW15i0736h0pjco10OpgY
	b[35] = a.HoB7nFxQHUY652NfN3D7g826sU8PN4K6xev42oO78OxmgFb4D
	b[36] = a.N22e881N0OcAnCFP7gD3o1lu66pnU07f8U8fhGjAE5fsm617Wknd20aBJC
	b[37] = a.BUL7SnjImLQ
	jay.WriteFloat64(b[38:46], a.S3KUyIH2uGr1YN27tQLcv2eAkEG1Dt4Y8hs2Ia)
	jay.WriteInt32(b[46:50], a.F3ft3g2uB7YU526LV0c0Oeq0Gf4YRaUB)
	jay.WriteIntArch64(b[50:58], a.C33lxaDuW2A6ybtWKj2TF5y0iDadC802S7RU5QD20WJ28iUW3P77s60eEb81Xi)
	jay.WriteUintArch64(b[58:66], a.DSuEeV4220rRXcqTr5w3bf48)
	jay.WriteInt16(b[66:68], a.Hn1Qexo2s4C4Td5e7XJFxpi2AApQqe5mcSBaYOlrs3L5l8MEB8418EwUB3HSn)
	jay.WriteUint64(b[68:76], a.Rk10bi2iS60caL5S5H33LCp7Y1C)
	jay.WriteFloat32(b[76:80], a.N7U00Jq7M4rb)
	jay.WriteUintArch64(b[80:88], a.Mu7L1fA5uQCm6fpEr38j7sL7C6i0Kh144G4mdhPTT77s62c7q3dDY2OKVwkeSM84D6tP6cECnc6BDKCtCb6DdX3N27D)
	jay.WriteInt64(b[88:96], a.UUNCBYqg0t5dAmgj2yv1f82)
	jay.WriteInt64(b[96:104], a.O4rMNxf3aO5IJWc6y2kkp)
	jay.WriteUint32(b[104:108], a.Ru61x3A3uvCu2762uCvK8d0V5rSR67s56Q3gp46xxfp)
	jay.WriteUintArch64(b[108:116], a.SV7844lBSVUnHGIkv15V8LW8s6u4)
	jay.WriteUint32(b[116:120], a.GWk0JT2GFoNPBwHS3WN151E6tcOfe3aNNxH0jxNQm36lVbQ8n8Iam400t4dJurQ)
	jay.WriteFloat32(b[120:124], a.J77kvKtw5KjuKE6iXmk45R8eLXIEdYPKWM4yj34hKN3H8L3)
	jay.WriteInt32(b[124:128], a.UfKf3EwHDcf65g4Fs6aAdRg12lTrCi4efXaQ0M80KO0x17HUOTxGJm14IBf5)
	jay.WriteFloat32(b[128:132], a.N)
	jay.WriteFloat32(b[132:136], a.FBK2Kv7Ig0qcgR8iQi0OY6upi1yBwxv6XisrWCUWTPa05mMI7bh2qg3WBSLN5mr1A)
	jay.WriteTime(b[136:144], a.H5GV5iLAgebIu7g4o2SKCc4myHxL3FeKdQ7JUopgV86fl3n8h6bbhw5KAiA6KgO2Jojxm7)
	jay.WriteUintArch64(b[144:152], a.Bwf7Y3J7ot17wch11036jO53W2XtoJ50QYy11s8wWQkuk2JnOb31wd1WHLH3VNSywJ7J7i2Lim0cGJKRJ6I6l5M)
	jay.WriteUint64(b[152:160], a.VcK0X26NlJuL85au66Ov66Kk2aO225tv0I1cAY3m2WVt087vVMm86MtTCSgj802OV1Fyxy1R2Ed4GhGgt1lgks)
	jay.WriteUint64(b[160:168], a.LVUcb8km4Wvq7d0Mi7ugkkvE2dS13sJL0Vchw24g6jIK5ETr4WrgT1DPb8e7xp)
	jay.WriteInt32(b[168:172], a.E6g5vtTKU5c03cO4EwArxLgqh8pnuRnthQiT6UW6187i35bj6u1K6851sk2q8sN3Q5c8B3GORHGXSXi8MUYT8)
	jay.WriteInt64(b[172:180], a.SM45EUMsP7c0BqSu05OwiHlKUx4wj56222mrA53gP2M5NHB80)
	jay.WriteInt64(b[180:188], a.IGYxbTLvrFlab41veBQj15qTX6uy7S)
	jay.WriteTime(b[188:196], a.OfX04QBY2XQI8npCSaEYGTYtVb1mdP6tlg05AO3mq422RT8jDi2FRqN5FF3Y5cF1OK1y2yW1Y8JK05Hk1CX87xxOL2F2iJT1)
	jay.WriteInt32(b[196:200], a.F20en5)
	jay.WriteIntArch64(b[200:208], a.SmD5u3Dp3u1YymhIc58r13ho80s2q56q1tR335181AYgRLt0TRM5Uxd5UM0Bs4xUA0KB4L28Q0HRs0wJgr1lYE8P6U00ca57Rdp)
	jay.WriteInt16(b[208:210], a.BAh65bIl5I44gOY47v4BrAH0Obql6fjCEd1r7S5xXumU1RWm6MTN8D6oBESvnG4IM1q3GieGLB30fO)
	jay.WriteInt32(b[210:214], a.TAp)
	jay.WriteInt16(b[214:216], a.IT2FPQXXca0Fu4BtXa1GFXV837EPBSI83e7la84TTd4g0e867m7u)
	jay.WriteUint32(b[216:220], a.Vb8BTfmBH262aGW8cBclN2VVWBHE45eEfAghn5kEd6lF61KoMwjHKd8hmiYl8gCWuLt6ExEs7VF680sv4)
	jay.WriteInt32(b[220:224], a.G55T53ie6mm1qR4S8j1k2np8LCc841sW2b7pHI3B64F4ei0kdJae67FRU8Arx6Ra)
	jay.WriteTime(b[224:232], a.XUvg4evc1auQ0rt1XPL8xLVt38qqiKjN0Tn5iy0u411e1h176PW1pIt3gU28jChT7Ub1VN2LJS606Ev3q78KO44wB8)
	jay.WriteFloat64(b[232:240], a.XhvCr720NYe5IxPtWWWW4va)
	jay.WriteInt16(b[240:242], a.D2nGeA50e8B7tNxbiG227RV864Qmt71T62mXGMT75cotRqCugu87swn)
	jay.WriteIntArch64(b[242:250], a.UTg7TawC4QO80)
	jay.WriteUint32(b[250:254], a.HaTJ5wctBlj0TS1aiiDS4w1vJGIMR51v4T47o5kxwQblt8rArOuuKd08X15x5444b6d2647J8f3)
	jay.WriteIntArch64(b[254:262], a.MO5n60vWB312SWHISn2wd4qQoer1y337f55axYs3Rc74h4k63yYxN42XtbV1h6mt208u64)
	jay.WriteUint64(b[262:270], a.Fb173eCxU17I)
	jay.WriteInt32(b[270:274], a.Ta5536bV3TH3nb7tGbBAm418ey4sBBVe2RdT6K2X8nq2eah2C3G55Y8)
	jay.WriteUint16(b[274:276], a.Wl12l4)
	jay.WriteInt32(b[276:280], a.J7FNI4821OH2VMBmjG3qNFy2SSI851nx17Q41RuWW8C2d)
	jay.WriteUintArch64(b[280:288], a.XAoxjdPDO8N28i1Kmwa547xJQS37al1Oy5OIYB37PmMVt6PXUTxvGQTBB38G4XpL4rS07gdhlTPm6mtC0m5JXmt8)
	jay.WriteUint64(b[288:296], a.IHHNryTqdNyOEXQD1P3O6vC12oeE6j2mml8dK882ok21pWNyW328DRbw1xCb5aFjfEwrh2M1WU5H23Ol45Aq0)
	jay.WriteUint32(b[296:300], a.Pe7BR1E2mr7BWA5y18HgeVEIsxKl0PPSjs1RTYEr03x7pBRbM64470Al41V76HMOc4P7runL)
	jay.WriteUint16(b[300:302], a.Wp7a6qr86735t1tTv338Snvr45jdCBJ45FpN0FFQf4tokXJw)
	jay.WriteUint32(b[302:306], a.T0NDiW7asNiR5A655ssSe4box32Roc7NL8H420pYjPS8a23jhIINjo70bI7Sew14TD84F8M2IM6t0IaNoMBx)
	jay.WriteTime(b[306:314], a.Nhjj038NJ04vqJDKgqkJ4wq6vlJAsD27hoPA7P)
	jay.WriteTime(b[314:322], a.KLCcq5F86SI53yi6454X1Q5X0OIDkl1aEjiIB1nkn45P10j0r5qb5y)
	jay.WriteUintArch64(b[322:330], a.Ln7qxIc1xGosRK8M62I5j80IJN7H1oB3KpkmN0LqqDlT87h)
	jay.WriteInt16(b[330:332], a.P0BfqN1q)
	jay.WriteInt16(b[332:334], a.I3SWg4CV77750OdfDI4Kt4An5N83Al66gd6yigS0q16X8w7hC)
	jay.WriteUintArch64(b[334:342], a.X2QRx455Wp2)
	jay.WriteInt16(b[342:344], a.YE348JHYKM4IewHYsW223u6l8qUOerISlv61J67T0khhR0dhXm68l24QTs018Hb863Fe0HRo4o0i1eRLfWQ)
	jay.WriteInt32(b[344:348], a.I4n0klX453ugOp6teq651uW4)
	jay.WriteUintArch64(b[348:356], a.C7gx8vVuco76psH10yhRE6nL45rr1b4fvWpbIN33411t02iP5DP4J3huU7Xl4B8w2t0h7471H5iW2jyxcD36UN58rsgN07N0770a)
	jay.WriteFloat64(b[356:364], a.Y3Ox80LRyRuLCO3P2yJ6I)
	jay.WriteInt32(b[364:368], a.DjE0g7jxOBuhNhf51pXvj5LhU6b6qsP6MX5Nv81EBy)
	jay.WriteUint32(b[368:372], a.Brnni3PeEi2XU10cyr6j0ppdG2a05BdIGlBpM687A1P66c2t)
	jay.WriteUint32(b[372:376], a.URL7gIQ16gfSyqcw51FQaE3wfRgTe5CE2uU0STpV7D)
	jay.WriteUintArch64(b[376:384], a.OW6r70Djqj)
	jay.WriteTime(b[384:392], a.J86wCAlDW41w0cl4FjCU08471hp2Q5Eo2Dw4Iwj8E2ySsy26N5yF30GUw0)
	jay.WriteUintArch64(b[392:400], a.Tn0RerY8Y81KFf1w7o82KukpV68736TLVKJP66s3Y1V54qT86MXtoWNUa2fudidETwHgV)
	jay.WriteUint16(b[400:402], a.EqXn3kdLI15O5GQyr6253kb7VdNv2uC4mwNLfOmR5SdMl5rdtum6vypL3)
	jay.WriteUint32(b[402:406], a.Q7vqKj51Qb84d48JEIvYNU75aWo0qAYSVjXY44j8AC7UD41pl51AR1d264nv2)
	jay.WriteFloat32(b[406:410], a.FmUJmlMOtNqi4uUR0N1K4o72E064hbj8jX5N1sEx6U67l680FymAOtc7StlcwoAdyD2TeJ12arXQg)
	jay.WriteInt32(b[410:414], a.BA0rA3ud8m5KCYi78NeWo7c7NSHQ3PdEMIPky2QQ3v6S8Ur6uqy1OK)
	jay.WriteTime(b[414:422], a.BXBVF4Q4iNdqfgAeaqK64s6t6Bav8ojL6KOwyY1052sL6bT1u04OSE)
	jay.WriteInt16(b[422:424], a.LO82V5X1RHx52i61e51fp6x2bbBgSBo70x34fuW5EtcR5GUlu4TP1B3QD472K8y8QFoa5YGg7425VTCka7A0rGNUyHU6)
	jay.WriteInt64(b[424:432], a.VT4F711YMnK5mS3RNF531Qpj8Kpo68q7nTp560YRLMsrAdD87o6U)
	jay.WriteFloat32(b[432:436], a.Ex3gdR0qi8fJJ0U86e0V1312cPMIldHI0cOsUrv4Y2NkAwtJ4TnHBS36nt1Hytn8il748is3xgE1i011j30A0sq2)
	jay.WriteTime(b[436:444], a.U6MGiW6FA2eKQwok4h4ED45D4x8PX3X8BUeBy2GYHGvGvgm67Us8g03)
	jay.WriteIntArch64(b[444:452], a.TLb58mN)
	jay.WriteUintArch64(b[452:460], a.VE00cVoA77jj656Vy7oj643l2pA)
	jay.WriteUint32(b[460:464], a.Uar0CX3o5u3WfqE7o6T3QSq2fMeM4QF)
	jay.WriteTime(b[464:472], a.LYLaR8VdnVR)
	jay.WriteInt64(b[472:480], a.Rnuds8B23000PDI6wyYK1nl12VYXV1a4mtyRRcRcsO24C5yB)
	jay.WriteUint32(b[480:484], a.OAG28SLLnNl77d27AKMI58db7M3LR65jX07870MAfIi24C2I3Go8cG2751b1H271H42Qp2)
	jay.WriteUint16(b[484:486], a.TGa26aGI2D3tjK4f72LR007N35qKNY4XvFpw5)
	jay.WriteUint64(b[486:494], a.G13VEkg4508ej7kiKJ3XKjDT8t6P55T711miJKSR0H27705r77BX5242YatijJe6X)
	jay.WriteInt16(b[494:496], a.Q1yYE381754DtTlMHg2UBKRd0hWe6Xp1nnrVuVc38WB2WDlTx)
	jay.WriteInt16(b[496:498], a.I535RC1JeWO4pDRE81cHuoubcU6aUc1Hogq04NdIx8dTYo5vjq8UtR50F2J02v63v0qD6l8634PmdPW4yY)
	jay.WriteIntArch64(b[498:506], a.Om40t0dTFg4XxBk247p8v26OYHbQKDogx04o8qEmNMdbOP)
	jay.WriteTime(b[506:514], a.V4oAFTJfic0g5r7Aj864wCtu7lMblg0L7i42xUHfB3M4L4EejhqpxusAAASj7Y0b87xlUB0l6485C0n5iL832aknd28pG7L)
	jay.WriteFloat32(b[514:518], a.GsXO60OQk2J1D1Fo5wDU86as6fmGC3yR21UgU83YOE2ROf3Sd0XpN2BCjr6R6WLtW3h2hUunD2e7gOURL3ieJoq)
	at, end := 518, 518+l0
	if l0 != 0 {
		copy(b[at:end], a.Kc3xL2bowR7TwOLpKkDMP44WlLgB5Rh5Ro82kAob3knH34)
	}
	at, end = end, end+l1
	copy(b[at:end], a.IW0B1ASu1777OmeqCcPQ45lC5YX2iqq)
	at, end = end, end+l2
	copy(b[at:end], a.U82Uao8X38P7YLkt4d8qmyl8dNBtG5HxD0DWt161SeQWT6mE)
	at, end = end, end+l3
	if l3 != 0 {
		copy(b[at:end], a.B46TTl2OIN0mgMdUcD8p21rsFa04Cm4sv)
	}
	at, end = end, end+l4
	if l4 != 0 {
		copy(b[at:end], a.C81nWkpqm630B8F0hS107UXT5T8)
	}
	at, end = end, end+l5
	copy(b[at:end], a.E161pw2FDkee46cYa85y2Y4X8)
	at, end = end, end+l6
	copy(b[at:end], a.UvSK)
	at, end = end, end+l7
	copy(b[at:end], a.F6w1voK3gWJ7wphds0Li8dJQ52W503DLR2lfRup0XxJ0Jf5VBkLN4F56Q)
	at, end = end, end+l8
	if l8 != 0 {
		copy(b[at:end], a.C56q26r)
	}
	if l9 != 0 {
		copy(b[end:], a.NEFmR3GYcsX67Uai11Ybyo4KyPhTa25E17EUEX36agNChN2j2k5064G830g08ta5Oje4rskK0xToMvYXWQYjCP21wFQF82xEbRw)
	}
	return
}

func (a *AMly01oki2JC2n77UJT22AVlo2VAiUh06W43tGk43P7th6t6MSj3ejR5PrL103BBIN1ji) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 518 {
		return jay.ErrUnexpectedEOB
	}
	l0, l1, l2, l3, l4, l5, l6, l7, l8, l9 := int(b[0]), int(b[1]), int(b[2]), int(b[3]), int(b[4]), int(b[5]), int(b[6]), int(b[7]), int(b[8]), int(b[9])
	if l < 518+l0+l1+l2+l3+l4+l5+l6+l7+l8+l9 {
		return jay.ErrUnexpectedEOB
	}
	a.K3EJ1UrKYkbWAauAtqwSN8AuP1rPdIEf2WJ886V006o, a.V5JvbOv0107N8qM2m5EPuM3rTIEPGSWFpkGLt4tvRWAk66181NKn7u3C1jak6A4YRc0S6hGQ8l7, a.UNW8I, a.Lv6uxvmRy6k50UkufS0i3LAC622511QkNF3pDmUCGpH6P6teD3oMJS0HkL5OLBVmjelU4O56f45ypWqy6UTLXD3x7GY8Q8MPRx, a.XDUv6BF2hW1u588d76C6qS0F64Q5c, a.F2iof7ha2MhsYvU3MQhB6ivy6X, a.P2J035F8Nk1, a.PX06Ty52WFLl3HwggY387niD34HBEp4QTvD37SXFBog7vh02RUMc4OI1OKJ641Ib3r67P = jay.ReadBool8(b[10])
	a.A6SPqF3gTP3b7kAHKcaQCjV1tT7pCTJOlP7Jtd5YWGP78Diw7N5F26kNPS, a.U2ii03A226243h1p18Wg7oUPc4sI, a.H82PSTYkUKHQ, a.X56gJ8sLWa2wbeWqSI7qK17563i6yh3O6fLjiQMh = jay.ReadBool4(b[11])
	a.RqwPs577d5lTDAQO171A0NwWB1L4cev = b[12]
	a.YCiS0s6Jgw2bWcHF685JKDC6Pi8N45aliRgAgcdtePj23p4w3OeAXvO78W6fb = b[13]
	a.U1CY87y2437vhKnBn6I3w527L05 = b[14]
	a.Ue0J8g2JhAeC0I = b[15]
	a.YBEW261AWb7VYuPT31nJ30LbCPg7y8YdXtj1sUN5q8rfxsNn1s024e6E17cfN21vng81mh1Y5jrD1QgHgRs7uTSw5h = b[16]
	a.T05AXG1G6h42vGYicYHni7hSo = b[17]
	a.NbF3sI6ScBuembX1mg3Tm0iGh2mC26R1M1FabP3rOc31M3Nmgpf7 = b[18]
	a.A5lQ = b[19]
	a.I5oWnf6tyS2mk4v3al1inMxpN7Wj08x7M15usu3xt63bM0epMffOCixf2Ogi3R351gO0 = b[20]
	a.Uq23yRI4W6 = b[21]
	a.E5wqcATKLnLHQ60rdrWDJ1yQ4oI16rxrN68FVMrN5RV1bjaLL6p7kNi6C4xLuyTPxb0cr7d7I287 = int8(b[22])
	a.W2xc78gY3V3xUESRUk44pxX16Ti002wW308Gk24HfgCckt70P3wmjmVwheea4w5b42Ju2m7S2AvO8thp507341yC7UHaIT0NB = b[23]
	a.EYW6cXT3PdjjbV5k52YMo7e7yY5FMDPuoY4GuUF11 = b[24]
	a.X6H47D6k02LwQQ08 = b[25]
	a.Gn01Up7J08XvEv6G5ure51GV0u8c7DGj0n7phy5U0clGd4dC2Cd3P5FNq1 = b[26]
	a.EFUQx0FBGN345SBPrwf42L82MGov7DkUBQk = b[27]
	a.F2Gfck8ev41X08qQE3wVKJ0weRiYTjgB5eYD0Ho4sx7jbMfs1Ftb42c52lYqtN22e4k6h617Ai = b[28]
	a.FE0118sftca22Uv = int8(b[29])
	a.We4o7Xt5TTm7Q0Xxb8XqTc1xj5LQ1daGEaqlQvJ6dF7d6TT42xIpDh = int8(b[30])
	a.CHaMB7Cw311V418f2W24J0kVYkVe548wfhv08Bk0275QnXbI = int8(b[31])
	a.PuNeJcTcveW3p5 = int8(b[32])
	a.JT0Mq1CSXk2rO4t1PMDW0YOiB14ih1pm6FgdvCbG3332i2Kl5c = b[33]
	a.O58y041UjLx2ew73u70WJcqFKrC654XTLsmb4EcM0aitN05VUyjp1kW15i0736h0pjco10OpgY = b[34]
	a.HoB7nFxQHUY652NfN3D7g826sU8PN4K6xev42oO78OxmgFb4D = b[35]
	a.N22e881N0OcAnCFP7gD3o1lu66pnU07f8U8fhGjAE5fsm617Wknd20aBJC = b[36]
	a.BUL7SnjImLQ = b[37]
	a.S3KUyIH2uGr1YN27tQLcv2eAkEG1Dt4Y8hs2Ia = jay.ReadFloat64(b[38:46])
	a.F3ft3g2uB7YU526LV0c0Oeq0Gf4YRaUB = jay.ReadInt32(b[46:50])
	a.C33lxaDuW2A6ybtWKj2TF5y0iDadC802S7RU5QD20WJ28iUW3P77s60eEb81Xi = jay.ReadIntArch64(b[50:58])
	a.DSuEeV4220rRXcqTr5w3bf48 = jay.ReadUintArch64(b[58:66])
	a.Hn1Qexo2s4C4Td5e7XJFxpi2AApQqe5mcSBaYOlrs3L5l8MEB8418EwUB3HSn = jay.ReadInt16(b[66:68])
	a.Rk10bi2iS60caL5S5H33LCp7Y1C = jay.ReadUint64(b[68:76])
	a.N7U00Jq7M4rb = jay.ReadFloat32(b[76:80])
	a.Mu7L1fA5uQCm6fpEr38j7sL7C6i0Kh144G4mdhPTT77s62c7q3dDY2OKVwkeSM84D6tP6cECnc6BDKCtCb6DdX3N27D = jay.ReadUintArch64(b[80:88])
	a.UUNCBYqg0t5dAmgj2yv1f82 = jay.ReadInt64(b[88:96])
	a.O4rMNxf3aO5IJWc6y2kkp = jay.ReadInt64(b[96:104])
	a.Ru61x3A3uvCu2762uCvK8d0V5rSR67s56Q3gp46xxfp = jay.ReadUint32(b[104:108])
	a.SV7844lBSVUnHGIkv15V8LW8s6u4 = jay.ReadUintArch64(b[108:116])
	a.GWk0JT2GFoNPBwHS3WN151E6tcOfe3aNNxH0jxNQm36lVbQ8n8Iam400t4dJurQ = jay.ReadUint32(b[116:120])
	a.J77kvKtw5KjuKE6iXmk45R8eLXIEdYPKWM4yj34hKN3H8L3 = jay.ReadFloat32(b[120:124])
	a.UfKf3EwHDcf65g4Fs6aAdRg12lTrCi4efXaQ0M80KO0x17HUOTxGJm14IBf5 = jay.ReadInt32(b[124:128])
	a.N = jay.ReadFloat32(b[128:132])
	a.FBK2Kv7Ig0qcgR8iQi0OY6upi1yBwxv6XisrWCUWTPa05mMI7bh2qg3WBSLN5mr1A = jay.ReadFloat32(b[132:136])
	a.H5GV5iLAgebIu7g4o2SKCc4myHxL3FeKdQ7JUopgV86fl3n8h6bbhw5KAiA6KgO2Jojxm7 = jay.ReadTime(b[136:144])
	a.Bwf7Y3J7ot17wch11036jO53W2XtoJ50QYy11s8wWQkuk2JnOb31wd1WHLH3VNSywJ7J7i2Lim0cGJKRJ6I6l5M = jay.ReadUintArch64(b[144:152])
	a.VcK0X26NlJuL85au66Ov66Kk2aO225tv0I1cAY3m2WVt087vVMm86MtTCSgj802OV1Fyxy1R2Ed4GhGgt1lgks = jay.ReadUint64(b[152:160])
	a.LVUcb8km4Wvq7d0Mi7ugkkvE2dS13sJL0Vchw24g6jIK5ETr4WrgT1DPb8e7xp = jay.ReadUint64(b[160:168])
	a.E6g5vtTKU5c03cO4EwArxLgqh8pnuRnthQiT6UW6187i35bj6u1K6851sk2q8sN3Q5c8B3GORHGXSXi8MUYT8 = jay.ReadInt32(b[168:172])
	a.SM45EUMsP7c0BqSu05OwiHlKUx4wj56222mrA53gP2M5NHB80 = jay.ReadInt64(b[172:180])
	a.IGYxbTLvrFlab41veBQj15qTX6uy7S = jay.ReadInt64(b[180:188])
	a.OfX04QBY2XQI8npCSaEYGTYtVb1mdP6tlg05AO3mq422RT8jDi2FRqN5FF3Y5cF1OK1y2yW1Y8JK05Hk1CX87xxOL2F2iJT1 = jay.ReadTime(b[188:196])
	a.F20en5 = jay.ReadInt32(b[196:200])
	a.SmD5u3Dp3u1YymhIc58r13ho80s2q56q1tR335181AYgRLt0TRM5Uxd5UM0Bs4xUA0KB4L28Q0HRs0wJgr1lYE8P6U00ca57Rdp = jay.ReadIntArch64(b[200:208])
	a.BAh65bIl5I44gOY47v4BrAH0Obql6fjCEd1r7S5xXumU1RWm6MTN8D6oBESvnG4IM1q3GieGLB30fO = jay.ReadInt16(b[208:210])
	a.TAp = jay.ReadInt32(b[210:214])
	a.IT2FPQXXca0Fu4BtXa1GFXV837EPBSI83e7la84TTd4g0e867m7u = jay.ReadInt16(b[214:216])
	a.Vb8BTfmBH262aGW8cBclN2VVWBHE45eEfAghn5kEd6lF61KoMwjHKd8hmiYl8gCWuLt6ExEs7VF680sv4 = jay.ReadUint32(b[216:220])
	a.G55T53ie6mm1qR4S8j1k2np8LCc841sW2b7pHI3B64F4ei0kdJae67FRU8Arx6Ra = jay.ReadInt32(b[220:224])
	a.XUvg4evc1auQ0rt1XPL8xLVt38qqiKjN0Tn5iy0u411e1h176PW1pIt3gU28jChT7Ub1VN2LJS606Ev3q78KO44wB8 = jay.ReadTime(b[224:232])
	a.XhvCr720NYe5IxPtWWWW4va = jay.ReadFloat64(b[232:240])
	a.D2nGeA50e8B7tNxbiG227RV864Qmt71T62mXGMT75cotRqCugu87swn = jay.ReadInt16(b[240:242])
	a.UTg7TawC4QO80 = jay.ReadIntArch64(b[242:250])
	a.HaTJ5wctBlj0TS1aiiDS4w1vJGIMR51v4T47o5kxwQblt8rArOuuKd08X15x5444b6d2647J8f3 = jay.ReadUint32(b[250:254])
	a.MO5n60vWB312SWHISn2wd4qQoer1y337f55axYs3Rc74h4k63yYxN42XtbV1h6mt208u64 = jay.ReadIntArch64(b[254:262])
	a.Fb173eCxU17I = jay.ReadUint64(b[262:270])
	a.Ta5536bV3TH3nb7tGbBAm418ey4sBBVe2RdT6K2X8nq2eah2C3G55Y8 = jay.ReadInt32(b[270:274])
	a.Wl12l4 = jay.ReadUint16(b[274:276])
	a.J7FNI4821OH2VMBmjG3qNFy2SSI851nx17Q41RuWW8C2d = jay.ReadInt32(b[276:280])
	a.XAoxjdPDO8N28i1Kmwa547xJQS37al1Oy5OIYB37PmMVt6PXUTxvGQTBB38G4XpL4rS07gdhlTPm6mtC0m5JXmt8 = jay.ReadUintArch64(b[280:288])
	a.IHHNryTqdNyOEXQD1P3O6vC12oeE6j2mml8dK882ok21pWNyW328DRbw1xCb5aFjfEwrh2M1WU5H23Ol45Aq0 = jay.ReadUint64(b[288:296])
	a.Pe7BR1E2mr7BWA5y18HgeVEIsxKl0PPSjs1RTYEr03x7pBRbM64470Al41V76HMOc4P7runL = jay.ReadUint32(b[296:300])
	a.Wp7a6qr86735t1tTv338Snvr45jdCBJ45FpN0FFQf4tokXJw = jay.ReadUint16(b[300:302])
	a.T0NDiW7asNiR5A655ssSe4box32Roc7NL8H420pYjPS8a23jhIINjo70bI7Sew14TD84F8M2IM6t0IaNoMBx = jay.ReadUint32(b[302:306])
	a.Nhjj038NJ04vqJDKgqkJ4wq6vlJAsD27hoPA7P = jay.ReadTime(b[306:314])
	a.KLCcq5F86SI53yi6454X1Q5X0OIDkl1aEjiIB1nkn45P10j0r5qb5y = jay.ReadTime(b[314:322])
	a.Ln7qxIc1xGosRK8M62I5j80IJN7H1oB3KpkmN0LqqDlT87h = jay.ReadUintArch64(b[322:330])
	a.P0BfqN1q = jay.ReadInt16(b[330:332])
	a.I3SWg4CV77750OdfDI4Kt4An5N83Al66gd6yigS0q16X8w7hC = jay.ReadInt16(b[332:334])
	a.X2QRx455Wp2 = jay.ReadUintArch64(b[334:342])
	a.YE348JHYKM4IewHYsW223u6l8qUOerISlv61J67T0khhR0dhXm68l24QTs018Hb863Fe0HRo4o0i1eRLfWQ = jay.ReadInt16(b[342:344])
	a.I4n0klX453ugOp6teq651uW4 = jay.ReadInt32(b[344:348])
	a.C7gx8vVuco76psH10yhRE6nL45rr1b4fvWpbIN33411t02iP5DP4J3huU7Xl4B8w2t0h7471H5iW2jyxcD36UN58rsgN07N0770a = jay.ReadUintArch64(b[348:356])
	a.Y3Ox80LRyRuLCO3P2yJ6I = jay.ReadFloat64(b[356:364])
	a.DjE0g7jxOBuhNhf51pXvj5LhU6b6qsP6MX5Nv81EBy = jay.ReadInt32(b[364:368])
	a.Brnni3PeEi2XU10cyr6j0ppdG2a05BdIGlBpM687A1P66c2t = jay.ReadUint32(b[368:372])
	a.URL7gIQ16gfSyqcw51FQaE3wfRgTe5CE2uU0STpV7D = jay.ReadUint32(b[372:376])
	a.OW6r70Djqj = jay.ReadUintArch64(b[376:384])
	a.J86wCAlDW41w0cl4FjCU08471hp2Q5Eo2Dw4Iwj8E2ySsy26N5yF30GUw0 = jay.ReadTime(b[384:392])
	a.Tn0RerY8Y81KFf1w7o82KukpV68736TLVKJP66s3Y1V54qT86MXtoWNUa2fudidETwHgV = jay.ReadUintArch64(b[392:400])
	a.EqXn3kdLI15O5GQyr6253kb7VdNv2uC4mwNLfOmR5SdMl5rdtum6vypL3 = jay.ReadUint16(b[400:402])
	a.Q7vqKj51Qb84d48JEIvYNU75aWo0qAYSVjXY44j8AC7UD41pl51AR1d264nv2 = jay.ReadUint32(b[402:406])
	a.FmUJmlMOtNqi4uUR0N1K4o72E064hbj8jX5N1sEx6U67l680FymAOtc7StlcwoAdyD2TeJ12arXQg = jay.ReadFloat32(b[406:410])
	a.BA0rA3ud8m5KCYi78NeWo7c7NSHQ3PdEMIPky2QQ3v6S8Ur6uqy1OK = jay.ReadInt32(b[410:414])
	a.BXBVF4Q4iNdqfgAeaqK64s6t6Bav8ojL6KOwyY1052sL6bT1u04OSE = jay.ReadTime(b[414:422])
	a.LO82V5X1RHx52i61e51fp6x2bbBgSBo70x34fuW5EtcR5GUlu4TP1B3QD472K8y8QFoa5YGg7425VTCka7A0rGNUyHU6 = jay.ReadInt16(b[422:424])
	a.VT4F711YMnK5mS3RNF531Qpj8Kpo68q7nTp560YRLMsrAdD87o6U = jay.ReadInt64(b[424:432])
	a.Ex3gdR0qi8fJJ0U86e0V1312cPMIldHI0cOsUrv4Y2NkAwtJ4TnHBS36nt1Hytn8il748is3xgE1i011j30A0sq2 = jay.ReadFloat32(b[432:436])
	a.U6MGiW6FA2eKQwok4h4ED45D4x8PX3X8BUeBy2GYHGvGvgm67Us8g03 = jay.ReadTime(b[436:444])
	a.TLb58mN = jay.ReadIntArch64(b[444:452])
	a.VE00cVoA77jj656Vy7oj643l2pA = jay.ReadUintArch64(b[452:460])
	a.Uar0CX3o5u3WfqE7o6T3QSq2fMeM4QF = jay.ReadUint32(b[460:464])
	a.LYLaR8VdnVR = jay.ReadTime(b[464:472])
	a.Rnuds8B23000PDI6wyYK1nl12VYXV1a4mtyRRcRcsO24C5yB = jay.ReadInt64(b[472:480])
	a.OAG28SLLnNl77d27AKMI58db7M3LR65jX07870MAfIi24C2I3Go8cG2751b1H271H42Qp2 = jay.ReadUint32(b[480:484])
	a.TGa26aGI2D3tjK4f72LR007N35qKNY4XvFpw5 = jay.ReadUint16(b[484:486])
	a.G13VEkg4508ej7kiKJ3XKjDT8t6P55T711miJKSR0H27705r77BX5242YatijJe6X = jay.ReadUint64(b[486:494])
	a.Q1yYE381754DtTlMHg2UBKRd0hWe6Xp1nnrVuVc38WB2WDlTx = jay.ReadInt16(b[494:496])
	a.I535RC1JeWO4pDRE81cHuoubcU6aUc1Hogq04NdIx8dTYo5vjq8UtR50F2J02v63v0qD6l8634PmdPW4yY = jay.ReadInt16(b[496:498])
	a.Om40t0dTFg4XxBk247p8v26OYHbQKDogx04o8qEmNMdbOP = jay.ReadIntArch64(b[498:506])
	a.V4oAFTJfic0g5r7Aj864wCtu7lMblg0L7i42xUHfB3M4L4EejhqpxusAAASj7Y0b87xlUB0l6485C0n5iL832aknd28pG7L = jay.ReadTime(b[506:514])
	a.GsXO60OQk2J1D1Fo5wDU86as6fmGC3yR21UgU83YOE2ROf3Sd0XpN2BCjr6R6WLtW3h2hUunD2e7gOURL3ieJoq = jay.ReadFloat32(b[514:518])
	at, end := 518, 518+l0
	if l0 != 0 {
		a.Kc3xL2bowR7TwOLpKkDMP44WlLgB5Rh5Ro82kAob3knH34 = b[at:end]
	}
	at, end = end, end+l1
	a.IW0B1ASu1777OmeqCcPQ45lC5YX2iqq = string(b[at:end])
	at, end = end, end+l2
	a.U82Uao8X38P7YLkt4d8qmyl8dNBtG5HxD0DWt161SeQWT6mE = string(b[at:end])
	at, end = end, end+l3
	if l3 != 0 {
		a.B46TTl2OIN0mgMdUcD8p21rsFa04Cm4sv = b[at:end]
	}
	at, end = end, end+l4
	if l4 != 0 {
		a.C81nWkpqm630B8F0hS107UXT5T8 = b[at:end]
	}
	at, end = end, end+l5
	a.E161pw2FDkee46cYa85y2Y4X8 = string(b[at:end])
	at, end = end, end+l6
	a.UvSK = string(b[at:end])
	at, end = end, end+l7
	a.F6w1voK3gWJ7wphds0Li8dJQ52W503DLR2lfRup0XxJ0Jf5VBkLN4F56Q = string(b[at:end])
	at, end = end, end+l8
	if l8 != 0 {
		a.C56q26r = b[at:end]
	}
	if l9 != 0 {
		a.NEFmR3GYcsX67Uai11Ybyo4KyPhTa25E17EUEX36agNChN2j2k5064G830g08ta5Oje4rskK0xToMvYXWQYjCP21wFQF82xEbRw = b[end:]
	}
	return nil
}

func (o O0x5DXIdW5D267tvCvQ35CkEn7oYIU30oGOTYy5EfC42i8PPpwin8n55cNSWllXyod) MarshalJ() (b []byte) {
	l0 := len(o.K3tR0F62ayb40x4Gtn4e7kOol87p7sJo55jH548y8Y0fYeK6)
	b = make([]byte, 145+l0)
	b[0] = byte(l0)
	b[1] = jay.Bool2(o.CwnoiTT, o.Y4202JJ58lJFxC5M3IGSCM1arBRxjUG156YFm1UEu21rXb71xiMks3c4uRMH01JnvG4AkW8u1O5WbQfKTd0)
	b[2] = o.CxPGQOKcIY1gS7HDiPs8gMNQkvwx4oDq511AI4HnKf07oJhum6M6vA2C47158JY0kAcHD
	b[3] = o.WPy74ranJyUTBhO6j1O14608e1j14AIJa3Ld0k4Vfx6O4R7INLT0
	b[4] = byte(o.KF8)
	b[5] = o.KdAU406a8jWCmU0M6Nx87XOSUVBKgNQp2cPC4Wh
	b[6] = byte(o.BL3yC8ql88yU6CjT8Cvo7jST711xldA4Nyb47503C6jULeLNIE4VYJrRrQmKIQghgWMOI06mOj)
	b[7] = byte(o.H3w6mA3vPBQIix80fXx8cwdWlpAW72Iajj37sl3kBhm5ilFp3B50SLEt)
	b[8] = o.J3IVanIdCgocc8ckBu42h6NIN5oVITm
	jay.WriteFloat64(b[9:17], o.DY72mjEfkQof3eUSDFCYo3qbdnxGsyl4oU4XkL0H2yLEdRx00844sYDmo716jQJIGI08hME0G)
	jay.WriteUint64(b[17:25], o.Sf44mn)
	jay.WriteInt64(b[25:33], o.A7sako5sUl618Cw55rd8E40X3W58wgwg5278C5mqSssANwC3h8W8xVAsX)
	jay.WriteTime(b[33:41], o.K2IE5QD3kD7qelMe72n60d2U71njtdKf)
	jay.WriteInt32(b[41:45], o.GA4pJHF6k0JfUbMJ0k5Eo8Wg4c5S0Nd1bf30M63860jtkk7s2i8ROJ6rWHOmXBfI655VLOOoc1nim0kYJ7nE0)
	jay.WriteIntArch64(b[45:53], o.JvSTSs42KDBJ5600KBTw)
	jay.WriteInt16(b[53:55], o.SBf)
	jay.WriteUint16(b[55:57], o.Uat82y8083s8XTd5mM5kFEHXgFU3uvYl8Vw24dQ1M8PU0J14J7j4DoGj0Yv1w2)
	jay.WriteUint16(b[57:59], o.J5m5WgMC1kDwGX83AQKKQOB3jmayDw85ly5331O)
	jay.WriteFloat32(b[59:63], o.M1T1vkIWcmAo6b7D8RJVVjN1ML7iFC7RQ7MhuLDlcu273UgUkKCOcdhJcXA535MVKAU7bK1tA0b11qP4)
	jay.WriteInt64(b[63:71], o.YhI6wLQx8642Qxs62hnLFj3f38j5830dADpQCC1TAMSDoCx)
	jay.WriteTime(b[71:79], o.P1MTN2K53f4vFu47Nq77ChYFHbo3cugNLFC7IjmPB6O2Yh6l45ByLYsm84xk06)
	jay.WriteUintArch64(b[79:87], o.NQ25SXoR2W6EdcJ2qh885)
	jay.WriteTime(b[87:95], o.UfyuExdG5MyYsm1)
	jay.WriteFloat64(b[95:103], o.UMwf0Xi6876K5PBppfrRuT1FLVWh88NuPy6d3mj7r3uaSCWe5cPUsSHqa7RB82bHcSOhchkv2Ko2yMD4mU60Y11eG)
	jay.WriteTime(b[103:111], o.EH4n5b55CYsMuP2CP8eDvg2ndeUI6lv1x8yEtW510IdxG5)
	jay.WriteUint16(b[111:113], o.E861rf02gHlam6RkarIbdYt86ODCLlnS3323yuXdTXdhXE67GiIhtSHvTWxiqaf1Am7P)
	jay.WriteFloat64(b[113:121], o.WgN4MRAKSU6fsOsIU4627)
	jay.WriteTime(b[121:129], o.E3E26VLqNXWkVK5YFc2YjL1tC05g0Qx5Mpx)
	jay.WriteFloat32(b[129:133], o.Yxk635XJgHai6GTOiIuBi1)
	jay.WriteInt64(b[133:141], o.Xm528xGY5VN724Qw6TI64WQP62MFjixAVsP4CLB3h255rsngUMsj5GK00Rk6p3kygvG5R42438ESf8skHXte11wrX24n1)
	jay.WriteUint32(b[141:145], o.E12ro)
	if l0 != 0 {
		copy(b[145:], o.K3tR0F62ayb40x4Gtn4e7kOol87p7sJo55jH548y8Y0fYeK6)
	}
	return
}

func (o *O0x5DXIdW5D267tvCvQ35CkEn7oYIU30oGOTYy5EfC42i8PPpwin8n55cNSWllXyod) UnmarshalJ(b []byte) error {
	l := len(b)
	if l < 145 {
		return jay.ErrUnexpectedEOB
	}
	l0 := int(b[0])
	if l < 145+l0 {
		return jay.ErrUnexpectedEOB
	}
	o.CwnoiTT, o.Y4202JJ58lJFxC5M3IGSCM1arBRxjUG156YFm1UEu21rXb71xiMks3c4uRMH01JnvG4AkW8u1O5WbQfKTd0 = jay.ReadBool2(b[1])
	o.CxPGQOKcIY1gS7HDiPs8gMNQkvwx4oDq511AI4HnKf07oJhum6M6vA2C47158JY0kAcHD = b[2]
	o.WPy74ranJyUTBhO6j1O14608e1j14AIJa3Ld0k4Vfx6O4R7INLT0 = b[3]
	o.KF8 = int8(b[4])
	o.KdAU406a8jWCmU0M6Nx87XOSUVBKgNQp2cPC4Wh = b[5]
	o.BL3yC8ql88yU6CjT8Cvo7jST711xldA4Nyb47503C6jULeLNIE4VYJrRrQmKIQghgWMOI06mOj = int8(b[6])
	o.H3w6mA3vPBQIix80fXx8cwdWlpAW72Iajj37sl3kBhm5ilFp3B50SLEt = int8(b[7])
	o.J3IVanIdCgocc8ckBu42h6NIN5oVITm = b[8]
	o.DY72mjEfkQof3eUSDFCYo3qbdnxGsyl4oU4XkL0H2yLEdRx00844sYDmo716jQJIGI08hME0G = jay.ReadFloat64(b[9:17])
	o.Sf44mn = jay.ReadUint64(b[17:25])
	o.A7sako5sUl618Cw55rd8E40X3W58wgwg5278C5mqSssANwC3h8W8xVAsX = jay.ReadInt64(b[25:33])
	o.K2IE5QD3kD7qelMe72n60d2U71njtdKf = jay.ReadTime(b[33:41])
	o.GA4pJHF6k0JfUbMJ0k5Eo8Wg4c5S0Nd1bf30M63860jtkk7s2i8ROJ6rWHOmXBfI655VLOOoc1nim0kYJ7nE0 = jay.ReadInt32(b[41:45])
	o.JvSTSs42KDBJ5600KBTw = jay.ReadIntArch64(b[45:53])
	o.SBf = jay.ReadInt16(b[53:55])
	o.Uat82y8083s8XTd5mM5kFEHXgFU3uvYl8Vw24dQ1M8PU0J14J7j4DoGj0Yv1w2 = jay.ReadUint16(b[55:57])
	o.J5m5WgMC1kDwGX83AQKKQOB3jmayDw85ly5331O = jay.ReadUint16(b[57:59])
	o.M1T1vkIWcmAo6b7D8RJVVjN1ML7iFC7RQ7MhuLDlcu273UgUkKCOcdhJcXA535MVKAU7bK1tA0b11qP4 = jay.ReadFloat32(b[59:63])
	o.YhI6wLQx8642Qxs62hnLFj3f38j5830dADpQCC1TAMSDoCx = jay.ReadInt64(b[63:71])
	o.P1MTN2K53f4vFu47Nq77ChYFHbo3cugNLFC7IjmPB6O2Yh6l45ByLYsm84xk06 = jay.ReadTime(b[71:79])
	o.NQ25SXoR2W6EdcJ2qh885 = jay.ReadUintArch64(b[79:87])
	o.UfyuExdG5MyYsm1 = jay.ReadTime(b[87:95])
	o.UMwf0Xi6876K5PBppfrRuT1FLVWh88NuPy6d3mj7r3uaSCWe5cPUsSHqa7RB82bHcSOhchkv2Ko2yMD4mU60Y11eG = jay.ReadFloat64(b[95:103])
	o.EH4n5b55CYsMuP2CP8eDvg2ndeUI6lv1x8yEtW510IdxG5 = jay.ReadTime(b[103:111])
	o.E861rf02gHlam6RkarIbdYt86ODCLlnS3323yuXdTXdhXE67GiIhtSHvTWxiqaf1Am7P = jay.ReadUint16(b[111:113])
	o.WgN4MRAKSU6fsOsIU4627 = jay.ReadFloat64(b[113:121])
	o.E3E26VLqNXWkVK5YFc2YjL1tC05g0Qx5Mpx = jay.ReadTime(b[121:129])
	o.Yxk635XJgHai6GTOiIuBi1 = jay.ReadFloat32(b[129:133])
	o.Xm528xGY5VN724Qw6TI64WQP62MFjixAVsP4CLB3h255rsngUMsj5GK00Rk6p3kygvG5R42438ESf8skHXte11wrX24n1 = jay.ReadInt64(b[133:141])
	o.E12ro = jay.ReadUint32(b[141:145])
	if l0 != 0 {
		o.K3tR0F62ayb40x4Gtn4e7kOol87p7sJo55jH548y8Y0fYeK6 = b[145:]
	}
	return nil
}
