// Code generated by gen.go; DO NOT EDIT.

package main

import "time"

type Fuzz0 struct {
	One bool
	Two []bool
}

type Fuzz1 struct {
	One bool
	Two byte
}

type Fuzz2 struct {
	One bool
	Two []byte
}

type Fuzz3 struct {
	One bool
	Two float32
}

type Fuzz4 struct {
	One bool
	Two []float32
}

type Fuzz5 struct {
	One bool
	Two float64
}

type Fuzz6 struct {
	One bool
	Two []float64
}

type Fuzz7 struct {
	One bool
	Two int
}

type Fuzz8 struct {
	One bool
	Two int8
}

type Fuzz9 struct {
	One bool
	Two int16
}

type Fuzz10 struct {
	One bool
	Two int32
}

type Fuzz11 struct {
	One bool
	Two rune
}

type Fuzz12 struct {
	One bool
	Two int64
}

type Fuzz13 struct {
	One bool
	Two []int
}

type Fuzz14 struct {
	One bool
	Two []int8
}

type Fuzz15 struct {
	One bool
	Two []int16
}

type Fuzz16 struct {
	One bool
	Two []int32
}

type Fuzz17 struct {
	One bool
	Two []int64
}

type Fuzz18 struct {
	One bool
	Two uint
}

type Fuzz19 struct {
	One bool
	Two uint8
}

type Fuzz20 struct {
	One bool
	Two uint16
}

type Fuzz21 struct {
	One bool
	Two uint32
}

type Fuzz22 struct {
	One bool
	Two uint64
}

type Fuzz23 struct {
	One bool
	Two []uint
}

type Fuzz24 struct {
	One bool
	Two []uint16
}

type Fuzz25 struct {
	One bool
	Two []uint32
}

type Fuzz26 struct {
	One bool
	Two []uint64
}

type Fuzz27 struct {
	One bool
	Two string
}

type Fuzz28 struct {
	One bool
	Two []string
}

type Fuzz29 struct {
	One bool
	Two time.Time
}

type Fuzz30 struct {
	One bool
	Two time.Duration
}

type Fuzz31 struct {
	One bool
	Two []time.Duration
}

type Fuzz32 struct {
	One []bool
	Two bool
}

type Fuzz33 struct {
	One []bool
	Two byte
}

type Fuzz34 struct {
	One []bool
	Two []byte
}

type Fuzz35 struct {
	One []bool
	Two float32
}

type Fuzz36 struct {
	One []bool
	Two []float32
}

type Fuzz37 struct {
	One []bool
	Two float64
}

type Fuzz38 struct {
	One []bool
	Two []float64
}

type Fuzz39 struct {
	One []bool
	Two int
}

type Fuzz40 struct {
	One []bool
	Two int8
}

type Fuzz41 struct {
	One []bool
	Two int16
}

type Fuzz42 struct {
	One []bool
	Two int32
}

type Fuzz43 struct {
	One []bool
	Two rune
}

type Fuzz44 struct {
	One []bool
	Two int64
}

type Fuzz45 struct {
	One []bool
	Two []int
}

type Fuzz46 struct {
	One []bool
	Two []int8
}

type Fuzz47 struct {
	One []bool
	Two []int16
}

type Fuzz48 struct {
	One []bool
	Two []int32
}

type Fuzz49 struct {
	One []bool
	Two []int64
}

type Fuzz50 struct {
	One []bool
	Two uint
}

type Fuzz51 struct {
	One []bool
	Two uint8
}

type Fuzz52 struct {
	One []bool
	Two uint16
}

type Fuzz53 struct {
	One []bool
	Two uint32
}

type Fuzz54 struct {
	One []bool
	Two uint64
}

type Fuzz55 struct {
	One []bool
	Two []uint
}

type Fuzz56 struct {
	One []bool
	Two []uint16
}

type Fuzz57 struct {
	One []bool
	Two []uint32
}

type Fuzz58 struct {
	One []bool
	Two []uint64
}

type Fuzz59 struct {
	One []bool
	Two string
}

type Fuzz60 struct {
	One []bool
	Two []string
}

type Fuzz61 struct {
	One []bool
	Two time.Time
}

type Fuzz62 struct {
	One []bool
	Two time.Duration
}

type Fuzz63 struct {
	One []bool
	Two []time.Duration
}

type Fuzz64 struct {
	One byte
	Two bool
}

type Fuzz65 struct {
	One byte
	Two []bool
}

type Fuzz66 struct {
	One byte
	Two []byte
}

type Fuzz67 struct {
	One byte
	Two float32
}

type Fuzz68 struct {
	One byte
	Two []float32
}

type Fuzz69 struct {
	One byte
	Two float64
}

type Fuzz70 struct {
	One byte
	Two []float64
}

type Fuzz71 struct {
	One byte
	Two int
}

type Fuzz72 struct {
	One byte
	Two int8
}

type Fuzz73 struct {
	One byte
	Two int16
}

type Fuzz74 struct {
	One byte
	Two int32
}

type Fuzz75 struct {
	One byte
	Two rune
}

type Fuzz76 struct {
	One byte
	Two int64
}

type Fuzz77 struct {
	One byte
	Two []int
}

type Fuzz78 struct {
	One byte
	Two []int8
}

type Fuzz79 struct {
	One byte
	Two []int16
}

type Fuzz80 struct {
	One byte
	Two []int32
}

type Fuzz81 struct {
	One byte
	Two []int64
}

type Fuzz82 struct {
	One byte
	Two uint
}

type Fuzz83 struct {
	One byte
	Two uint8
}

type Fuzz84 struct {
	One byte
	Two uint16
}

type Fuzz85 struct {
	One byte
	Two uint32
}

type Fuzz86 struct {
	One byte
	Two uint64
}

type Fuzz87 struct {
	One byte
	Two []uint
}

type Fuzz88 struct {
	One byte
	Two []uint16
}

type Fuzz89 struct {
	One byte
	Two []uint32
}

type Fuzz90 struct {
	One byte
	Two []uint64
}

type Fuzz91 struct {
	One byte
	Two string
}

type Fuzz92 struct {
	One byte
	Two []string
}

type Fuzz93 struct {
	One byte
	Two time.Time
}

type Fuzz94 struct {
	One byte
	Two time.Duration
}

type Fuzz95 struct {
	One byte
	Two []time.Duration
}

type Fuzz96 struct {
	One []byte
	Two bool
}

type Fuzz97 struct {
	One []byte
	Two []bool
}

type Fuzz98 struct {
	One []byte
	Two byte
}

type Fuzz99 struct {
	One []byte
	Two float32
}

type Fuzz100 struct {
	One []byte
	Two []float32
}

type Fuzz101 struct {
	One []byte
	Two float64
}

type Fuzz102 struct {
	One []byte
	Two []float64
}

type Fuzz103 struct {
	One []byte
	Two int
}

type Fuzz104 struct {
	One []byte
	Two int8
}

type Fuzz105 struct {
	One []byte
	Two int16
}

type Fuzz106 struct {
	One []byte
	Two int32
}

type Fuzz107 struct {
	One []byte
	Two rune
}

type Fuzz108 struct {
	One []byte
	Two int64
}

type Fuzz109 struct {
	One []byte
	Two []int
}

type Fuzz110 struct {
	One []byte
	Two []int8
}

type Fuzz111 struct {
	One []byte
	Two []int16
}

type Fuzz112 struct {
	One []byte
	Two []int32
}

type Fuzz113 struct {
	One []byte
	Two []int64
}

type Fuzz114 struct {
	One []byte
	Two uint
}

type Fuzz115 struct {
	One []byte
	Two uint8
}

type Fuzz116 struct {
	One []byte
	Two uint16
}

type Fuzz117 struct {
	One []byte
	Two uint32
}

type Fuzz118 struct {
	One []byte
	Two uint64
}

type Fuzz119 struct {
	One []byte
	Two []uint
}

type Fuzz120 struct {
	One []byte
	Two []uint16
}

type Fuzz121 struct {
	One []byte
	Two []uint32
}

type Fuzz122 struct {
	One []byte
	Two []uint64
}

type Fuzz123 struct {
	One []byte
	Two string
}

type Fuzz124 struct {
	One []byte
	Two []string
}

type Fuzz125 struct {
	One []byte
	Two time.Time
}

type Fuzz126 struct {
	One []byte
	Two time.Duration
}

type Fuzz127 struct {
	One []byte
	Two []time.Duration
}

type Fuzz128 struct {
	One float32
	Two bool
}

type Fuzz129 struct {
	One float32
	Two []bool
}

type Fuzz130 struct {
	One float32
	Two byte
}

type Fuzz131 struct {
	One float32
	Two []byte
}

type Fuzz132 struct {
	One float32
	Two []float32
}

type Fuzz133 struct {
	One float32
	Two float64
}

type Fuzz134 struct {
	One float32
	Two []float64
}

type Fuzz135 struct {
	One float32
	Two int
}

type Fuzz136 struct {
	One float32
	Two int8
}

type Fuzz137 struct {
	One float32
	Two int16
}

type Fuzz138 struct {
	One float32
	Two int32
}

type Fuzz139 struct {
	One float32
	Two rune
}

type Fuzz140 struct {
	One float32
	Two int64
}

type Fuzz141 struct {
	One float32
	Two []int
}

type Fuzz142 struct {
	One float32
	Two []int8
}

type Fuzz143 struct {
	One float32
	Two []int16
}

type Fuzz144 struct {
	One float32
	Two []int32
}

type Fuzz145 struct {
	One float32
	Two []int64
}

type Fuzz146 struct {
	One float32
	Two uint
}

type Fuzz147 struct {
	One float32
	Two uint8
}

type Fuzz148 struct {
	One float32
	Two uint16
}

type Fuzz149 struct {
	One float32
	Two uint32
}

type Fuzz150 struct {
	One float32
	Two uint64
}

type Fuzz151 struct {
	One float32
	Two []uint
}

type Fuzz152 struct {
	One float32
	Two []uint16
}

type Fuzz153 struct {
	One float32
	Two []uint32
}

type Fuzz154 struct {
	One float32
	Two []uint64
}

type Fuzz155 struct {
	One float32
	Two string
}

type Fuzz156 struct {
	One float32
	Two []string
}

type Fuzz157 struct {
	One float32
	Two time.Time
}

type Fuzz158 struct {
	One float32
	Two time.Duration
}

type Fuzz159 struct {
	One float32
	Two []time.Duration
}

type Fuzz160 struct {
	One []float32
	Two bool
}

type Fuzz161 struct {
	One []float32
	Two []bool
}

type Fuzz162 struct {
	One []float32
	Two byte
}

type Fuzz163 struct {
	One []float32
	Two []byte
}

type Fuzz164 struct {
	One []float32
	Two float32
}

type Fuzz165 struct {
	One []float32
	Two float64
}

type Fuzz166 struct {
	One []float32
	Two []float64
}

type Fuzz167 struct {
	One []float32
	Two int
}

type Fuzz168 struct {
	One []float32
	Two int8
}

type Fuzz169 struct {
	One []float32
	Two int16
}

type Fuzz170 struct {
	One []float32
	Two int32
}

type Fuzz171 struct {
	One []float32
	Two rune
}

type Fuzz172 struct {
	One []float32
	Two int64
}

type Fuzz173 struct {
	One []float32
	Two []int
}

type Fuzz174 struct {
	One []float32
	Two []int8
}

type Fuzz175 struct {
	One []float32
	Two []int16
}

type Fuzz176 struct {
	One []float32
	Two []int32
}

type Fuzz177 struct {
	One []float32
	Two []int64
}

type Fuzz178 struct {
	One []float32
	Two uint
}

type Fuzz179 struct {
	One []float32
	Two uint8
}

type Fuzz180 struct {
	One []float32
	Two uint16
}

type Fuzz181 struct {
	One []float32
	Two uint32
}

type Fuzz182 struct {
	One []float32
	Two uint64
}

type Fuzz183 struct {
	One []float32
	Two []uint
}

type Fuzz184 struct {
	One []float32
	Two []uint16
}

type Fuzz185 struct {
	One []float32
	Two []uint32
}

type Fuzz186 struct {
	One []float32
	Two []uint64
}

type Fuzz187 struct {
	One []float32
	Two string
}

type Fuzz188 struct {
	One []float32
	Two []string
}

type Fuzz189 struct {
	One []float32
	Two time.Time
}

type Fuzz190 struct {
	One []float32
	Two time.Duration
}

type Fuzz191 struct {
	One []float32
	Two []time.Duration
}

type Fuzz192 struct {
	One float64
	Two bool
}

type Fuzz193 struct {
	One float64
	Two []bool
}

type Fuzz194 struct {
	One float64
	Two byte
}

type Fuzz195 struct {
	One float64
	Two []byte
}

type Fuzz196 struct {
	One float64
	Two float32
}

type Fuzz197 struct {
	One float64
	Two []float32
}

type Fuzz198 struct {
	One float64
	Two []float64
}

type Fuzz199 struct {
	One float64
	Two int
}

type Fuzz200 struct {
	One float64
	Two int8
}

type Fuzz201 struct {
	One float64
	Two int16
}

type Fuzz202 struct {
	One float64
	Two int32
}

type Fuzz203 struct {
	One float64
	Two rune
}

type Fuzz204 struct {
	One float64
	Two int64
}

type Fuzz205 struct {
	One float64
	Two []int
}

type Fuzz206 struct {
	One float64
	Two []int8
}

type Fuzz207 struct {
	One float64
	Two []int16
}

type Fuzz208 struct {
	One float64
	Two []int32
}

type Fuzz209 struct {
	One float64
	Two []int64
}

type Fuzz210 struct {
	One float64
	Two uint
}

type Fuzz211 struct {
	One float64
	Two uint8
}

type Fuzz212 struct {
	One float64
	Two uint16
}

type Fuzz213 struct {
	One float64
	Two uint32
}

type Fuzz214 struct {
	One float64
	Two uint64
}

type Fuzz215 struct {
	One float64
	Two []uint
}

type Fuzz216 struct {
	One float64
	Two []uint16
}

type Fuzz217 struct {
	One float64
	Two []uint32
}

type Fuzz218 struct {
	One float64
	Two []uint64
}

type Fuzz219 struct {
	One float64
	Two string
}

type Fuzz220 struct {
	One float64
	Two []string
}

type Fuzz221 struct {
	One float64
	Two time.Time
}

type Fuzz222 struct {
	One float64
	Two time.Duration
}

type Fuzz223 struct {
	One float64
	Two []time.Duration
}

type Fuzz224 struct {
	One []float64
	Two bool
}

type Fuzz225 struct {
	One []float64
	Two []bool
}

type Fuzz226 struct {
	One []float64
	Two byte
}

type Fuzz227 struct {
	One []float64
	Two []byte
}

type Fuzz228 struct {
	One []float64
	Two float32
}

type Fuzz229 struct {
	One []float64
	Two []float32
}

type Fuzz230 struct {
	One []float64
	Two float64
}

type Fuzz231 struct {
	One []float64
	Two int
}

type Fuzz232 struct {
	One []float64
	Two int8
}

type Fuzz233 struct {
	One []float64
	Two int16
}

type Fuzz234 struct {
	One []float64
	Two int32
}

type Fuzz235 struct {
	One []float64
	Two rune
}

type Fuzz236 struct {
	One []float64
	Two int64
}

type Fuzz237 struct {
	One []float64
	Two []int
}

type Fuzz238 struct {
	One []float64
	Two []int8
}

type Fuzz239 struct {
	One []float64
	Two []int16
}

type Fuzz240 struct {
	One []float64
	Two []int32
}

type Fuzz241 struct {
	One []float64
	Two []int64
}

type Fuzz242 struct {
	One []float64
	Two uint
}

type Fuzz243 struct {
	One []float64
	Two uint8
}

type Fuzz244 struct {
	One []float64
	Two uint16
}

type Fuzz245 struct {
	One []float64
	Two uint32
}

type Fuzz246 struct {
	One []float64
	Two uint64
}

type Fuzz247 struct {
	One []float64
	Two []uint
}

type Fuzz248 struct {
	One []float64
	Two []uint16
}

type Fuzz249 struct {
	One []float64
	Two []uint32
}

type Fuzz250 struct {
	One []float64
	Two []uint64
}

type Fuzz251 struct {
	One []float64
	Two string
}

type Fuzz252 struct {
	One []float64
	Two []string
}

type Fuzz253 struct {
	One []float64
	Two time.Time
}

type Fuzz254 struct {
	One []float64
	Two time.Duration
}

type Fuzz255 struct {
	One []float64
	Two []time.Duration
}

type Fuzz256 struct {
	One int
	Two bool
}

type Fuzz257 struct {
	One int
	Two []bool
}

type Fuzz258 struct {
	One int
	Two byte
}

type Fuzz259 struct {
	One int
	Two []byte
}

type Fuzz260 struct {
	One int
	Two float32
}

type Fuzz261 struct {
	One int
	Two []float32
}

type Fuzz262 struct {
	One int
	Two float64
}

type Fuzz263 struct {
	One int
	Two []float64
}

type Fuzz264 struct {
	One int
	Two int8
}

type Fuzz265 struct {
	One int
	Two int16
}

type Fuzz266 struct {
	One int
	Two int32
}

type Fuzz267 struct {
	One int
	Two rune
}

type Fuzz268 struct {
	One int
	Two int64
}

type Fuzz269 struct {
	One int
	Two []int
}

type Fuzz270 struct {
	One int
	Two []int8
}

type Fuzz271 struct {
	One int
	Two []int16
}

type Fuzz272 struct {
	One int
	Two []int32
}

type Fuzz273 struct {
	One int
	Two []int64
}

type Fuzz274 struct {
	One int
	Two uint
}

type Fuzz275 struct {
	One int
	Two uint8
}

type Fuzz276 struct {
	One int
	Two uint16
}

type Fuzz277 struct {
	One int
	Two uint32
}

type Fuzz278 struct {
	One int
	Two uint64
}

type Fuzz279 struct {
	One int
	Two []uint
}

type Fuzz280 struct {
	One int
	Two []uint16
}

type Fuzz281 struct {
	One int
	Two []uint32
}

type Fuzz282 struct {
	One int
	Two []uint64
}

type Fuzz283 struct {
	One int
	Two string
}

type Fuzz284 struct {
	One int
	Two []string
}

type Fuzz285 struct {
	One int
	Two time.Time
}

type Fuzz286 struct {
	One int
	Two time.Duration
}

type Fuzz287 struct {
	One int
	Two []time.Duration
}

type Fuzz288 struct {
	One int8
	Two bool
}

type Fuzz289 struct {
	One int8
	Two []bool
}

type Fuzz290 struct {
	One int8
	Two byte
}

type Fuzz291 struct {
	One int8
	Two []byte
}

type Fuzz292 struct {
	One int8
	Two float32
}

type Fuzz293 struct {
	One int8
	Two []float32
}

type Fuzz294 struct {
	One int8
	Two float64
}

type Fuzz295 struct {
	One int8
	Two []float64
}

type Fuzz296 struct {
	One int8
	Two int
}

type Fuzz297 struct {
	One int8
	Two int16
}

type Fuzz298 struct {
	One int8
	Two int32
}

type Fuzz299 struct {
	One int8
	Two rune
}

type Fuzz300 struct {
	One int8
	Two int64
}

type Fuzz301 struct {
	One int8
	Two []int
}

type Fuzz302 struct {
	One int8
	Two []int8
}

type Fuzz303 struct {
	One int8
	Two []int16
}

type Fuzz304 struct {
	One int8
	Two []int32
}

type Fuzz305 struct {
	One int8
	Two []int64
}

type Fuzz306 struct {
	One int8
	Two uint
}

type Fuzz307 struct {
	One int8
	Two uint8
}

type Fuzz308 struct {
	One int8
	Two uint16
}

type Fuzz309 struct {
	One int8
	Two uint32
}

type Fuzz310 struct {
	One int8
	Two uint64
}

type Fuzz311 struct {
	One int8
	Two []uint
}

type Fuzz312 struct {
	One int8
	Two []uint16
}

type Fuzz313 struct {
	One int8
	Two []uint32
}

type Fuzz314 struct {
	One int8
	Two []uint64
}

type Fuzz315 struct {
	One int8
	Two string
}

type Fuzz316 struct {
	One int8
	Two []string
}

type Fuzz317 struct {
	One int8
	Two time.Time
}

type Fuzz318 struct {
	One int8
	Two time.Duration
}

type Fuzz319 struct {
	One int8
	Two []time.Duration
}

type Fuzz320 struct {
	One int16
	Two bool
}

type Fuzz321 struct {
	One int16
	Two []bool
}

type Fuzz322 struct {
	One int16
	Two byte
}

type Fuzz323 struct {
	One int16
	Two []byte
}

type Fuzz324 struct {
	One int16
	Two float32
}

type Fuzz325 struct {
	One int16
	Two []float32
}

type Fuzz326 struct {
	One int16
	Two float64
}

type Fuzz327 struct {
	One int16
	Two []float64
}

type Fuzz328 struct {
	One int16
	Two int
}

type Fuzz329 struct {
	One int16
	Two int8
}

type Fuzz330 struct {
	One int16
	Two int32
}

type Fuzz331 struct {
	One int16
	Two rune
}

type Fuzz332 struct {
	One int16
	Two int64
}

type Fuzz333 struct {
	One int16
	Two []int
}

type Fuzz334 struct {
	One int16
	Two []int8
}

type Fuzz335 struct {
	One int16
	Two []int16
}

type Fuzz336 struct {
	One int16
	Two []int32
}

type Fuzz337 struct {
	One int16
	Two []int64
}

type Fuzz338 struct {
	One int16
	Two uint
}

type Fuzz339 struct {
	One int16
	Two uint8
}

type Fuzz340 struct {
	One int16
	Two uint16
}

type Fuzz341 struct {
	One int16
	Two uint32
}

type Fuzz342 struct {
	One int16
	Two uint64
}

type Fuzz343 struct {
	One int16
	Two []uint
}

type Fuzz344 struct {
	One int16
	Two []uint16
}

type Fuzz345 struct {
	One int16
	Two []uint32
}

type Fuzz346 struct {
	One int16
	Two []uint64
}

type Fuzz347 struct {
	One int16
	Two string
}

type Fuzz348 struct {
	One int16
	Two []string
}

type Fuzz349 struct {
	One int16
	Two time.Time
}

type Fuzz350 struct {
	One int16
	Two time.Duration
}

type Fuzz351 struct {
	One int16
	Two []time.Duration
}

type Fuzz352 struct {
	One int32
	Two bool
}

type Fuzz353 struct {
	One int32
	Two []bool
}

type Fuzz354 struct {
	One int32
	Two byte
}

type Fuzz355 struct {
	One int32
	Two []byte
}

type Fuzz356 struct {
	One int32
	Two float32
}

type Fuzz357 struct {
	One int32
	Two []float32
}

type Fuzz358 struct {
	One int32
	Two float64
}

type Fuzz359 struct {
	One int32
	Two []float64
}

type Fuzz360 struct {
	One int32
	Two int
}

type Fuzz361 struct {
	One int32
	Two int8
}

type Fuzz362 struct {
	One int32
	Two int16
}

type Fuzz363 struct {
	One int32
	Two rune
}

type Fuzz364 struct {
	One int32
	Two int64
}

type Fuzz365 struct {
	One int32
	Two []int
}

type Fuzz366 struct {
	One int32
	Two []int8
}

type Fuzz367 struct {
	One int32
	Two []int16
}

type Fuzz368 struct {
	One int32
	Two []int32
}

type Fuzz369 struct {
	One int32
	Two []int64
}

type Fuzz370 struct {
	One int32
	Two uint
}

type Fuzz371 struct {
	One int32
	Two uint8
}

type Fuzz372 struct {
	One int32
	Two uint16
}

type Fuzz373 struct {
	One int32
	Two uint32
}

type Fuzz374 struct {
	One int32
	Two uint64
}

type Fuzz375 struct {
	One int32
	Two []uint
}

type Fuzz376 struct {
	One int32
	Two []uint16
}

type Fuzz377 struct {
	One int32
	Two []uint32
}

type Fuzz378 struct {
	One int32
	Two []uint64
}

type Fuzz379 struct {
	One int32
	Two string
}

type Fuzz380 struct {
	One int32
	Two []string
}

type Fuzz381 struct {
	One int32
	Two time.Time
}

type Fuzz382 struct {
	One int32
	Two time.Duration
}

type Fuzz383 struct {
	One int32
	Two []time.Duration
}

type Fuzz384 struct {
	One rune
	Two bool
}

type Fuzz385 struct {
	One rune
	Two []bool
}

type Fuzz386 struct {
	One rune
	Two byte
}

type Fuzz387 struct {
	One rune
	Two []byte
}

type Fuzz388 struct {
	One rune
	Two float32
}

type Fuzz389 struct {
	One rune
	Two []float32
}

type Fuzz390 struct {
	One rune
	Two float64
}

type Fuzz391 struct {
	One rune
	Two []float64
}

type Fuzz392 struct {
	One rune
	Two int
}

type Fuzz393 struct {
	One rune
	Two int8
}

type Fuzz394 struct {
	One rune
	Two int16
}

type Fuzz395 struct {
	One rune
	Two int32
}

type Fuzz396 struct {
	One rune
	Two int64
}

type Fuzz397 struct {
	One rune
	Two []int
}

type Fuzz398 struct {
	One rune
	Two []int8
}

type Fuzz399 struct {
	One rune
	Two []int16
}

type Fuzz400 struct {
	One rune
	Two []int32
}

type Fuzz401 struct {
	One rune
	Two []int64
}

type Fuzz402 struct {
	One rune
	Two uint
}

type Fuzz403 struct {
	One rune
	Two uint8
}

type Fuzz404 struct {
	One rune
	Two uint16
}

type Fuzz405 struct {
	One rune
	Two uint32
}

type Fuzz406 struct {
	One rune
	Two uint64
}

type Fuzz407 struct {
	One rune
	Two []uint
}

type Fuzz408 struct {
	One rune
	Two []uint16
}

type Fuzz409 struct {
	One rune
	Two []uint32
}

type Fuzz410 struct {
	One rune
	Two []uint64
}

type Fuzz411 struct {
	One rune
	Two string
}

type Fuzz412 struct {
	One rune
	Two []string
}

type Fuzz413 struct {
	One rune
	Two time.Time
}

type Fuzz414 struct {
	One rune
	Two time.Duration
}

type Fuzz415 struct {
	One rune
	Two []time.Duration
}

type Fuzz416 struct {
	One int64
	Two bool
}

type Fuzz417 struct {
	One int64
	Two []bool
}

type Fuzz418 struct {
	One int64
	Two byte
}

type Fuzz419 struct {
	One int64
	Two []byte
}

type Fuzz420 struct {
	One int64
	Two float32
}

type Fuzz421 struct {
	One int64
	Two []float32
}

type Fuzz422 struct {
	One int64
	Two float64
}

type Fuzz423 struct {
	One int64
	Two []float64
}

type Fuzz424 struct {
	One int64
	Two int
}

type Fuzz425 struct {
	One int64
	Two int8
}

type Fuzz426 struct {
	One int64
	Two int16
}

type Fuzz427 struct {
	One int64
	Two int32
}

type Fuzz428 struct {
	One int64
	Two rune
}

type Fuzz429 struct {
	One int64
	Two []int
}

type Fuzz430 struct {
	One int64
	Two []int8
}

type Fuzz431 struct {
	One int64
	Two []int16
}

type Fuzz432 struct {
	One int64
	Two []int32
}

type Fuzz433 struct {
	One int64
	Two []int64
}

type Fuzz434 struct {
	One int64
	Two uint
}

type Fuzz435 struct {
	One int64
	Two uint8
}

type Fuzz436 struct {
	One int64
	Two uint16
}

type Fuzz437 struct {
	One int64
	Two uint32
}

type Fuzz438 struct {
	One int64
	Two uint64
}

type Fuzz439 struct {
	One int64
	Two []uint
}

type Fuzz440 struct {
	One int64
	Two []uint16
}

type Fuzz441 struct {
	One int64
	Two []uint32
}

type Fuzz442 struct {
	One int64
	Two []uint64
}

type Fuzz443 struct {
	One int64
	Two string
}

type Fuzz444 struct {
	One int64
	Two []string
}

type Fuzz445 struct {
	One int64
	Two time.Time
}

type Fuzz446 struct {
	One int64
	Two time.Duration
}

type Fuzz447 struct {
	One int64
	Two []time.Duration
}

type Fuzz448 struct {
	One []int
	Two bool
}

type Fuzz449 struct {
	One []int
	Two []bool
}

type Fuzz450 struct {
	One []int
	Two byte
}

type Fuzz451 struct {
	One []int
	Two []byte
}

type Fuzz452 struct {
	One []int
	Two float32
}

type Fuzz453 struct {
	One []int
	Two []float32
}

type Fuzz454 struct {
	One []int
	Two float64
}

type Fuzz455 struct {
	One []int
	Two []float64
}

type Fuzz456 struct {
	One []int
	Two int
}

type Fuzz457 struct {
	One []int
	Two int8
}

type Fuzz458 struct {
	One []int
	Two int16
}

type Fuzz459 struct {
	One []int
	Two int32
}

type Fuzz460 struct {
	One []int
	Two rune
}

type Fuzz461 struct {
	One []int
	Two int64
}

type Fuzz462 struct {
	One []int
	Two []int8
}

type Fuzz463 struct {
	One []int
	Two []int16
}

type Fuzz464 struct {
	One []int
	Two []int32
}

type Fuzz465 struct {
	One []int
	Two []int64
}

type Fuzz466 struct {
	One []int
	Two uint
}

type Fuzz467 struct {
	One []int
	Two uint8
}

type Fuzz468 struct {
	One []int
	Two uint16
}

type Fuzz469 struct {
	One []int
	Two uint32
}

type Fuzz470 struct {
	One []int
	Two uint64
}

type Fuzz471 struct {
	One []int
	Two []uint
}

type Fuzz472 struct {
	One []int
	Two []uint16
}

type Fuzz473 struct {
	One []int
	Two []uint32
}

type Fuzz474 struct {
	One []int
	Two []uint64
}

type Fuzz475 struct {
	One []int
	Two string
}

type Fuzz476 struct {
	One []int
	Two []string
}

type Fuzz477 struct {
	One []int
	Two time.Time
}

type Fuzz478 struct {
	One []int
	Two time.Duration
}

type Fuzz479 struct {
	One []int
	Two []time.Duration
}

type Fuzz480 struct {
	One []int8
	Two bool
}

type Fuzz481 struct {
	One []int8
	Two []bool
}

type Fuzz482 struct {
	One []int8
	Two byte
}

type Fuzz483 struct {
	One []int8
	Two []byte
}

type Fuzz484 struct {
	One []int8
	Two float32
}

type Fuzz485 struct {
	One []int8
	Two []float32
}

type Fuzz486 struct {
	One []int8
	Two float64
}

type Fuzz487 struct {
	One []int8
	Two []float64
}

type Fuzz488 struct {
	One []int8
	Two int
}

type Fuzz489 struct {
	One []int8
	Two int8
}

type Fuzz490 struct {
	One []int8
	Two int16
}

type Fuzz491 struct {
	One []int8
	Two int32
}

type Fuzz492 struct {
	One []int8
	Two rune
}

type Fuzz493 struct {
	One []int8
	Two int64
}

type Fuzz494 struct {
	One []int8
	Two []int
}

type Fuzz495 struct {
	One []int8
	Two []int16
}

type Fuzz496 struct {
	One []int8
	Two []int32
}

type Fuzz497 struct {
	One []int8
	Two []int64
}

type Fuzz498 struct {
	One []int8
	Two uint
}

type Fuzz499 struct {
	One []int8
	Two uint8
}

type Fuzz500 struct {
	One []int8
	Two uint16
}

type Fuzz501 struct {
	One []int8
	Two uint32
}

type Fuzz502 struct {
	One []int8
	Two uint64
}

type Fuzz503 struct {
	One []int8
	Two []uint
}

type Fuzz504 struct {
	One []int8
	Two []uint16
}

type Fuzz505 struct {
	One []int8
	Two []uint32
}

type Fuzz506 struct {
	One []int8
	Two []uint64
}

type Fuzz507 struct {
	One []int8
	Two string
}

type Fuzz508 struct {
	One []int8
	Two []string
}

type Fuzz509 struct {
	One []int8
	Two time.Time
}

type Fuzz510 struct {
	One []int8
	Two time.Duration
}

type Fuzz511 struct {
	One []int8
	Two []time.Duration
}

type Fuzz512 struct {
	One []int16
	Two bool
}

type Fuzz513 struct {
	One []int16
	Two []bool
}

type Fuzz514 struct {
	One []int16
	Two byte
}

type Fuzz515 struct {
	One []int16
	Two []byte
}

type Fuzz516 struct {
	One []int16
	Two float32
}

type Fuzz517 struct {
	One []int16
	Two []float32
}

type Fuzz518 struct {
	One []int16
	Two float64
}

type Fuzz519 struct {
	One []int16
	Two []float64
}

type Fuzz520 struct {
	One []int16
	Two int
}

type Fuzz521 struct {
	One []int16
	Two int8
}

type Fuzz522 struct {
	One []int16
	Two int16
}

type Fuzz523 struct {
	One []int16
	Two int32
}

type Fuzz524 struct {
	One []int16
	Two rune
}

type Fuzz525 struct {
	One []int16
	Two int64
}

type Fuzz526 struct {
	One []int16
	Two []int
}

type Fuzz527 struct {
	One []int16
	Two []int8
}

type Fuzz528 struct {
	One []int16
	Two []int32
}

type Fuzz529 struct {
	One []int16
	Two []int64
}

type Fuzz530 struct {
	One []int16
	Two uint
}

type Fuzz531 struct {
	One []int16
	Two uint8
}

type Fuzz532 struct {
	One []int16
	Two uint16
}

type Fuzz533 struct {
	One []int16
	Two uint32
}

type Fuzz534 struct {
	One []int16
	Two uint64
}

type Fuzz535 struct {
	One []int16
	Two []uint
}

type Fuzz536 struct {
	One []int16
	Two []uint16
}

type Fuzz537 struct {
	One []int16
	Two []uint32
}

type Fuzz538 struct {
	One []int16
	Two []uint64
}

type Fuzz539 struct {
	One []int16
	Two string
}

type Fuzz540 struct {
	One []int16
	Two []string
}

type Fuzz541 struct {
	One []int16
	Two time.Time
}

type Fuzz542 struct {
	One []int16
	Two time.Duration
}

type Fuzz543 struct {
	One []int16
	Two []time.Duration
}

type Fuzz544 struct {
	One []int32
	Two bool
}

type Fuzz545 struct {
	One []int32
	Two []bool
}

type Fuzz546 struct {
	One []int32
	Two byte
}

type Fuzz547 struct {
	One []int32
	Two []byte
}

type Fuzz548 struct {
	One []int32
	Two float32
}

type Fuzz549 struct {
	One []int32
	Two []float32
}

type Fuzz550 struct {
	One []int32
	Two float64
}

type Fuzz551 struct {
	One []int32
	Two []float64
}

type Fuzz552 struct {
	One []int32
	Two int
}

type Fuzz553 struct {
	One []int32
	Two int8
}

type Fuzz554 struct {
	One []int32
	Two int16
}

type Fuzz555 struct {
	One []int32
	Two int32
}

type Fuzz556 struct {
	One []int32
	Two rune
}

type Fuzz557 struct {
	One []int32
	Two int64
}

type Fuzz558 struct {
	One []int32
	Two []int
}

type Fuzz559 struct {
	One []int32
	Two []int8
}

type Fuzz560 struct {
	One []int32
	Two []int16
}

type Fuzz561 struct {
	One []int32
	Two []int64
}

type Fuzz562 struct {
	One []int32
	Two uint
}

type Fuzz563 struct {
	One []int32
	Two uint8
}

type Fuzz564 struct {
	One []int32
	Two uint16
}

type Fuzz565 struct {
	One []int32
	Two uint32
}

type Fuzz566 struct {
	One []int32
	Two uint64
}

type Fuzz567 struct {
	One []int32
	Two []uint
}

type Fuzz568 struct {
	One []int32
	Two []uint16
}

type Fuzz569 struct {
	One []int32
	Two []uint32
}

type Fuzz570 struct {
	One []int32
	Two []uint64
}

type Fuzz571 struct {
	One []int32
	Two string
}

type Fuzz572 struct {
	One []int32
	Two []string
}

type Fuzz573 struct {
	One []int32
	Two time.Time
}

type Fuzz574 struct {
	One []int32
	Two time.Duration
}

type Fuzz575 struct {
	One []int32
	Two []time.Duration
}

type Fuzz576 struct {
	One []int64
	Two bool
}

type Fuzz577 struct {
	One []int64
	Two []bool
}

type Fuzz578 struct {
	One []int64
	Two byte
}

type Fuzz579 struct {
	One []int64
	Two []byte
}

type Fuzz580 struct {
	One []int64
	Two float32
}

type Fuzz581 struct {
	One []int64
	Two []float32
}

type Fuzz582 struct {
	One []int64
	Two float64
}

type Fuzz583 struct {
	One []int64
	Two []float64
}

type Fuzz584 struct {
	One []int64
	Two int
}

type Fuzz585 struct {
	One []int64
	Two int8
}

type Fuzz586 struct {
	One []int64
	Two int16
}

type Fuzz587 struct {
	One []int64
	Two int32
}

type Fuzz588 struct {
	One []int64
	Two rune
}

type Fuzz589 struct {
	One []int64
	Two int64
}

type Fuzz590 struct {
	One []int64
	Two []int
}

type Fuzz591 struct {
	One []int64
	Two []int8
}

type Fuzz592 struct {
	One []int64
	Two []int16
}

type Fuzz593 struct {
	One []int64
	Two []int32
}

type Fuzz594 struct {
	One []int64
	Two uint
}

type Fuzz595 struct {
	One []int64
	Two uint8
}

type Fuzz596 struct {
	One []int64
	Two uint16
}

type Fuzz597 struct {
	One []int64
	Two uint32
}

type Fuzz598 struct {
	One []int64
	Two uint64
}

type Fuzz599 struct {
	One []int64
	Two []uint
}

type Fuzz600 struct {
	One []int64
	Two []uint16
}

type Fuzz601 struct {
	One []int64
	Two []uint32
}

type Fuzz602 struct {
	One []int64
	Two []uint64
}

type Fuzz603 struct {
	One []int64
	Two string
}

type Fuzz604 struct {
	One []int64
	Two []string
}

type Fuzz605 struct {
	One []int64
	Two time.Time
}

type Fuzz606 struct {
	One []int64
	Two time.Duration
}

type Fuzz607 struct {
	One []int64
	Two []time.Duration
}

type Fuzz608 struct {
	One uint
	Two bool
}

type Fuzz609 struct {
	One uint
	Two []bool
}

type Fuzz610 struct {
	One uint
	Two byte
}

type Fuzz611 struct {
	One uint
	Two []byte
}

type Fuzz612 struct {
	One uint
	Two float32
}

type Fuzz613 struct {
	One uint
	Two []float32
}

type Fuzz614 struct {
	One uint
	Two float64
}

type Fuzz615 struct {
	One uint
	Two []float64
}

type Fuzz616 struct {
	One uint
	Two int
}

type Fuzz617 struct {
	One uint
	Two int8
}

type Fuzz618 struct {
	One uint
	Two int16
}

type Fuzz619 struct {
	One uint
	Two int32
}

type Fuzz620 struct {
	One uint
	Two rune
}

type Fuzz621 struct {
	One uint
	Two int64
}

type Fuzz622 struct {
	One uint
	Two []int
}

type Fuzz623 struct {
	One uint
	Two []int8
}

type Fuzz624 struct {
	One uint
	Two []int16
}

type Fuzz625 struct {
	One uint
	Two []int32
}

type Fuzz626 struct {
	One uint
	Two []int64
}

type Fuzz627 struct {
	One uint
	Two uint8
}

type Fuzz628 struct {
	One uint
	Two uint16
}

type Fuzz629 struct {
	One uint
	Two uint32
}

type Fuzz630 struct {
	One uint
	Two uint64
}

type Fuzz631 struct {
	One uint
	Two []uint
}

type Fuzz632 struct {
	One uint
	Two []uint16
}

type Fuzz633 struct {
	One uint
	Two []uint32
}

type Fuzz634 struct {
	One uint
	Two []uint64
}

type Fuzz635 struct {
	One uint
	Two string
}

type Fuzz636 struct {
	One uint
	Two []string
}

type Fuzz637 struct {
	One uint
	Two time.Time
}

type Fuzz638 struct {
	One uint
	Two time.Duration
}

type Fuzz639 struct {
	One uint
	Two []time.Duration
}

type Fuzz640 struct {
	One uint8
	Two bool
}

type Fuzz641 struct {
	One uint8
	Two []bool
}

type Fuzz642 struct {
	One uint8
	Two byte
}

type Fuzz643 struct {
	One uint8
	Two []byte
}

type Fuzz644 struct {
	One uint8
	Two float32
}

type Fuzz645 struct {
	One uint8
	Two []float32
}

type Fuzz646 struct {
	One uint8
	Two float64
}

type Fuzz647 struct {
	One uint8
	Two []float64
}

type Fuzz648 struct {
	One uint8
	Two int
}

type Fuzz649 struct {
	One uint8
	Two int8
}

type Fuzz650 struct {
	One uint8
	Two int16
}

type Fuzz651 struct {
	One uint8
	Two int32
}

type Fuzz652 struct {
	One uint8
	Two rune
}

type Fuzz653 struct {
	One uint8
	Two int64
}

type Fuzz654 struct {
	One uint8
	Two []int
}

type Fuzz655 struct {
	One uint8
	Two []int8
}

type Fuzz656 struct {
	One uint8
	Two []int16
}

type Fuzz657 struct {
	One uint8
	Two []int32
}

type Fuzz658 struct {
	One uint8
	Two []int64
}

type Fuzz659 struct {
	One uint8
	Two uint
}

type Fuzz660 struct {
	One uint8
	Two uint16
}

type Fuzz661 struct {
	One uint8
	Two uint32
}

type Fuzz662 struct {
	One uint8
	Two uint64
}

type Fuzz663 struct {
	One uint8
	Two []uint
}

type Fuzz664 struct {
	One uint8
	Two []uint16
}

type Fuzz665 struct {
	One uint8
	Two []uint32
}

type Fuzz666 struct {
	One uint8
	Two []uint64
}

type Fuzz667 struct {
	One uint8
	Two string
}

type Fuzz668 struct {
	One uint8
	Two []string
}

type Fuzz669 struct {
	One uint8
	Two time.Time
}

type Fuzz670 struct {
	One uint8
	Two time.Duration
}

type Fuzz671 struct {
	One uint8
	Two []time.Duration
}

type Fuzz672 struct {
	One uint16
	Two bool
}

type Fuzz673 struct {
	One uint16
	Two []bool
}

type Fuzz674 struct {
	One uint16
	Two byte
}

type Fuzz675 struct {
	One uint16
	Two []byte
}

type Fuzz676 struct {
	One uint16
	Two float32
}

type Fuzz677 struct {
	One uint16
	Two []float32
}

type Fuzz678 struct {
	One uint16
	Two float64
}

type Fuzz679 struct {
	One uint16
	Two []float64
}

type Fuzz680 struct {
	One uint16
	Two int
}

type Fuzz681 struct {
	One uint16
	Two int8
}

type Fuzz682 struct {
	One uint16
	Two int16
}

type Fuzz683 struct {
	One uint16
	Two int32
}

type Fuzz684 struct {
	One uint16
	Two rune
}

type Fuzz685 struct {
	One uint16
	Two int64
}

type Fuzz686 struct {
	One uint16
	Two []int
}

type Fuzz687 struct {
	One uint16
	Two []int8
}

type Fuzz688 struct {
	One uint16
	Two []int16
}

type Fuzz689 struct {
	One uint16
	Two []int32
}

type Fuzz690 struct {
	One uint16
	Two []int64
}

type Fuzz691 struct {
	One uint16
	Two uint
}

type Fuzz692 struct {
	One uint16
	Two uint8
}

type Fuzz693 struct {
	One uint16
	Two uint32
}

type Fuzz694 struct {
	One uint16
	Two uint64
}

type Fuzz695 struct {
	One uint16
	Two []uint
}

type Fuzz696 struct {
	One uint16
	Two []uint16
}

type Fuzz697 struct {
	One uint16
	Two []uint32
}

type Fuzz698 struct {
	One uint16
	Two []uint64
}

type Fuzz699 struct {
	One uint16
	Two string
}

type Fuzz700 struct {
	One uint16
	Two []string
}

type Fuzz701 struct {
	One uint16
	Two time.Time
}

type Fuzz702 struct {
	One uint16
	Two time.Duration
}

type Fuzz703 struct {
	One uint16
	Two []time.Duration
}

type Fuzz704 struct {
	One uint32
	Two bool
}

type Fuzz705 struct {
	One uint32
	Two []bool
}

type Fuzz706 struct {
	One uint32
	Two byte
}

type Fuzz707 struct {
	One uint32
	Two []byte
}

type Fuzz708 struct {
	One uint32
	Two float32
}

type Fuzz709 struct {
	One uint32
	Two []float32
}

type Fuzz710 struct {
	One uint32
	Two float64
}

type Fuzz711 struct {
	One uint32
	Two []float64
}

type Fuzz712 struct {
	One uint32
	Two int
}

type Fuzz713 struct {
	One uint32
	Two int8
}

type Fuzz714 struct {
	One uint32
	Two int16
}

type Fuzz715 struct {
	One uint32
	Two int32
}

type Fuzz716 struct {
	One uint32
	Two rune
}

type Fuzz717 struct {
	One uint32
	Two int64
}

type Fuzz718 struct {
	One uint32
	Two []int
}

type Fuzz719 struct {
	One uint32
	Two []int8
}

type Fuzz720 struct {
	One uint32
	Two []int16
}

type Fuzz721 struct {
	One uint32
	Two []int32
}

type Fuzz722 struct {
	One uint32
	Two []int64
}

type Fuzz723 struct {
	One uint32
	Two uint
}

type Fuzz724 struct {
	One uint32
	Two uint8
}

type Fuzz725 struct {
	One uint32
	Two uint16
}

type Fuzz726 struct {
	One uint32
	Two uint64
}

type Fuzz727 struct {
	One uint32
	Two []uint
}

type Fuzz728 struct {
	One uint32
	Two []uint16
}

type Fuzz729 struct {
	One uint32
	Two []uint32
}

type Fuzz730 struct {
	One uint32
	Two []uint64
}

type Fuzz731 struct {
	One uint32
	Two string
}

type Fuzz732 struct {
	One uint32
	Two []string
}

type Fuzz733 struct {
	One uint32
	Two time.Time
}

type Fuzz734 struct {
	One uint32
	Two time.Duration
}

type Fuzz735 struct {
	One uint32
	Two []time.Duration
}

type Fuzz736 struct {
	One uint64
	Two bool
}

type Fuzz737 struct {
	One uint64
	Two []bool
}

type Fuzz738 struct {
	One uint64
	Two byte
}

type Fuzz739 struct {
	One uint64
	Two []byte
}

type Fuzz740 struct {
	One uint64
	Two float32
}

type Fuzz741 struct {
	One uint64
	Two []float32
}

type Fuzz742 struct {
	One uint64
	Two float64
}

type Fuzz743 struct {
	One uint64
	Two []float64
}

type Fuzz744 struct {
	One uint64
	Two int
}

type Fuzz745 struct {
	One uint64
	Two int8
}

type Fuzz746 struct {
	One uint64
	Two int16
}

type Fuzz747 struct {
	One uint64
	Two int32
}

type Fuzz748 struct {
	One uint64
	Two rune
}

type Fuzz749 struct {
	One uint64
	Two int64
}

type Fuzz750 struct {
	One uint64
	Two []int
}

type Fuzz751 struct {
	One uint64
	Two []int8
}

type Fuzz752 struct {
	One uint64
	Two []int16
}

type Fuzz753 struct {
	One uint64
	Two []int32
}

type Fuzz754 struct {
	One uint64
	Two []int64
}

type Fuzz755 struct {
	One uint64
	Two uint
}

type Fuzz756 struct {
	One uint64
	Two uint8
}

type Fuzz757 struct {
	One uint64
	Two uint16
}

type Fuzz758 struct {
	One uint64
	Two uint32
}

type Fuzz759 struct {
	One uint64
	Two []uint
}

type Fuzz760 struct {
	One uint64
	Two []uint16
}

type Fuzz761 struct {
	One uint64
	Two []uint32
}

type Fuzz762 struct {
	One uint64
	Two []uint64
}

type Fuzz763 struct {
	One uint64
	Two string
}

type Fuzz764 struct {
	One uint64
	Two []string
}

type Fuzz765 struct {
	One uint64
	Two time.Time
}

type Fuzz766 struct {
	One uint64
	Two time.Duration
}

type Fuzz767 struct {
	One uint64
	Two []time.Duration
}

type Fuzz768 struct {
	One []uint
	Two bool
}

type Fuzz769 struct {
	One []uint
	Two []bool
}

type Fuzz770 struct {
	One []uint
	Two byte
}

type Fuzz771 struct {
	One []uint
	Two []byte
}

type Fuzz772 struct {
	One []uint
	Two float32
}

type Fuzz773 struct {
	One []uint
	Two []float32
}

type Fuzz774 struct {
	One []uint
	Two float64
}

type Fuzz775 struct {
	One []uint
	Two []float64
}

type Fuzz776 struct {
	One []uint
	Two int
}

type Fuzz777 struct {
	One []uint
	Two int8
}

type Fuzz778 struct {
	One []uint
	Two int16
}

type Fuzz779 struct {
	One []uint
	Two int32
}

type Fuzz780 struct {
	One []uint
	Two rune
}

type Fuzz781 struct {
	One []uint
	Two int64
}

type Fuzz782 struct {
	One []uint
	Two []int
}

type Fuzz783 struct {
	One []uint
	Two []int8
}

type Fuzz784 struct {
	One []uint
	Two []int16
}

type Fuzz785 struct {
	One []uint
	Two []int32
}

type Fuzz786 struct {
	One []uint
	Two []int64
}

type Fuzz787 struct {
	One []uint
	Two uint
}

type Fuzz788 struct {
	One []uint
	Two uint8
}

type Fuzz789 struct {
	One []uint
	Two uint16
}

type Fuzz790 struct {
	One []uint
	Two uint32
}

type Fuzz791 struct {
	One []uint
	Two uint64
}

type Fuzz792 struct {
	One []uint
	Two []uint16
}

type Fuzz793 struct {
	One []uint
	Two []uint32
}

type Fuzz794 struct {
	One []uint
	Two []uint64
}

type Fuzz795 struct {
	One []uint
	Two string
}

type Fuzz796 struct {
	One []uint
	Two []string
}

type Fuzz797 struct {
	One []uint
	Two time.Time
}

type Fuzz798 struct {
	One []uint
	Two time.Duration
}

type Fuzz799 struct {
	One []uint
	Two []time.Duration
}

type Fuzz800 struct {
	One []uint16
	Two bool
}

type Fuzz801 struct {
	One []uint16
	Two []bool
}

type Fuzz802 struct {
	One []uint16
	Two byte
}

type Fuzz803 struct {
	One []uint16
	Two []byte
}

type Fuzz804 struct {
	One []uint16
	Two float32
}

type Fuzz805 struct {
	One []uint16
	Two []float32
}

type Fuzz806 struct {
	One []uint16
	Two float64
}

type Fuzz807 struct {
	One []uint16
	Two []float64
}

type Fuzz808 struct {
	One []uint16
	Two int
}

type Fuzz809 struct {
	One []uint16
	Two int8
}

type Fuzz810 struct {
	One []uint16
	Two int16
}

type Fuzz811 struct {
	One []uint16
	Two int32
}

type Fuzz812 struct {
	One []uint16
	Two rune
}

type Fuzz813 struct {
	One []uint16
	Two int64
}

type Fuzz814 struct {
	One []uint16
	Two []int
}

type Fuzz815 struct {
	One []uint16
	Two []int8
}

type Fuzz816 struct {
	One []uint16
	Two []int16
}

type Fuzz817 struct {
	One []uint16
	Two []int32
}

type Fuzz818 struct {
	One []uint16
	Two []int64
}

type Fuzz819 struct {
	One []uint16
	Two uint
}

type Fuzz820 struct {
	One []uint16
	Two uint8
}

type Fuzz821 struct {
	One []uint16
	Two uint16
}

type Fuzz822 struct {
	One []uint16
	Two uint32
}

type Fuzz823 struct {
	One []uint16
	Two uint64
}

type Fuzz824 struct {
	One []uint16
	Two []uint
}

type Fuzz825 struct {
	One []uint16
	Two []uint32
}

type Fuzz826 struct {
	One []uint16
	Two []uint64
}

type Fuzz827 struct {
	One []uint16
	Two string
}

type Fuzz828 struct {
	One []uint16
	Two []string
}

type Fuzz829 struct {
	One []uint16
	Two time.Time
}

type Fuzz830 struct {
	One []uint16
	Two time.Duration
}

type Fuzz831 struct {
	One []uint16
	Two []time.Duration
}

type Fuzz832 struct {
	One []uint32
	Two bool
}

type Fuzz833 struct {
	One []uint32
	Two []bool
}

type Fuzz834 struct {
	One []uint32
	Two byte
}

type Fuzz835 struct {
	One []uint32
	Two []byte
}

type Fuzz836 struct {
	One []uint32
	Two float32
}

type Fuzz837 struct {
	One []uint32
	Two []float32
}

type Fuzz838 struct {
	One []uint32
	Two float64
}

type Fuzz839 struct {
	One []uint32
	Two []float64
}

type Fuzz840 struct {
	One []uint32
	Two int
}

type Fuzz841 struct {
	One []uint32
	Two int8
}

type Fuzz842 struct {
	One []uint32
	Two int16
}

type Fuzz843 struct {
	One []uint32
	Two int32
}

type Fuzz844 struct {
	One []uint32
	Two rune
}

type Fuzz845 struct {
	One []uint32
	Two int64
}

type Fuzz846 struct {
	One []uint32
	Two []int
}

type Fuzz847 struct {
	One []uint32
	Two []int8
}

type Fuzz848 struct {
	One []uint32
	Two []int16
}

type Fuzz849 struct {
	One []uint32
	Two []int32
}

type Fuzz850 struct {
	One []uint32
	Two []int64
}

type Fuzz851 struct {
	One []uint32
	Two uint
}

type Fuzz852 struct {
	One []uint32
	Two uint8
}

type Fuzz853 struct {
	One []uint32
	Two uint16
}

type Fuzz854 struct {
	One []uint32
	Two uint32
}

type Fuzz855 struct {
	One []uint32
	Two uint64
}

type Fuzz856 struct {
	One []uint32
	Two []uint
}

type Fuzz857 struct {
	One []uint32
	Two []uint16
}

type Fuzz858 struct {
	One []uint32
	Two []uint64
}

type Fuzz859 struct {
	One []uint32
	Two string
}

type Fuzz860 struct {
	One []uint32
	Two []string
}

type Fuzz861 struct {
	One []uint32
	Two time.Time
}

type Fuzz862 struct {
	One []uint32
	Two time.Duration
}

type Fuzz863 struct {
	One []uint32
	Two []time.Duration
}

type Fuzz864 struct {
	One []uint64
	Two bool
}

type Fuzz865 struct {
	One []uint64
	Two []bool
}

type Fuzz866 struct {
	One []uint64
	Two byte
}

type Fuzz867 struct {
	One []uint64
	Two []byte
}

type Fuzz868 struct {
	One []uint64
	Two float32
}

type Fuzz869 struct {
	One []uint64
	Two []float32
}

type Fuzz870 struct {
	One []uint64
	Two float64
}

type Fuzz871 struct {
	One []uint64
	Two []float64
}

type Fuzz872 struct {
	One []uint64
	Two int
}

type Fuzz873 struct {
	One []uint64
	Two int8
}

type Fuzz874 struct {
	One []uint64
	Two int16
}

type Fuzz875 struct {
	One []uint64
	Two int32
}

type Fuzz876 struct {
	One []uint64
	Two rune
}

type Fuzz877 struct {
	One []uint64
	Two int64
}

type Fuzz878 struct {
	One []uint64
	Two []int
}

type Fuzz879 struct {
	One []uint64
	Two []int8
}

type Fuzz880 struct {
	One []uint64
	Two []int16
}

type Fuzz881 struct {
	One []uint64
	Two []int32
}

type Fuzz882 struct {
	One []uint64
	Two []int64
}

type Fuzz883 struct {
	One []uint64
	Two uint
}

type Fuzz884 struct {
	One []uint64
	Two uint8
}

type Fuzz885 struct {
	One []uint64
	Two uint16
}

type Fuzz886 struct {
	One []uint64
	Two uint32
}

type Fuzz887 struct {
	One []uint64
	Two uint64
}

type Fuzz888 struct {
	One []uint64
	Two []uint
}

type Fuzz889 struct {
	One []uint64
	Two []uint16
}

type Fuzz890 struct {
	One []uint64
	Two []uint32
}

type Fuzz891 struct {
	One []uint64
	Two string
}

type Fuzz892 struct {
	One []uint64
	Two []string
}

type Fuzz893 struct {
	One []uint64
	Two time.Time
}

type Fuzz894 struct {
	One []uint64
	Two time.Duration
}

type Fuzz895 struct {
	One []uint64
	Two []time.Duration
}

type Fuzz896 struct {
	One string
	Two bool
}

type Fuzz897 struct {
	One string
	Two []bool
}

type Fuzz898 struct {
	One string
	Two byte
}

type Fuzz899 struct {
	One string
	Two []byte
}

type Fuzz900 struct {
	One string
	Two float32
}

type Fuzz901 struct {
	One string
	Two []float32
}

type Fuzz902 struct {
	One string
	Two float64
}

type Fuzz903 struct {
	One string
	Two []float64
}

type Fuzz904 struct {
	One string
	Two int
}

type Fuzz905 struct {
	One string
	Two int8
}

type Fuzz906 struct {
	One string
	Two int16
}

type Fuzz907 struct {
	One string
	Two int32
}

type Fuzz908 struct {
	One string
	Two rune
}

type Fuzz909 struct {
	One string
	Two int64
}

type Fuzz910 struct {
	One string
	Two []int
}

type Fuzz911 struct {
	One string
	Two []int8
}

type Fuzz912 struct {
	One string
	Two []int16
}

type Fuzz913 struct {
	One string
	Two []int32
}

type Fuzz914 struct {
	One string
	Two []int64
}

type Fuzz915 struct {
	One string
	Two uint
}

type Fuzz916 struct {
	One string
	Two uint8
}

type Fuzz917 struct {
	One string
	Two uint16
}

type Fuzz918 struct {
	One string
	Two uint32
}

type Fuzz919 struct {
	One string
	Two uint64
}

type Fuzz920 struct {
	One string
	Two []uint
}

type Fuzz921 struct {
	One string
	Two []uint16
}

type Fuzz922 struct {
	One string
	Two []uint32
}

type Fuzz923 struct {
	One string
	Two []uint64
}

type Fuzz924 struct {
	One string
	Two []string
}

type Fuzz925 struct {
	One string
	Two time.Time
}

type Fuzz926 struct {
	One string
	Two time.Duration
}

type Fuzz927 struct {
	One string
	Two []time.Duration
}

type Fuzz928 struct {
	One []string
	Two bool
}

type Fuzz929 struct {
	One []string
	Two []bool
}

type Fuzz930 struct {
	One []string
	Two byte
}

type Fuzz931 struct {
	One []string
	Two []byte
}

type Fuzz932 struct {
	One []string
	Two float32
}

type Fuzz933 struct {
	One []string
	Two []float32
}

type Fuzz934 struct {
	One []string
	Two float64
}

type Fuzz935 struct {
	One []string
	Two []float64
}

type Fuzz936 struct {
	One []string
	Two int
}

type Fuzz937 struct {
	One []string
	Two int8
}

type Fuzz938 struct {
	One []string
	Two int16
}

type Fuzz939 struct {
	One []string
	Two int32
}

type Fuzz940 struct {
	One []string
	Two rune
}

type Fuzz941 struct {
	One []string
	Two int64
}

type Fuzz942 struct {
	One []string
	Two []int
}

type Fuzz943 struct {
	One []string
	Two []int8
}

type Fuzz944 struct {
	One []string
	Two []int16
}

type Fuzz945 struct {
	One []string
	Two []int32
}

type Fuzz946 struct {
	One []string
	Two []int64
}

type Fuzz947 struct {
	One []string
	Two uint
}

type Fuzz948 struct {
	One []string
	Two uint8
}

type Fuzz949 struct {
	One []string
	Two uint16
}

type Fuzz950 struct {
	One []string
	Two uint32
}

type Fuzz951 struct {
	One []string
	Two uint64
}

type Fuzz952 struct {
	One []string
	Two []uint
}

type Fuzz953 struct {
	One []string
	Two []uint16
}

type Fuzz954 struct {
	One []string
	Two []uint32
}

type Fuzz955 struct {
	One []string
	Two []uint64
}

type Fuzz956 struct {
	One []string
	Two string
}

type Fuzz957 struct {
	One []string
	Two time.Time
}

type Fuzz958 struct {
	One []string
	Two time.Duration
}

type Fuzz959 struct {
	One []string
	Two []time.Duration
}

type Fuzz960 struct {
	One time.Time
	Two bool
}

type Fuzz961 struct {
	One time.Time
	Two []bool
}

type Fuzz962 struct {
	One time.Time
	Two byte
}

type Fuzz963 struct {
	One time.Time
	Two []byte
}

type Fuzz964 struct {
	One time.Time
	Two float32
}

type Fuzz965 struct {
	One time.Time
	Two []float32
}

type Fuzz966 struct {
	One time.Time
	Two float64
}

type Fuzz967 struct {
	One time.Time
	Two []float64
}

type Fuzz968 struct {
	One time.Time
	Two int
}

type Fuzz969 struct {
	One time.Time
	Two int8
}

type Fuzz970 struct {
	One time.Time
	Two int16
}

type Fuzz971 struct {
	One time.Time
	Two int32
}

type Fuzz972 struct {
	One time.Time
	Two rune
}

type Fuzz973 struct {
	One time.Time
	Two int64
}

type Fuzz974 struct {
	One time.Time
	Two []int
}

type Fuzz975 struct {
	One time.Time
	Two []int8
}

type Fuzz976 struct {
	One time.Time
	Two []int16
}

type Fuzz977 struct {
	One time.Time
	Two []int32
}

type Fuzz978 struct {
	One time.Time
	Two []int64
}

type Fuzz979 struct {
	One time.Time
	Two uint
}

type Fuzz980 struct {
	One time.Time
	Two uint8
}

type Fuzz981 struct {
	One time.Time
	Two uint16
}

type Fuzz982 struct {
	One time.Time
	Two uint32
}

type Fuzz983 struct {
	One time.Time
	Two uint64
}

type Fuzz984 struct {
	One time.Time
	Two []uint
}

type Fuzz985 struct {
	One time.Time
	Two []uint16
}

type Fuzz986 struct {
	One time.Time
	Two []uint32
}

type Fuzz987 struct {
	One time.Time
	Two []uint64
}

type Fuzz988 struct {
	One time.Time
	Two string
}

type Fuzz989 struct {
	One time.Time
	Two []string
}

type Fuzz990 struct {
	One time.Time
	Two time.Duration
}

type Fuzz991 struct {
	One time.Time
	Two []time.Duration
}

type Fuzz992 struct {
	One time.Duration
	Two bool
}

type Fuzz993 struct {
	One time.Duration
	Two []bool
}

type Fuzz994 struct {
	One time.Duration
	Two byte
}

type Fuzz995 struct {
	One time.Duration
	Two []byte
}

type Fuzz996 struct {
	One time.Duration
	Two float32
}

type Fuzz997 struct {
	One time.Duration
	Two []float32
}

type Fuzz998 struct {
	One time.Duration
	Two float64
}

type Fuzz999 struct {
	One time.Duration
	Two []float64
}

type Fuzz1000 struct {
	One time.Duration
	Two int
}

type Fuzz1001 struct {
	One time.Duration
	Two int8
}

type Fuzz1002 struct {
	One time.Duration
	Two int16
}

type Fuzz1003 struct {
	One time.Duration
	Two int32
}

type Fuzz1004 struct {
	One time.Duration
	Two rune
}

type Fuzz1005 struct {
	One time.Duration
	Two int64
}

type Fuzz1006 struct {
	One time.Duration
	Two []int
}

type Fuzz1007 struct {
	One time.Duration
	Two []int8
}

type Fuzz1008 struct {
	One time.Duration
	Two []int16
}

type Fuzz1009 struct {
	One time.Duration
	Two []int32
}

type Fuzz1010 struct {
	One time.Duration
	Two []int64
}

type Fuzz1011 struct {
	One time.Duration
	Two uint
}

type Fuzz1012 struct {
	One time.Duration
	Two uint8
}

type Fuzz1013 struct {
	One time.Duration
	Two uint16
}

type Fuzz1014 struct {
	One time.Duration
	Two uint32
}

type Fuzz1015 struct {
	One time.Duration
	Two uint64
}

type Fuzz1016 struct {
	One time.Duration
	Two []uint
}

type Fuzz1017 struct {
	One time.Duration
	Two []uint16
}

type Fuzz1018 struct {
	One time.Duration
	Two []uint32
}

type Fuzz1019 struct {
	One time.Duration
	Two []uint64
}

type Fuzz1020 struct {
	One time.Duration
	Two string
}

type Fuzz1021 struct {
	One time.Duration
	Two []string
}

type Fuzz1022 struct {
	One time.Duration
	Two time.Time
}

type Fuzz1023 struct {
	One time.Duration
	Two []time.Duration
}

type Fuzz1024 struct {
	One []time.Duration
	Two bool
}

type Fuzz1025 struct {
	One []time.Duration
	Two []bool
}

type Fuzz1026 struct {
	One []time.Duration
	Two byte
}

type Fuzz1027 struct {
	One []time.Duration
	Two []byte
}

type Fuzz1028 struct {
	One []time.Duration
	Two float32
}

type Fuzz1029 struct {
	One []time.Duration
	Two []float32
}

type Fuzz1030 struct {
	One []time.Duration
	Two float64
}

type Fuzz1031 struct {
	One []time.Duration
	Two []float64
}

type Fuzz1032 struct {
	One []time.Duration
	Two int
}

type Fuzz1033 struct {
	One []time.Duration
	Two int8
}

type Fuzz1034 struct {
	One []time.Duration
	Two int16
}

type Fuzz1035 struct {
	One []time.Duration
	Two int32
}

type Fuzz1036 struct {
	One []time.Duration
	Two rune
}

type Fuzz1037 struct {
	One []time.Duration
	Two int64
}

type Fuzz1038 struct {
	One []time.Duration
	Two []int
}

type Fuzz1039 struct {
	One []time.Duration
	Two []int8
}

type Fuzz1040 struct {
	One []time.Duration
	Two []int16
}

type Fuzz1041 struct {
	One []time.Duration
	Two []int32
}

type Fuzz1042 struct {
	One []time.Duration
	Two []int64
}

type Fuzz1043 struct {
	One []time.Duration
	Two uint
}

type Fuzz1044 struct {
	One []time.Duration
	Two uint8
}

type Fuzz1045 struct {
	One []time.Duration
	Two uint16
}

type Fuzz1046 struct {
	One []time.Duration
	Two uint32
}

type Fuzz1047 struct {
	One []time.Duration
	Two uint64
}

type Fuzz1048 struct {
	One []time.Duration
	Two []uint
}

type Fuzz1049 struct {
	One []time.Duration
	Two []uint16
}

type Fuzz1050 struct {
	One []time.Duration
	Two []uint32
}

type Fuzz1051 struct {
	One []time.Duration
	Two []uint64
}

type Fuzz1052 struct {
	One []time.Duration
	Two string
}

type Fuzz1053 struct {
	One []time.Duration
	Two []string
}

type Fuzz1054 struct {
	One []time.Duration
	Two time.Time
}

type Fuzz1055 struct {
	One []time.Duration
	Two time.Duration
}
