// Code generated by testdata/fuzz_test; DO NOT EDIT.

package main

type One struct {
	One [6]rune
}

type Two struct {
	One [6]rune
	Two [6]rune
}

type Three struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
}

type Four struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
}

type Five struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
	Five  [6]rune
}

type Six struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
	Five  [6]rune
	Six   [6]rune
}

type Seven struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
	Five  [6]rune
	Six   [6]rune
	Seven [6]rune
}

type Eight struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
	Five  [6]rune
	Six   [6]rune
	Seven [6]rune
	Eight [6]rune
}

type Nine struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
	Five  [6]rune
	Six   [6]rune
	Seven [6]rune
	Eight [6]rune
	Nine  [6]rune
}

type Ten struct {
	One   [6]rune
	Two   [6]rune
	Three [6]rune
	Four  [6]rune
	Five  [6]rune
	Six   [6]rune
	Seven [6]rune
	Eight [6]rune
	Nine  [6]rune
	Ten   [6]rune
}

type Eleven struct {
	One    [6]rune
	Two    [6]rune
	Three  [6]rune
	Four   [6]rune
	Five   [6]rune
	Six    [6]rune
	Seven  [6]rune
	Eight  [6]rune
	Nine   [6]rune
	Ten    [6]rune
	Eleven [6]rune
}

type Twelve struct {
	One    [6]rune
	Two    [6]rune
	Three  [6]rune
	Four   [6]rune
	Five   [6]rune
	Six    [6]rune
	Seven  [6]rune
	Eight  [6]rune
	Nine   [6]rune
	Ten    [6]rune
	Eleven [6]rune
	Twelve [6]rune
}

type Thirteen struct {
	One      [6]rune
	Two      [6]rune
	Three    [6]rune
	Four     [6]rune
	Five     [6]rune
	Six      [6]rune
	Seven    [6]rune
	Eight    [6]rune
	Nine     [6]rune
	Ten      [6]rune
	Eleven   [6]rune
	Twelve   [6]rune
	Thirteen [6]rune
}

type Fourteen struct {
	One      [6]rune
	Two      [6]rune
	Three    [6]rune
	Four     [6]rune
	Five     [6]rune
	Six      [6]rune
	Seven    [6]rune
	Eight    [6]rune
	Nine     [6]rune
	Ten      [6]rune
	Eleven   [6]rune
	Twelve   [6]rune
	Thirteen [6]rune
	Fourteen [6]rune
}

type Fifteen struct {
	One      [6]rune
	Two      [6]rune
	Three    [6]rune
	Four     [6]rune
	Five     [6]rune
	Six      [6]rune
	Seven    [6]rune
	Eight    [6]rune
	Nine     [6]rune
	Ten      [6]rune
	Eleven   [6]rune
	Twelve   [6]rune
	Thirteen [6]rune
	Fourteen [6]rune
	Fifteen  [6]rune
}

type Sixteen struct {
	One      [6]rune
	Two      [6]rune
	Three    [6]rune
	Four     [6]rune
	Five     [6]rune
	Six      [6]rune
	Seven    [6]rune
	Eight    [6]rune
	Nine     [6]rune
	Ten      [6]rune
	Eleven   [6]rune
	Twelve   [6]rune
	Thirteen [6]rune
	Fourteen [6]rune
	Fifteen  [6]rune
	Sixteen  [6]rune
}

type Seventeen struct {
	One       [6]rune
	Two       [6]rune
	Three     [6]rune
	Four      [6]rune
	Five      [6]rune
	Six       [6]rune
	Seven     [6]rune
	Eight     [6]rune
	Nine      [6]rune
	Ten       [6]rune
	Eleven    [6]rune
	Twelve    [6]rune
	Thirteen  [6]rune
	Fourteen  [6]rune
	Fifteen   [6]rune
	Sixteen   [6]rune
	Seventeen [6]rune
}

type Eighteen struct {
	One       [6]rune
	Two       [6]rune
	Three     [6]rune
	Four      [6]rune
	Five      [6]rune
	Six       [6]rune
	Seven     [6]rune
	Eight     [6]rune
	Nine      [6]rune
	Ten       [6]rune
	Eleven    [6]rune
	Twelve    [6]rune
	Thirteen  [6]rune
	Fourteen  [6]rune
	Fifteen   [6]rune
	Sixteen   [6]rune
	Seventeen [6]rune
	Eighteen  [6]rune
}

type Nineteen struct {
	One       [6]rune
	Two       [6]rune
	Three     [6]rune
	Four      [6]rune
	Five      [6]rune
	Six       [6]rune
	Seven     [6]rune
	Eight     [6]rune
	Nine      [6]rune
	Ten       [6]rune
	Eleven    [6]rune
	Twelve    [6]rune
	Thirteen  [6]rune
	Fourteen  [6]rune
	Fifteen   [6]rune
	Sixteen   [6]rune
	Seventeen [6]rune
	Eighteen  [6]rune
	Nineteen  [6]rune
}

type Twenty struct {
	One       [6]rune
	Two       [6]rune
	Three     [6]rune
	Four      [6]rune
	Five      [6]rune
	Six       [6]rune
	Seven     [6]rune
	Eight     [6]rune
	Nine      [6]rune
	Ten       [6]rune
	Eleven    [6]rune
	Twelve    [6]rune
	Thirteen  [6]rune
	Fourteen  [6]rune
	Fifteen   [6]rune
	Sixteen   [6]rune
	Seventeen [6]rune
	Eighteen  [6]rune
	Nineteen  [6]rune
	Twenty    [6]rune
}

type TwentyOne struct {
	One       [6]rune
	Two       [6]rune
	Three     [6]rune
	Four      [6]rune
	Five      [6]rune
	Six       [6]rune
	Seven     [6]rune
	Eight     [6]rune
	Nine      [6]rune
	Ten       [6]rune
	Eleven    [6]rune
	Twelve    [6]rune
	Thirteen  [6]rune
	Fourteen  [6]rune
	Fifteen   [6]rune
	Sixteen   [6]rune
	Seventeen [6]rune
	Eighteen  [6]rune
	Nineteen  [6]rune
	Twenty    [6]rune
	TwentyOne [6]rune
}

type TwentyTwo struct {
	One       [6]rune
	Two       [6]rune
	Three     [6]rune
	Four      [6]rune
	Five      [6]rune
	Six       [6]rune
	Seven     [6]rune
	Eight     [6]rune
	Nine      [6]rune
	Ten       [6]rune
	Eleven    [6]rune
	Twelve    [6]rune
	Thirteen  [6]rune
	Fourteen  [6]rune
	Fifteen   [6]rune
	Sixteen   [6]rune
	Seventeen [6]rune
	Eighteen  [6]rune
	Nineteen  [6]rune
	Twenty    [6]rune
	TwentyOne [6]rune
	TwentyTwo [6]rune
}

type TwentyThree struct {
	One         [6]rune
	Two         [6]rune
	Three       [6]rune
	Four        [6]rune
	Five        [6]rune
	Six         [6]rune
	Seven       [6]rune
	Eight       [6]rune
	Nine        [6]rune
	Ten         [6]rune
	Eleven      [6]rune
	Twelve      [6]rune
	Thirteen    [6]rune
	Fourteen    [6]rune
	Fifteen     [6]rune
	Sixteen     [6]rune
	Seventeen   [6]rune
	Eighteen    [6]rune
	Nineteen    [6]rune
	Twenty      [6]rune
	TwentyOne   [6]rune
	TwentyTwo   [6]rune
	TwentyThree [6]rune
}
