// Code generated by Jay; DO NOT EDIT. Tool documentation available at: https://github.com/speedyhoon/jay

package main

import "github.com/speedyhoon/jay"

func (o *One) MarshalJ() (b []byte) {
	b = make([]byte, 8)
	jay.WriteComplex64(b, complex64(o.One))
	return
}

func (o *One) UnmarshalJ(b []byte) error {
	if len(b) != 8 {
		return jay.ErrUnexpectedEOB
	}
	o.One = cpx(jay.ReadComplex64(b))
	return nil
}

func (t *Two) MarshalJ() (b []byte) {
	b = make([]byte, 16)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:], complex64(t.Two))
	return
}

func (t *Two) UnmarshalJ(b []byte) error {
	if len(b) != 16 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:]))
	return nil
}

func (t *Three) MarshalJ() (b []byte) {
	b = make([]byte, 24)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:], complex64(t.Three))
	return
}

func (t *Three) UnmarshalJ(b []byte) error {
	if len(b) != 24 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:]))
	return nil
}

func (f *Four) MarshalJ() (b []byte) {
	b = make([]byte, 32)
	jay.WriteComplex64(b[:8], complex64(f.One))
	jay.WriteComplex64(b[8:16], complex64(f.Two))
	jay.WriteComplex64(b[16:24], complex64(f.Three))
	jay.WriteComplex64(b[24:], complex64(f.Four))
	return
}

func (f *Four) UnmarshalJ(b []byte) error {
	if len(b) != 32 {
		return jay.ErrUnexpectedEOB
	}
	f.One = cpx(jay.ReadComplex64(b[:8]))
	f.Two = cpx(jay.ReadComplex64(b[8:16]))
	f.Three = cpx(jay.ReadComplex64(b[16:24]))
	f.Four = cpx(jay.ReadComplex64(b[24:]))
	return nil
}

func (f *Five) MarshalJ() (b []byte) {
	b = make([]byte, 40)
	jay.WriteComplex64(b[:8], complex64(f.One))
	jay.WriteComplex64(b[8:16], complex64(f.Two))
	jay.WriteComplex64(b[16:24], complex64(f.Three))
	jay.WriteComplex64(b[24:32], complex64(f.Four))
	jay.WriteComplex64(b[32:], complex64(f.Five))
	return
}

func (f *Five) UnmarshalJ(b []byte) error {
	if len(b) != 40 {
		return jay.ErrUnexpectedEOB
	}
	f.One = cpx(jay.ReadComplex64(b[:8]))
	f.Two = cpx(jay.ReadComplex64(b[8:16]))
	f.Three = cpx(jay.ReadComplex64(b[16:24]))
	f.Four = cpx(jay.ReadComplex64(b[24:32]))
	f.Five = cpx(jay.ReadComplex64(b[32:]))
	return nil
}

func (s *Six) MarshalJ() (b []byte) {
	b = make([]byte, 48)
	jay.WriteComplex64(b[:8], complex64(s.One))
	jay.WriteComplex64(b[8:16], complex64(s.Two))
	jay.WriteComplex64(b[16:24], complex64(s.Three))
	jay.WriteComplex64(b[24:32], complex64(s.Four))
	jay.WriteComplex64(b[32:40], complex64(s.Five))
	jay.WriteComplex64(b[40:], complex64(s.Six))
	return
}

func (s *Six) UnmarshalJ(b []byte) error {
	if len(b) != 48 {
		return jay.ErrUnexpectedEOB
	}
	s.One = cpx(jay.ReadComplex64(b[:8]))
	s.Two = cpx(jay.ReadComplex64(b[8:16]))
	s.Three = cpx(jay.ReadComplex64(b[16:24]))
	s.Four = cpx(jay.ReadComplex64(b[24:32]))
	s.Five = cpx(jay.ReadComplex64(b[32:40]))
	s.Six = cpx(jay.ReadComplex64(b[40:]))
	return nil
}

func (s *Seven) MarshalJ() (b []byte) {
	b = make([]byte, 56)
	jay.WriteComplex64(b[:8], complex64(s.One))
	jay.WriteComplex64(b[8:16], complex64(s.Two))
	jay.WriteComplex64(b[16:24], complex64(s.Three))
	jay.WriteComplex64(b[24:32], complex64(s.Four))
	jay.WriteComplex64(b[32:40], complex64(s.Five))
	jay.WriteComplex64(b[40:48], complex64(s.Six))
	jay.WriteComplex64(b[48:], complex64(s.Seven))
	return
}

func (s *Seven) UnmarshalJ(b []byte) error {
	if len(b) != 56 {
		return jay.ErrUnexpectedEOB
	}
	s.One = cpx(jay.ReadComplex64(b[:8]))
	s.Two = cpx(jay.ReadComplex64(b[8:16]))
	s.Three = cpx(jay.ReadComplex64(b[16:24]))
	s.Four = cpx(jay.ReadComplex64(b[24:32]))
	s.Five = cpx(jay.ReadComplex64(b[32:40]))
	s.Six = cpx(jay.ReadComplex64(b[40:48]))
	s.Seven = cpx(jay.ReadComplex64(b[48:]))
	return nil
}

func (e *Eight) MarshalJ() (b []byte) {
	b = make([]byte, 64)
	jay.WriteComplex64(b[:8], complex64(e.One))
	jay.WriteComplex64(b[8:16], complex64(e.Two))
	jay.WriteComplex64(b[16:24], complex64(e.Three))
	jay.WriteComplex64(b[24:32], complex64(e.Four))
	jay.WriteComplex64(b[32:40], complex64(e.Five))
	jay.WriteComplex64(b[40:48], complex64(e.Six))
	jay.WriteComplex64(b[48:56], complex64(e.Seven))
	jay.WriteComplex64(b[56:], complex64(e.Eight))
	return
}

func (e *Eight) UnmarshalJ(b []byte) error {
	if len(b) != 64 {
		return jay.ErrUnexpectedEOB
	}
	e.One = cpx(jay.ReadComplex64(b[:8]))
	e.Two = cpx(jay.ReadComplex64(b[8:16]))
	e.Three = cpx(jay.ReadComplex64(b[16:24]))
	e.Four = cpx(jay.ReadComplex64(b[24:32]))
	e.Five = cpx(jay.ReadComplex64(b[32:40]))
	e.Six = cpx(jay.ReadComplex64(b[40:48]))
	e.Seven = cpx(jay.ReadComplex64(b[48:56]))
	e.Eight = cpx(jay.ReadComplex64(b[56:]))
	return nil
}

func (n *Nine) MarshalJ() (b []byte) {
	b = make([]byte, 72)
	jay.WriteComplex64(b[:8], complex64(n.One))
	jay.WriteComplex64(b[8:16], complex64(n.Two))
	jay.WriteComplex64(b[16:24], complex64(n.Three))
	jay.WriteComplex64(b[24:32], complex64(n.Four))
	jay.WriteComplex64(b[32:40], complex64(n.Five))
	jay.WriteComplex64(b[40:48], complex64(n.Six))
	jay.WriteComplex64(b[48:56], complex64(n.Seven))
	jay.WriteComplex64(b[56:64], complex64(n.Eight))
	jay.WriteComplex64(b[64:], complex64(n.Nine))
	return
}

func (n *Nine) UnmarshalJ(b []byte) error {
	if len(b) != 72 {
		return jay.ErrUnexpectedEOB
	}
	n.One = cpx(jay.ReadComplex64(b[:8]))
	n.Two = cpx(jay.ReadComplex64(b[8:16]))
	n.Three = cpx(jay.ReadComplex64(b[16:24]))
	n.Four = cpx(jay.ReadComplex64(b[24:32]))
	n.Five = cpx(jay.ReadComplex64(b[32:40]))
	n.Six = cpx(jay.ReadComplex64(b[40:48]))
	n.Seven = cpx(jay.ReadComplex64(b[48:56]))
	n.Eight = cpx(jay.ReadComplex64(b[56:64]))
	n.Nine = cpx(jay.ReadComplex64(b[64:]))
	return nil
}

func (t *Ten) MarshalJ() (b []byte) {
	b = make([]byte, 80)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:], complex64(t.Ten))
	return
}

func (t *Ten) UnmarshalJ(b []byte) error {
	if len(b) != 80 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:]))
	return nil
}

func (e *Eleven) MarshalJ() (b []byte) {
	b = make([]byte, 88)
	jay.WriteComplex64(b[:8], complex64(e.One))
	jay.WriteComplex64(b[8:16], complex64(e.Two))
	jay.WriteComplex64(b[16:24], complex64(e.Three))
	jay.WriteComplex64(b[24:32], complex64(e.Four))
	jay.WriteComplex64(b[32:40], complex64(e.Five))
	jay.WriteComplex64(b[40:48], complex64(e.Six))
	jay.WriteComplex64(b[48:56], complex64(e.Seven))
	jay.WriteComplex64(b[56:64], complex64(e.Eight))
	jay.WriteComplex64(b[64:72], complex64(e.Nine))
	jay.WriteComplex64(b[72:80], complex64(e.Ten))
	jay.WriteComplex64(b[80:], complex64(e.Eleven))
	return
}

func (e *Eleven) UnmarshalJ(b []byte) error {
	if len(b) != 88 {
		return jay.ErrUnexpectedEOB
	}
	e.One = cpx(jay.ReadComplex64(b[:8]))
	e.Two = cpx(jay.ReadComplex64(b[8:16]))
	e.Three = cpx(jay.ReadComplex64(b[16:24]))
	e.Four = cpx(jay.ReadComplex64(b[24:32]))
	e.Five = cpx(jay.ReadComplex64(b[32:40]))
	e.Six = cpx(jay.ReadComplex64(b[40:48]))
	e.Seven = cpx(jay.ReadComplex64(b[48:56]))
	e.Eight = cpx(jay.ReadComplex64(b[56:64]))
	e.Nine = cpx(jay.ReadComplex64(b[64:72]))
	e.Ten = cpx(jay.ReadComplex64(b[72:80]))
	e.Eleven = cpx(jay.ReadComplex64(b[80:]))
	return nil
}

func (t *Twelve) MarshalJ() (b []byte) {
	b = make([]byte, 96)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:80], complex64(t.Ten))
	jay.WriteComplex64(b[80:88], complex64(t.Eleven))
	jay.WriteComplex64(b[88:], complex64(t.Twelve))
	return
}

func (t *Twelve) UnmarshalJ(b []byte) error {
	if len(b) != 96 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:80]))
	t.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	t.Twelve = cpx(jay.ReadComplex64(b[88:]))
	return nil
}

func (t *Thirteen) MarshalJ() (b []byte) {
	b = make([]byte, 104)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:80], complex64(t.Ten))
	jay.WriteComplex64(b[80:88], complex64(t.Eleven))
	jay.WriteComplex64(b[88:96], complex64(t.Twelve))
	jay.WriteComplex64(b[96:], complex64(t.Thirteen))
	return
}

func (t *Thirteen) UnmarshalJ(b []byte) error {
	if len(b) != 104 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:80]))
	t.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	t.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	t.Thirteen = cpx(jay.ReadComplex64(b[96:]))
	return nil
}

func (f *Fourteen) MarshalJ() (b []byte) {
	b = make([]byte, 112)
	jay.WriteComplex64(b[:8], complex64(f.One))
	jay.WriteComplex64(b[8:16], complex64(f.Two))
	jay.WriteComplex64(b[16:24], complex64(f.Three))
	jay.WriteComplex64(b[24:32], complex64(f.Four))
	jay.WriteComplex64(b[32:40], complex64(f.Five))
	jay.WriteComplex64(b[40:48], complex64(f.Six))
	jay.WriteComplex64(b[48:56], complex64(f.Seven))
	jay.WriteComplex64(b[56:64], complex64(f.Eight))
	jay.WriteComplex64(b[64:72], complex64(f.Nine))
	jay.WriteComplex64(b[72:80], complex64(f.Ten))
	jay.WriteComplex64(b[80:88], complex64(f.Eleven))
	jay.WriteComplex64(b[88:96], complex64(f.Twelve))
	jay.WriteComplex64(b[96:104], complex64(f.Thirteen))
	jay.WriteComplex64(b[104:], complex64(f.Fourteen))
	return
}

func (f *Fourteen) UnmarshalJ(b []byte) error {
	if len(b) != 112 {
		return jay.ErrUnexpectedEOB
	}
	f.One = cpx(jay.ReadComplex64(b[:8]))
	f.Two = cpx(jay.ReadComplex64(b[8:16]))
	f.Three = cpx(jay.ReadComplex64(b[16:24]))
	f.Four = cpx(jay.ReadComplex64(b[24:32]))
	f.Five = cpx(jay.ReadComplex64(b[32:40]))
	f.Six = cpx(jay.ReadComplex64(b[40:48]))
	f.Seven = cpx(jay.ReadComplex64(b[48:56]))
	f.Eight = cpx(jay.ReadComplex64(b[56:64]))
	f.Nine = cpx(jay.ReadComplex64(b[64:72]))
	f.Ten = cpx(jay.ReadComplex64(b[72:80]))
	f.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	f.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	f.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	f.Fourteen = cpx(jay.ReadComplex64(b[104:]))
	return nil
}

func (f *Fifteen) MarshalJ() (b []byte) {
	b = make([]byte, 120)
	jay.WriteComplex64(b[:8], complex64(f.One))
	jay.WriteComplex64(b[8:16], complex64(f.Two))
	jay.WriteComplex64(b[16:24], complex64(f.Three))
	jay.WriteComplex64(b[24:32], complex64(f.Four))
	jay.WriteComplex64(b[32:40], complex64(f.Five))
	jay.WriteComplex64(b[40:48], complex64(f.Six))
	jay.WriteComplex64(b[48:56], complex64(f.Seven))
	jay.WriteComplex64(b[56:64], complex64(f.Eight))
	jay.WriteComplex64(b[64:72], complex64(f.Nine))
	jay.WriteComplex64(b[72:80], complex64(f.Ten))
	jay.WriteComplex64(b[80:88], complex64(f.Eleven))
	jay.WriteComplex64(b[88:96], complex64(f.Twelve))
	jay.WriteComplex64(b[96:104], complex64(f.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(f.Fourteen))
	jay.WriteComplex64(b[112:], complex64(f.Fifteen))
	return
}

func (f *Fifteen) UnmarshalJ(b []byte) error {
	if len(b) != 120 {
		return jay.ErrUnexpectedEOB
	}
	f.One = cpx(jay.ReadComplex64(b[:8]))
	f.Two = cpx(jay.ReadComplex64(b[8:16]))
	f.Three = cpx(jay.ReadComplex64(b[16:24]))
	f.Four = cpx(jay.ReadComplex64(b[24:32]))
	f.Five = cpx(jay.ReadComplex64(b[32:40]))
	f.Six = cpx(jay.ReadComplex64(b[40:48]))
	f.Seven = cpx(jay.ReadComplex64(b[48:56]))
	f.Eight = cpx(jay.ReadComplex64(b[56:64]))
	f.Nine = cpx(jay.ReadComplex64(b[64:72]))
	f.Ten = cpx(jay.ReadComplex64(b[72:80]))
	f.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	f.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	f.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	f.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	f.Fifteen = cpx(jay.ReadComplex64(b[112:]))
	return nil
}

func (s *Sixteen) MarshalJ() (b []byte) {
	b = make([]byte, 128)
	jay.WriteComplex64(b[:8], complex64(s.One))
	jay.WriteComplex64(b[8:16], complex64(s.Two))
	jay.WriteComplex64(b[16:24], complex64(s.Three))
	jay.WriteComplex64(b[24:32], complex64(s.Four))
	jay.WriteComplex64(b[32:40], complex64(s.Five))
	jay.WriteComplex64(b[40:48], complex64(s.Six))
	jay.WriteComplex64(b[48:56], complex64(s.Seven))
	jay.WriteComplex64(b[56:64], complex64(s.Eight))
	jay.WriteComplex64(b[64:72], complex64(s.Nine))
	jay.WriteComplex64(b[72:80], complex64(s.Ten))
	jay.WriteComplex64(b[80:88], complex64(s.Eleven))
	jay.WriteComplex64(b[88:96], complex64(s.Twelve))
	jay.WriteComplex64(b[96:104], complex64(s.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(s.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(s.Fifteen))
	jay.WriteComplex64(b[120:], complex64(s.Sixteen))
	return
}

func (s *Sixteen) UnmarshalJ(b []byte) error {
	if len(b) != 128 {
		return jay.ErrUnexpectedEOB
	}
	s.One = cpx(jay.ReadComplex64(b[:8]))
	s.Two = cpx(jay.ReadComplex64(b[8:16]))
	s.Three = cpx(jay.ReadComplex64(b[16:24]))
	s.Four = cpx(jay.ReadComplex64(b[24:32]))
	s.Five = cpx(jay.ReadComplex64(b[32:40]))
	s.Six = cpx(jay.ReadComplex64(b[40:48]))
	s.Seven = cpx(jay.ReadComplex64(b[48:56]))
	s.Eight = cpx(jay.ReadComplex64(b[56:64]))
	s.Nine = cpx(jay.ReadComplex64(b[64:72]))
	s.Ten = cpx(jay.ReadComplex64(b[72:80]))
	s.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	s.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	s.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	s.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	s.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	s.Sixteen = cpx(jay.ReadComplex64(b[120:]))
	return nil
}

func (s *Seventeen) MarshalJ() (b []byte) {
	b = make([]byte, 136)
	jay.WriteComplex64(b[:8], complex64(s.One))
	jay.WriteComplex64(b[8:16], complex64(s.Two))
	jay.WriteComplex64(b[16:24], complex64(s.Three))
	jay.WriteComplex64(b[24:32], complex64(s.Four))
	jay.WriteComplex64(b[32:40], complex64(s.Five))
	jay.WriteComplex64(b[40:48], complex64(s.Six))
	jay.WriteComplex64(b[48:56], complex64(s.Seven))
	jay.WriteComplex64(b[56:64], complex64(s.Eight))
	jay.WriteComplex64(b[64:72], complex64(s.Nine))
	jay.WriteComplex64(b[72:80], complex64(s.Ten))
	jay.WriteComplex64(b[80:88], complex64(s.Eleven))
	jay.WriteComplex64(b[88:96], complex64(s.Twelve))
	jay.WriteComplex64(b[96:104], complex64(s.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(s.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(s.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(s.Sixteen))
	jay.WriteComplex64(b[128:], complex64(s.Seventeen))
	return
}

func (s *Seventeen) UnmarshalJ(b []byte) error {
	if len(b) != 136 {
		return jay.ErrUnexpectedEOB
	}
	s.One = cpx(jay.ReadComplex64(b[:8]))
	s.Two = cpx(jay.ReadComplex64(b[8:16]))
	s.Three = cpx(jay.ReadComplex64(b[16:24]))
	s.Four = cpx(jay.ReadComplex64(b[24:32]))
	s.Five = cpx(jay.ReadComplex64(b[32:40]))
	s.Six = cpx(jay.ReadComplex64(b[40:48]))
	s.Seven = cpx(jay.ReadComplex64(b[48:56]))
	s.Eight = cpx(jay.ReadComplex64(b[56:64]))
	s.Nine = cpx(jay.ReadComplex64(b[64:72]))
	s.Ten = cpx(jay.ReadComplex64(b[72:80]))
	s.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	s.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	s.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	s.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	s.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	s.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	s.Seventeen = cpx(jay.ReadComplex64(b[128:]))
	return nil
}

func (e *Eighteen) MarshalJ() (b []byte) {
	b = make([]byte, 144)
	jay.WriteComplex64(b[:8], complex64(e.One))
	jay.WriteComplex64(b[8:16], complex64(e.Two))
	jay.WriteComplex64(b[16:24], complex64(e.Three))
	jay.WriteComplex64(b[24:32], complex64(e.Four))
	jay.WriteComplex64(b[32:40], complex64(e.Five))
	jay.WriteComplex64(b[40:48], complex64(e.Six))
	jay.WriteComplex64(b[48:56], complex64(e.Seven))
	jay.WriteComplex64(b[56:64], complex64(e.Eight))
	jay.WriteComplex64(b[64:72], complex64(e.Nine))
	jay.WriteComplex64(b[72:80], complex64(e.Ten))
	jay.WriteComplex64(b[80:88], complex64(e.Eleven))
	jay.WriteComplex64(b[88:96], complex64(e.Twelve))
	jay.WriteComplex64(b[96:104], complex64(e.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(e.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(e.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(e.Sixteen))
	jay.WriteComplex64(b[128:136], complex64(e.Seventeen))
	jay.WriteComplex64(b[136:], complex64(e.Eighteen))
	return
}

func (e *Eighteen) UnmarshalJ(b []byte) error {
	if len(b) != 144 {
		return jay.ErrUnexpectedEOB
	}
	e.One = cpx(jay.ReadComplex64(b[:8]))
	e.Two = cpx(jay.ReadComplex64(b[8:16]))
	e.Three = cpx(jay.ReadComplex64(b[16:24]))
	e.Four = cpx(jay.ReadComplex64(b[24:32]))
	e.Five = cpx(jay.ReadComplex64(b[32:40]))
	e.Six = cpx(jay.ReadComplex64(b[40:48]))
	e.Seven = cpx(jay.ReadComplex64(b[48:56]))
	e.Eight = cpx(jay.ReadComplex64(b[56:64]))
	e.Nine = cpx(jay.ReadComplex64(b[64:72]))
	e.Ten = cpx(jay.ReadComplex64(b[72:80]))
	e.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	e.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	e.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	e.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	e.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	e.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	e.Seventeen = cpx(jay.ReadComplex64(b[128:136]))
	e.Eighteen = cpx(jay.ReadComplex64(b[136:]))
	return nil
}

func (n *Nineteen) MarshalJ() (b []byte) {
	b = make([]byte, 152)
	jay.WriteComplex64(b[:8], complex64(n.One))
	jay.WriteComplex64(b[8:16], complex64(n.Two))
	jay.WriteComplex64(b[16:24], complex64(n.Three))
	jay.WriteComplex64(b[24:32], complex64(n.Four))
	jay.WriteComplex64(b[32:40], complex64(n.Five))
	jay.WriteComplex64(b[40:48], complex64(n.Six))
	jay.WriteComplex64(b[48:56], complex64(n.Seven))
	jay.WriteComplex64(b[56:64], complex64(n.Eight))
	jay.WriteComplex64(b[64:72], complex64(n.Nine))
	jay.WriteComplex64(b[72:80], complex64(n.Ten))
	jay.WriteComplex64(b[80:88], complex64(n.Eleven))
	jay.WriteComplex64(b[88:96], complex64(n.Twelve))
	jay.WriteComplex64(b[96:104], complex64(n.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(n.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(n.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(n.Sixteen))
	jay.WriteComplex64(b[128:136], complex64(n.Seventeen))
	jay.WriteComplex64(b[136:144], complex64(n.Eighteen))
	jay.WriteComplex64(b[144:], complex64(n.Nineteen))
	return
}

func (n *Nineteen) UnmarshalJ(b []byte) error {
	if len(b) != 152 {
		return jay.ErrUnexpectedEOB
	}
	n.One = cpx(jay.ReadComplex64(b[:8]))
	n.Two = cpx(jay.ReadComplex64(b[8:16]))
	n.Three = cpx(jay.ReadComplex64(b[16:24]))
	n.Four = cpx(jay.ReadComplex64(b[24:32]))
	n.Five = cpx(jay.ReadComplex64(b[32:40]))
	n.Six = cpx(jay.ReadComplex64(b[40:48]))
	n.Seven = cpx(jay.ReadComplex64(b[48:56]))
	n.Eight = cpx(jay.ReadComplex64(b[56:64]))
	n.Nine = cpx(jay.ReadComplex64(b[64:72]))
	n.Ten = cpx(jay.ReadComplex64(b[72:80]))
	n.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	n.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	n.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	n.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	n.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	n.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	n.Seventeen = cpx(jay.ReadComplex64(b[128:136]))
	n.Eighteen = cpx(jay.ReadComplex64(b[136:144]))
	n.Nineteen = cpx(jay.ReadComplex64(b[144:]))
	return nil
}

func (t *Twenty) MarshalJ() (b []byte) {
	b = make([]byte, 160)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:80], complex64(t.Ten))
	jay.WriteComplex64(b[80:88], complex64(t.Eleven))
	jay.WriteComplex64(b[88:96], complex64(t.Twelve))
	jay.WriteComplex64(b[96:104], complex64(t.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(t.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(t.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(t.Sixteen))
	jay.WriteComplex64(b[128:136], complex64(t.Seventeen))
	jay.WriteComplex64(b[136:144], complex64(t.Eighteen))
	jay.WriteComplex64(b[144:152], complex64(t.Nineteen))
	jay.WriteComplex64(b[152:], complex64(t.Twenty))
	return
}

func (t *Twenty) UnmarshalJ(b []byte) error {
	if len(b) != 160 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:80]))
	t.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	t.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	t.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	t.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	t.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	t.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	t.Seventeen = cpx(jay.ReadComplex64(b[128:136]))
	t.Eighteen = cpx(jay.ReadComplex64(b[136:144]))
	t.Nineteen = cpx(jay.ReadComplex64(b[144:152]))
	t.Twenty = cpx(jay.ReadComplex64(b[152:]))
	return nil
}

func (t *TwentyOne) MarshalJ() (b []byte) {
	b = make([]byte, 168)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:80], complex64(t.Ten))
	jay.WriteComplex64(b[80:88], complex64(t.Eleven))
	jay.WriteComplex64(b[88:96], complex64(t.Twelve))
	jay.WriteComplex64(b[96:104], complex64(t.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(t.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(t.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(t.Sixteen))
	jay.WriteComplex64(b[128:136], complex64(t.Seventeen))
	jay.WriteComplex64(b[136:144], complex64(t.Eighteen))
	jay.WriteComplex64(b[144:152], complex64(t.Nineteen))
	jay.WriteComplex64(b[152:160], complex64(t.Twenty))
	jay.WriteComplex64(b[160:], complex64(t.TwentyOne))
	return
}

func (t *TwentyOne) UnmarshalJ(b []byte) error {
	if len(b) != 168 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:80]))
	t.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	t.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	t.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	t.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	t.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	t.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	t.Seventeen = cpx(jay.ReadComplex64(b[128:136]))
	t.Eighteen = cpx(jay.ReadComplex64(b[136:144]))
	t.Nineteen = cpx(jay.ReadComplex64(b[144:152]))
	t.Twenty = cpx(jay.ReadComplex64(b[152:160]))
	t.TwentyOne = cpx(jay.ReadComplex64(b[160:]))
	return nil
}

func (t *TwentyTwo) MarshalJ() (b []byte) {
	b = make([]byte, 176)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:80], complex64(t.Ten))
	jay.WriteComplex64(b[80:88], complex64(t.Eleven))
	jay.WriteComplex64(b[88:96], complex64(t.Twelve))
	jay.WriteComplex64(b[96:104], complex64(t.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(t.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(t.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(t.Sixteen))
	jay.WriteComplex64(b[128:136], complex64(t.Seventeen))
	jay.WriteComplex64(b[136:144], complex64(t.Eighteen))
	jay.WriteComplex64(b[144:152], complex64(t.Nineteen))
	jay.WriteComplex64(b[152:160], complex64(t.Twenty))
	jay.WriteComplex64(b[160:168], complex64(t.TwentyOne))
	jay.WriteComplex64(b[168:], complex64(t.TwentyTwo))
	return
}

func (t *TwentyTwo) UnmarshalJ(b []byte) error {
	if len(b) != 176 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:80]))
	t.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	t.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	t.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	t.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	t.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	t.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	t.Seventeen = cpx(jay.ReadComplex64(b[128:136]))
	t.Eighteen = cpx(jay.ReadComplex64(b[136:144]))
	t.Nineteen = cpx(jay.ReadComplex64(b[144:152]))
	t.Twenty = cpx(jay.ReadComplex64(b[152:160]))
	t.TwentyOne = cpx(jay.ReadComplex64(b[160:168]))
	t.TwentyTwo = cpx(jay.ReadComplex64(b[168:]))
	return nil
}

func (t *TwentyThree) MarshalJ() (b []byte) {
	b = make([]byte, 184)
	jay.WriteComplex64(b[:8], complex64(t.One))
	jay.WriteComplex64(b[8:16], complex64(t.Two))
	jay.WriteComplex64(b[16:24], complex64(t.Three))
	jay.WriteComplex64(b[24:32], complex64(t.Four))
	jay.WriteComplex64(b[32:40], complex64(t.Five))
	jay.WriteComplex64(b[40:48], complex64(t.Six))
	jay.WriteComplex64(b[48:56], complex64(t.Seven))
	jay.WriteComplex64(b[56:64], complex64(t.Eight))
	jay.WriteComplex64(b[64:72], complex64(t.Nine))
	jay.WriteComplex64(b[72:80], complex64(t.Ten))
	jay.WriteComplex64(b[80:88], complex64(t.Eleven))
	jay.WriteComplex64(b[88:96], complex64(t.Twelve))
	jay.WriteComplex64(b[96:104], complex64(t.Thirteen))
	jay.WriteComplex64(b[104:112], complex64(t.Fourteen))
	jay.WriteComplex64(b[112:120], complex64(t.Fifteen))
	jay.WriteComplex64(b[120:128], complex64(t.Sixteen))
	jay.WriteComplex64(b[128:136], complex64(t.Seventeen))
	jay.WriteComplex64(b[136:144], complex64(t.Eighteen))
	jay.WriteComplex64(b[144:152], complex64(t.Nineteen))
	jay.WriteComplex64(b[152:160], complex64(t.Twenty))
	jay.WriteComplex64(b[160:168], complex64(t.TwentyOne))
	jay.WriteComplex64(b[168:176], complex64(t.TwentyTwo))
	jay.WriteComplex64(b[176:], complex64(t.TwentyThree))
	return
}

func (t *TwentyThree) UnmarshalJ(b []byte) error {
	if len(b) != 184 {
		return jay.ErrUnexpectedEOB
	}
	t.One = cpx(jay.ReadComplex64(b[:8]))
	t.Two = cpx(jay.ReadComplex64(b[8:16]))
	t.Three = cpx(jay.ReadComplex64(b[16:24]))
	t.Four = cpx(jay.ReadComplex64(b[24:32]))
	t.Five = cpx(jay.ReadComplex64(b[32:40]))
	t.Six = cpx(jay.ReadComplex64(b[40:48]))
	t.Seven = cpx(jay.ReadComplex64(b[48:56]))
	t.Eight = cpx(jay.ReadComplex64(b[56:64]))
	t.Nine = cpx(jay.ReadComplex64(b[64:72]))
	t.Ten = cpx(jay.ReadComplex64(b[72:80]))
	t.Eleven = cpx(jay.ReadComplex64(b[80:88]))
	t.Twelve = cpx(jay.ReadComplex64(b[88:96]))
	t.Thirteen = cpx(jay.ReadComplex64(b[96:104]))
	t.Fourteen = cpx(jay.ReadComplex64(b[104:112]))
	t.Fifteen = cpx(jay.ReadComplex64(b[112:120]))
	t.Sixteen = cpx(jay.ReadComplex64(b[120:128]))
	t.Seventeen = cpx(jay.ReadComplex64(b[128:136]))
	t.Eighteen = cpx(jay.ReadComplex64(b[136:144]))
	t.Nineteen = cpx(jay.ReadComplex64(b[144:152]))
	t.Twenty = cpx(jay.ReadComplex64(b[152:160]))
	t.TwentyOne = cpx(jay.ReadComplex64(b[160:168]))
	t.TwentyTwo = cpx(jay.ReadComplex64(b[168:176]))
	t.TwentyThree = cpx(jay.ReadComplex64(b[176:]))
	return nil
}
