// Code generated by testdata/fuzz_test; DO NOT EDIT.

package main

type One struct {
	One [6]float32
}

type Two struct {
	One [6]float32
	Two [6]float32
}

type Three struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
}

type Four struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
}

type Five struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
	Five  [6]float32
}

type Six struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
	Five  [6]float32
	Six   [6]float32
}

type Seven struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
	Five  [6]float32
	Six   [6]float32
	Seven [6]float32
}

type Eight struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
	Five  [6]float32
	Six   [6]float32
	Seven [6]float32
	Eight [6]float32
}

type Nine struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
	Five  [6]float32
	Six   [6]float32
	Seven [6]float32
	Eight [6]float32
	Nine  [6]float32
}

type Ten struct {
	One   [6]float32
	Two   [6]float32
	Three [6]float32
	Four  [6]float32
	Five  [6]float32
	Six   [6]float32
	Seven [6]float32
	Eight [6]float32
	Nine  [6]float32
	Ten   [6]float32
}

type Eleven struct {
	One    [6]float32
	Two    [6]float32
	Three  [6]float32
	Four   [6]float32
	Five   [6]float32
	Six    [6]float32
	Seven  [6]float32
	Eight  [6]float32
	Nine   [6]float32
	Ten    [6]float32
	Eleven [6]float32
}

type Twelve struct {
	One    [6]float32
	Two    [6]float32
	Three  [6]float32
	Four   [6]float32
	Five   [6]float32
	Six    [6]float32
	Seven  [6]float32
	Eight  [6]float32
	Nine   [6]float32
	Ten    [6]float32
	Eleven [6]float32
	Twelve [6]float32
}

type Thirteen struct {
	One      [6]float32
	Two      [6]float32
	Three    [6]float32
	Four     [6]float32
	Five     [6]float32
	Six      [6]float32
	Seven    [6]float32
	Eight    [6]float32
	Nine     [6]float32
	Ten      [6]float32
	Eleven   [6]float32
	Twelve   [6]float32
	Thirteen [6]float32
}

type Fourteen struct {
	One      [6]float32
	Two      [6]float32
	Three    [6]float32
	Four     [6]float32
	Five     [6]float32
	Six      [6]float32
	Seven    [6]float32
	Eight    [6]float32
	Nine     [6]float32
	Ten      [6]float32
	Eleven   [6]float32
	Twelve   [6]float32
	Thirteen [6]float32
	Fourteen [6]float32
}

type Fifteen struct {
	One      [6]float32
	Two      [6]float32
	Three    [6]float32
	Four     [6]float32
	Five     [6]float32
	Six      [6]float32
	Seven    [6]float32
	Eight    [6]float32
	Nine     [6]float32
	Ten      [6]float32
	Eleven   [6]float32
	Twelve   [6]float32
	Thirteen [6]float32
	Fourteen [6]float32
	Fifteen  [6]float32
}

type Sixteen struct {
	One      [6]float32
	Two      [6]float32
	Three    [6]float32
	Four     [6]float32
	Five     [6]float32
	Six      [6]float32
	Seven    [6]float32
	Eight    [6]float32
	Nine     [6]float32
	Ten      [6]float32
	Eleven   [6]float32
	Twelve   [6]float32
	Thirteen [6]float32
	Fourteen [6]float32
	Fifteen  [6]float32
	Sixteen  [6]float32
}

type Seventeen struct {
	One       [6]float32
	Two       [6]float32
	Three     [6]float32
	Four      [6]float32
	Five      [6]float32
	Six       [6]float32
	Seven     [6]float32
	Eight     [6]float32
	Nine      [6]float32
	Ten       [6]float32
	Eleven    [6]float32
	Twelve    [6]float32
	Thirteen  [6]float32
	Fourteen  [6]float32
	Fifteen   [6]float32
	Sixteen   [6]float32
	Seventeen [6]float32
}

type Eighteen struct {
	One       [6]float32
	Two       [6]float32
	Three     [6]float32
	Four      [6]float32
	Five      [6]float32
	Six       [6]float32
	Seven     [6]float32
	Eight     [6]float32
	Nine      [6]float32
	Ten       [6]float32
	Eleven    [6]float32
	Twelve    [6]float32
	Thirteen  [6]float32
	Fourteen  [6]float32
	Fifteen   [6]float32
	Sixteen   [6]float32
	Seventeen [6]float32
	Eighteen  [6]float32
}

type Nineteen struct {
	One       [6]float32
	Two       [6]float32
	Three     [6]float32
	Four      [6]float32
	Five      [6]float32
	Six       [6]float32
	Seven     [6]float32
	Eight     [6]float32
	Nine      [6]float32
	Ten       [6]float32
	Eleven    [6]float32
	Twelve    [6]float32
	Thirteen  [6]float32
	Fourteen  [6]float32
	Fifteen   [6]float32
	Sixteen   [6]float32
	Seventeen [6]float32
	Eighteen  [6]float32
	Nineteen  [6]float32
}

type Twenty struct {
	One       [6]float32
	Two       [6]float32
	Three     [6]float32
	Four      [6]float32
	Five      [6]float32
	Six       [6]float32
	Seven     [6]float32
	Eight     [6]float32
	Nine      [6]float32
	Ten       [6]float32
	Eleven    [6]float32
	Twelve    [6]float32
	Thirteen  [6]float32
	Fourteen  [6]float32
	Fifteen   [6]float32
	Sixteen   [6]float32
	Seventeen [6]float32
	Eighteen  [6]float32
	Nineteen  [6]float32
	Twenty    [6]float32
}

type TwentyOne struct {
	One       [6]float32
	Two       [6]float32
	Three     [6]float32
	Four      [6]float32
	Five      [6]float32
	Six       [6]float32
	Seven     [6]float32
	Eight     [6]float32
	Nine      [6]float32
	Ten       [6]float32
	Eleven    [6]float32
	Twelve    [6]float32
	Thirteen  [6]float32
	Fourteen  [6]float32
	Fifteen   [6]float32
	Sixteen   [6]float32
	Seventeen [6]float32
	Eighteen  [6]float32
	Nineteen  [6]float32
	Twenty    [6]float32
	TwentyOne [6]float32
}

type TwentyTwo struct {
	One       [6]float32
	Two       [6]float32
	Three     [6]float32
	Four      [6]float32
	Five      [6]float32
	Six       [6]float32
	Seven     [6]float32
	Eight     [6]float32
	Nine      [6]float32
	Ten       [6]float32
	Eleven    [6]float32
	Twelve    [6]float32
	Thirteen  [6]float32
	Fourteen  [6]float32
	Fifteen   [6]float32
	Sixteen   [6]float32
	Seventeen [6]float32
	Eighteen  [6]float32
	Nineteen  [6]float32
	Twenty    [6]float32
	TwentyOne [6]float32
	TwentyTwo [6]float32
}

type TwentyThree struct {
	One         [6]float32
	Two         [6]float32
	Three       [6]float32
	Four        [6]float32
	Five        [6]float32
	Six         [6]float32
	Seven       [6]float32
	Eight       [6]float32
	Nine        [6]float32
	Ten         [6]float32
	Eleven      [6]float32
	Twelve      [6]float32
	Thirteen    [6]float32
	Fourteen    [6]float32
	Fifteen     [6]float32
	Sixteen     [6]float32
	Seventeen   [6]float32
	Eighteen    [6]float32
	Nineteen    [6]float32
	Twenty      [6]float32
	TwentyOne   [6]float32
	TwentyTwo   [6]float32
	TwentyThree [6]float32
}
