// Code generated by Jay; DO NOT EDIT. Tool documentation available at: https://github.com/speedyhoon/jay

package main

import "github.com/speedyhoon/jay"

func (o *One) MarshalJ() (b []byte) {
	b = make([]byte, 8)
	jay.WriteUintX64(b, uint(o.One))
	return
}

func (o *One) UnmarshalJ(b []byte) error {
	if len(b) < 8 {
		return jay.ErrUnexpectedEOB
	}
	o.One = long(jay.ReadUintX64(b))
	return nil
}

func (t *Two) MarshalJ() (b []byte) {
	b = make([]byte, 16)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:], uint(t.Two))
	return
}

func (t *Two) UnmarshalJ(b []byte) error {
	if len(b) < 16 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:]))
	return nil
}

func (t *Three) MarshalJ() (b []byte) {
	b = make([]byte, 24)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:], uint(t.Three))
	return
}

func (t *Three) UnmarshalJ(b []byte) error {
	if len(b) < 24 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:]))
	return nil
}

func (f *Four) MarshalJ() (b []byte) {
	b = make([]byte, 32)
	jay.WriteUintX64(b[:8], uint(f.One))
	jay.WriteUintX64(b[8:16], uint(f.Two))
	jay.WriteUintX64(b[16:24], uint(f.Three))
	jay.WriteUintX64(b[24:], uint(f.Four))
	return
}

func (f *Four) UnmarshalJ(b []byte) error {
	if len(b) < 32 {
		return jay.ErrUnexpectedEOB
	}
	f.One = long(jay.ReadUintX64(b[:8]))
	f.Two = long(jay.ReadUintX64(b[8:16]))
	f.Three = long(jay.ReadUintX64(b[16:24]))
	f.Four = long(jay.ReadUintX64(b[24:]))
	return nil
}

func (f *Five) MarshalJ() (b []byte) {
	b = make([]byte, 40)
	jay.WriteUintX64(b[:8], uint(f.One))
	jay.WriteUintX64(b[8:16], uint(f.Two))
	jay.WriteUintX64(b[16:24], uint(f.Three))
	jay.WriteUintX64(b[24:32], uint(f.Four))
	jay.WriteUintX64(b[32:], uint(f.Five))
	return
}

func (f *Five) UnmarshalJ(b []byte) error {
	if len(b) < 40 {
		return jay.ErrUnexpectedEOB
	}
	f.One = long(jay.ReadUintX64(b[:8]))
	f.Two = long(jay.ReadUintX64(b[8:16]))
	f.Three = long(jay.ReadUintX64(b[16:24]))
	f.Four = long(jay.ReadUintX64(b[24:32]))
	f.Five = long(jay.ReadUintX64(b[32:]))
	return nil
}

func (s *Six) MarshalJ() (b []byte) {
	b = make([]byte, 48)
	jay.WriteUintX64(b[:8], uint(s.One))
	jay.WriteUintX64(b[8:16], uint(s.Two))
	jay.WriteUintX64(b[16:24], uint(s.Three))
	jay.WriteUintX64(b[24:32], uint(s.Four))
	jay.WriteUintX64(b[32:40], uint(s.Five))
	jay.WriteUintX64(b[40:], uint(s.Six))
	return
}

func (s *Six) UnmarshalJ(b []byte) error {
	if len(b) < 48 {
		return jay.ErrUnexpectedEOB
	}
	s.One = long(jay.ReadUintX64(b[:8]))
	s.Two = long(jay.ReadUintX64(b[8:16]))
	s.Three = long(jay.ReadUintX64(b[16:24]))
	s.Four = long(jay.ReadUintX64(b[24:32]))
	s.Five = long(jay.ReadUintX64(b[32:40]))
	s.Six = long(jay.ReadUintX64(b[40:]))
	return nil
}

func (s *Seven) MarshalJ() (b []byte) {
	b = make([]byte, 56)
	jay.WriteUintX64(b[:8], uint(s.One))
	jay.WriteUintX64(b[8:16], uint(s.Two))
	jay.WriteUintX64(b[16:24], uint(s.Three))
	jay.WriteUintX64(b[24:32], uint(s.Four))
	jay.WriteUintX64(b[32:40], uint(s.Five))
	jay.WriteUintX64(b[40:48], uint(s.Six))
	jay.WriteUintX64(b[48:], uint(s.Seven))
	return
}

func (s *Seven) UnmarshalJ(b []byte) error {
	if len(b) < 56 {
		return jay.ErrUnexpectedEOB
	}
	s.One = long(jay.ReadUintX64(b[:8]))
	s.Two = long(jay.ReadUintX64(b[8:16]))
	s.Three = long(jay.ReadUintX64(b[16:24]))
	s.Four = long(jay.ReadUintX64(b[24:32]))
	s.Five = long(jay.ReadUintX64(b[32:40]))
	s.Six = long(jay.ReadUintX64(b[40:48]))
	s.Seven = long(jay.ReadUintX64(b[48:]))
	return nil
}

func (e *Eight) MarshalJ() (b []byte) {
	b = make([]byte, 64)
	jay.WriteUintX64(b[:8], uint(e.One))
	jay.WriteUintX64(b[8:16], uint(e.Two))
	jay.WriteUintX64(b[16:24], uint(e.Three))
	jay.WriteUintX64(b[24:32], uint(e.Four))
	jay.WriteUintX64(b[32:40], uint(e.Five))
	jay.WriteUintX64(b[40:48], uint(e.Six))
	jay.WriteUintX64(b[48:56], uint(e.Seven))
	jay.WriteUintX64(b[56:], uint(e.Eight))
	return
}

func (e *Eight) UnmarshalJ(b []byte) error {
	if len(b) < 64 {
		return jay.ErrUnexpectedEOB
	}
	e.One = long(jay.ReadUintX64(b[:8]))
	e.Two = long(jay.ReadUintX64(b[8:16]))
	e.Three = long(jay.ReadUintX64(b[16:24]))
	e.Four = long(jay.ReadUintX64(b[24:32]))
	e.Five = long(jay.ReadUintX64(b[32:40]))
	e.Six = long(jay.ReadUintX64(b[40:48]))
	e.Seven = long(jay.ReadUintX64(b[48:56]))
	e.Eight = long(jay.ReadUintX64(b[56:]))
	return nil
}

func (n *Nine) MarshalJ() (b []byte) {
	b = make([]byte, 72)
	jay.WriteUintX64(b[:8], uint(n.One))
	jay.WriteUintX64(b[8:16], uint(n.Two))
	jay.WriteUintX64(b[16:24], uint(n.Three))
	jay.WriteUintX64(b[24:32], uint(n.Four))
	jay.WriteUintX64(b[32:40], uint(n.Five))
	jay.WriteUintX64(b[40:48], uint(n.Six))
	jay.WriteUintX64(b[48:56], uint(n.Seven))
	jay.WriteUintX64(b[56:64], uint(n.Eight))
	jay.WriteUintX64(b[64:], uint(n.Nine))
	return
}

func (n *Nine) UnmarshalJ(b []byte) error {
	if len(b) < 72 {
		return jay.ErrUnexpectedEOB
	}
	n.One = long(jay.ReadUintX64(b[:8]))
	n.Two = long(jay.ReadUintX64(b[8:16]))
	n.Three = long(jay.ReadUintX64(b[16:24]))
	n.Four = long(jay.ReadUintX64(b[24:32]))
	n.Five = long(jay.ReadUintX64(b[32:40]))
	n.Six = long(jay.ReadUintX64(b[40:48]))
	n.Seven = long(jay.ReadUintX64(b[48:56]))
	n.Eight = long(jay.ReadUintX64(b[56:64]))
	n.Nine = long(jay.ReadUintX64(b[64:]))
	return nil
}

func (t *Ten) MarshalJ() (b []byte) {
	b = make([]byte, 80)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:], uint(t.Ten))
	return
}

func (t *Ten) UnmarshalJ(b []byte) error {
	if len(b) < 80 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:]))
	return nil
}

func (e *Eleven) MarshalJ() (b []byte) {
	b = make([]byte, 88)
	jay.WriteUintX64(b[:8], uint(e.One))
	jay.WriteUintX64(b[8:16], uint(e.Two))
	jay.WriteUintX64(b[16:24], uint(e.Three))
	jay.WriteUintX64(b[24:32], uint(e.Four))
	jay.WriteUintX64(b[32:40], uint(e.Five))
	jay.WriteUintX64(b[40:48], uint(e.Six))
	jay.WriteUintX64(b[48:56], uint(e.Seven))
	jay.WriteUintX64(b[56:64], uint(e.Eight))
	jay.WriteUintX64(b[64:72], uint(e.Nine))
	jay.WriteUintX64(b[72:80], uint(e.Ten))
	jay.WriteUintX64(b[80:], uint(e.Eleven))
	return
}

func (e *Eleven) UnmarshalJ(b []byte) error {
	if len(b) < 88 {
		return jay.ErrUnexpectedEOB
	}
	e.One = long(jay.ReadUintX64(b[:8]))
	e.Two = long(jay.ReadUintX64(b[8:16]))
	e.Three = long(jay.ReadUintX64(b[16:24]))
	e.Four = long(jay.ReadUintX64(b[24:32]))
	e.Five = long(jay.ReadUintX64(b[32:40]))
	e.Six = long(jay.ReadUintX64(b[40:48]))
	e.Seven = long(jay.ReadUintX64(b[48:56]))
	e.Eight = long(jay.ReadUintX64(b[56:64]))
	e.Nine = long(jay.ReadUintX64(b[64:72]))
	e.Ten = long(jay.ReadUintX64(b[72:80]))
	e.Eleven = long(jay.ReadUintX64(b[80:]))
	return nil
}

func (t *Twelve) MarshalJ() (b []byte) {
	b = make([]byte, 96)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:80], uint(t.Ten))
	jay.WriteUintX64(b[80:88], uint(t.Eleven))
	jay.WriteUintX64(b[88:], uint(t.Twelve))
	return
}

func (t *Twelve) UnmarshalJ(b []byte) error {
	if len(b) < 96 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:80]))
	t.Eleven = long(jay.ReadUintX64(b[80:88]))
	t.Twelve = long(jay.ReadUintX64(b[88:]))
	return nil
}

func (t *Thirteen) MarshalJ() (b []byte) {
	b = make([]byte, 104)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:80], uint(t.Ten))
	jay.WriteUintX64(b[80:88], uint(t.Eleven))
	jay.WriteUintX64(b[88:96], uint(t.Twelve))
	jay.WriteUintX64(b[96:], uint(t.Thirteen))
	return
}

func (t *Thirteen) UnmarshalJ(b []byte) error {
	if len(b) < 104 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:80]))
	t.Eleven = long(jay.ReadUintX64(b[80:88]))
	t.Twelve = long(jay.ReadUintX64(b[88:96]))
	t.Thirteen = long(jay.ReadUintX64(b[96:]))
	return nil
}

func (f *Fourteen) MarshalJ() (b []byte) {
	b = make([]byte, 112)
	jay.WriteUintX64(b[:8], uint(f.One))
	jay.WriteUintX64(b[8:16], uint(f.Two))
	jay.WriteUintX64(b[16:24], uint(f.Three))
	jay.WriteUintX64(b[24:32], uint(f.Four))
	jay.WriteUintX64(b[32:40], uint(f.Five))
	jay.WriteUintX64(b[40:48], uint(f.Six))
	jay.WriteUintX64(b[48:56], uint(f.Seven))
	jay.WriteUintX64(b[56:64], uint(f.Eight))
	jay.WriteUintX64(b[64:72], uint(f.Nine))
	jay.WriteUintX64(b[72:80], uint(f.Ten))
	jay.WriteUintX64(b[80:88], uint(f.Eleven))
	jay.WriteUintX64(b[88:96], uint(f.Twelve))
	jay.WriteUintX64(b[96:104], uint(f.Thirteen))
	jay.WriteUintX64(b[104:], uint(f.Fourteen))
	return
}

func (f *Fourteen) UnmarshalJ(b []byte) error {
	if len(b) < 112 {
		return jay.ErrUnexpectedEOB
	}
	f.One = long(jay.ReadUintX64(b[:8]))
	f.Two = long(jay.ReadUintX64(b[8:16]))
	f.Three = long(jay.ReadUintX64(b[16:24]))
	f.Four = long(jay.ReadUintX64(b[24:32]))
	f.Five = long(jay.ReadUintX64(b[32:40]))
	f.Six = long(jay.ReadUintX64(b[40:48]))
	f.Seven = long(jay.ReadUintX64(b[48:56]))
	f.Eight = long(jay.ReadUintX64(b[56:64]))
	f.Nine = long(jay.ReadUintX64(b[64:72]))
	f.Ten = long(jay.ReadUintX64(b[72:80]))
	f.Eleven = long(jay.ReadUintX64(b[80:88]))
	f.Twelve = long(jay.ReadUintX64(b[88:96]))
	f.Thirteen = long(jay.ReadUintX64(b[96:104]))
	f.Fourteen = long(jay.ReadUintX64(b[104:]))
	return nil
}

func (f *Fifteen) MarshalJ() (b []byte) {
	b = make([]byte, 120)
	jay.WriteUintX64(b[:8], uint(f.One))
	jay.WriteUintX64(b[8:16], uint(f.Two))
	jay.WriteUintX64(b[16:24], uint(f.Three))
	jay.WriteUintX64(b[24:32], uint(f.Four))
	jay.WriteUintX64(b[32:40], uint(f.Five))
	jay.WriteUintX64(b[40:48], uint(f.Six))
	jay.WriteUintX64(b[48:56], uint(f.Seven))
	jay.WriteUintX64(b[56:64], uint(f.Eight))
	jay.WriteUintX64(b[64:72], uint(f.Nine))
	jay.WriteUintX64(b[72:80], uint(f.Ten))
	jay.WriteUintX64(b[80:88], uint(f.Eleven))
	jay.WriteUintX64(b[88:96], uint(f.Twelve))
	jay.WriteUintX64(b[96:104], uint(f.Thirteen))
	jay.WriteUintX64(b[104:112], uint(f.Fourteen))
	jay.WriteUintX64(b[112:], uint(f.Fifteen))
	return
}

func (f *Fifteen) UnmarshalJ(b []byte) error {
	if len(b) < 120 {
		return jay.ErrUnexpectedEOB
	}
	f.One = long(jay.ReadUintX64(b[:8]))
	f.Two = long(jay.ReadUintX64(b[8:16]))
	f.Three = long(jay.ReadUintX64(b[16:24]))
	f.Four = long(jay.ReadUintX64(b[24:32]))
	f.Five = long(jay.ReadUintX64(b[32:40]))
	f.Six = long(jay.ReadUintX64(b[40:48]))
	f.Seven = long(jay.ReadUintX64(b[48:56]))
	f.Eight = long(jay.ReadUintX64(b[56:64]))
	f.Nine = long(jay.ReadUintX64(b[64:72]))
	f.Ten = long(jay.ReadUintX64(b[72:80]))
	f.Eleven = long(jay.ReadUintX64(b[80:88]))
	f.Twelve = long(jay.ReadUintX64(b[88:96]))
	f.Thirteen = long(jay.ReadUintX64(b[96:104]))
	f.Fourteen = long(jay.ReadUintX64(b[104:112]))
	f.Fifteen = long(jay.ReadUintX64(b[112:]))
	return nil
}

func (s *Sixteen) MarshalJ() (b []byte) {
	b = make([]byte, 128)
	jay.WriteUintX64(b[:8], uint(s.One))
	jay.WriteUintX64(b[8:16], uint(s.Two))
	jay.WriteUintX64(b[16:24], uint(s.Three))
	jay.WriteUintX64(b[24:32], uint(s.Four))
	jay.WriteUintX64(b[32:40], uint(s.Five))
	jay.WriteUintX64(b[40:48], uint(s.Six))
	jay.WriteUintX64(b[48:56], uint(s.Seven))
	jay.WriteUintX64(b[56:64], uint(s.Eight))
	jay.WriteUintX64(b[64:72], uint(s.Nine))
	jay.WriteUintX64(b[72:80], uint(s.Ten))
	jay.WriteUintX64(b[80:88], uint(s.Eleven))
	jay.WriteUintX64(b[88:96], uint(s.Twelve))
	jay.WriteUintX64(b[96:104], uint(s.Thirteen))
	jay.WriteUintX64(b[104:112], uint(s.Fourteen))
	jay.WriteUintX64(b[112:120], uint(s.Fifteen))
	jay.WriteUintX64(b[120:], uint(s.Sixteen))
	return
}

func (s *Sixteen) UnmarshalJ(b []byte) error {
	if len(b) < 128 {
		return jay.ErrUnexpectedEOB
	}
	s.One = long(jay.ReadUintX64(b[:8]))
	s.Two = long(jay.ReadUintX64(b[8:16]))
	s.Three = long(jay.ReadUintX64(b[16:24]))
	s.Four = long(jay.ReadUintX64(b[24:32]))
	s.Five = long(jay.ReadUintX64(b[32:40]))
	s.Six = long(jay.ReadUintX64(b[40:48]))
	s.Seven = long(jay.ReadUintX64(b[48:56]))
	s.Eight = long(jay.ReadUintX64(b[56:64]))
	s.Nine = long(jay.ReadUintX64(b[64:72]))
	s.Ten = long(jay.ReadUintX64(b[72:80]))
	s.Eleven = long(jay.ReadUintX64(b[80:88]))
	s.Twelve = long(jay.ReadUintX64(b[88:96]))
	s.Thirteen = long(jay.ReadUintX64(b[96:104]))
	s.Fourteen = long(jay.ReadUintX64(b[104:112]))
	s.Fifteen = long(jay.ReadUintX64(b[112:120]))
	s.Sixteen = long(jay.ReadUintX64(b[120:]))
	return nil
}

func (s *Seventeen) MarshalJ() (b []byte) {
	b = make([]byte, 136)
	jay.WriteUintX64(b[:8], uint(s.One))
	jay.WriteUintX64(b[8:16], uint(s.Two))
	jay.WriteUintX64(b[16:24], uint(s.Three))
	jay.WriteUintX64(b[24:32], uint(s.Four))
	jay.WriteUintX64(b[32:40], uint(s.Five))
	jay.WriteUintX64(b[40:48], uint(s.Six))
	jay.WriteUintX64(b[48:56], uint(s.Seven))
	jay.WriteUintX64(b[56:64], uint(s.Eight))
	jay.WriteUintX64(b[64:72], uint(s.Nine))
	jay.WriteUintX64(b[72:80], uint(s.Ten))
	jay.WriteUintX64(b[80:88], uint(s.Eleven))
	jay.WriteUintX64(b[88:96], uint(s.Twelve))
	jay.WriteUintX64(b[96:104], uint(s.Thirteen))
	jay.WriteUintX64(b[104:112], uint(s.Fourteen))
	jay.WriteUintX64(b[112:120], uint(s.Fifteen))
	jay.WriteUintX64(b[120:128], uint(s.Sixteen))
	jay.WriteUintX64(b[128:], uint(s.Seventeen))
	return
}

func (s *Seventeen) UnmarshalJ(b []byte) error {
	if len(b) < 136 {
		return jay.ErrUnexpectedEOB
	}
	s.One = long(jay.ReadUintX64(b[:8]))
	s.Two = long(jay.ReadUintX64(b[8:16]))
	s.Three = long(jay.ReadUintX64(b[16:24]))
	s.Four = long(jay.ReadUintX64(b[24:32]))
	s.Five = long(jay.ReadUintX64(b[32:40]))
	s.Six = long(jay.ReadUintX64(b[40:48]))
	s.Seven = long(jay.ReadUintX64(b[48:56]))
	s.Eight = long(jay.ReadUintX64(b[56:64]))
	s.Nine = long(jay.ReadUintX64(b[64:72]))
	s.Ten = long(jay.ReadUintX64(b[72:80]))
	s.Eleven = long(jay.ReadUintX64(b[80:88]))
	s.Twelve = long(jay.ReadUintX64(b[88:96]))
	s.Thirteen = long(jay.ReadUintX64(b[96:104]))
	s.Fourteen = long(jay.ReadUintX64(b[104:112]))
	s.Fifteen = long(jay.ReadUintX64(b[112:120]))
	s.Sixteen = long(jay.ReadUintX64(b[120:128]))
	s.Seventeen = long(jay.ReadUintX64(b[128:]))
	return nil
}

func (e *Eighteen) MarshalJ() (b []byte) {
	b = make([]byte, 144)
	jay.WriteUintX64(b[:8], uint(e.One))
	jay.WriteUintX64(b[8:16], uint(e.Two))
	jay.WriteUintX64(b[16:24], uint(e.Three))
	jay.WriteUintX64(b[24:32], uint(e.Four))
	jay.WriteUintX64(b[32:40], uint(e.Five))
	jay.WriteUintX64(b[40:48], uint(e.Six))
	jay.WriteUintX64(b[48:56], uint(e.Seven))
	jay.WriteUintX64(b[56:64], uint(e.Eight))
	jay.WriteUintX64(b[64:72], uint(e.Nine))
	jay.WriteUintX64(b[72:80], uint(e.Ten))
	jay.WriteUintX64(b[80:88], uint(e.Eleven))
	jay.WriteUintX64(b[88:96], uint(e.Twelve))
	jay.WriteUintX64(b[96:104], uint(e.Thirteen))
	jay.WriteUintX64(b[104:112], uint(e.Fourteen))
	jay.WriteUintX64(b[112:120], uint(e.Fifteen))
	jay.WriteUintX64(b[120:128], uint(e.Sixteen))
	jay.WriteUintX64(b[128:136], uint(e.Seventeen))
	jay.WriteUintX64(b[136:], uint(e.Eighteen))
	return
}

func (e *Eighteen) UnmarshalJ(b []byte) error {
	if len(b) < 144 {
		return jay.ErrUnexpectedEOB
	}
	e.One = long(jay.ReadUintX64(b[:8]))
	e.Two = long(jay.ReadUintX64(b[8:16]))
	e.Three = long(jay.ReadUintX64(b[16:24]))
	e.Four = long(jay.ReadUintX64(b[24:32]))
	e.Five = long(jay.ReadUintX64(b[32:40]))
	e.Six = long(jay.ReadUintX64(b[40:48]))
	e.Seven = long(jay.ReadUintX64(b[48:56]))
	e.Eight = long(jay.ReadUintX64(b[56:64]))
	e.Nine = long(jay.ReadUintX64(b[64:72]))
	e.Ten = long(jay.ReadUintX64(b[72:80]))
	e.Eleven = long(jay.ReadUintX64(b[80:88]))
	e.Twelve = long(jay.ReadUintX64(b[88:96]))
	e.Thirteen = long(jay.ReadUintX64(b[96:104]))
	e.Fourteen = long(jay.ReadUintX64(b[104:112]))
	e.Fifteen = long(jay.ReadUintX64(b[112:120]))
	e.Sixteen = long(jay.ReadUintX64(b[120:128]))
	e.Seventeen = long(jay.ReadUintX64(b[128:136]))
	e.Eighteen = long(jay.ReadUintX64(b[136:]))
	return nil
}

func (n *Nineteen) MarshalJ() (b []byte) {
	b = make([]byte, 152)
	jay.WriteUintX64(b[:8], uint(n.One))
	jay.WriteUintX64(b[8:16], uint(n.Two))
	jay.WriteUintX64(b[16:24], uint(n.Three))
	jay.WriteUintX64(b[24:32], uint(n.Four))
	jay.WriteUintX64(b[32:40], uint(n.Five))
	jay.WriteUintX64(b[40:48], uint(n.Six))
	jay.WriteUintX64(b[48:56], uint(n.Seven))
	jay.WriteUintX64(b[56:64], uint(n.Eight))
	jay.WriteUintX64(b[64:72], uint(n.Nine))
	jay.WriteUintX64(b[72:80], uint(n.Ten))
	jay.WriteUintX64(b[80:88], uint(n.Eleven))
	jay.WriteUintX64(b[88:96], uint(n.Twelve))
	jay.WriteUintX64(b[96:104], uint(n.Thirteen))
	jay.WriteUintX64(b[104:112], uint(n.Fourteen))
	jay.WriteUintX64(b[112:120], uint(n.Fifteen))
	jay.WriteUintX64(b[120:128], uint(n.Sixteen))
	jay.WriteUintX64(b[128:136], uint(n.Seventeen))
	jay.WriteUintX64(b[136:144], uint(n.Eighteen))
	jay.WriteUintX64(b[144:], uint(n.Nineteen))
	return
}

func (n *Nineteen) UnmarshalJ(b []byte) error {
	if len(b) < 152 {
		return jay.ErrUnexpectedEOB
	}
	n.One = long(jay.ReadUintX64(b[:8]))
	n.Two = long(jay.ReadUintX64(b[8:16]))
	n.Three = long(jay.ReadUintX64(b[16:24]))
	n.Four = long(jay.ReadUintX64(b[24:32]))
	n.Five = long(jay.ReadUintX64(b[32:40]))
	n.Six = long(jay.ReadUintX64(b[40:48]))
	n.Seven = long(jay.ReadUintX64(b[48:56]))
	n.Eight = long(jay.ReadUintX64(b[56:64]))
	n.Nine = long(jay.ReadUintX64(b[64:72]))
	n.Ten = long(jay.ReadUintX64(b[72:80]))
	n.Eleven = long(jay.ReadUintX64(b[80:88]))
	n.Twelve = long(jay.ReadUintX64(b[88:96]))
	n.Thirteen = long(jay.ReadUintX64(b[96:104]))
	n.Fourteen = long(jay.ReadUintX64(b[104:112]))
	n.Fifteen = long(jay.ReadUintX64(b[112:120]))
	n.Sixteen = long(jay.ReadUintX64(b[120:128]))
	n.Seventeen = long(jay.ReadUintX64(b[128:136]))
	n.Eighteen = long(jay.ReadUintX64(b[136:144]))
	n.Nineteen = long(jay.ReadUintX64(b[144:]))
	return nil
}

func (t *Twenty) MarshalJ() (b []byte) {
	b = make([]byte, 160)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:80], uint(t.Ten))
	jay.WriteUintX64(b[80:88], uint(t.Eleven))
	jay.WriteUintX64(b[88:96], uint(t.Twelve))
	jay.WriteUintX64(b[96:104], uint(t.Thirteen))
	jay.WriteUintX64(b[104:112], uint(t.Fourteen))
	jay.WriteUintX64(b[112:120], uint(t.Fifteen))
	jay.WriteUintX64(b[120:128], uint(t.Sixteen))
	jay.WriteUintX64(b[128:136], uint(t.Seventeen))
	jay.WriteUintX64(b[136:144], uint(t.Eighteen))
	jay.WriteUintX64(b[144:152], uint(t.Nineteen))
	jay.WriteUintX64(b[152:], uint(t.Twenty))
	return
}

func (t *Twenty) UnmarshalJ(b []byte) error {
	if len(b) < 160 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:80]))
	t.Eleven = long(jay.ReadUintX64(b[80:88]))
	t.Twelve = long(jay.ReadUintX64(b[88:96]))
	t.Thirteen = long(jay.ReadUintX64(b[96:104]))
	t.Fourteen = long(jay.ReadUintX64(b[104:112]))
	t.Fifteen = long(jay.ReadUintX64(b[112:120]))
	t.Sixteen = long(jay.ReadUintX64(b[120:128]))
	t.Seventeen = long(jay.ReadUintX64(b[128:136]))
	t.Eighteen = long(jay.ReadUintX64(b[136:144]))
	t.Nineteen = long(jay.ReadUintX64(b[144:152]))
	t.Twenty = long(jay.ReadUintX64(b[152:]))
	return nil
}

func (t *TwentyOne) MarshalJ() (b []byte) {
	b = make([]byte, 168)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:80], uint(t.Ten))
	jay.WriteUintX64(b[80:88], uint(t.Eleven))
	jay.WriteUintX64(b[88:96], uint(t.Twelve))
	jay.WriteUintX64(b[96:104], uint(t.Thirteen))
	jay.WriteUintX64(b[104:112], uint(t.Fourteen))
	jay.WriteUintX64(b[112:120], uint(t.Fifteen))
	jay.WriteUintX64(b[120:128], uint(t.Sixteen))
	jay.WriteUintX64(b[128:136], uint(t.Seventeen))
	jay.WriteUintX64(b[136:144], uint(t.Eighteen))
	jay.WriteUintX64(b[144:152], uint(t.Nineteen))
	jay.WriteUintX64(b[152:160], uint(t.Twenty))
	jay.WriteUintX64(b[160:], uint(t.TwentyOne))
	return
}

func (t *TwentyOne) UnmarshalJ(b []byte) error {
	if len(b) < 168 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:80]))
	t.Eleven = long(jay.ReadUintX64(b[80:88]))
	t.Twelve = long(jay.ReadUintX64(b[88:96]))
	t.Thirteen = long(jay.ReadUintX64(b[96:104]))
	t.Fourteen = long(jay.ReadUintX64(b[104:112]))
	t.Fifteen = long(jay.ReadUintX64(b[112:120]))
	t.Sixteen = long(jay.ReadUintX64(b[120:128]))
	t.Seventeen = long(jay.ReadUintX64(b[128:136]))
	t.Eighteen = long(jay.ReadUintX64(b[136:144]))
	t.Nineteen = long(jay.ReadUintX64(b[144:152]))
	t.Twenty = long(jay.ReadUintX64(b[152:160]))
	t.TwentyOne = long(jay.ReadUintX64(b[160:]))
	return nil
}

func (t *TwentyTwo) MarshalJ() (b []byte) {
	b = make([]byte, 176)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:80], uint(t.Ten))
	jay.WriteUintX64(b[80:88], uint(t.Eleven))
	jay.WriteUintX64(b[88:96], uint(t.Twelve))
	jay.WriteUintX64(b[96:104], uint(t.Thirteen))
	jay.WriteUintX64(b[104:112], uint(t.Fourteen))
	jay.WriteUintX64(b[112:120], uint(t.Fifteen))
	jay.WriteUintX64(b[120:128], uint(t.Sixteen))
	jay.WriteUintX64(b[128:136], uint(t.Seventeen))
	jay.WriteUintX64(b[136:144], uint(t.Eighteen))
	jay.WriteUintX64(b[144:152], uint(t.Nineteen))
	jay.WriteUintX64(b[152:160], uint(t.Twenty))
	jay.WriteUintX64(b[160:168], uint(t.TwentyOne))
	jay.WriteUintX64(b[168:], uint(t.TwentyTwo))
	return
}

func (t *TwentyTwo) UnmarshalJ(b []byte) error {
	if len(b) < 176 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:80]))
	t.Eleven = long(jay.ReadUintX64(b[80:88]))
	t.Twelve = long(jay.ReadUintX64(b[88:96]))
	t.Thirteen = long(jay.ReadUintX64(b[96:104]))
	t.Fourteen = long(jay.ReadUintX64(b[104:112]))
	t.Fifteen = long(jay.ReadUintX64(b[112:120]))
	t.Sixteen = long(jay.ReadUintX64(b[120:128]))
	t.Seventeen = long(jay.ReadUintX64(b[128:136]))
	t.Eighteen = long(jay.ReadUintX64(b[136:144]))
	t.Nineteen = long(jay.ReadUintX64(b[144:152]))
	t.Twenty = long(jay.ReadUintX64(b[152:160]))
	t.TwentyOne = long(jay.ReadUintX64(b[160:168]))
	t.TwentyTwo = long(jay.ReadUintX64(b[168:]))
	return nil
}

func (t *TwentyThree) MarshalJ() (b []byte) {
	b = make([]byte, 184)
	jay.WriteUintX64(b[:8], uint(t.One))
	jay.WriteUintX64(b[8:16], uint(t.Two))
	jay.WriteUintX64(b[16:24], uint(t.Three))
	jay.WriteUintX64(b[24:32], uint(t.Four))
	jay.WriteUintX64(b[32:40], uint(t.Five))
	jay.WriteUintX64(b[40:48], uint(t.Six))
	jay.WriteUintX64(b[48:56], uint(t.Seven))
	jay.WriteUintX64(b[56:64], uint(t.Eight))
	jay.WriteUintX64(b[64:72], uint(t.Nine))
	jay.WriteUintX64(b[72:80], uint(t.Ten))
	jay.WriteUintX64(b[80:88], uint(t.Eleven))
	jay.WriteUintX64(b[88:96], uint(t.Twelve))
	jay.WriteUintX64(b[96:104], uint(t.Thirteen))
	jay.WriteUintX64(b[104:112], uint(t.Fourteen))
	jay.WriteUintX64(b[112:120], uint(t.Fifteen))
	jay.WriteUintX64(b[120:128], uint(t.Sixteen))
	jay.WriteUintX64(b[128:136], uint(t.Seventeen))
	jay.WriteUintX64(b[136:144], uint(t.Eighteen))
	jay.WriteUintX64(b[144:152], uint(t.Nineteen))
	jay.WriteUintX64(b[152:160], uint(t.Twenty))
	jay.WriteUintX64(b[160:168], uint(t.TwentyOne))
	jay.WriteUintX64(b[168:176], uint(t.TwentyTwo))
	jay.WriteUintX64(b[176:], uint(t.TwentyThree))
	return
}

func (t *TwentyThree) UnmarshalJ(b []byte) error {
	if len(b) < 184 {
		return jay.ErrUnexpectedEOB
	}
	t.One = long(jay.ReadUintX64(b[:8]))
	t.Two = long(jay.ReadUintX64(b[8:16]))
	t.Three = long(jay.ReadUintX64(b[16:24]))
	t.Four = long(jay.ReadUintX64(b[24:32]))
	t.Five = long(jay.ReadUintX64(b[32:40]))
	t.Six = long(jay.ReadUintX64(b[40:48]))
	t.Seven = long(jay.ReadUintX64(b[48:56]))
	t.Eight = long(jay.ReadUintX64(b[56:64]))
	t.Nine = long(jay.ReadUintX64(b[64:72]))
	t.Ten = long(jay.ReadUintX64(b[72:80]))
	t.Eleven = long(jay.ReadUintX64(b[80:88]))
	t.Twelve = long(jay.ReadUintX64(b[88:96]))
	t.Thirteen = long(jay.ReadUintX64(b[96:104]))
	t.Fourteen = long(jay.ReadUintX64(b[104:112]))
	t.Fifteen = long(jay.ReadUintX64(b[112:120]))
	t.Sixteen = long(jay.ReadUintX64(b[120:128]))
	t.Seventeen = long(jay.ReadUintX64(b[128:136]))
	t.Eighteen = long(jay.ReadUintX64(b[136:144]))
	t.Nineteen = long(jay.ReadUintX64(b[144:152]))
	t.Twenty = long(jay.ReadUintX64(b[152:160]))
	t.TwentyOne = long(jay.ReadUintX64(b[160:168]))
	t.TwentyTwo = long(jay.ReadUintX64(b[168:176]))
	t.TwentyThree = long(jay.ReadUintX64(b[176:]))
	return nil
}
